### ISSUE TITLE
IllegalStateException on Driver after closing a subscription

### ISSUE THREAD

**Issue by mst4** [real-logic/Aeron#102]
I created an app that will create and delete publications and subscriptions quickly while sending data.  

When I run this app, the driver will periodically pop out some exceptions:

[960215.713885] EXCEPTION [503/503]: java.lang.IllegalStateException(No subscription registered on stream 4)
uk.co.real_logic.aeron.driver.DataPacketDispatcher.addConnection DataPacketDispatcher.java:80
uk.co.real_logic.aeron.driver.Receiver.onNewConnection Receiver.java:99
uk.co.real_logic.aeron.driver.cmd.NewConnectionCmd.execute NewConnectionCmd.java:35
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:116
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:27
[960217.169434] EXCEPTION [503/503]: java.lang.IllegalStateException(No subscription registered on stream 4)
uk.co.real_logic.aeron.driver.DataPacketDispatcher.addConnection DataPacketDispatcher.java:80
uk.co.real_logic.aeron.driver.Receiver.onNewConnection Receiver.java:99
uk.co.real_logic.aeron.driver.cmd.NewConnectionCmd.execute NewConnectionCmd.java:35
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:116
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:27
[960217.228502] EXCEPTION [503/503]: java.lang.IllegalStateException(No subscription registered on stream 5)
uk.co.real_logic.aeron.driver.DataPacketDispatcher.addConnection DataPacketDispatcher.java:80
uk.co.real_logic.aeron.driver.Receiver.onNewConnection Receiver.java:99
uk.co.real_logic.aeron.driver.cmd.NewConnectionCmd.execute NewConnectionCmd.java:35
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:116
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:27

It seems to happen right after I call Subscription.close().

The thwacker app is here https://github.com/strangelydim/Aeron/blob/master/aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/ThwackerTool.java

**Comment by tmontgomery** [comment]
I added a check for this exact scenario. faa5689bc8d8f3742636235c04dfe273adf1c016

I no longer see these in Thwacker runs.
