### ISSUE TITLE
OnInactiveConnection issue

### ISSUE THREAD

**Issue by rmizuta** [real-logic/Aeron#103]
Hi,

I am getting an onInactiveConnection callback while I'm sending data every second.  Once this happens, I could never get the publisher and driver to be in a working state until some random time passes. The driver keeps calling the onInactiveConnection and I can't get the application to run more than a 30 sec. ~ 1 min properly even after I delete the folder or restart the computer.  I remember it used to reconnect automatically in the old build but it's not reconnecting anymore. 

Any thoughts?

Thanks.

RM

**Comment by mjpt777** [comment]
Can you create a test case?

**Comment by mjpt777** [comment]
Without more information we cannot recreate.
