### ISSUE TITLE
[QUESTION] Upper limit of buffer size that can be pass to aeron_publication_offer

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [real-logic/aeron#1046]
Using aeron C.
Is there any upper limit to the size of the buffer that can be pass to aeron_publication_offer or can I offer a large buffer (200kb) at once?

**Comment by mikeb01** [comment]
16MB.

https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/c/protocol/aeron_udp_protocol.h#L174.

**Comment by epickrram** [comment]
Isn't it also a function (i.e. 1/8th) of the `termLength`?

https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp/concurrent/logbuffer/FrameDescriptor.h#L91

**Comment by mjpt777** [comment]
That is correct @epickrram. I'm correcting the C code to match the Java and C++.
