### ISSUE TITLE
BasicSub logs core dump when reporting inactive connection following BasicPub suspension

### ISSUE THREAD

**Issue by antrongladney** [real-logic/Aeron#105]
Summary:
The BasicSubscriber core dumps when reporting inactive connection after the BasicPublisher is suspended using Ctrl-Z

Initial Conditions:
Using default values

Procedure:
Start the mediaDriver using the following command:
     java -cp samples.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.driver.MediaDriver

Start the BasicSubscriber using the following command:
   java -cp samples.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.samples.BasicSubscriber

Start the BasicPublisher using the following command
   java -cp samples.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.samples.BasicPublisher

The subscriber received a few messages before the publisher was suspended via Ctrl-Z.  After 5 secs, the publisher was resumed.  From the publisher's console, it appears messages are still being sent. However, the subscriber does NOT receive any messages.

This scenario has been executed ~7 times. The subscriber core dumped twice.
The first time the subscriber did not receive any additional messages after the publisher was resumed, reported the INACTIVE connection, and then core dumped.
The second time the subscriber did not report the INACTIVE connection on the console, however it still did not receive any messages and it core dumped.
Below is the output of the second error:
```
#  SIGSEGV (0xb) at pc=0x00007f3a74925bf0, pid=6366, tid=139889377175296
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 363 C2 uk.co.real_logic.aeron.Subscription$$Lambda$12.apply(Ljava/lang/Object;I)I (9 bytes) @ 0x00007f3a74925bf0 [0x00007f3a74925ae0+0x110]
#
# Core dump written. Default location: /home/agladney/aeron/aeron-samples/build/libs/core or core.6366
#
# An error report file with more information is saved as:
# /home/agladney/aeron/aeron-samples/build/libs/hs_err_pid6366.log
Inactive connection on udp://localhost:40123 streamId 10 sessionId 80e15b90 @ position 640
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
Aborted (core dumped)
```
Question regarding the expected results:
Even though the client liveness timeout is 5 secs, when the publisher  resumes, it is NOT a new publisher or session. Therefore, communication should continue and the connection should NOT be declared inactive. Is this correct?

[hs_err_pid6366.log | uploaded via ZenHub](https://files.zenhub.io/5540f8547e16e31d71f2ed1b)

**Comment by tmontgomery** [comment]
Would you be so kind to retest this with the latest and let us know what happens?

**Comment by rlankenau** [comment]
I've run this a number of times since @tmontgomery's latest fixes, and I haven't seen any SEGVs on the BasicSubscriber.
