### ISSUE TITLE
Subscriber re-reads data when Media Driver exits if the publisher is on the same driver.

### ISSUE THREAD

**Issue by brianhorst** [real-logic/Aeron#106]
If a publisher and subscriber are both on the same Media Driver and the media driver is killed, then the subscriber re-reads the current log and delivers those messages again. 

Basic Subscriber Output (notice the messages repeat after 4)
Subscribing to udp://localhost:40123 on stream Id 10
New connection on udp://localhost:40123 streamId 10 sessionId e41fc947 @ position 0 from 127.0.0.1:43795
Message to stream 10 from session e41fc947 (14@24) \<\<Hello World! 0>>
Message to stream 10 from session e41fc947 (14@64) \<\<Hello World! 1>>
Message to stream 10 from session e41fc947 (14@104) \<\<Hello World! 2>>
Message to stream 10 from session e41fc947 (14@144) \<\<Hello World! 3>>
Message to stream 10 from session e41fc947 (14@184) \<\<Hello World! 4>>
__--media driver killed using CTRL-C--__
Message to stream 10 from session e41fc947 (14@24) \<\<Hello World! 0>> 
Message to stream 10 from session e41fc947 (14@64) \<\<Hello World! 1>>
Message to stream 10 from session e41fc947 (14@104) \<\<Hello World! 2>>
Message to stream 10 from session e41fc947 (14@144) \<\<Hello World! 3>>
Message to stream 10 from session e41fc947 (14@184) \<\<Hello World! 4>>
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms

Basic Publisher Output:
Publishing to udp://localhost:40123 on stream Id 10
offering 0/1000000 yay!
offering 1/1000000 yay!
offering 2/1000000 yay!
offering 3/1000000 yay!
offering 4/1000000 yay!
offering 5/1000000 Offer failed because publisher is not yet connected to subscriber
offering 6/1000000 Offer failed because publisher is not yet connected to subscriber
offering 7/1000000 Offer failed because publisher is not yet connected to subscriber
offering 8/1000000 Offer failed because publisher is not yet connected to subscriber
offering 9/1000000 Offer failed because publisher is not yet connected to subscriber
offering 10/1000000 Offer failed because publisher is not yet connected to subscriber
offering 11/1000000 Offer failed because publisher is not yet connected to subscriber
offering 12/1000000 Offer failed because publisher is not yet connected to subscriber
offering 13/1000000 Offer failed because publisher is not yet connected to subscriber
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms

**Comment by brianhorst** [comment]
I've tracked this down to a line in Agrona in CountersManager.free():

countersBuffer.putLongOrdered(counterOffset(counterId), 0L);

I don't know why it puts 8 bytes of zeros before adding it to the free list, but the position being read by the subscription is in that location. The subscriber then believes it needs to read from the beginning. Removing that line causes this issue's behavior to go away. I don't know what other issues might be caused by the removed code but all system tests and unit tests in both projects still pass.

**Comment by mjpt777** [comment]
The counter should have been zero'ed on allocation not on free. Does the follow fix work for you?

https://github.com/real-logic/Agrona/commit/160eca7c12479e8cdf8bc73b82635d6e4def108d

**Comment by brianhorst** [comment]
Yep, I don't see the issue after that change to Agrona.
