### ISSUE TITLE
Align agent logging between Java and C drivers

### ISSUE THREAD

**Issue by vyazelenko** [real-logic/aeron#1072]
Currently Java driver logs many more events than the C driver. In addition C driver logs some events that are not logged by the Java driver (e.g. `AERON_MAP_RAW_LOG_OP`, `AERON_MAP_RAW_LOG_OP_CLOSE` etc.).

**Comment by mjpt777** [comment]
Agreed. We should keep things as consistent as possible.

We also need to add events for neighbors being added and removed for resolution to both.

**Comment by vyazelenko** [comment]
We should also think about using the same or similar logging format.
