### ISSUE TITLE
Add a string to Aeron connection 

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#1074]
proposal: 
now every application has a uniq ID for each aeron connection. It would be convenient if application could add a string value to connection and that value would be visible in the Aeron stats. Like
```java
Aeron.connect(new Aeron.Context().name("mySuperApp")); 
```

and in Aeron stats: 
```
 29:    1,537,738,373,872 - client-heartbeat: 1 mySuperApp
```

Of course every app could publish the id to it's own monitoring system and bla-bla-bla. But I try to come up with a [solution](https://github.com/easy-logic/aeron-monitoring) for aeron monitoring out the box and this value would be helpful.

**Comment by tmontgomery** [comment]
This can be done now. The application can `Aeron.addCounter` with the clientId value from `Aeron.clientId` and the string `mySuperApp` that it wants. No need to have Aeron do it.

**Comment by QIvan** [comment]
yes, application can do a lot of things. It can send a value to an elastic, can print in a file, you name it. I'm talking about what you've got out the box. Adding a counter is a kind of "advance" thing and I doubt everyone will do it by default and especially in the same format. So we cannot rely on stuff like that except it's done by `Aeron.connect()` method
