### ISSUE TITLE
Add metadata information for client's pub/subs 

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#1075]
in continuation to https://github.com/real-logic/aeron/issues/1074

right now only if an application makes some log or publishes somewhere values we could correlate which application is responsible for a sub/pub. 
the idea to have somewhere an information (a file similar to lossData? ) where another process could read the correlation between an aeron client Id and a pub/sub correlation Id. 

I imagine it like: 
```json 
{
  "42": {
     "publications": [1, 2],
     "subscriptions": [3, 4, 5]
  },
  "123": {
     "publications": [1],
     "subscriptions": [6, 7, 8]
  }
}
```
here we've got 2 clients on the MD 42 and 123, both created ConcurrentPublication with ID = 1 but the client 42 created also a publication with id = 2. But clients created 3 subscriptions. 
the exact format might be any, of course. But I hope you got my idea. 

with this information and https://github.com/real-logic/aeron/issues/1074 we could answer on questions like "Who is subscribed on channel <URI/stream id>?" out the box without any additional information from client side.

**Comment by mjpt777** [comment]
All the necessary metadata is available with client id relating to owner id on resources.
