### ISSUE TITLE
C++ function to set up initialPosition 

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#1076]
I don't see any equivalent of [the initialPosition function](https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/ChannelUri.java#L333) in C/C++ code, is there such function?

**Comment by tmontgomery** [comment]
The constituent parts can be used from https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp_wrapper/ChannelUriStringBuilder.h

**Comment by mjpt777** [comment]
An `initialPosition` method has been added to `ChannelUriStringBuilder`.
