### ISSUE TITLE
Connection opening delay

### ISSUE THREAD

**Issue by Ambrase** [real-logic/aeron#1080]
Hello

I'm currently experimenting with Aeron and I've run into the following problem:
I have an app where I have a publication and an app with a subscription. I use the reliable multicast, C++ Aeron driver, Centos 7. The publication is opened at the program start, but the subscription is only opened on demand.
My network's trip time from the publisher to the subscriber is 8-10 ms.
Although, the connection establishment takes about 130ms - 1 second time.
I expected it to be close to or slightly higher than TCP.

I tried to reduce delays in configuration but still have the same problem.
I also experimented with the pre-touch and sparse files without noticeable results.
How can I reduce both average and maximum connection opening time, so it will be closer to TCP? 
Or maybe is it expected that all publications and subscriptions are preopened much before data transmission?

My current configuration is:
```
-Djava.net.preferIPv4Stack=true
-Daeron.mtu.length=16k
-Daeron.socket.so_sndbuf=2m
-Daeron.socket.so_rcvbuf=2m
-Daeron.rcv.initial.window.length=2m
-Dagrona.disable.bounds.checks=true
-Daeron.term.buffer.sparse.file=false
-Daeron.pre.touch.mapped.memory=true
-Daeron.driver.timeout=1000 (1 sec)
-Daeron.client.resource.linger.duration=500000000 (500ms)
-Daeron.timer.interval=100000 (100 mcs)
-Daeron.rcv.status.message.timeout=20000000 (20ms)
-Daeron.publication.connection.timeout=40000000 (40 ms)
-Daeron.publication.linger.timeout 0
-Daeron.publication.unblock.timeout=2000000000 (2sec)
-Daeron.untethered.window.limit.timeout=1000000000 (1 sec)
-Daeron.untethered.resting.timeout=100000000 (100ms)
-Daeron.client.liveness.timeout=1000 000 000 (1 sec)
-Daeron.image.liveness.timeout=100000000  (100 ms)
-Daeron.flow.control.receiver.timeout=100000000 (100ms)
```

Thanks

**Comment by mjpt777** [comment]
You have changed most of the significant configuration from the default settings. Without a deep understand of how they interact this is not advisable. It would make most sense to get commercial consulting to understand your needs and have Aeron configured appropriately.

**Comment by Ambrase** [comment]
With the default settings, delays are 130ms - 12 seconds

**Comment by mjpt777** [comment]
Connection setup is much quicker than that typically. We would need to understand a lot more about your environment and usecase.
