### ISSUE TITLE
C++ build needs Java on OS X

### ISSUE THREAD

**Issue by echelon2020** [real-logic/aeron#1087]
C++ build needs Java on OS X even this is not mentioned in the list of prerequisites for c++.
Not an issue on my Mac. But I would like to build on an embedded arm64 system where there may be no java available...

**Comment by mjpt777** [comment]
The SBE compiler is written in Java and this is needed to generate the codecs. You can build the codec without Java on another platform. Where is the list of C++ prerequisites you are referring to?

**Comment by echelon2020** [comment]
Thanks. Sorry what is the SBE-compiler ??

Prerequisites....

It is on the project root-dir in the readme-file...

****************
snip
****************

C++ Build

You require the following to build the C++ API for Aeron:

3.6.1 or higher of CMake
C++11 supported compiler for the supported platform
C11 supported compiler for the supported platform
Requirements to build HdrHistogram_c.
Note: Aeron support is available for 64-bit Linux, OSX, and Windows.

For convenience, the cppbuild script does a full clean, build, and test of all targets as a Release build.

**Comment by mikeb01** [comment]
SBE: https://github.com/real-logic/simple-binary-encoding.

I've updated the README.md to reflect the build requirement.

**Comment by dendisuhubdy** [comment]
I did this

```
sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
java -version
```
