### ISSUE TITLE
Cannot use Aeron:ipc as transport

### ISSUE THREAD

**Issue by echelon2020** [real-logic/aeron#1088]
Wanted to test pic (shared mem) on local machine on OS X

*********
This seems not to work, wehre is the error ?

./Throughput -L 4096 -m 1000000 -p /Volumes/DevShm/aeron -c "aeron:ipc"   
       
Subscribing to channel aeron:ipc on Stream ID 1001
Streaming 1000000 messages of payload length 4096 bytes to aeron:ipc on stream ID 1001
Subscription: aeron:ipc 42:1001
Publication: aeron:ipc 43:1001:1369783632
Available image correlationId=43 sessionId=1369783632 at position=0 from aeron:ipc
libc++abi.dylib: terminating
zsh: abort      ./Throughput -L 4096 -m 1000000 -p /Volumes/DevShm/aeron -c "aeron:ipc"

**Comment by mikeb01** [comment]
Have you started the media driver?

**Comment by echelon2020** [comment]
Yes

It works without the "-c aeron:ipc" option

This is how I start the c media driver

****
% cat md
#!/usr/bin/env bash

AERON_BUILD_DIR=..

export AERON_DIR="/Volumes/DevShm/aeron"
export AERON_TERM_BUFFER_SPARSE_FILE="0"
export AERON_SOCKET_SO_SNDBUF="9216"
export AERON_MTU_LENGTH="8k"
export AERON_THREADING_MODE="SHARED"
export AERON_SHARED_IDLE_STRATEGY="spin"

${AERON_BUILD_DIR}/binaries/aeronmd

*********

Using udp it gives me this..

*******
% ./Throughput -L 4096 -m 1000000 -p /Volumes/DevShm/aeron                
Subscribing to channel aeron:udp?endpoint=localhost:20121 on Stream ID 1001
Streaming 1000000 messages of payload length 4096 bytes to aeron:udp?endpoint=localhost:20121 on stream ID 1001
Subscription: aeron:udp?endpoint=localhost:20121 5:1001 it 
Publication: aeron:udp?endpoint=localhost:20121 6:1001:-388967803
Available image correlationId=7 sessionId=-388967803 at position=0 from 127.0.0.1:49914
1.204e+05 msgs/sec, 4.933e+08 bytes/sec, totals 997958 messages 3898 MB payloads
Done streaming. Back pressure ratio 123.523
*******

using ipc

******
% ./Throughput -L 4096 -m 1000000 -p /Volumes/DevShm/aeron -c "aeron:ipc?"
Subscribing to channel aeron:ipc? on Stream ID 1001
Streaming 1000000 messages of payload length 4096 bytes to aeron:ipc? on stream ID 1001
Subscription: aeron:ipc? 2:1001
Publication: aeron:ipc? 3:1001:-388967804
Available image correlationId=3 sessionId=-388967804 at position=0 from aeron:ipc
libc++abi.dylib: terminating
zsh: abort      ./Throughput -L 4096 -m 1000000 -p /Volumes/DevShm/aeron -c "aeron:ipc?"
******

**Comment by mjpt777** [comment]
What is in the distinct error log? You can find out by running error stat.

**Comment by echelon2020** [comment]
Nothing....

% ./ErrorStat                                                             

0 distinct errors observed.

For me this seems to be kind of a crash.
I tried to debug that down but according to lldb the build within /Debug/binaries seems to contain no debug info. If I try to build a simple hello world on my machine using my clang toolchain it puts out an additional filename.dSYM with the symbols. Here debugging works....

**Comment by echelon2020** [comment]
Update:
Aeron:ipc works up to a message size of 1376bytes

./Throughput -L 1376 -m 100000000 -p /Volumes/DevShm/aeron -c "aeron:ipc"

Subscribing to channel aeron:ipc on Stream ID 1001
Streaming 100000000 messages of payload length 1376 bytes to aeron:ipc on stream ID 1001
Subscription: aeron:ipc 2:1001
Publication: aeron:ipc 3:1001:-1550552481
Available image correlationId=3 sessionId=-1550552481 at position=0 from aeron:ipc
1.64e+07 msgs/sec, 2.257e+10 bytes/sec, totals 99980584 messages 131200 MB payloads
Done streaming. Back pressure ratio 0.360949

****
media driver is started like this:

+++++
#!/usr/bin/env bash

set +e

killall aeronmd

AERON_BUILD_DIR=..

export AERON_DIR="/Volumes/DevShm/aeron"
export AERON_TERM_BUFFER_SPARSE_FILE="0"
export AERON_SOCKET_SO_SNDBUF="9216"
export AERON_MTU_LENGTH="8k"
export AERON_THREADING_MODE="SHARED"
export AERON_SHARED_IDLE_STRATEGY="spin"

echo "Start media driver"
${AERON_BUILD_DIR}/binaries/aeronmd &
-----

Seems to be a strange limit btw...

**Comment by mikeb01** [comment]
You will need to use `AERON_IPC_MTU_LENGTH`.

**Comment by echelon2020** [comment]
Thanks. ok I see.
Which itself is limited by MAX_UDP_PAYLOAD_LENGTH which seems so be somewhat strange to me.....
