### ISSUE TITLE
UDP via shared Media Driver == IPC?

### ISSUE THREAD

**Issue by tipame** [real-logic/aeron#1093]
Hello, i'm using Aeron as transport for Akka. In Akka there is no way to configure IPC (only UDP is available).
In my scenario 2 modules (2 JVM process) run on same physical device and use shared Media Driver. 
In my logic - there is no need to send messages via network (UDP) because both sender and  reciever connected to same Media Driver. So my thought - in that configuration Aeron should work just like IPC (with the same performance).
Is it right?

PS: in production modules will run in one Kubernetes Pod (in differend containers with shared Media Driver Dir).

**Comment by mjpt777** [comment]
Aeron can communicate over IPC (aka shared memory) on the same media driver if you can set the channel to `aeron:ipc`.

**Comment by tipame** [comment]
I use Akka framework witch relies on  Aeron UDP as transport (no way to configure channel to aeron:ipc).
The question was: does Aeron send data over UDP even if both interacting sides connected to one Media Driver?

**Comment by mjpt777** [comment]
If the channel is specified as UDP then Aeron will use UDP.
