### ISSUE TITLE
Driver gets wedged using PublisherTool & SubscriberTool with 100 stream IDs

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#110]
Start driver:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.MediaDriverTool
```

Start subscriber:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.SubscriberTool -c udp://localhost:30123#1-100
```

Start publisher sending large-ish messages:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.PublisherTool -s 90000-90001 -c udp://localhost:30123#1-100
```

Wait a few seconds for everything to get created and start; some messages get through, and a few seconds later, messages stop.  Sometimes, a little while after that (up to a few minutes later, with no messages going through), the clients report that the driver has timed out.

It doesn't seem that the driver is actually deadlocked, exactly - it's still "doing" things.  Sending, receiving, scanning for gaps... it just appears it has such an utterly overwhelming amount of work to do that it never gets caught up enough to do any more work.

**Comment by tmontgomery** [comment]
I believe that if the publisher is trying to saturate all 100 streams without congestion control that it is likely that huge amounts of loss will occur and slow everything down painfully.

It would be great to see what happens now with the latest set of changes, though.

**Comment by tmontgomery** [comment]
What OS is this?

On Mac, I can reproduce this. But I've also tracked it down to over 9GB of space on the file system and the VM subsystem being totally thrashed causing the timeout.

**Comment by tmontgomery** [comment]
90K messages to 100 pubs/subs. So, 200 for a single driver. As fast as possible. A bit of pressure on the VM. Just a tad.

It's also almost 10GB of space in the Aeron directory.

On Mac, I can sustain this at 100 mps without really breathing hard. Things are fine.

**Comment by tmontgomery** [comment]
On Linux, I couldn't create 100 pubs/subs, `/dev/shm` runs out of memory. However, when I reduce this to 50, everything is created and runs fine even at no rate set.

So, I am closing this.
