### ISSUE TITLE
why my publisher and subscriber can not find driver

### ISSUE THREAD

**Issue by JsonStarrk** [real-logic/aeron#1100]
Hi，Dear。
i‘m a rookie for aeron and multicast。need your help
 I deploy my MediaDriver on server ip：192.168.4.120，
and deploy subscriber and publisher on server ip ：192.168.4.119
then i watch log find ：
io.aeron.exceptions.DriverTimeoutException: FATAL - no driver heartbeat detected
i know it means i cannot link my driver。but when they on same server ，it can link 。why
 
thank you very much

**Comment by jvirtanen** [comment]
You have to run a media driver on each host (server) that has Aeron clients (publishers or subscribers). The Aeron clients [communicate with the media driver over inter-process communication (IPC)](https://github.com/real-logic/aeron/wiki/Design-Overview).

A better place for questions like this than GitHub issues is [the Gitter chat](https://gitter.im/real-logic/Aeron).

**Comment by mjpt777** [comment]
You need to ensure the aeron directory name is the same for driver and client on the same machine.

**Comment by JsonStarrk** [comment]
> You need to ensure the aeron directory name is the same for driver and client on the same machine.

every machine need to deploy a driver?

**Comment by JsonStarrk** [comment]
> You have to run a media driver on each host (server) that has Aeron clients (publishers or subscribers). The Aeron clients [communicate with the media driver over inter-process communication (IPC)](https://github.com/real-logic/aeron/wiki/Design-Overview).
> 
> A better place for questions like this is [the Gitter chat](https://gitter.im/real-logic/Aeron).

hey，if  i need to deploy 50 machine in a multicast ，Do I need to deploy a driver on each node？

**Comment by mjpt777** [comment]
Yes, each machine requires a media driver.

**Comment by JsonStarrk** [comment]
> Yes, each machine requires a media driver.

Thank you very much～

**Comment by JsonStarrk** [comment]
> Yes, each machine requires a media driver.

hey，sorry，i deploy media on each machine，and deploy pub on a machine，sub on b machine，why my pub's log says Offer failed because publisher is not connected to a subscriber？
i conf -Daeron.sample.channel=aeron:udp?endpoint=224.0.1.1:40456 &&-Daeron.sample.streamId=20 on my subscriber and publisher, i'm wrong?
