### ISSUE TITLE
[C] On Windows, aeron_delete_directory requires double-null terminated string

### ISSUE THREAD

**Issue by buybackoff** [real-logic/aeron#1108]
According to the [docs](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/aa453691(v=msdn.10)) and a [SO question](https://stackoverflow.com/questions/4180351/unable-to-delete-a-folder-with-shfileoperation/4180426), `SHFILEOPSTRUCT`'s parameter `pFrom` must be double-null terminated:

> An additional NULL character must be appended to the end of the final name to indicate the end of pFrom.

Here, the `dir` is taken from a context directly: https://github.com/real-logic/aeron/blob/654949cd1e58e36ed35a192887a98e638a06c754/aeron-client/src/main/c/util/aeron_fileutil.c#L163-L180

and

https://github.com/real-logic/aeron/blob/654949cd1e58e36ed35a192887a98e638a06c754/aeron-driver/src/main/c/aeron_driver.c#L1046-L1049

The dir is set in `aeron_driver_context_set_dir` like this: https://github.com/real-logic/aeron/blob/654949cd1e58e36ed35a192887a98e638a06c754/aeron-driver/src/main/c/aeron_driver_context.c#L1296-L1303

This _likely_ leads to `SHFileOperation` silent failure and `dirs_delete_on_shutdown` having no effect. "Likely" because I've not tested the C code, but am observing that the setting is not working when I run a C driver embedded into .NET process. And from the snippets the dir is not appended with the second null anywhere.

**Comment by mjpt777** [comment]
@buybackoff Can you test with main to see if this if fixed for you?

**Comment by buybackoff** [comment]
@mjpt777 The dir is still not deleted. `cnc.dat` and `loss-report.dat` are there.

Am I right that calling `aeron_driver_close` followed by `aeron_driver_context_close` is enough to expect the the dir is deleted? Sleeping for 65 seconds doesn't help. I could delete the dir manually during the sleep after the closing, so nothing is locking the files after the two close calls. When trying to delete the files before the calls to close, the files are locked as expected.

**Comment by buybackoff** [comment]
I found that `SHFileOperation` returns code 32 `ERROR_SHARING_VIOLATION`. What is strange is that in `aeron_driver_context_close` we have:

```
    aeron_unmap(&context->loss_report);
    aeron_unmap(&context->cnc_map);
```
So we try to delete the directory before unmapping the files.

**Comment by buybackoff** [comment]
In `strncpy` aren't we reading past the dir length when copying with `dir_length + 2`?

Also, according to the same docs, `pTo` should be null when unused. It was an empty string. Other parameters are also just simpler to keep as nulls.

```
    strncpy(temp, dir, dir_length);
    
    SHFILEOPSTRUCT file_op =
        {
            NULL,
            FO_DELETE,
            temp,
            NULL,
            FOF_NOCONFIRMATION |
            FOF_NOERRORUI |
            FOF_SILENT,
            false,
            NULL,
            NULL
        };
```
I was testing with this `file_op` and used some one-off logging to read the result.

**Comment by mjpt777** [comment]
Yes the driver was trying to delete the directory while the files were still mapped. I'm move the delete of the aeron directory from the driver to driver context close.

**Comment by buybackoff** [comment]
It works now, thank you!
