### ISSUE TITLE
[C++] ExclusivePublication inheritance difference in comparison with Java

### ISSUE THREAD

**Issue by sshanks-kx** [real-logic/aeron#1109]
ExclusivePublication looks like it has a relation to Publication in Java, but not C++.

C++:
https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp/ExclusivePublication.h
Java:
https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/ExclusivePublication.java

Not sure if this was done on purpose or not.

Noticed when an app was created to use a Publication object, then decided to try to create an ExclusivePublication to see how it compared which broke some of the interfaces as they expected a Publication object (whereas I suspect the java version wouldn't have had the same issue).

**Comment by mjpt777** [comment]
The C++ client uses parametric polymorphism and the Java client uses inheritance based polymorphism.  If  the C++ client used inheritance and virtual methods this would introduce a performance cost. With Java this can be avoided by runtime optimisation at call sites.

Other than the templated type are you seeing any differences in the API?

**Comment by sshanks-kx** [comment]
OK thanks, I suspected that might be the answer. I'll try changing the code being used.

Not tried to much between the 2 as yet.
The one thing I did notice, which caught me out, is the Java examples cover much more ground than the C++ ones. So when starting with the C++ examples (and not with Java) there was time spent wondering how things were intended to be used, til I noticed the Java examples provide much more content & should currently also be referenced (even when not using Java).
i.e. 
Started looking at these thinking they were the complete set of sample code
https://github.com/real-logic/aeron/tree/master/aeron-samples/src/main/cpp
and then noticed these
https://github.com/real-logic/aeron/tree/master/aeron-samples/src/main/java/io/aeron/samples

You can close this issue off if you wish.

Thanks

**Comment by mjpt777** [comment]
Yes the Java samples are more extensive. It is also worth looking at the Java system tests for more examples.
