### ISSUE TITLE
[C++] Method differences between ExclusivePublication/Publication and language versions

### ISSUE THREAD

**Issue by sshanks-kx** [real-logic/aeron#1110]
Tried moving from Publication to ExclusivePublication in C++. 
Noticed these difference between the 2, and also with comparing to Java/cpp_wrapper. 
Ive tried to list what I can see:

* addDestination - returns a value in C++ Publication, returns value in CPP_WRAPPER Publication/ExclusivePublication, doesn't return a value in C++ ExclusivePublication, doesn't return a value in Java Publication (and therefore ExclusivePublication).
* removeDestination - returns a value in C++ Publication, returns value in CPP_WRAPPER Publication/ExclusivePublication, doesn't return a value in C++ ExclusivePublication, doesn't return a value in Java Publication (and therefore ExclusivePublication).
* findDestinationResponse - exists in C++ Publication, exists in CPP_WRAPPER Publication/ExclusivePublication, doesn't exist in C++ ExclusivePublication, doesn't exist in Java

Checking if these are on purpose, or issue. May be some changes related to threadsafety on some versions (haven't yet traced code/etc to check)

Thanks

**Comment by mjpt777** [comment]
Thanks @sshanks-kx, the existing `ExclusivePublication` had not been updated to match `Publication` in the C++ client. The wrapper is consistent. I'll push a fix shortly. The Java client is different having a blocking add/remove method and async alternatives given the different idioms of the language.
