### ISSUE TITLE
Opaque AgentTerminationException being routinely thrown 

### ISSUE THREAD

**Issue by vemv** [real-logic/aeron#1112]
Hi,

in a simple application's test suite which starts up Aeron, exercises some basic features and then tears down the system setup, I am perceiving the following being printed to stdout:

```
1608763406602 Exception:
org.agrona.concurrent.AgentTerminationException
	at io.aeron.ClientConductor.doWork(ClientConductor.java:206)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.lang.Thread.run(Thread.java:748)
```

(that appears to be the whole stacktrace)

...this stacktrace is printed about 30m after the  system has been tear down. Which can be a bit surprising/unsettling because maybe I was doing something else (within the same JVM) so suddenly I get interrupted with something that can only be ignored, atm.

Could you share any insight of why this exception is thrown, and what can be done about it? Might be a good item to add to the FAQ.

Thanks - V

**Comment by vemv** [comment]
Worth adding, I use the `interrupt` mechanism to stop a certain thread that was invoking `some_subscription.poll(...`. That appears to be caught and rethrown here:

https://github.com/real-logic/aeron/blob/9cc8458d892333160e160a92fe34e509969bef37/aeron-client/src/main/java/io/aeron/ClientConductor.java#L1139

However the AgentTerminationException I see in stdout does not mention `thread interrupted`.

**Comment by mjpt777** [comment]
What version of Aeron are you using?

**Comment by vemv** [comment]
`io.aeron/aeron-all "1.27.0"`

**Comment by mjpt777** [comment]
This exception is used to terminate the client agent after the `isTerminating` field is set due to the previous interrupt. Looks like your code caught the exception during an add or close of a resource. I've changed the code in main to throw an `InterruptedException` instead.  https://github.com/real-logic/aeron/commit/475ccc410334563e5a0788c6552e56cb5a498437

**Comment by vemv** [comment]
That looks promising, thanks!
