### ISSUE TITLE
Multicast channel with remote & local client - cant receive on both at the same time

### ISSUE THREAD

**Issue by sshanks-kx** [real-logic/aeron#1116]
I dont seem to be able to run a subscriber locally & remotely at the same time - **is this normal or is there a config I have missed?**

Publisher on box `local ip`
./StreamingPublisher -c "aeron:udp?endpoint=224.0.1.1:20121|interface=`local ip`" -m 1000000000

I can run multiple clients on remote box, and they receive data e.g.
./RateSubscriber -c "aeron:udp?endpoint=224.0.1.1:20121|interface=`remote ip`"

If I run a local client also e.g.
./RateSubscriber -c "aeron:udp?endpoint=224.0.1.1:20121|interface=`local ip`"
nothing is received by this local client, until the remote ones are killed, then it'll start getting data.

The inverse also occurs i.e. if I start the local client first it'll receive data but the remote ones wont, until the local client killed.

**Comment by sshanks-kx** [comment]
Might be related to #552 , if on that issue the remote client was accidently left running & same thing was done

**Comment by mikeb01** [comment]
This is likely to do with flow control.  The default flow control strategy for the driver is max.  This will mean that slower subscribers that can't keep up will end up missing messages.  To make this work, use `|fc=min` at the end of the aeron URI and you should see messages on both subscribers (tested locally and I see messages on both subscribers).  

More detail on the various forms of flow control and their configuration options are available here: https://github.com/real-logic/aeron/wiki/Flow-and-Congestion-Control#flow-control
