### ISSUE TITLE
unused param -Wall

### ISSUE THREAD

**Issue by danny-pav** [real-logic/aeron#1119]
https://github.com/real-logic/aeron/blob/4bb183dc737418ed6f7b45aa3bfeea7fa5b2425d/aeron-client/src/main/cpp/BufferBuilder.h#L75

unused param: header

**Comment by mjpt777** [comment]
Fixed by https://github.com/real-logic/aeron/commit/166271a4f258ec28232b4f234d9bb4e270f45045
