### ISSUE TITLE
putDouble / getDouble

### ISSUE THREAD

**Issue by danny-pav** [real-logic/aeron#1121]
https://github.com/real-logic/aeron/blob/4bb183dc737418ed6f7b45aa3bfeea7fa5b2425d/aeron-client/src/main/cpp/concurrent/AtomicBuffer.h#L35

there is a putInt## / getInt## for 8, 16, 32, 64 but no putDouble / getDouble

**Comment by mjpt777** [comment]
We have not needed these methods ourselves. Feel free to send a PR is you need them.

**Comment by danny-pav** [comment]
Martin-
I had tried to make changes via PR before for some of the simpler issues (1119 or 1120 -- can't remember) and was unable to.  I will try again and let you know what error I was getting.  I feel like it was a permissioning issue of some sort.  Additionally, is there a naming standard for branches for the PR?
Thanks,
Dan

________________________________

**Comment by mikeb01** [comment]
There are no naming conventions for branches, but in order to raise a PR you need to fork your own copy of the repo and create the branch there.

**Comment by danny-pav** [comment]
That's the problem.  I did not create a fork.  Simply made a clone, created a branch, then pushed to branch of same name.  (this is the workflow i use professionally)

________________________________

**Comment by mjpt777** [comment]
Closing due to no further activity.
