### ISSUE TITLE
Why subscription is not thread safe

### ISSUE THREAD

**Issue by ratanasov1** [real-logic/aeron#1126]
I have found that "The logbuffer is an MPMC structure. So, multiple Publication threads and multiple Subscription threads all are fine." from [here](https://gitter.im/real-logic/Aeron?at=5aba16032b9dfdbc3a2850c6)

Then why concurrent publication is thread safe and subscription is not?

**Comment by tmontgomery** [comment]
Subscriptions can be thread safe as long as you use an individual Subscription object per thread.
