### ISSUE TITLE
Is it safe to publish to the same channel and stream id across machines?

### ISSUE THREAD

**Issue by sheepgrass** [real-logic/aeron#1131]
As from wiki here ([https://github.com/real-logic/aeron/wiki/Client-Concurrency-Model#publications](https://github.com/real-logic/aeron/wiki/Client-Concurrency-Model#publications)), it states that:
> Aeron Publications are thread safe within and across processes.

However, is it safe to publish to the same channel and stream id across machines?  Will there be any unexpected behavior doing so?

**Comment by tmontgomery** [comment]
It is safe. But, each publication when using multiple drivers will appear as separate images. Also, for multiple subscribers reading the messages the order of messages across the images will not be the same. i.e. not totally ordered.
