### ISSUE TITLE
Broken POM coordinates for Aeron, Agrona and SBE

### ISSUE THREAD

**Issue by vyazelenko** [real-logic/aeron#1138]
All three projects have the same problem with the POM definition, i.e. there is `<packaging>pom</packaging>` defined.

For example [sbe-tool-1.21.0.pom](https://repo1.maven.org/maven2/uk/co/real-logic/sbe-tool/1.21.0/sbe-tool-1.21.0.pom) contains:
```xml
<groupId>uk.co.real-logic</groupId>
<artifactId>sbe-tool</artifactId>
<version>1.21.0</version>
<packaging>pom</packaging>
<name>sbe</name>
```
whereas  [sbe-tool-1.16.1.pom](https://repo1.maven.org/maven2/uk/co/real-logic/sbe-tool/1.16.1/sbe-tool-1.16.1.pom):
```xml
<groupId>uk.co.real-logic</groupId>
<artifactId>sbe-tool</artifactId>
<version>1.16.1</version>
<name>sbe</name>
```

As the result Maven Central suggest to define dependency for a POM file instead of the corresponding jar, e.g.:
```xml
<dependency>
    <groupId>uk.co.real-logic</groupId>
    <artifactId>sbe-tool</artifactId>
    <version>1.21.0</version>
    <type>pom</type>
</dependency>
```

**Comment by mjpt777** [comment]
Do we need to do anything about this?

**Comment by vyazelenko** [comment]
Fixed with https://github.com/real-logic/aeron/commit/2845bf77baebcd733cc48fb0a2d21f443dfd08ff.
