### ISSUE TITLE
Particular stream stops receiving data. 

### ISSUE THREAD

**Issue by alexkoon** [real-logic/aeron#1139]
We have observed one particular stream id on a particular server not receiving messages. Other stream id on the same channel are processing fine. 

For this particular session on the server, the rcv-pos is moving and then it just stops increasing stating at the same value. Checking other servers, the rcv-pos for this stream is moving. The process sending the messages happens to be on the same server. On checking the snd-pos, I can see this is continuing to increase in line with the messages sent.

This isn't high volume messages, and we can control when to send this (off the back of some external human event). So doubt it is load related. The producer and subscribers has no errors and other messages on other streams work fine. Just happens to be this particular stream id. I can start a new command line process to subscribe to this stream on the deaf server and this too cannot receive messages.

Restarting the media driver, and having the components reconnect to the new media driver resolves the 'issue'. One unconfirmed observation was a server was deaf for a period then starting working again with no changes - I say unconfirmed because this was in the early days off suspecting this problem and we have no logs or anything to confirm.

Any ideas where I can look further into this or where to investigate to try and determine the root cause before upgrading to the latest?

(Aeron version 1.28.2 used in the media driver and the clients).

**Comment by mikeb01** [comment]
I recommend updating and trying to reproduce on the latest as the best course of action.

**Comment by alexkoon** [comment]
I have updated only the client to the latest, then only the media driver, then both and can reproduce the problem. 
I had a producer app on Server A, a consumer on A. Then a consumer on Server B and ran a test.  The consumer app is the same for both servers. Both consumer apps on A and B became deaf at the same time. I had a separate app on a third server and that continued fine.
Next test was simple changing the stream id from 201 to 211. This fixed the issue. 

I would really like to find out the cause so any help investigating or where to look appreciated. I find it odd that servers A and B stopped at the same time. 

Some other observations. When restarting the deaf apps did not resume the stream of data. What I did observe was the 'missing' data seemed to be pushed to the consumer and then continued deaf. Restarting the producer app seems to have resumed data flow until the inevitable stop. 

I have a way forward - but very strange to change the stream id is ok. I am thinking something of a fixed nature (say like a buffer that eventually fills, or a threshold value being hit) for A and B to reach deafness at the same time. Or an external factor that impacts both servers.

**Comment by alexkoon** [comment]
Further information. 
We have a bunch of different applications consuming the same message via Aeron. We have narrowed down the cause now. One such application is a using Chronicle Fix and we have integrated the Aeron dispatch polling to use the main Chronicle Fix thread. For whatever reason we can see that this works up to a point and then stops receiving the callback messages. The thread is dead, polling is continuously called. We an see that but the call to poll on the subscription doesn't ever return with data. 

Exactly the same code placed in a different thread works continuously with problem.

**Comment by tmontgomery** [comment]
If you can isolate this into a test that doesn't include Chronicle, we can take a look.

**Comment by alexkoon** [comment]
Had to leave this for a while but had a chance to look more. Will try and see if we can strip out and have a raw test and try and reproduce. However, in our own unit test for testing our API (on top of Aeron) I can reproduce this to an extent. The unit test consists of 4 publications, 4 subscriptions. The dispatcher is a single thread loop through 4 subscriptions. Messages are iteratively published.

When we use an ipc channel, or a channel aeron:udp?endpopint=localhost:9888, the unit test passes. All publications are published, and subscriptions receive all messages and the messages are as expected and in order.

However, when we use a channel defines as aeron:udp?endpoint=239.100.0.1:20000, the same unit test fails as the subscriptions stops 'receiving data after a particular point (for 32 bytes of data per messages, after 1364 messages received, there is no more). With a separate thread per subscription polling this is not a problem.

This has no Chronicle in the code or unit test.

Hoping this may spark a suspicion or rings a bell to help us narrow the problem area.

**Comment by alexkoon** [comment]
Found the issue now. The changes made to our API to allow a custom dispatcher was a 'hack' utilising a a static reference to the single thread dispatcher. This being static was reused which worked as all dispatchers were attached to this single instance and satisfied the requirements. However, the above problems happened with deafness. 

Changing the API to utilise a Supplier<Dispatcher> and then supplying the same instance changed the behaviour - still single threaded as expected but the eventual deafness did not manifest.

Not 100% sure what is going on and why the difference but for now its fixed and we can move on. Will have to invest some time and see if we can reproduce via a raw unit test to give back.
