### ISSUE TITLE
Issue with ReplayLog when recording log last entry is a leadership term

### ISSUE THREAD

**Issue by scyd** [real-logic/aeron#1146]
When trying to replay from archive log and the recording log last entry is leadership term, if a appendSnapshot is called and does not match any invalidated snapshot because logPosition might differ, it might check for leadershipTerm independently of the validity of the entry.

https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/RecordingLog.java#L957-L962

In case, we invalidate the last log leadershipTerm entry, it will not take it into consideration.

**Comment by mjpt777** [comment]
Thanks for the report. Can you create a test to illustrate the issue so we have a better understanding?

**Comment by mjpt777** [comment]
Closing due to no further information.
