### ISSUE TITLE
Larger messages not being reassembled properly with the C client

### ISSUE THREAD

**Issue by irisliu88** [real-logic/aeron#1158]
When testing with the C `basic_publisher` and `basic_subscriber`, if I send larger messages (~8kb), I am getting empty bytes in the received buffer of the `poll_handler`. Specifically missing parts of/the entire first message. Increasing the MTU to be larger than the message does resolve the issue.

**Comment by tmontgomery** [comment]
Try with the latest head of the repo.

**Comment by irisliu88** [comment]
That solves it - thank you!
