### ISSUE TITLE
Evaluate performance of non-final Header methods

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#117]
Making the methods on the Header class non-final would make it easier to mock the header. The downside is potential performance hit from virtual calls. Need to bench to make sure its not important.

**Comment by mjpt777** [comment]
It does have a performance impact. I'm closing for now unless you believe you cannot make progress without it?

**Comment by mjpt777** [comment]
Powermock can be used as an alternative which can mock final methods.
