### ISSUE TITLE
Second Subscriber causes Segfault

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#119]
Looks like it happens when there's data to poll off of the subscription.

Stack: [0x00007f43c00d1000,0x00007f43c01d2000],  sp=0x00007f43c01d05a0,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 910 C1 uk.co.real_logic.aeron.common.concurrent.logbuffer.TermReader.read(ILuk/co/real_logic/aeron/common/concurrent/logbuffer/DataHandler;I)I (117 bytes) @ 0x00007f43c93398bd [0x00007f43c93396a0+0x21d]
J 912 C1 uk.co.real_logic.aeron.Connection.poll(I)I (86 bytes) @ 0x00007f43c933cb3c [0x00007f43c933c8a0+0x29c]
J 880 C1 uk.co.real_logic.agrona.concurrent.AtomicArray.doLimitedAction(IILuk/co/real_logic/agrona/concurrent/AtomicArray$ToIntLimitedFunction;)I (85 bytes) @ 0x00007f43c932ba34 [0x00007f43c932b700+0x334]
J 854 C1 uk.co.real_logic.aeron.Subscription.poll(I)I (44 bytes) @ 0x00007f43c931f164 [0x00007f43c931ebe0+0x584]
J 920 C1 uk.co.real_logic.fix_gateway.logger.Archiver.doWork()I (10 bytes) @ 0x00007f43c934021c [0x00007f43c9340180+0x9c]
j  uk.co.real_logic.agrona.concurrent.AgentRunner.run()V+42

**Comment by mjpt777** [comment]
I've added a system test for this and it passes without a access violation. 

https://github.com/real-logic/Aeron/blob/master/aeron-system-tests/src/test/java/uk/co/real_logic/aeron/MultiSubscriberTest.java

Is it possible your subscription has been closed and you are using it after that?

**Comment by mjpt777** [comment]
I've added checks to ensure publications and subscriptions are open when being used. Can you check if this catches the issue?

**Comment by RichardWarburton** [comment]
No - I've just pulled/reinstalled and its still segfaulting. Will try to narrow it down a bit more.

**Comment by RichardWarburton** [comment]
Managed to produce another segfault around what looks to be the same/similar issue:

```Stack: [0x00007efef9787000,0x00007efef9888000],  sp=0x00007efef9886240,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 870 C1 uk.co.real_logic.aeron.common.concurrent.logbuffer.TermReader.read(ILuk/co/real_logic/aeron/common/concurrent/logbuffer/DataHandler;I)I (117 bytes) @ 0x00007eff113068a9 [0x00007eff113066c0+0x1e9]
J 869 C1 uk.co.real_logic.aeron.Connection.poll(I)I (86 bytes) @ 0x00007eff11307aac [0x00007eff11307820+0x28c]
J 882 C1 uk.co.real_logic.agrona.concurrent.AtomicArray.doLimitedAction(IILuk/co/real_logic/agrona/concurrent/AtomicArray$ToIntLimitedFunction;)I (85 bytes) @ 0x00007eff1132430c [0x00007eff11324000+0x30c]
J 865 C1 uk.co.real_logic.aeron.Subscription.poll(I)I (48 bytes) @ 0x00007eff1130c404 [0x00007eff1130c140+0x2c4]
J 879 C1 uk.co.real_logic.fix_gateway.logger.Archiver.doWork()I (10 bytes) @ 0x00007eff11324a94 [0x00007eff11324a00+0x94]
j  uk.co.real_logic.agrona.concurrent.AgentRunner.run()V+33
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x627306]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x627811]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x627cb7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x6a0e4e]  thread_entry(JavaThread*, Thread*)+0x7e
V  [libjvm.so+0x9e2fef]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0x9e31b5]  JavaThread::run()+0x1b5```

**Comment by mjpt777** [comment]
I believe this now should be fixed. Can you confirm?

**Comment by RichardWarburton** [comment]
Yes, I think this is fixed thanks.
