### ISSUE TITLE
[C++] poll ocasionally returns nothing on image that has data in it

### ISSUE THREAD

**Issue by indiosmo** [real-logic/aeron#1194]
Hi. I have an issue where occasionaly a subscription has an image available, the publisher has sent data, everything looks good yet `poll()` returns nothing.

The issue happens more often under debug builds or running under gdb which suggests some sort of resource starvation but it does happen occasionally on release mode as well.

I have checked for possible races by debug printing the thread_ids and running under TSAN and no races have been detected (other than in the *concurrent* aeron classes which I'm assuming are safe to ignore as false positives).

Below is a description of the protocol and the threading model along with the results for both a sucessful and a failed run of a sample ping/pong test.
I have also attached a screenshot of both runs (client/server/aeron stat) along with the buffer log.
`/dev/shm` was cleared before each run.

I also checked imageArraySize when polling and it shows 1 so the image looks in fact available.
The issue sometimes happens on the other way around, i.e.: The server receives the establish packet and writes the response but the client poll() never returns.

### Build Params
Aeron: 1.34.0

gcc version 11.1.0 (GCC) running under WSL on Windows 10.

Build Flags:
`/home/msi/cpp_workspace/gcc-11.1.0/bin/g++ -DBOOST_ALL_NO_LIB -DCLIENT_SHARED -DDISABLE_BOUNDS_CHECKS -DDLL_EXPORT -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -D__PROJECT_SOURCE_DIR__=\\\"/home/msi/cpp_workspace/abacus/_build/release/_deps/aeron-src\\\" -I/home/msi/cpp_workspace/abacus/mil -I/home/msi/cpp_workspace/aba    cus/_build/release/_deps/fmt-src/include -I/home/msi/cpp_workspace/abacus/_build/release/_deps/expected-src/include -I/home/msi/cpp_workspace/abacus/_build/release/_deps/magic_enum-src/include -I/home/msi/cpp_workspace/abacus/_build/release/_deps/namedtype-src/include -I/home/msi/cpp_workspace/abacus/_build/release/_deps/aeron-src/aeron-client/src/main/cpp -I/home/msi/cpp_works    pace/abacus/_build/release/_deps/hdr_histogram-src/src -I/home/msi/cpp_workspace/abacus/_build/release/_deps/readerwriterqueue-src -I/home/msi/cpp_workspace/abacus/_build/release/_deps/spdlog-src/include -isystem /home/msi/cpp_workspace/boost_1_76_0/include -O3 -DNDEBUG -fPIE -ggdb -fdiagnostics-color=always -fstrict-aliasing -Wall -Wextra -Werror -Wcast-align -Wfatal-errors -W    dangling-else -Wnull-dereference -Wpedantic -Wimplicit-fallthrough -Wno-unused-parameter -pedantic-errors -Werror=format -Wno-null-dereference -DBOOST_ASIO_CONCURRENCY_HINT_DEFAULT=1 -DLinux -DSAVE_CLORDID -O3 -std=c++2a -o CMakeFiles/atp_echo_server.dir/src/main.cpp.o -c /home/msi/cpp_workspace/abacus/mil/libs/atp/examples/echo_server/src/main.cpp`

### Protocol
I have the following two-way protocol:

1. Server opens an ipc Subscription on stream 1234 and starts polling.
2. Client opens an ipc Subscription on stream 4321 and starts polling.
3. Client opens an ExclusivePublication to stream 1234
4. Client sends an "establish" packet to server containing the return channel/stream information
5. Server opens an ExclusivePublication back to client using the data from the establish packet
6. Server replies to client with an establishment_ack
7. Client/Server ready to transfer.

Client keeps trying to send establish ever X seconds until it succeeds in case `offer()` returns "NOT_CONNECTED".

The server replies with an ack every time an establish is received in case it tries to ack while still "NOT_CONNECTED".

### Thread Model
The model is the same for both client and server.

There is a main thread which calls `poll()` on the Subscription on a loop.

There is an aux thread where `Aeron::findSubscription()` and `Aeron::findExclusivePublication()` run in a loop on until success and then the resulting shared_ptr is marshalled back to the main queue via an spsc_queue.

Image available/unavailable handlers run in the Conductor thread, are marshalled to the aux thread via an spsc_queue and from the aux thread are marshalled to the main thread via an spsc_queue.

### Success
[success_client.log](https://github.com/real-logic/aeron/files/6736118/success_client.log)
[success_server.log](https://github.com/real-logic/aeron/files/6736119/success_server.log)
![success](https://user-images.githubusercontent.com/4126274/123860357-3061b500-d8fc-11eb-8268-2f87feb04461.png)

### Error
[error.log](https://github.com/real-logic/aeron/files/6736120/error.log)
![error](https://user-images.githubusercontent.com/4126274/123860364-322b7880-d8fc-11eb-8af1-c11b7e70fc5f.png)

**Comment by tmontgomery** [comment]
As the sub-pos never moves, the most likely issue is that the various duty cycles and loops are too aggressive. Try to use a yielding or backoff idle strategy.

**Comment by indiosmo** [comment]
Hi Todd, as a quick test I introduced a timer on the calls to `findX()` so that attempts happen at 100ms intervals.

I've also added code to the main loop so that it only polls aeron every 1mm cycles (between 800ms and 1.5s as seen on the screenshot below).
The `polling now` logs are the timestamps of each call to poll.

Problem still persists.
These are the only two calls to aeron that happen on a loop so I'm not sure where else to look.

I wondered if maybe a write is holding up the buffer but the write function also looks ok:

```
...
  ::aeron::BufferClaim claim;
  auto stream_position = publication.tryClaim(length, claim);

  if (stream_position > 0L) {
    std::size_t offset = claim.offset();
    auto& aeron_buffer = claim.buffer();
    aeron_buffer.putBytes(offset, static_cast<const uint8_t*>(buffer.data()), buffer.size());
    claim.commit();
  }
...
````

For the media driver I've tried both using SHARED/yielding threading strategies and DEDICATED/spinning with the driver threads appropriately affinitized (as seen on htop).

### SHARED
``` 
export AERON_DIR_WARN_IF_EXISTS="1"
export AERON_THREADING_MODE="SHARED"
export AERON_CONDUCTOR_IDLE_STRATEGY="yielding"
export AERON_SENDER_IDLE_STRATEGY="yielding"
export AERON_RECEIVER_IDLE_STRATEGY="yielding"
``` 

![timers](https://user-images.githubusercontent.com/4126274/123883644-d4a92300-d91f-11eb-9aef-44afddead608.png)

### DEDICATED
```
export AERON_DIR_WARN_IF_EXISTS="1"
export AERON_TERM_BUFFER_LENGTH="64m"
export AERON_IPC_TERM_BUFFER_LENGTH="128m"
export AERON_TERM_BUFFER_SPARSE_FILE="0"
export AERON_MTU_LENGTH="8k"
export AERON_SOCKET_SO_RCVBUF="2m"
export AERON_SOCKET_SO_SNDBUF="2m"
export AERON_RCV_INITIAL_WINDOW_LENGTH="2m"
export AERON_THREADING_MODE="DEDICATED"
export AERON_CONDUCTOR_IDLE_STRATEGY="spinning"
export AERON_SENDER_IDLE_STRATEGY="spinning"
export AERON_RECEIVER_IDLE_STRATEGY="spinning"
export AERON_CONDUCTOR_AFFINITY="9"
export AERON_SENDER_AFFINITY="10"
export AERON_RECEIVER_AFFINITY="11"
export AERON_AGENT_ON_START_FUNCTION="affinitize_media_driver"
export AERON_REJOIN_STREAM="0"
LD_PRELOAD=/home/msi/cpp_workspace/abacus/lib/libmil_aeron_affinity.so ${AERON_BUILD_DIR}/binaries/aeronmd
```

**affinitizing function**
````
void affinitize_media_driver(__attribute__((unused)) void* state, const char* role_name)
{
  int core_id = 0;

  if (strcmp(role_name, "conductor") == 0) {
    core_id = atoi(getenv("AERON_CONDUCTOR_AFFINITY"));
  } else if (strcmp(role_name, "sender") == 0) {
    core_id = atoi(getenv("AERON_SENDER_AFFINITY"));
  } else if (strcmp(role_name, "receiver") == 0) {
    core_id = atoi(getenv("AERON_RECEIVER_AFFINITY"));
  } else {
    return;
  }

  cpu_set_t cpuset;
  CPU_ZERO(&cpuset);
  CPU_SET(core_id, &cpuset);
  pthread_t current_thread = pthread_self();
  pthread_setaffinity_np(current_thread, sizeof(cpu_set_t), &cpuset);
}
````

![timers_dedicated](https://user-images.githubusercontent.com/4126274/123884537-d247c880-d921-11eb-82ae-ddc629790743.png)

**Comment by tmontgomery** [comment]
I would simplify things down. Remove affinity, don't set rejoin, and reduce to a minimal reproducible setup.

**Comment by indiosmo** [comment]
The simple case is the `SHARED` run.
I'll see if I can come up with a more concise example.

Thanks.

**Comment by indiosmo** [comment]
It was a bug on my end where I was passing an uninitialized value as fragmentLimit to poll(), so likely what was happening is that some times it was initialized to a positive value and poll suceeded, and some times to zero thus poll succeeded but didn't handle any fragments.

Thanks

**Comment by tmontgomery** [comment]
No worries.
