### ISSUE TITLE
Support Cluster with Only 2 Replicas and Automatic Election of Surviving Node

### ISSUE THREAD

**Issue by klauswuestefeld** [real-logic/aeron#1199]
Currently aeron-cluster/README.md reads: "2 node clusters are supported whereby both members must agree the log and in the event of failure the remaining member must be manually reconfigured as a single node cluster to progress."

A 3rd "tie-breaker" machine can be used to elect the surviving replica node, in case one replica goes down or there is a network partition between both replicas. That is, in essence, the role of the human doing the "manual reconfiguration" Aeron Cluster requires today.

This 3rd "tie-breaker" machine doesn't need to have a replica of the state or even of the log and can be a really cheap machine, even a lambda.

The cluster will only halt when 2 of the 3 machines or all network connections go down simultaneously.

**Comment by mjpt777** [comment]
What is the point of this "issue"? You seem to be making a statement.

**Comment by klauswuestefeld** [comment]
Hi, I've changed the title to make it clearer.

**Comment by mjpt777** [comment]
I don't understand the issue. If not clarified I will close. If you are asking for a feature request then that is only what we offer to customers on commercial support.

**Comment by klauswuestefeld** [comment]
Yes, it is a feature request. Most of the "issues" on the project's "issues" list are feature requests, aren't they? They have "Enhancement" and  "Sponsorship Required" tags.

That's OK. You are not obliged to implement anything for free, of course, but simply closing it will be arbitrary, discourages contribution and will hide a major opportunity you have to make clustering way more effective.

**Comment by mjpt777** [comment]
A much better solution than adding the "tie-breaker" machine is to use a full 3 node cluster. This is what is recommended and we would like to discourage the likes of what you suggest. Sorry but we do not see this as a means to "make clustering way more effective".
