### ISSUE TITLE
ReplayMerge IPC Question

### ISSUE THREAD

**Issue by caueteixeira** [real-logic/aeron#1201]
Hi,

I am using Aeron Archiving to record publication from a single publisher and read them from various subscribers in the same host. I have an IPC channel set-up over a single streamId between the publisher and the subscribers. I am trying to use ReplayMerge to bring subscribers up to date from previous recorded files to a live stream but I noticed It won't accept merge from IPC channels. 
I couldn't find the design principle behind this behaviour. As far as I can see, I must use an UDP channel pointing to localhost instead. It applies for both the replay stream and live stream. Does it mean I can't have IPC when merging streams from recorded to live?

Thanks,
Caue

**Comment by mjpt777** [comment]
ReplayMerge does not support IPC.
