### ISSUE TITLE
Can't set driver timeout - Archive Conductor 

### ISSUE THREAD

**Issue by vitor-tadashi** [real-logic/aeron#1206]
Hi @RichardWarburton @tmontgomery, I'm having a problem related to the driver timeout.
 
Just to give you a little context, there is a admin command inside our application that runs garbage collector manually, and to run GC takes more than 10 seconds.
 
For MediaDriver.Context() there is a setter for driverTimeoutMs and it works, but for Achive.Context() I couldn't find a way to set it and because of this I'm getting this error:
"[archive-conductor] DropCopyEngine - FATAL - MediaDriver keepalive (ms): age=10050 > timeout=10000"
 
We did a test running our application with this environment variable and it works fine ("-Daeron.driver.timeout=20000"), but the ideia is to use the config file and set programatically. Can you help us?

I did another test to make sure the MediaDriver.Context timeout that we set was working, I changed the driverTimeoutMs to 3 seconds and I got this:
[aeron-client-conductor] Runner - FATAL - MediaDriver keepalive (ms): age=9823 > timeout=3000

The code to make it easier for you to understand:

```
final MediaDriver.Context mediaDriverContext = new MediaDriver.Context()
    .threadingMode(DriverThreadingModeUtil.valueOf(config.getDriverThreadingMode()))
    .dirDeleteOnStart(config.isDeleteDriverLogOnStart())
    .driverTimeoutMs(config.getAeronDriverTimeoutMs()) //20000ms
    .clientLivenessTimeoutNs(config.getAeronClientLivenessTimeoutNs())
    .publicationUnblockTimeoutNs(config.getAeronPublicationUnblockTimeoutNs())
    .publicationConnectionTimeoutNs(config.getAeronPublicationConnectionTimeoutNs())
    .aeronDirectoryName(config.getAeronDirectoryName());
final Archive.Context archiveContext = new Archive.Context()
    .archiveDirectoryName(config.getArchiverDir())
    .replicationChannel(config.getArchiverResponseChannel())
    .recordingEventsChannel(config.getArchiverEventsChannel())
    .threadingMode(ArchiveThreadModeUtil.valueOf(config.getArchiveThreadingMode()))
    .deleteArchiveOnStart(config.isDeleteArchiveLogOnStart())
    .aeronDirectoryName(config.getAeronDirectoryName())
    .controlChannel(config.getArchiverRequestChannel())
    .segmentFileLength(config.getArchiveSegmentFileLength())
    .errorHandler(throwable -> LOGGER.fatal(throwable.getMessage()));

this.mediaDriver = ArchivingMediaDriver.launch(mediaDriverContext, archiveContext);
```

**Comment by vitor-tadashi** [comment]
Additionaly I can't `archiveContext.setAeron(aeron)` because `MediaDriver` is only started inside `ArchivingMediaDriver.launch(mediaDriverContext, archiveContext)` and to `Aeron.connect()` I need MediaDriver started.

And I can't customize either because `ArchivingMediaDriver` constructor is not public as well.

**Comment by tmontgomery** [comment]
One way to set the variable is via changing the `System.property` manually before initializing anything related to Aeron. This is how the properties files work, BTW.

In terms of setting the Aeron instance for the Archive, you can separate the Archive and MediaDriver into separate entities, the ArchivingMediaDriver is simply a convenience.

**Comment by vitor-tadashi** [comment]
Ok cool, I will be using `System.setProperty`
