### ISSUE TITLE
Discuss whether to expose when a Subscription is Open/Closed via API

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#121]
Filing an issue rather than a PR, because it requires discussion.

Do you think we should expose to API users whether a subscription is open or closed?

At the moment there's no public method to read the isClosed variable and it seems like it would be useful to API users. On the other hand it does increase the API's surface area.

**Comment by strangelydim** [comment]
I would vote for no.

There's no good thread-safe way to answer the question; all you can get, at best, is a hint.  You might read .isClosed in Thread A and it returns false, and so you decide to do something with the object, only to have Thread B close it a moment later after the check.

And the only way around that problem is making just about every method on an object fully synchronous with a lock.  That's never going to be acceptable for performance.  Users should keep track of Publications and Subscriptions and manage their lifecycle themselves; allowing anything else encourages bad application design by _usually_ allowing users to get away with it.

**Comment by mjpt777** [comment]
@strangelydim I agree and the "edge conditions" I referred to are not common but as you point out are possible.

My vote is to do the volatile check but allow it to be be something that can be turned on or off via a system property.

**Comment by RichardWarburton** [comment]
Ok. Thanks for your feedback gents. I see your point, we're just encouraging race conditions if we expose the field.

I'm a bit concerned that if you have two subscriptions to the same stream, then closing one of them at the moment seems to mean that you close both of them. This puts a lot of burden on the API user to manage their resources which I think we should be managing for them. In fact I can't see a way of managing this nicely in my code without reference counting my subscriptions and closing them at the end.

Wouldn't it be better to have the close method close the single subscription object, and not other subscriptions? Apologies if this has been discussed before, but i can't recall a reason why that's an issue.

**Comment by mjpt777** [comment]
Additionally, we can provide the option to no unmap the buffers and leave them to GC. This way it is fast and safe but is a strategy that could not be used in tests or a server that never runs GC.

**Comment by dameiss** [comment]
"Unique receivers" anyone? :-)

Having a close method close only the specific subscription object (and not other subscriptions) allows much more flexibility. For example, two subscriptions to the same stream could serve completely different purposes semantically, or be the result of two independent threads (who don't know of the other's existence). Closing all subscriptions to a stream would seem kind of... well, rude.

**Comment by rlankenau** [comment]
I agree.  We have been burned by conveniently tearing down related state in
the past.  If there is a reason for creating multiple subscriptions, then
they need to be independently manageable.

It may not seem critical now, but when that subscription is buried in some
type of abstraction layer, having a subscription closed automatically is
mysterious and dangerous.

**Comment by brianhorst** [comment]
I agree that Subscriptions should be independently manageable from the client API. This is even more important if there is some kind of persistence strategy where an individual Subscription needs to report what it has read. Additionally, I would be wary of excessive configuration. Configuration should be possible only when absolutely necessary.

**Comment by RichardWarburton** [comment]
In that case I'm going to close this issue and raise another issue to handle the subscriber close scenario.
