### ISSUE TITLE
Data corruption occasionally when a process is publishing to 2 different channels simultaneously

### ISSUE THREAD

**Issue by sheepgrass** [real-logic/aeron#1211]
We are experiencing an issue when a process is publishing to 2 different channels simultaneously and continuously, over a few million of messages, there would be nearly a hundred of messages being corrupted.  In all of the corrupted messages, we can see that the data is correct at the beginning until some random point of the whole message buffer.  In one of the corrupted messages, we find a clue that actually, at that random point, the data is coming from the other channel which published almost at the same time.

We are also ensured that it's the publisher issue instead of subscriber issue since we have 3 nodes from 3 machines receiving the same corrupted message.  We have already using the latest master branch for test and tried both C and Java media drivers but with no luck.

We suspect if Aeron media driver would assemble data frame packets incorrectly from different channels when there is a high publish rate from both channels?  And may I know what mechanism Aeron has to ensure the data integrity?  Thanks~

**Comment by mikeb01** [comment]
Do you have a test that we can use to reproduce the issue?

**Comment by sheepgrass** [comment]
Sorry that we don't have a specific test for this because we are experiencing this issue on our internal system during performance test.  We are willing to provide additional information if we can help on this issue.

The test setup should not be difficult though.  In our case, we have two channels:
channel 1 (with stream id = 1001):
aeron:udp?endpoint=224.0.1.1:40001|interface=192.168.75.0/24|fc=min
channel 2 (with stream id = 1001):
aeron:udp?endpoint=224.0.1.9:40007|interface=192.168.75.0/24|fc=min

We have two threads which are responsible for publishing to each of the channels respectively.

First channel is publishing messages with message length ~ 280 bytes (may a few bytes varying) making up the aeron frame size of 320 bytes.
Second channel is publishing messages with varying message lengths (from 120 bytes to <1K bytes). (Actually, we are suspecting the short message length (120 bytes message, leading to aeron frame size of 160 bytes) would trigger this issue)

We have added crc32 checksum to aeron header reserved value field to verify the message integrity on subscriber side.  (We have 3 machines subscribing to the first channel and figure out the issue by checking the received message body and checksum)

**Comment by mjpt777** [comment]
@sheepgrass it is possible a bug does exist here. However, Aeron is used in many places and has been for many years with others not seeing such issues. When we have investigated claims of corrupt messages for our commercial support customers it is often a bug in their own code. Without a reproducible test there is little we can do when you are not on commercial support. Given the C and Java drivers are separate codebases it is suggestive of a client or test issue.

**Comment by mjpt777** [comment]
Which client language is your performance test using? Also what compiler/JVM/OS? We have seen bugs with some JVMs and compilers.

**Comment by sheepgrass** [comment]
Compiler:
```
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.1.1-20190605/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.1.1 20190605 (Red Hat 9.1.1-2) (GCC)
```

OS:
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by mjpt777** [comment]
Is this the C, pure C++, or C++ wrapper of the C client?

**Comment by sheepgrass** [comment]
> Is this the C, pure C++, or C++ wrapper of the C client?

we are using pure C++ of C client

**Comment by mjpt777** [comment]
> we are using pure C++ of C client

This is not clear.

**Comment by sheepgrass** [comment]
> > we are using pure C++ of C client
> 
> This is not clear.

We are compiling c media driver following [C++ Build](https://github.com/real-logic/aeron#c-build) and we are compiling our aeron client with files under [aeron/aeron-client/src/main/cpp/](https://github.com/real-logic/aeron/tree/master/aeron-client/src/main/cpp)

**Comment by mjpt777** [comment]
@sheepgrass You will need to provide a repeatable test case or sign up to commercial support so we can review your code if you want to take this further.

**Comment by sheepgrass** [comment]
> @sheepgrass You will need to provide a repeatable test case or sign up to commercial support so we can review your code if you want to take this further.

Thanks~ We will try to setup a repeatable test case if possible or otherwise will approach for commercial support.

**Comment by vyazelenko** [comment]
@sheepgrass The `resevedValue` is written with every fragment that Aeron sends. For messages bigger than the `MTU - 32` there will be multiple fragments. Default MTU is `1408` bytes so if the message size is bigger than `1376` bytes it will be fragmented.
If on the subscriber side you are using a `FragmentAssembler` then you'll read the entire message and thus the checksum computed over it will not match with the checksum that is contained in the `resevedValue` of the last fragment.

The correct approach to verifying message integrity that works irrespective of the message length is to reserve a space at the end of the message and write a checksum there. Upon arrival compute the checksum over the entire message length minus the reserved space for the checksum and compare it with the value at the end of the message.

**Comment by sheepgrass** [comment]
@vyazelenko 

Thanks for your recommendation~

Actually, we notice the message size limitation and have limited the message size to be less than 1k bytes so that the message would not be fragmented. 

We are following this unofficial site (https://aeroncookbook.com/cookbook-content/aeron-app-checksum/) to add the checksum to aeron header after we found out the data corruption issue.

**Comment by sheepgrass** [comment]
We finally found out that it's our application code issue.  Sorry for bother you and thanks for your kindly help~
