### ISSUE TITLE
Question about Gateways / Cluster Clients

### ISSUE THREAD

**Issue by sklose-nydig** [real-logic/aeron#1213]
Hi,

apologies if this questions has already been answered elsewhere. I have been playing with Aeron Cluster for about a week now and there is one thing about Aeron Cluster and Cluster Clients / Gateways that I cannot quite wrap my head around.

Let's assume some kind of trading system setup where the Cluster has all of the business logic and there is an API Gateway that holds the materialized state of an order for query via HTTP, and there is another Gateway that is talking to the EMS system to route orders and push fills back into the Cluster.

All my business logic that lives within Aeron Cluster perfectly recovers on restarts (replay from archive + snapshots). How do I achieve a similar behavior for my Gateways?

I assume I could enable Aeron Archive within each Gateway / Client and use it to do the replay on startup. In addition I would likely need to implement snapshotting so the archive doesn't grow infinitely. Ideally I'd also like to run my Gateways with redundancy. All in all this kinda sounds like reimplementing Aeron Cluster to me within the Gateway. Is the answer to simply use Aeron Cluster to build Gateways? If so, how would one make two clusters exchange messages (like a Cluster + Client would do)?

Another point I am not quite clear on: how do I recover lost/missed messages from my business logic while a Gateway was down? Does Aeron Cluster have some kind of API the Gateway could invoke to request a replay of the output events from a certain point?

Thanks,
Sebastian

**Comment by mjpt777** [comment]
@sklose-nydig We can offer commercial support and consultancy services if you contact sales@real-logic.co.uk.
