### ISSUE TITLE
Multicast UDP sender stops making progress causing backpressure

### ISSUE THREAD

**Issue by chrisejones** [real-logic/aeron#1224]
Hi, we've seen this issue a few times over the last couple of months. Our application experiences back pressure, but none of the consuming applications appear to be behind. The most recent time I grabbed the counters using the AeronStat tool during the incident. 

These are the counters for the affected stream. I've changed the IPs and the service names that appeared in the channel string.

```
175:       47,441,980,448 - pub-pos (sampled): 217 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
176:       47,441,979,808 - pub-lmt: 217 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
177:       47,408,425,376 - snd-pos: 217 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
178:  369,036,638,760,032 - snd-lmt: 217 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
179:                    1 - snd-bpe: 217 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
185:       47,441,980,448 - sub-pos: 231 -661565896 70008 aeron-spy:aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1 @0
186:       47,441,980,448 - rec-pos: 7 -661565896 70008 aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1
202:       47,441,980,448 - sub-pos: 281 -661565896 70008 aeron-spy:aeron:udp?alias=service2|endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx @32928
245:       47,441,980,448 - sub-pos: 339 -661565896 70008 aeron-spy:aeron:udp?alias=service3|endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx @57344
173:                    1 - snd-channel: aeron:udp?endpoint=239.68.xx.xx:xxxxx|interface=xx.xx.xx.0/xx|alias=service1 0.0.0.0:xxxxx
```

pub-pos has apparently exceeded pub-lmt, which is why the application is experiencing back pressure. It appears to be snd-pos that is causing pub-lmt to not move forward. snd-limit appears to be set to a large garbage value.

Other multicast UDP publications are progressing during this time and their snd-limits have sensible values. The Errors counter is set to 0.

We are using the Java media driver version 1.34.0. We've recently upgraded, but I believe that we saw the same version when running 1.29.0.

I may be able to get a pcap recorded during the incident if you think there might be info in their that could help us debug this.

**Comment by tmontgomery** [comment]
Don't think this would specifically related to multicast. If you can write something to reproduce it, we will take a look.

**Comment by mikeb01** [comment]
Are you using `tryClaim` to pass data to the publication?

**Comment by chrisejones** [comment]
Hi, thanks for your help.

This particular application is using offer, not tryClaim. Though other applications sharing the same media driver are using tryClaim.

We're having trouble reproducing it. We have hundreds of instances of this application and it only happens maybe a couple of times a month.

**Comment by mikeb01** [comment]
The only time I have seen something similar is with `tryClaim` and a bug in the writing code that overwrites the end of the claimed buffer.  This can cause the problem to manifest on later offers/tryClaims.  One possible diagnosis would be to use `offer` exclusively and see if the problem persists.

**Comment by mikeb01** [comment]
I have occasionally observed this behaviour with `tryClaim` and has always come down to a bug in its use.  The most common one I have seen is the subtle:

```Java
long position = publication.tryClaim(bufferClaim, length);
bufferClaim.buffer().putBytes(0 /* this needs to be bufferClaim.offset() */, data);
```
