### ISSUE TITLE
Missing method on asciidoctor plugin

### ISSUE THREAD

**Issue by vaci** [real-logic/aeron#1234]
Hi, 

I see the following error when building with gradle 7.1.1.

* What went wrong:
A problem occurred evaluating root project 'buildSrc'.
> Could not find method implementation() for arguments [org.asciidoctor:asciidoctorj:2.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Does this imply that the module has a version mismatch with gradle 7.1.1, or that it is not being downloaded at all?

**Comment by mikeb01** [comment]
How did you run the build?  Did you use the supplied `gradlew` wrapper script?

**Comment by mikeb01** [comment]
I wasn't able to replicate this issue, but did upgrade asciijdoctorj.  Please can you retry with the latest from the repository.

**Comment by vaci** [comment]
Clearing every gradle cache I could find, and then re-running using the gradlew wrapper script, works fine with both the previous and latest commit. I'm not familiar enough with gradle to understand the issue but looks good now. Thanks for investigating.
