### ISSUE TITLE
Closing a subscription should not close other subscriptions.

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#124]
If you have multiple subscriptions open for the same stream then calling the `close` method should close each subscription, not all subscriptions on the client.

**Comment by mjpt777** [comment]
Subscriptions are single threaded and each subscriber should have their own subscription which they are responsible for closing. This is different from publications that are shared and ref counted.

**Comment by RichardWarburton** [comment]
Apologies, the title and text on the original issue had a typo in. I meant "subscription" where I wrote "subscriber". Does that make more sense now?

**Comment by mjpt777** [comment]
The subscriptions are independent and should not be shared. I cannot recreate. Can you provide more details?

**Comment by tmontgomery** [comment]
Does this still happen with latest changes?

**Comment by RichardWarburton** [comment]
I've not seen this issue now, so I'm going to close it.  If it crops up again then I'll re-open.
