### ISSUE TITLE
Sending large messages via pub sub

### ISSUE THREAD

**Issue by yoursweet667** [real-logic/aeron#1246]
I'm new to Java and learning Aeron.

I need to send a large message via pubsub and I use basic sample (https://aeroncookbook.com/aeron/basic-sample /)

In the process, both small and large data will be sent, so I use ByteBuffer.allocate(8192).
When a sub receives an object and tries to deserialize it:
com occurs.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (String)""; line: 1, column: 0].

Here is my code:

`public static void main(String[] args) {

        final String channel = "aeron:ipc";
        final IdleStrategy idle = new SleepingIdleStrategy();
        final UnsafeBuffer unsafeBuffer = new UnsafeBuffer(ByteBuffer.allocate(8192));

        try (
                Aeron aeron = Aeron.connect();
                Publication pub = aeron.addPublication(channel, 1)) {
            while (!pub.isConnected()) {
                idle.idle();
            }
            
            long latency = Long.parseLong(dbService.getBalanceLoaderLatency(args[0])) / 1000;

            while (true) {

                Thread.sleep(latency);

                //sending
                unsafeBuffer.putStringAscii(0, OBJECT_MAPPER.writeValueAsString(getOrderBook(CurrencyPair.BTC_USDT)));
                while (pub.offer(unsafeBuffer) < 0) {
                    idle.idle();
                }
            }
        } catch (InterruptedException | JsonProcessingException e) {
            e.printStackTrace();
        }
    }
    
        public static void main(String[] args) {

        final String channel = "aeron:ipc";
        final IdleStrategy idle = new SleepingIdleStrategy();

        try (
                Aeron aeron = Aeron.connect();
                Subscription sub = aeron.addSubscription(channel, 1)) {

            while (true) {

                //receiving
                FragmentHandler handler = (buffer, offset, length, header) ->
                {
                    String s = buffer.getStringAscii(offset);

                    ReceivingObject receivingObject = null;

                    try {
                        System.out.println("My object: " + s);
                        receivingObject = OBJECT_MAPPER.readValue(s, ReceivingObject.class);

                    } catch (JsonProcessingException e) {
                        e.printStackTrace();
                    }
                };
                while (sub.poll(handler, 1) <= 0) {
                    idle.idle();
                }
            }
        }
    }`

**Comment by vyazelenko** [comment]
@yoursweet667 Such questions should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/aeron) but in your case the [basic-sample](https://aeroncookbook.com/aeron/basic-sample/) contains the answer:

> Lines 1-2 construct the FragmentHandler. In this case we know it is a simple, small message so we can use the most basic FragmentHandler to accept the message. FragmentAssembler should be used to reassemble larger messages.

So what you need to do is to wrap your `FrameHandler` in `FragmentAssembler`, i.e.:
```java
FragmentHandler handler = new FragmentAssembler((buffer, offset, length, header) ->
{
    String s = buffer.getStringAscii(offset);

    ReceivingObject receivingObject = null;

    try {
        System.out.println("My object: " + s);
        receivingObject = OBJECT_MAPPER.readValue(s, ReceivingObject.class);

    } catch (JsonProcessingException e) {
        e.printStackTrace();
    }
});
```
Also you should probably remove `while (true)` as it not needed.
