### ISSUE TITLE
unable to use java standalone archive media driver with C++ srv/client on different hosts

### ISSUE THREAD

**Issue by zjufish** [real-logic/aeron#1255]
There is no embedded c++ archive media driver so i have to use the standalone java one as below.  it seems the default setup will use localhost:8010 as request channel and localhost:8030 as recording channel so if i put the archive client on a different host it wont be able connect to the remote archive because it is listening on lcoalhost. i failed to find a c++ way to use a ArchiveContext object to config the java archive media driver to set the control/recording channel and there seems no control variable like '-D aeron.request.channel' either. please advise if this is doable with current 1.35 code to have c++ archive server, client working on different host. 

`$JAVA_BIN -Daeron.dir.delete.on.start=true \
-Daeron.dir.delete.on.shutdown=true \
-Daeron.archive.dir.delete.on.start=true \
-Daeron.archive.max.catalog.entries=128 \
-Daeron.term.buffer.sparse.file=true \
-Daeron.perform.storage.checks=false \
-Daeron.term.buffer.length=64k -Daeron.threading.mode=SHARED \
-Daeron.shared.idle.strategy=yield \
-Daeron.archive.threading.mode=SHARED \
-Daeron.archive.idle.strategy=yield \
-Daeron.archive.recording.events.enabled=false \
-Daeron.driver.termination.validator=io.aeron.driver.DefaultAllowTerminationValidator \
-Daeron.archive.authenticator.supplier=io.aeron.samples.archive.SampleAuthenticatorSupplier \
-Daeron.archive.dir=$ARCHIVE_DIR  \
-Daeron.dir=$AERON_DIR \
-cp $AERON_JAR io.aeron.archive.ArchivingMediaDriver`

`netstat -anp | egrep "8010"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 127.0.0.1:8010          0.0.0.0:*                           8284/java`

**Comment by mjpt777** [comment]
You can configure the C++ archive client via the `ArchiveConfiguration` programmatically. 

https://github.com/real-logic/aeron/blob/master/aeron-archive/src/main/cpp/client/ArchiveConfiguration.h#L374

These type of questions are better answered on Stackoverflow in the future.

**Comment by zjufish** [comment]
thx martin. i know we can use fluent api to set the recording/response/request on the client side when connecting to a remote archive server. how should that work with a standalone java archive media driver? in java i can create the context and start a embedded java archive driver. in c++ i just start the media driver on command line and seems no way for me to configure these endpoints to not listening on localhost but use the actual ip address so a remote client can connect to it.

**Comment by mjpt777** [comment]
The Java side can be configured with a fluent API on Context, via a properties files, or via system properties in the environment.
