### ISSUE TITLE
How to take snapshots on followers? not block the leader

### ISSUE THREAD

**Issue by vach-himself** [real-logic/aeron#1263]
I've been experimenting with aeron cluster, and one thing that is unclear to me is how do you deal with applications where nodes have 10s of gigabytes of state... this state is in memory and is accumulated by playing the events.

However if i initiate a snapshot (only can on master) this will obviously block since you cant keep applying events and take snapshot at the same time... for latency critical apps obviously you cant wait for seconds while snapshot is taken.

One solution that comes to mind is that follower can take a snapshot and when its done catch up with master and then take over, when snapshot is taken and log is in right state you know your snapshot is valid. This way you have seconds to take your snapshot.

Or you'r master when it tries to take a snapshot hands over master to a follower that is the most up to date, takes the snapshot then if needed can take over master again... no blocking your clients.

Am i doing something wrong, or misunderstanding the snapshots?
Any help is appreciated, there is not much info on this amazing library. At least i couldn't find an answer to this.

`https://stackoverflow.com/questions/70163681/aeron-cluster-gets-blocked-when-taking-a-big-snapshot`

**Comment by mikeb01** [comment]
You are correct, currently snapshots are a blocking operation across the cluster.  Being able to take snapshots concurrently with cluster application operations continue is a feature that we would like to add.

**Comment by vach-himself** [comment]
i'm going to try and add it, since this is deal breaker for my use-case, so if you have any tips (what i should be careful with, where this can be a problem) please do leave few comments.

my plan is as follows, 
1. i'm gonna remove the restriction of taking snapshot only on master, each node works on their own storage/files so why such restriction... make the aeron tool snapshot command work on non master.
2. find out how to request any healthy node to become master, (i couldn't find such command in aeron tool), you can do pretty advanced things like snapshot, invalidate, shutdown entire cluster but you cant choose who should be master
3. automate 1-2 : if snapshot is requested on current master, find a follower that is most up to date, do a hand over, take a snapshot, request to take back master

does this sound reasonable?

**Comment by mikeb01** [comment]
Co-incidentally I've been looking at this feature over the last couple of days.  With regards to the snapshot, there are a couple of subtleties that crop up.  The snapshot still needs to be triggered on the leader[^1], and the leader determines which follower to take the snapshot on[^2].  This is because the snapshot still needs to be a event written to the log[^3], but the message will include the member which needs to take the snapshot.

So far actually getting the node to take the snapshot is the easy part.  The tricky part is deciding on how to get the snapshot onto the other nodes.  We have to be careful about we replicate the snapshots as it can lead to contention in the archive and potential latency spikes.

[^1] How we trigger this may be changed.  At the moment we use a counter toggle, but we are considering other options to not require users to locate and execute code on the leader.
[^2] How we select the specific follower is something that is yet to be determined, currently the leader just picked the next member id (modulo the number of active members).
[^3] This is required to allow the snapshot for the consensus module and the clustered services to be synchronised.

**Comment by vach-himself** [comment]
oh absolutely it must be on the leader i didn't know snapshots are messages going to the log, i had implemented crude version of this via chronicle and snapshots there were very optional things, log would not know about them, i would look up for a file with specific name pattern, if its there you take latest one, snapshot would have the exact sequence of the last message, you load snapshot and go directly to the message you need to replay from, but i do think this is better.

If there is a branch with work in progress code i'd be happy to help, at least i'll see what you're doing and make more sense of the source code.

**Comment by vach-himself** [comment]
regarding how to send snapshots, are snapshots part of the log? or they are optional files that may or may not be present at that moment on specific node?

my use case will be such that snapshots are many GBs in size, i don't want to use any external databases, everything is going to be in memory or off heap memory for maximum performance.

**Comment by mikeb01** [comment]
A small subtlety in what I was saying, a message to trigger the snapshot needs to be present in the log.  The snapshot itself is not part of the log as such, but instead is a separate recording in the Archive being used by that node.

Technically they can be optional, but you still want a way to get the snapshots onto each node, so when they restart they can all get access to the most recent snapshot.  There needs to be a co-ordination between the consensus module and the clustered services regarding the snapshot (hence the pre-supplied `ClusteredService::onTakeSnapshot`) as the consensus module will store some of its own information in the snapshot and also will use the position to know where to start the log replay from.

**Comment by mikeb01** [comment]
My current work in progress is here: https://github.com/mikeb01/Aeron/tree/add_hot_snapshots.  It is passing a very basic test, but it is still some way from being ready for a PR.  Needs more failure/error checking and retry behaviour.

**Comment by SipanVardanyan** [comment]
@mikeb01 How far is your work https://github.com/mikeb01/Aeron/tree/add_hot_snapshots from being ready to PR? I need to use the feature of non-blocking snapshots in my project.
