### ISSUE TITLE
How can i request a specific follower to be leader?

### ISSUE THREAD

**Issue by vach-himself** [real-logic/aeron#1276]
I might have the wrong idea how this is done (if so please correct me) but when deploying new versions of a software using aeron cluster, if you want no downtime deploys then you would take down one of the followers upgrade to your new version, let it sync up with snapshots and the log and then make it the leader when you are confident everything is good.

Is there a way to request a specific follower to take over and be the leader? ClusterTool seems not to have such functionality

How do you do 0 downtime deploys with services that are using aeron cluster?

**Comment by mjpt777** [comment]
With Raft you never decide which node should be leader. For our customers on commercial support we can detail what steps are necessary to do hot upgrades.
