### ISSUE TITLE
Is it possible to dynamically add/remove nodes?

### ISSUE THREAD

**Issue by vach-himself** [real-logic/aeron#1277]
I couldn't find anything on this anywhere, but from what i can see all components in a node get passed hosts/ports of all other nodes at the beginning of the initialisation and there seems to be no way to modify that.

Is there any mechanism that i overlooked to do this? or one just simply deploys new versions of a service which has hardcoded the new locations of other nodes (if there was a change)

**Comment by mjpt777** [comment]
Dynamic join/quit is the means to add or remove members from a cluster. You can see this in operation with `DynamicMembershipTest`.

**Comment by mjpt777** [comment]
Questions are better asked in Stackoverflow.

**Comment by vach-himself** [comment]
Will do sorry, just thought this is not supported.
