### ISSUE TITLE
java media driver on windows issue

### ISSUE THREAD

**Issue by MarshalOfficial** [real-logic/aeron#1278]
I run java media driver on Windows via the below batch script:

```
@echo off
echo Media Driver Started...
java --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.util.zip=ALL-UNNAMED  -Daeron.dir.delete.on.start=true -Daeron.dir.delete.on.shutdown=true -cp media-driver.jar io.aeron.driver.MediaDriver
echo Media Driver Stopped.
pause
```
In this way, it makes a folder named Aeron-UserName in the windows temp folder.
For performance issues, I assumed that I need to create a ram-disk drive on windows and forced the media driver to create a folder in it.
I added this option to solve it: -Daeron.dir=Z:\temp1\
or also -Daeron.dir="Z:\temp1"

```
@echo off
echo Media Driver Started...
java --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.util.zip=ALL-UNNAMED -Daeron.dir=Z:\temp1\ -Daeron.dir.delete.on.start=true -Daeron.dir.delete.on.shutdown=true -cp media-driver.jar io.aeron.driver.MediaDriver
echo Media Driver Stopped.
pause
```

but it doesn't work. and this is the output:

> Usage: java [options] <mainclass> [args...]
>            (to execute a class)
>    or  java [options] -jar <jarfile> [args...]
>            (to execute a jar file)
>    or  java [options] -m <module>[/<mainclass>] [args...]
>        java [options] --module <module>[/<mainclass>] [args...]
>            (to execute the main class in a module)
>    or  java [options] <sourcefile> [args]
>            (to execute a single source-file program)
> 
>  Arguments following the main class, source file, -jar <jarfile>,
>  -m or --module <module>/<mainclass> are passed as the arguments to
>  main class.

**Comment by MarshalOfficial** [comment]
hope to not detect this issue as free support.

**Comment by mikeb01** [comment]
This looks like an issue with the syntax you are using to launch Java.  It hasn't reached the point where the MediaDriver has started (so this is not really an Aeron issue).  You may need to escape the parameter `Z:\\temp1` or use a forward slash `Z:/temp1`.
