### ISSUE TITLE
Putting other key/values in Aeron channel leads to deafness in subscriptions

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Aeron#128]
While testing an app that creates two subscriptions on the same channel but different stream ids, I noticed that I was not receiving any messages in the second subscription.  I have two publications in the system (one sending on stream 10 and one sending on stream 11).  It turned out that this was due to using additional key/values in the Aeron channel string.  When I use a simple Aeron channel string such as:

```
private static final String CHANNEL1 = "aeron:udp?remote=127.0.0.1:40123";
private static final String CHANNEL2 = "aeron:udp?remote=127.0.0.1:40123";
private static final int STREAM_ID1 = 10;
private static final int STREAM_ID2 = 11;
```

then both subscriptions get its expected stream of messages.

However, when I use additional key/values in the Aeron channel such as:

```
private static final String CHANNEL1 = "aeron:udp?remote=127.0.0.1:40123|fruit=apple";
private static final String CHANNEL2 = "aeron:udp?remote=127.0.0.1:40123|fruit=banana";
private static final int STREAM_ID1 = 10;
private static final int STREAM_ID2 = 11;
```

then the second subscription on stream 11 never receives messages.

It appears this is due to the fact that the channel string is used as keys into various Maps and some use the original channel string and some use the canonical version which strips out the extra keys and eventually leads to weird behavior.  For example, ActiveSubscriptions in the client has a subscriptionByChannelMap field that uses the full channel string as specified by the user but the DriverConductor has a receiveChannelEndpointByChannelMap field that uses the canonical form of the udpChannel as the key.  This udpChannel object has a canonical form that matches both streams but it also has a "originalUri" method that only matches the first stream.  When the driver sends messages back to the client, it uses the originalUri as the channel and it appears that this inconsistency is what leads to the deafness.

**Comment by mikeb01** [comment]
We could change the URI parser to reject invalid arguments, but I suspect that it would be possible to trigger the same behaviour without weird parameters.  Due to defaulting of some values (like local address), so that canonical URI are the same, but the initial strings are different.

**Comment by mjpt777** [comment]
I'm looking are removing the orginalUriString from the UdpChannel and always just use the canonical form as a key.

**Comment by jessefugitt** [comment]
Agreed that it looked to me like trying to reject invalid arguments could still lead to the same deafness issue by using variations on ordering or weird values and that the ideal approach would be to standardize on one value for they keys in the code (original or canonical).

**Comment by tmontgomery** [comment]
The driver should always use the canonical form internally (aside from logging and for counters, etc.). The client can't use the canonical form since it has no idea how that is generated for the media (and it is media specific).

Invalid and unknown fields in the URI should cause it to be rejected.

**Comment by mikeb01** [comment]
I'll fix up the parsing/rejecting of unknown fields in the URI.  I'll raise a separate bug for that.

**Comment by tmontgomery** [comment]
Thanks, @mikeb01 . Would like to know why this causes deafness, though.

**Comment by jessefugitt** [comment]
I had a chance to test this with only valid fields in the URI and I can still create the deafness as mentioned earlier (by just swapping the order of remote and local) so the invalid URI fields are definitely fine to be treated as a separate issue.  Basically this works as expected:

```
private static final String CHANNEL1 = "aeron:udp?remote=127.0.0.1:40123|local=127.0.0.1";
private static final String CHANNEL2 = "aeron:udp?remote=127.0.0.1:40123|local=127.0.0.1";
private static final int STREAM_ID1 = 10;
private static final int STREAM_ID2 = 11;
```

but this causes the second stream to be deaf:

```
private static final String CHANNEL1 = "aeron:udp?local=127.0.0.1|remote=127.0.0.1:40123";
private static final String CHANNEL2 = "aeron:udp?remote=127.0.0.1:40123|local=127.0.0.1";
private static final int STREAM_ID1 = 10;
private static final int STREAM_ID2 = 11;
```

The UdpChannel in the media driver code sort of becomes a merged version representing both clients but yet it only has a single originalUri string from the first one and in the future, it only uses that originalUri when it communicates back to the client (meaning no communication seems to flow back to the second channel/stream).

**Comment by tmontgomery** [comment]
I think I know why this happens now.

When the ConnectionReady is sent out, it contains the first URI only. The client can't match up both subscriptions. So, only the first subscription gets data. The second is deaf because it never sees a matching URI from ConnectionReady.

This indicates to me that making sure unknown params cause an invalid URI is the right way to go.

Also, one additional thing to notice is that if multiple URIs are used that have different params, but the same canonical form, then they will not match either. Thus causing the same behavior. One thing to do about that is to either WARN or invalidate when the originalUri does not match when the canonical forms are the same. thoughts?

**Comment by tmontgomery** [comment]
@jessefugitt I think I see why that behavior is seen. The URI strings don't match, so the client can't tell.

The change in behavior I suggest would cause a warning (or an invalid URI exception) for this.

**Comment by jessefugitt** [comment]
Warning in the media driver and then allowing deafness seems a little tough from a usability standpoint to me, especially when the input parameters are all valid but just in a different order.  

It seems like the media driver should have the capability to distribute back out to each client from the underlying media regardless of what order they entered their parameters (maybe create two UdpChannels each with its own key or a a single UdpChannel with a list originalUris keys or something) or else the parameter input needs to be tightened up a lot to prevent entering invalid URIs (I suppose parameters would all need to be required and in a specific order).  The danger at preventing it with URI validation is that as soon as a future version adds a new parameter, you'll get the deafness again when two clients with different versions share the same media driver and have different originalUris that are both valid for that client version..

**Comment by tmontgomery** [comment]
@mjpt777 and I discussed it a bit earlier and I'm going to look at doing away with the string in the ConnectionReady and using an ID. Have to work it through, though.

**Comment by tmontgomery** [comment]
Turns out that the ConnectionReady flyweight already explicitly contains all the registration IDs for all the subscriptions. w00t!

**Comment by jessefugitt** [comment]
Tested with the latest pull and the code that was previously failing due to this bug is now working as expected for me.  Thanks @tmontgomery.
