### ISSUE TITLE
Subscription poll function seems a little off...

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Aeron#129]
The subscription poll function has a roundRobinIndex that is incremented and then used in its doLimitedAction function (presumably to add some fairness or prevent head of line blocking).  However, it looks like the check is reversed unless I'm not understanding what is going on:

```
public int poll(final int fragmentCountLimit)
    {
        ensureOpen();

        if (connections.size() >= ++roundRobinIndex)
        {
            roundRobinIndex = 0;
        }

        return connections.doLimitedAction(roundRobinIndex, fragmentCountLimit, Connection::poll);
    }
```

If connections is size 3 and roundRobinIndex starts out at 0, then it will get incremented to 1 and then set back to 0 and then in the next call be incremented to 1 and then set back to 0, etc.  On the other hand, if before there are any connections, roundRobinIndex increases to 37, and connections gets set to 2, then roundRobinIndex will just increase forever.  Bummer.

I think the if check was supposed to be <= instead of >= but am not sure exactly what the intention was here with this piece of code.

**Comment by mjpt777** [comment]
Nice spot!

**Comment by tmontgomery** [comment]
Is this fixed now?

**Comment by jessefugitt** [comment]
I don't have a test that proves the correctness of this bug but I can confirm that with the latest pull, I can see @mjpt777 has changed the code in the original bug report to the following code below (which looks correct to me):
```
    public int poll(final int fragmentCountLimit)
    {
        ensureOpen();

        int index = ++roundRobinIndex;
        if (index >= connections.size())
        {
            roundRobinIndex = index = 0;
        }

        return connections.doLimitedAction(index, fragmentCountLimit, Connection::poll);
    }
```
