### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NikitaMishin** [real-logic/aeron#1309]
Hi, is the addition of "spy semantic" for the  Unicast publishers worth to be implemented?
I thought about the case when we have a Unicast subscriber on machine X to which different publishers send messages.
So the feature should cover the case when we have Publisher on machine Y and publisher on machine X. So for the first case we use UDP and for the second one IPC.
If I correctly understand, right now to cover this case we need to create 2 Subscribers: IPC and UDP. Could u please correct me if I am wrong?

P.S thanks for creating Aeron. it is awesome.

**Comment by mjpt777** [comment]
Spy semantics are already supported for unicast UDP publications. The subscriber has to be on the same machine as traffic is consumed over IPC. If you need further help on how to use Aeron then please consider commercial support or ask questions on Stackoverflow.

**Comment by NikitaMishin** [comment]
I meant that from [documentation](https://github.com/real-logic/aeron/wiki/Channel-Configuration)  Outgoing Channel Spy working but I refer to the case when we have one Subscriber and several publishers (all sending messages to this subscriber). Some of these publishers are located on the same machine as this subscriber while the other ones are not.

Or am I incorrectly parsed u response and this feature is already supported by Aeron?

**Comment by mjpt777** [comment]
Yes, you need to create two subscriptions in that case.
