### ISSUE TITLE
aeron_subscription_poll does not handle negative aeron_image_poll return values

### ISSUE THREAD

**Issue by alokpr** [real-logic/aeron#1312]
`aeron_image_poll` may return -1 if invalid arguments are provided:
https://github.com/real-logic/aeron/blob/1.38.1/aeron-client/src/main/c/aeron_image.c#L252

`aeron_subscription_poll` blindly casts the returned potentially-negative value to `size_t` and adds to `fragments_read` variable:
https://github.com/real-logic/aeron/blob/1.38.1/aeron-client/src/main/c/aeron_subscription.c#L444
https://github.com/real-logic/aeron/blob/1.38.1/aeron-client/src/main/c/aeron_subscription.c#L450

The same is true for controlled and block polling modes.

**Comment by tmontgomery** [comment]
Thanks! Addressed in 930b3004c22b5.

**Comment by alokpr** [comment]
Thanks for the prompt fix!
