### ISSUE TITLE
how config channel udp multicast all subs can receive messages

### ISSUE THREAD

**Issue by anyex-net** [real-logic/aeron#1321]
Hi, I just testing aeron with udp multicast, my env is

pub matchine ip is 192.168.31.52, 
sub1 matchine ip is 192.168.31.56, 
sub2 matchine ip is 192.168.31.58, 
how config channel udp multicast all subs can receive messages?

my test case is:
pub: final String channel = "aeron:udp?endpoint=192.168.31.56:40456|interface=192.168.31.0/24|ttl=16";
sub1: final String channel = "aeron:udp?endpoint=192.168.31.56:40456|interface=192.168.31.0/24|ttl=16";
sub2: final String channel = "aeron:udp?endpoint=192.168.31.58:40456|interface=192.168.31.0/24|ttl=16";
but only sub1 can receive all messages, sub2 can not receive any messages.
i guess the "interface" paramter config may be not right.

I want to know how config channel udp multicast all subs can receive all messages? 
thank you!

**Comment by tmontgomery** [comment]
You are using a unicast address and not a multicast address for the endpoint. Check the wiki for some examples. https://github.com/real-logic/aeron/wiki/Channel-Configuration#examples

**Comment by sunbiaozj** [comment]
endpoint config udp multicast ip, for example 224.0.1.1 is test pass。
