### ISSUE TITLE
Spy subscriptions and flow control

### ISSUE THREAD

**Issue by jrsala-auguration** [real-logic/aeron#1333]
I want to record a publication with `SourceLocation.LOCAL` to benefit from the zero-copy spy archive subscriptions. However the documentation says that spy subscriptions do not factor in receiver flow control strategies.

Assume there is only one other subscriber besides the archive, that it's a remote subscriber and that it's slow. Since it's the only one taken into account for flow control, it will cause back-pressure even with `fc=tagged,g:42/1` on the publication and `gtag=42` on the archive subscription. But if the archive subscription was taken into account in flow control, since it is likely faster the laggy subscriber could be left behind as I intend.

Is it possible to get both the optimized zero-copy spy subscriptions for recording and the removal of subscribers that lag behind the archive's spy subscription?

**Comment by mjpt777** [comment]
Please ask questions on Stackoverflow.
