### ISSUE TITLE
example for using aeron as an external library

### ISSUE THREAD

**Issue by chromafunk** [real-logic/aeron#1335]
as far as I understand, once we build the cpp library, all related libs are compiled as well in the source directory. Now, I need to run a modified example from a custom project directory. Can I link to the already built Aeron library and import the headers and work with it ? Is there any example or guide on how to achieve this ?

**Comment by chromafunk** [comment]
```
project(aeroncpp)

set(INCLUDE_DIR /sandisk250/aeron/aeron-client/src/main/cpp/)

include_directories (${INCLUDE_DIR})

add_executable(aeroncpp main.cc)

target_link_libraries(aeroncpp /sandisk250/aeron/cppbuild/Release/lib/libaeron_client_shared.so)
```

Made it work like this, just posting and closing in case somebody needs it

**Comment by mikeb01** [comment]
As an aside, you also have the option to run with the C library with the C++ wrapper which is header only.

You also can do a `./cppbuild/cppbuild --package` on the compile Aeron code which will create a tar.gz which you can unpack that contains the cpp and cpp wrapper libraries.

**Comment by chromafunk** [comment]
Good to know ! Thanks
