### ISSUE TITLE
Question on reliable UDP if the last message is lost.

### ISSUE THREAD

**Issue by newbie689** [real-logic/aeron#1344]
Hello,

I have tried to use Aeron and everything looks good. Therefore plan to start to work on production.
However I have one question that relate to reliable UDP.

As I look at the document, it will do a NAK and ask for resend when there is missing message.
But the example is all about when you get at least one message and then can deduce what have been missed.

What if it is the last and only message at one hour interval and then it lost, will Aeron also able to detect this message have been lost and resend it?

I want to see if I need to manually handle this case. I have checked LossDetector class and maybe I have overlook something.

Thanks you very much.

**Comment by tmontgomery** [comment]
Look on the publication side for heartbeats sent in the absence of data.

**Comment by newbie689** [comment]
thanks you
