### ISSUE TITLE
[Archive]ReplaySession-Improving error messages

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1346]
`private void onError(final String errorMessage)
    {
        this.errorMessage = errorMessage; 
        state(State.INACTIVE);
 }`
Can I add some information here？ e.g.  recordingId, sessionId and so on

When an error occurs, more information can be learned

**Comment by tmontgomery** [comment]
Great idea! Go ahead and add some information and submit a PR and we will look at it.
