### ISSUE TITLE
Is it possible to redirect udp stream message to IPC stream directly?

### ISSUE THREAD

**Issue by cagev** [real-logic/aeron#1353]
As a portal server  , it will receive  message from both udp and ipc channels ,  so I need to start two thread to  subscribe  udp and IPC channels.   If I want all message to be processed in IPC thread , then I need forward udp messages to IPC channel  using publish method , the message from udp will be copied again.  so is it possible receive the udp message directly into IPC buffer? then user can get message from IPC channel  without copy.  It seems to combine two streams to one. 

![bridge](https://user-images.githubusercontent.com/499566/188254219-782e00de-a6b4-4f1a-9975-050ffdab0d77.png)

**Comment by mikeb01** [comment]
You don't need to have separate threads for each subscription.  You can poll both subscriptions from the same thread.

**Comment by cagev** [comment]
thanks , it can work.
