### ISSUE TITLE
CnC file not created: /dev/shm/aeron-root/cnc.dat

### ISSUE THREAD

**Issue by GoldenFishCS** [real-logic/aeron#1362]
Trying to run sample program and it is retuning with error messages.

# ./basic_subscriber -c aeron:udp?endpoint=224.0.1.1:40456|interface=192.168.30.239
aeron_init: (-1000) unknown error code
[aeron_client_connect_to_driver, aeronc.c:54] CnC file not created: /dev/shm/aeron-root/cnc.dat

**Comment by mjpt777** [comment]
You need to be running a media driver.

**Comment by GoldenFishCS** [comment]
Yes.  I did run media driver.
# ps -ef | grep aeron
root     31461 31308  1 Sep19 pts/0    00:23:33 ./aeronmd.

But 
# ./AeronStat
(-1000) unknown error code
[aeron_cnc_init, aeron_cnc.c:72] Timed out waiting for CnC file to become available after 1000ms

**Comment by tmontgomery** [comment]
The media driver and the app needs to be the same USER. Or you have to specify the Aeron directory. Also, the directory needs to be accessible by both, etc.

If you need assistance, we offer support.

**Comment by GoldenFishCS** [comment]
USER is root to start all the apps.
Directory permission is 755.

How can I get support?

**Comment by mjpt777** [comment]
> How can I get support?

Email: sales@real-logic.co.uk

**Comment by M4K1SAMA** [comment]
CnC file not created: /tmp/aeron/cnc.dat
I'm encountering the same issue.
I'm sure I'm running media driver with the same user
