### ISSUE TITLE
Implementing disk persistence over Aeron

### ISSUE THREAD

**Issue by amit2103** [real-logic/Aeron#137]
Many thanks for the fantastic library. I actually had a couple of queries.
How should I go about implementing the following:-
1) A disk backed Topic, (messages are logged to disk before sending over the wire.)
2) Client Acknowledgements , after consuming messages.

Is there any roadmap in Aeron for doing some of these?

**Comment by tmontgomery** [comment]
Thanks!

Yes, disk persistence is something that the LogBuffer structure and general architecture of Aeron fit very well with. @mjpt777 has mentioned this in his talks as well.

Persistence is, in fact, on our TODO lists and something we have spent a good bit of time thinking about and designing already.

**Comment by amit2103** [comment]
Todd ,
Thanks. I feel much better now.
However I have one small request. Its always better for people like me who are  following the project if a roadmap is  available. 
Can you please write a roadmap? And it will be great if you could guide me on how to add client acknowledgement , a bit like local acknowledgements in JMS (sorry to JMS in this discussion :)  ).

Regards

**Comment by RichardWarburton** [comment]
I'm not sure committing to a roadmap/schedule is a good idea necessarily. It often sets false expectations which disappoint. I think having a list of features which we would like to implement without committing to timing is a better plan.

**Comment by amit2103** [comment]
Richard,
A list of features will also be great. Atleast we can then understand which are the features , "we" have to build ourselves.
Thanks

**Comment by mjpt777** [comment]
@amit2103 Client acknowledgement is not something we have been considering. I tend to address this by having a application level protocol on top of messaging. Putting it into the messaging leads to designs that don't cope well with failure and retry scenarios. JMS has a lot of bad things to answer for ;-)

**Comment by amit2103** [comment]
@mjpt777 I believe keeping a counter of messages we read will also be okay. Thanks for the response though. I dont think rebuilding another Jms like protocol is useful. The performance of some of the Jms providers is abysmal as it is.
Thanks for the answers. I will be closing the issue. A list of planned features will be nice though :)

**Comment by mjpt777** [comment]
I case you have not noticed it is possible to track position on any stream. Offers to a publication return the position of the stream after successful offer. Callbacks on a subscription also have the position in the header that has been consumed to. These figures are also available via AeronStat. We designed the systems so that stream progress is observable. So it would be possible to track consumption out of band.

**Comment by tmontgomery** [comment]
Combining the position information into simple pieces of logic allows much more complex behaviors without adding that behavior internally.

**Comment by amit2103** [comment]
@mjpt777  Yes, I was confident that keeping a counter of messages we read will work, because Aeron internally does provide that. This will help us in ensuring that a consumer does not read duplicate messages.
