### ISSUE TITLE
two publications and two subs on same channel may lose data

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1373]
Hi,
  Please have a look at the code below. pub1 and sub1 works fine. But sub2 cannot receive data from pub2. The code works in this way:
1. sub1 is built
2. pub1 is built, creating a NetworkPublication
3. pub1 offer data, NetworkPublication will send setup message before sending the data
4. sub1 receives setup message and creates publication image, after which receiving the data offered by pub1
5. sub1 is is closed
6. sub2 is built
7. pub2 is built, **reusing** the NetworkPublication created by pub1
8. pub2 offer data, NetworkPublication will **not** send setup message before sending the data
9. sub2 receives the data, but can't insert it to image because it hasn't received a setup message and hasn't created image
10. sub2 sends elicit setup message to pub2
11. NetworkPublication of pub2 then sends setup message to sub2
12. sub2 receives the setup message and creates an image, whose join position is behind the data offered by pub2, so it will not receive the data offered by pub2 before

In phase 9, if pub2 waits for a while before offering, after which NetworkPublication of pub2 sends heartbeat message, then sub2 can receive the data. Because in this case, sub2 can elicit setup message after receiving heartbeat message and create the image.

Thanks for having a look.

-----------------Code----------------------

class TestPub {

    static class ReceiverHandler implements FragmentHandler {
        public void onFragment(final DirectBuffer buffer, final int offset, final int length, final Header header) {
            int i = buffer.getByte(offset);
            System.out.println("sub result: " + i);
        }
    }

    private static final String CHANNEL = "aeron:udp?endpoint=localhost:20123";
    private static final int STREAM_ID = 3000;
    private static final int BUFFER_LENGTH = 16;
    private static ReceiverHandler handler = new ReceiverHandler();
    public static void main(String[] args) {
        final MediaDriver driver =  MediaDriver.launchEmbedded();
        final Aeron.Context ctx = new Aeron.Context().aeronDirectoryName(driver.aeronDirectoryName());
        Aeron aeron = Aeron.connect(ctx);

        Publication pub1 = aeron.addPublication(CHANNEL, STREAM_ID);
        Subscription sub1 = aeron.addSubscription(CHANNEL, STREAM_ID, TestBug::onAvailableImageHandler, TestBug::onUnAvailableImageHandler);

        ExpandableDirectByteBuffer buffer = new ExpandableDirectByteBuffer(BUFFER_LENGTH);
        buffer.putInt(0, 10);

        long result = 0;
        while ((result = pub1.offer(buffer, 0, BUFFER_LENGTH)) < 0) {
        }
        System.out.println("pub1 success: " + result);

        while (sub1.poll(handler, 10) <= 0) {
        }
        System.out.println("sub1 success");

        sub1.close();
        Subscription sub2 = aeron.addSubscription(CHANNEL, STREAM_ID, TestBug::onAvailableImageHandler, TestBug::onUnAvailableImageHandler);
        Publication pub2 = aeron.addPublication(CHANNEL, STREAM_ID);

        while (!pub2.isConnected()) {
        }
        System.out.println("pub2 connected");

        while ((result = pub2.offer(buffer, 0, BUFFER_LENGTH)) < 0) {
        }
        System.out.println("pub2 success: " + result);

        while (sub2.poll(handler, 10) <= 0) {
        }
        System.out.println("sub2 success");
    }

    static void onAvailableImageHandler(Image image) {
        System.out.println("[available image] connect success. image=" + image);
    }

    static void onUnAvailableImageHandler(Image image) {
        System.out.println("[unavailable image] disconnect success. image=" + image);
    }
}

**Comment by tmontgomery** [comment]
This is expected behavior. Aeron does not have a strict connection semantic. The close of the subscription does not, and can not, stop the missing of messages during this scenario. Because of the close of the subscription, all bets are off. If you need to not miss messages in this way, then I would suggest using the Archive to store the stream and provide the means for a durable message stream.

**Comment by spiritlcx** [comment]
Got it, thanks very much
