### ISSUE TITLE
Move related class AeronStat, BacklogStat into package io.aeron.driver.status, DriverTool into package io.aeron, DriverEventDissector into package io.aeron.command

### ISSUE THREAD

**Issue by yanyiyi-yi** [real-logic/aeron#1374]
Hi, @mjpt777 

**Issue Description**

Package **_io.aeron.samples_**, and **_io.aeron.agent_** group together miscellaneous classes that might be useful to different packages. The package structure violates the “high cohesion and low coupling” design rules. I found that class **_AeronStat_**, **_BacklogStat_**, **_DriverTool_**, and **_DriverEventDissector_** strongly interact with classes in the other package (**_io.aeron.driver.status_**, **_io.aeron_**, and **_io.aeron.command_**) by checking the source code and the snippet of the dependency graph. The project has grown larger, leading to becoming increasingly hard to maintain. During the development process, one groups together classes (that often co-change) with similar responsibilities in one package to facilitate maintenance, which prevents a change that causes other packages to be modified. For example, if one modifies package **_io.aeron.driver.status_** (i.e., package rename), and forget to change class **_AeronStat_** during the maintenance process, there are indirect consequences for the class **_AeronStat_**.
Location: The source file can be found at path File  aeron-samples/src/main/java/io/aeron/samples/AeronStat.java
aeron-samples/src/main/java/io/aeron/samples/BacklogStat.java 
aeron-samples/src/main/java/io/aeron/samples/DriverTool.java
aeron-agent/src/main/java/io/aeron/agent/DriverEventDissector.java
Refactoring suggestions

I suggest to move related class **_AeronStat_**, **_BacklogStat_** into package **_io.aeron.driver.status_**, **_DriverTool_** into package **_io.aeron_**, **_DriverEventDissector_** into package **_io.aeron.command_**.

![AeronStat-java](https://user-images.githubusercontent.com/29889989/198890679-9864cfef-d3d7-4f52-9141-efddbdf1d5f9.png)
![BacklogStat-java](https://user-images.githubusercontent.com/29889989/198890685-c7436a07-0e3c-4ad6-888c-25632036c065.png)
![DriverTool-java](https://user-images.githubusercontent.com/29889989/198890691-2eddfebf-2356-4f80-bd8a-23d710057b01.png)
![DriverEventDissector-java](https://user-images.githubusercontent.com/29889989/198890703-649460f9-60e5-4b05-af7a-41b54d171dd9.png)

**Comment by mjpt777** [comment]
Most of these are samples using public classes from Aeron. The samples are for illustration and not part of the core API.
