### ISSUE TITLE
[driver] The number of undesired images

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1378]
is it a bug?

![image](https://user-images.githubusercontent.com/13658946/199663048-49426ea4-ab6a-4778-893e-8bc9f05a5672.png)

**Comment by WorkingChen** [comment]
The new sub receives data from the control port that is not expected

**Comment by tmontgomery** [comment]
You have 2 exclusive publications. Thus 2 images.

**Comment by WorkingChen** [comment]
> The new sub receives data from the control port that is not expected. consuming multiple data sources.

But sub2 explicitly specifies a different control endpoint to receive data

> You have 2 exclusive publications. Thus 2 images.

But sub2 explicitly specifies a different control endpoint to receive data

**Comment by WorkingChen** [comment]
> You have 2 exclusive publications. Thus 2 images.

But sub2 explicitly specifies a different control endpoint to receive data

**Comment by mikeb01** [comment]
The control address does not specific the address for receiving of data.  The control address is used for sending control information back to the publication (e.g. setup eliciting status messages).  The endpoint address is where data is sent and both publications have the same endpoint, therefore you will have two images.
