### ISSUE TITLE
[driver] An exception about subscription.close()

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1379]
Is there any way to ensure that the state of PublicationImage has changed to LINGER, so that the next step can be done safely？

![image](https://user-images.githubusercontent.com/13658946/199704202-4683c7f3-9f08-44f3-a504-6ffa7b641225.png)

**Comment by mjpt777** [comment]
You can check for presence of the send channel status counter to see if it is still around. 

https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/status/SendChannelStatus.java#L32

**Comment by WorkingChen** [comment]
But it doesn't seem to work
channelStatus() always return -1 when subscription is closed.
![image](https://user-images.githubusercontent.com/13658946/205893258-d57a0885-eb2a-4aad-864d-c727f1bcf17e.png)

**Comment by WorkingChen** [comment]
> If you need to await that the sockets are no longer in use. Which seems to be what you want, then use something like `LocalSocketAddressStatus.findNumberOfAddressesByRegistrationId`. It will let you know if all of the sockets under the subscription (in case it is MDS) are closed or still open.

it works. 
However, exceptions may be thrown in some scenarios, such as when an AeronAchive connection fails(close subscription) and retries(add subscription) immediately。I mean that some of the internal logic is not under the control of the user

**Comment by WorkingChen** [comment]
> If you need to await that the sockets are no longer in use. Which seems to be what you want, then use something like `LocalSocketAddressStatus.findNumberOfAddressesByRegistrationId`. It will let you know if all of the sockets under the subscription (in case it is MDS) are closed or still open.

thks. i get it
