### ISSUE TITLE
UdpChannel "interface" search should check if interface isUp

### ISSUE THREAD

**Issue by seh4nc** [real-logic/aeron#1387]
One of our servers has two interfaces with the same address, one is UP, one is DOWN, because reasons.

Currently our Aeron channel configuration picks the wrong one, whether we set the "interface" parameters explicitly or omit it.

The loop in `UdpChannel.findInterface` should check for `networkInterface.isUp()`.

Is there any case where someone would want to select an interface that's not UP ?

**Comment by tmontgomery** [comment]
Yes, there are some cases where we do not care. If it is picking the wrong interface where you are specifying the interface unambiguously. i.e. without a mask, etc. Send us a test case. But it sounds like you are not specifying the interface in a way that is unambiguous. i.e. without a netmask, for example.
