### ISSUE TITLE
MediaDriver keepalive timeout due to driver being slow on munmaps

### ISSUE THREAD

**Issue by reissGRVS** [real-logic/aeron#1388]
In the case where we have an application subscribing to a large number of streams, if we then shut that application down we have a massive influx of freeing the publication images.
Due to munmap being potentially slow (in the milliseconds) and the large number of streams, we can see a single driver_conductor work loop take over 1 second. This then triggers media driver keepalive timeouts for clients.

Would it be possible to queue up the munmaps so that other driver_conductor work isn't entirely blocked by a large number of munmaps? i.e. only free N publication images per driver_conductor work loop?

**Comment by tmontgomery** [comment]
Just FYI. We are looking into what can be done better here.

**Comment by reissGRVS** [comment]
What would be the downside of queuing the image frees?

**Comment by tmontgomery** [comment]
That may be what we end up as a solution. However, it makes reasoning about free space in `/dev/shm` difficult as well as adds some possible conflicts to consider.
