### ISSUE TITLE
`ConsensusModule` throws `IllegalArgumentException` for ingress channel that must be looked up first 

### ISSUE THREAD

**Issue by artem-v** [real-logic/aeron#1394]
Hi 

At  `1.40.0` method `ConsensusModuleAgent.isIngressMulticast()` calls `UdpChannel.destinationAddress(ingressUri, DefaultNameResolver.INSTANCE)`. `ConsensusModuleAgent` uses hardcoded/default nameResolver, which doesn't assume any lookup logic, hence if client has ingress channel that requires lookup first and can't be resolved as-is => then it's always `IllegalArgumentException("invalid format: " + value)` thrown from the `UdpChannel#destinationAddress -> SocketAddressParser#parse`.

Should I provide test to make it more obvious?

**Comment by vyazelenko** [comment]
@artem-v Thanks for reporting the issue. Yes, the test would be helpful.

**Comment by artem-v** [comment]
[issue1394.zip](https://github.com/real-logic/aeron/files/10264082/issue1394.zip)

On `1.35.1` it gives:
```
[Issue1394][awaitLeader] Leader found: foobar-cluster-42-2/localhost:7000
[Issue1394][connectClient] Client connected: io.aeron.cluster.client.AeronCluster$AsyncConnect@3e92efc3
```

On `1.40.0` it produces:
```
[foobar-cluster-42-0][ConsensusModule] exception: io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: invalid format: foobar-cluster-42-0:isPortOffset=true:5
[foobar-cluster-42-2][ConsensusModule] exception: io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: invalid format: foobar-cluster-42-2:isPortOffset=true:5
[foobar-cluster-42-1][ConsensusModule] exception: io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: invalid format: foobar-cluster-42-1:isPortOffset=true:5

[Issue1394][awaitLeader] Leader found: foobar-cluster-42-1/localhost:6000
...
Exception in thread "main" io.aeron.exceptions.TimeoutException: ERROR - cluster connect timeout: step=1 ingressChannel=aeron:udp ingressPublication=null egress.isConnected=false responseChannel=aeron:udp?endpoint=localhost:33452
	at io.aeron.cluster.client.AeronCluster$AsyncConnect.checkDeadline(AeronCluster.java:1784)
	at io.aeron.cluster.client.AeronCluster$AsyncConnect.poll(AeronCluster.java:1741)
	at issue1394.Issue1394.lambda$connectClient$1(Issue1394.java:55)
```

**Comment by vyazelenko** [comment]
The `io.aeron.driver.media.SocketAddressParser#parse` will throw an `IllegalArgumentException` if the address string is in the wrong format. Supported formats are:
* `hostname:port` (e.g. `example.com:8080`)
* `ipV4Address:port` (e.g. `127.0.0.1:19019`)
* `[ipV6Address]:port` (e.g. `[f0:2f:74:cc:73:c2]:12345`)

As can be seen from the following exception:
```
java.lang.IllegalArgumentException: invalid format: foobar-cluster-42-1:isPortOffset=true:5
```
the value `foobar-cluster-42-1:isPortOffset=true:5` does not match any of the supported formats.

**Comment by artem-v** [comment]
When aeron cluster is started - neither `hostname` nor the `ipV4Address` are not known. Hence I start it with some identifiers/aliases that later/eventually will be resolved to real addresses using custom NameResolver implementation.

**Comment by vyazelenko** [comment]
@artem-v My comment was just to illustrate that the issue could have been worked around if the format of your alias would match the supported ones, i.e. the unresolved address would  have been created and the `ConsensusModuleAgent.isIngressMulticast` would have returned `false`.

However the proper fix is to allow for custom `NameResolver` to be configured on the `ConsensusModule` which was done in [this commit](https://github.com/real-logic/aeron/commit/ba67b1a86cfc776342e9a6febecd1973cdf1925f).

The test that you've submitted passes with this fix.

**Comment by artem-v** [comment]
@vyazelenko Thanks.
