### ISSUE TITLE
the message written into shared memory will dropped when restart subscription after liveness timeout ?

### ISSUE THREAD

**Issue by cagev** [real-logic/aeron#1395]
when using unicast udp channel,  the sender can continue  to write message before detected the subscription is down .  when client restart after liveness timeout(15s) ,  the message  written into shared memory  after client  shutdown  will missing . is it possible to retranslate the message to client in aeron ?  or sender can immediately report which message is not ACKed/NACK when client subscription shutdown ?

**Comment by vyazelenko** [comment]
@cagev It seems what you are looking for is the recorded publication, i.e. using Archive to record the publication which allows subscribers to consume from any point in time using a replay feature. See `io.aeron.archive.client.AeronArchive` API.

When `Subscription` times out and is re-created it starts from scratch, i.e. it will consume the published stream from the its current position. All messages between the timeout and now will be lost.
