### ISSUE TITLE
[cluster]The cluster receives a message about a connection that has been closed

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1398]
When the cluster restarts at the same time, clients will not receive the close event and will not be able to recover automatically。
It is normal for the client to send heartbeats and commands。
![image](https://user-images.githubusercontent.com/13658946/209159912-910f9280-3cb5-4454-a96b-fb928ece7ca1.png)

**Comment by mjpt777** [comment]
If the whole cluster is restarted then no notification can be sent to the client. The client will eventually timeout and keepalives will fail to be sent. You should try to send in a loop sending a keepalive and polling for egress with a idle strategy and you will see this eventually happen.

Please ask general questions on stackoverflow and not use issues here to get consulting.
