### ISSUE TITLE
[AeronArchive] listRecording timeout

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1399]
I want to know what scenarios will cause timeout?  aeronArchive uses ipc channel to communicate with the local archive.
Most of the time is normal, with occasional timeouts.

`io.aeron.exceptions.TimeoutException: ERROR - awaiting recording descriptors - correlationId=3343917 
at io.aeron.archive.client.AeronArchive.checkDeadline(AeronArchive.java:2046)
at io.aeron.archive.client.AeronArchive.pollForDescriptors(AeronArchive.java:2223)
at io.aeron.archive.client.AeronArchive.listRecording(AeronArchive.java:1317)`

**Comment by vyazelenko** [comment]
The `TimeoutException` is thrown if the response was not received within the `aeron.archive.message.timeout` (defaults to 10 seconds). There could be many reasons for why the response is not received, including:
- Control response channel subscription is not connected.
- The Archive is stalled (e.g. resource starvation, VM taking a long GC pause).
- The Archive process is dead.
- The `Archive.Context#threadingMode()` is set to `ArchiveThreadingMode.INVOKER` and the `Archive#invoker` is not invoked frequently enough.
