### ISSUE TITLE
How ClusterClient connect to a cluster in IPC 

### ISSUE THREAD

**Issue by imkcy9** [real-logic/aeron#1404]

**Comment by imkcy9** [comment]
BTW, is there any plan to implement ClusterClient in C++?

**Comment by vyazelenko** [comment]
@imkcy9 You have to enable IPC for the ingress channel on the `ConsensusModule` by setting the system property `aeron.cluster.ingress.ipc.allowed` to `true` (or programmatically via `io.aeron.cluster.ConsensusModule.Context#isIpcIngressAllowed(boolean)`).

Then set the ingress channel (`aeron.cluster.ingress.channel` or `io.aeron.cluster.client.AeronCluster.Context#ingressChannel(java.lang.String)`) on the `AeronCluster` to `aeron:ipc`. Note: the `aeron.dir` on the client side should point to the directory of the `MediaDriver` used by the `ConsensusModule`.

**Comment by mjpt777** [comment]
> BTW, is there any plan to implement ClusterClient in C++?

A C++ cluster client will be driven by paying customer need. If you company signs up to commercial support then we can consider this. sales@aeron.io
