### ISSUE TITLE
[cluster] Error sending data asynchronously using the egress channel

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1408]
hi bro, I'm a little confused about this and I don't think that sending data asynchronously to the egress channel will affect consistency :)

![image](https://user-images.githubusercontent.com/13658946/212528779-4622460a-e75d-4e86-8682-3904ffd66dd7.png)

![image](https://user-images.githubusercontent.com/13658946/212528795-f51cf6d5-c7e4-48a3-8df1-219370251211.png)

**Comment by mjpt777** [comment]
Replicated machines must have deterministic state changes and outputs based on the same inputs.

**Comment by WorkingChen** [comment]
> Replicated machines must have deterministic state changes and outputs based on the same inputs.

At present, our service uses asynchronous sending data. If we upgrade the aeron version 1.40.0, it will change a lot. Is it possible to create a separate ConcurrentPublication(clientSession.responseChannel(), clientSession.responseStreamId()) object to send data to the egress channel?
