### ISSUE TITLE
subscribe to all streams on the channel?

### ISSUE THREAD

**Issue by yuriymyronovych** [real-logic/aeron#1409]
I have multiple streams on the channel which cover majority of use-cases, however some clients need to get all data from the channel. I can't find anything in docs that handle this case. Is there any easy solution? In fact complicated solution is fine too as long as it does not have performance/latency impact.

**Comment by tmontgomery** [comment]
Unfortunately, Aeron does not support wildcarding of streamIds on a channel to receive all streams from all publications. It is best to consider this for your architecture and keep track of streams and interest for the subscriptions.
