### ISSUE TITLE
Stopping and then restarting a subscription causes it to never receive data again

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Aeron#141]
Using the latest code from GitHub, I've been testing a stop and restart subscription scenario where both subscriptions are on the same channel but different streams.  On Machine 1, I have a media driver app, a publication app on stream 1, and a publication app on stream 2.  On Machine 2, I have a media driver app, a subscription app on stream 1, and a subscription app on stream 2.  When I start everything up, the two subscription apps are receiving data:

NEW CONNECTION: channel "aeron:udp?remote=192.168.14.14:31111", stream 1, session 1496040322
1.000034: 334.554 Kmsgs/sec 85.6 Mbps
0.999995: 1.049 Mmsgs/sec 268.5 Mbps
1.000004: 1.059 Mmsgs/sec 271.1 Mbps
1.000001: 1.017 Mmsgs/sec 260.3 Mbps
...

NEW CONNECTION: channel "aeron:udp?remote=192.168.14.14:31111", stream 2, session -578364638
1.000047: 1.671 Mmsgs/sec 427.8 Mbps
0.999997: 1.576 Mmsgs/sec 403.4 Mbps
1.000010: 1.054 Mmsgs/sec 269.7 Mbps
1.000009: 1.040 Mmsgs/sec 266.4 Mbps
...

Then, I stop and restart the subscription app on stream 2.  It gets a new connection message but it never receives data:

NEW CONNECTION: channel "aeron:udp?remote=192.168.14.14:31111", stream 2, session -578364638
1.000362: 0.000 msgs/sec 0 bps
0.999624: 0.000 msgs/sec 0 bps
1.000001: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
...

The publication app seems to be sending a small bit of data every 10 seconds or so but it never gets delivered to the subscription app:

0.999975: 1.036 Mmsgs/sec 265.1 Mbps
0.999999: 1.090 Mmsgs/sec 279.1 Mbps
1.000002: 1.085 Mmsgs/sec 277.9 Mbps
1.000000: 231.696 Kmsgs/sec 59.3 Mbps
1.000001: 0.000 msgs/sec 0 bps
0.999999: 0.000 msgs/sec 0 bps
1.000008: 0.000 msgs/sec 0 bps
0.999992: 2.340 Kmsgs/sec 599.0 Kbps
1.000002: 0.000 msgs/sec 0 bps
1.000061: 0.000 msgs/sec 0 bps
0.999947: 0.000 msgs/sec 0 bps
0.999990: 0.000 msgs/sec 0 bps
1.000058: 0.000 msgs/sec 0 bps
0.999943: 2.340 Kmsgs/sec 599.1 Kbps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000001: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
0.999999: 0.000 msgs/sec 0 bps
0.999998: 2.340 Kmsgs/sec 599.0 Kbps
1.000003: 0.000 msgs/sec 0 bps
0.999999: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
...

This scenario seems to be reproducible each time and the bug only seems to occur if the channels are the same but the streams are different (in other words, the behavior is fine if the setup uses different channels).

The commands to reproduce using aeron-tools are:

Machine 1
```
java -cp tools.jar uk.co.real_logic.aeron.tools.MediaDriverTool
java -cp tools.jar uk.co.real_logic.aeron.tools.SubscriberTool -c aeron:udp?remote=192.168.14.14:31111#1
java -cp tools.jar uk.co.real_logic.aeron.tools.SubscriberTool -c aeron:udp?remote=192.168.14.14:31111#2
```

Machine 2
```
java -cp tools.jar uk.co.real_logic.aeron.tools.MediaDriverTool
java -cp tools.jar uk.co.real_logic.aeron.tools.PublisherTool -c aeron:udp?remote=192.168.14.14:31111#1
java -cp tools.jar uk.co.real_logic.aeron.tools.PublisherTool -c aeron:udp?remote=192.168.14.14:31111#2
```

Stop subscription 2 on machine 1 and then restart it immediately.  It fails to receive data.

**Comment by jessefugitt** [comment]
Added a bit of debug logging today to try to figure out this issue.  It appears that there are some soft spots related to having multiple subscriptions on the same channel but on different streams.  Closing one of the subscriptions appears to mess up the NetworkConnection object which leads to no data being delivered to future subscriptions.  Specifically, the problem happens after this code runs in DataPacketDispatcher:

```
    public void removeSubscription(final int streamId)
    {
        final Int2ObjectHashMap<NetworkConnection> connectionBySessionIdMap = sessionsByStreamIdMap.remove(streamId);
        if (null == connectionBySessionIdMap)
        {
            throw new UnknownSubscriptionException("No subscription registered on stream " + streamId);
        }

        connectionBySessionIdMap.values().forEach(NetworkConnection::ifActiveGoInactive);
    }
```

It looks like some of the code related to addSubscription/removeSubscription and addConnection/removeConnection as well code from the calling functions don't correctly support events coming in the order:

addSubscriber
addConnection
removeSubscriber
addSubscriber (won't receive data)

**Comment by tmontgomery** [comment]
That combination of events sounds what @brianhorst has been tracking down. It might be the same thing.

Here is a little information, though, on what you mention.

A subscription in the dispatcher is protected by ref counts (in essence). So, the only time the subscription should be removed is when no one wants that subscription. A subscription is unique to a channel + streamId. As a NetworkConnection is specific to a channel + streamId, they should not be shared by another subscription unless that subscription is also the same channel + streamId.

**Comment by jessefugitt** [comment]
Ya I've been working with @brianhorst and it seems like a separate bug but in the same general area.  He has a small fix that allows the inactive connection callback to work but it doesn't fix the subscription deafness problem I'm seeing.

**Comment by jessefugitt** [comment]
After more digging on this issue, the root cause seems like it is actually composed of two major issues.  The first issue is that the a REMOVE_SUBSCRIPTION client command ends up being handled in two parts in the driver (on two different threads) and in that window, an ADD_SUBSCRIPTION client command in the DriverConductor can end up being associated with the NetworkConnection that is about to immediately be marked inactive and removed.  The second issue is that after the receiver thread marks the connection inactive, the subscription on the client never fixes up its state causing the client subscription to never get data for the specific publication.

More Details
The subscription is being cleaned up as part of the remove client command and leads to a RemoveSubscriptionCmd (receiver command) being put on the receiver's command queue which will later cause the NetworkConnection to be marked inactive and then cleaned up.  Meanwhile, the ADD_SUBSCRIPTION client command being processed on the conductor thread becomes associated with the NetworkConnection (just before it is marked inactive) and that connection and log file information is communicated back to the client because it appears to be valid at that instant.  The NetworkConnection then goes away after being marked inactive on the receiver thread and no data is ever delivered back to the client but yet the client continues to believe that it is still connected to a valid NetworkConnection for a given publication's sessionId even though new NetworkConnections are being created and delivered by the driver for that publication.

I don't see an obvious fix other than reworking how the remove subscription flow works and possibly setting a flag when the refCount goes to 0 for a given channelEndpoint/streamId to prevent add subscriptions from being associated to something that is about to be cleaned up.  Any other ideas for a fix @tmontgomery ?

**Comment by tmontgomery** [comment]
From what you are saying, the sequence of events is:

1. ADD_SUBSCRIPTION
1. new connection
1. REMOVE_SUBSCRIPTION
1. ADD_SUBSCRIPTION (before Receiver thread can set status)

Correct?

**Comment by jessefugitt** [comment]
There is a new system test in the pull request (see StopStartSecondSubscriberTest in https://github.com/jessefugitt/Aeron/commit/2db7d96e03ebf6bf55f96b674da9fdf8f739be14) that reproduces this behavior every time and basically, yes, you just need a publication running and then do ADD_SUBSCRIPTION, REMOVE_SUBSCRIPTION, ADD_SUBSCRIPTION.

**Comment by tmontgomery** [comment]
Thanks! Yes, I see the test. I was just making sure I had the sequence of events correct from what you observed. The system test is great, but it is harder to make the sequence happen with. A test under DriverConductorTest is ideal in that it can assert the exact sequence and verify behavior.

Also, knowing the sequence let's me think how best to handle it.

**Comment by jessefugitt** [comment]
Also, the other tricky thing about reproducing is that you must have another subscriber on the same channel but on a different stream.  In the system test, 3 of the 4 tests pass (the one that fails is *SameChannelDifferentStreams)

```
    @Test(timeout = 10000)
    public void shouldReceiveMessagesAfterStopStartOnSameChannelSameStream() throws Exception
    {
        shouldReceiveMessagesAfterStopStart(CHANNEL1, STREAM_ID1, CHANNEL1, STREAM_ID1);
    }

    @Test(timeout = 10000)
    public void shouldReceiveMessagesAfterStopStartOnSameChannelDifferentStreams() throws Exception
    {
        shouldReceiveMessagesAfterStopStart(CHANNEL1, STREAM_ID1, CHANNEL1, STREAM_ID2);
    }

    @Test(timeout = 10000)
    public void shouldReceiveMessagesAfterStopStartOnDifferentChannelsSameStream() throws Exception
    {
        shouldReceiveMessagesAfterStopStart(CHANNEL1, STREAM_ID1, CHANNEL2, STREAM_ID1);
    }

    @Test(timeout = 10000)
    public void shouldReceiveMessagesAfterStopStartOnDifferentChannelsDifferentStreams() throws Exception
    {
        shouldReceiveMessagesAfterStopStart(CHANNEL1, STREAM_ID1, CHANNEL2, STREAM_ID2);
    }```

**Comment by tmontgomery** [comment]
By allowing the conductor thread to set the connection status, it could flap back from LINGER to INACTIVE, I think, if the Receiver deems the connection not getting data for a while. This results in double ON_INACTIVE_CONNECTION events.

Saw this a couple weeks ago and fixed it by adhering to a stricter means of changing status.

**Comment by tmontgomery** [comment]
I changed this to look at the network connection subscriber count and avoid setting the status. This seems to work. So, going to close this as of c39160d4904424b85e1073484cf226557c0893a9

A quick check on your end, @jessefugitt , would be great.

**Comment by jessefugitt** [comment]
It seems fine to check the connection subscriber count as you are doing now (so that you don't need to modify connection status from the driver conductor thread).  Also, when I run the newly added system test (which was failing) from the pull request that you merged, it now passes and the original use case of stopping and restarting a subscriber process also works as expected so this one looks fixed to me.
