### ISSUE TITLE
C driver stops responding after some time: no driver heartbeat detected

### ISSUE THREAD

**Issue by yuriymyronovych** [real-logic/aeron#1419]
Running:
 - C driver release/1.40.x.       version.txt="1.40.1-SNAPSHOT"
 - java client 1.40.0

After a few days days of normal operations I am unable to instantiate new Aeron java instance, it throws "DriverTimeoutException". Behaviour often observed when closing some or all of existing subscribers/publishers via Aeron.close and attempting to create new Aeron instances in new java process. Subs/pubs are mostly MDC and IPC

ps -x shows running aeron process
ErrorStats: 0 distinct errors observed.
Aeron Stats:
05:45:56 - Aeron Stat (CnC v0.2.0), pid 83222, heartbeat age 545018ms
  0:       62,811,684,768 - Bytes sent
  1:    9,790,476,101,912 - Bytes received
  2:        4,220,393,535 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:        4,276,188,552 - Failed offers to DriverConductorProxy
  5:                    0 - NAKs sent
  6:                    0 - NAKs received
  7:          228,542,503 - Status Messages sent
  8:           33,125,829 - Status Messages received
  9:           42,830,104 - Heartbeats sent
 10:          248,110,212 - Heartbeats received
 11:                    0 - Retransmits sent
 12:                  375 - Flow control under runs
 13:                1,871 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:                    0 - Short sends
 17:                    0 - Failed attempt to free log buffers
 18:                    0 - Sender flow control limits, i.e. back-pressure events
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    0 - ControllableIdleStrategy status
 23:                5,542 - Loss gap fills
 24:                    0 - Client liveness timeouts
 25:                    0 - Resolution changes: driverName= hostname=*****

**Comment by mikeb01** [comment]
I notice you are using a snapshot version of the driver.  Which version are you running?  We have made some changes around the way resources are closed within the driver recently.

**Comment by yuriymyronovych** [comment]
@mikeb01 we are running this one:

commit 5f1ba0aa33f80d40e9ab85cd8752f91dbf31de3e (HEAD -> release/1.40.x, origin/release/1.40.x)
Author: Dmitry Vyazelenko <696855+vyazelenko@users.noreply.github.com>
Date:   Mon Nov 21 17:24:40 2022 +0100

**Comment by mikeb01** [comment]
We may have addressed this in commit: 055131d3e4040f4487c92762a7508628647a4ec3.  If you can try that or some later version.  Prior to this change closing a large number of publications or subscriptions could stall the conductor thread resulting in client timeouts.

**Comment by yuriymyronovych** [comment]
thank you, I will close the issue for now and will recreate if the same will be happening on latest master commit.
