### ISSUE TITLE
Aeron Cluster Tutorial doesn't work with Aeron 1.40

### ISSUE THREAD

**Issue by pieceofchum** [real-logic/aeron#1420]
Just reporting that trying to start the basic-auction-cluster in the Aeron Cluster tutorial gives the following error:

[663524.832683] log started 2023-02-04 20:16:18.899-0500
Exception in thread "main" Exception in thread "main" Exception in thread "main" io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
        at io.aeron.archive.Archive$Context.conclude(Archive.java:985)

This occurs with Windows and Linux using either JDK17 or 11.

**Comment by mikeb01** [comment]
Thank you, we had patched this in HEAD, but the tutorial runs off the release version.  I've created a branch from the 1.40.0 release that includes the fix and updated the tutorial documentation to reference that branch.

**Comment by pieceofchum** [comment]
Thanks this is great news.Sent from my iPhoneOn Feb 7, 2023, at 6:48 PM, Michael Barker ***@***.***> wrote:﻿
Thank you, we had patched this in HEAD, but the tutorial runs off the release version.  I've created a branch from the 1.40.0 release that includes the fix and updated the tutorial documentation to reference that branch.
