### ISSUE TITLE
port conflict after role change from leader to follower then to leader

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1430]
1. leader node adds publication for log channel
2. The leader node becomes follower and close the log channel. But since the close is asynchronous, the resource related to log channel such as port is not cleared immediately.
3. The node becomes leader again and adds publication for log channel again. Since port has not been closed yet, address already used problem appears.

![image](https://user-images.githubusercontent.com/1705403/221419062-c2185f53-831b-4cc7-816f-c6e546965868.png)

**Comment by mjpt777** [comment]
You can experiment with setting shorter linger value for the log as the conditions for its use are special. We have also been making changes lately with EOS-SMs to shorten the linger period based on state of the receivers.

If you wish to get into more specialised tuning of Aeron we can offer commercial support at sales@aeron.io.
