### ISSUE TITLE
Building C++ without Java

### ISSUE THREAD

**Issue by mark-99** [real-logic/aeron#1432]
Hi, we're interested in using Aeron, but the Java dependency in the build process is a bit of a show-stopper.

The docs say "JDK 8 or later to compile the SBE schema definitions used by the archive client."

- What is the "archive client" and can be built without it? We just need a low latency transport protocol to send data between servers, no other bells & whistles. *edit* ok found this: https://github.com/real-logic/aeron/wiki/Aeron-Archive , yeah we definitely don't need that.
- We definitely don't need SBE protocol, can it be compiled without this, thus removing JDK requirement?
- Alternatively can the SBE schemas be pre-compiled once and we just add them to the source tree (and then ignore them as they won't be used anyway).

We're trying to add Aeron as a (local) vcpkg portfile, and having to both install Java everywhere and have some cheesy `set(ENV{JAVA_HOME} "C:\\Program Files\\Java\\jdk-18.0.2.1")` in our build is not ok.

I'd imagine a lot of people go through this loop, lose patience and just use something else, but thought I'd see if there is a solution.

Also I'd strongly encourage you to submit Aeron to vcpkg & Conan so there's 1st class support, to reduce friction and thus encourage wider adoption.

Thanks.

**Comment by mikeb01** [comment]
```
cmake -DBUILD_AERON_ARCHIVE_API=OFF -DAERON_SYSTEM_TESTS=OFF ${AERON_SOURCE_DIR}
```
If you make any local changes to the implementation I would recommend installing Java in order to run the system tests.

> Also I'd strongly encourage you to submit Aeron to vcpkg & Conan so there's 1st class support, to reduce friction and thus encourage wider adoption.
This hasn't come up with customers previously and is not currently on our radar.  We would consider any PRs required to make the build work with their submission process.
