### ISSUE TITLE
The cluster gets stuck when leader encounters port already in use problem

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1433]
Hi, this is a follow up issue of https://github.com/real-logic/aeron/issues/1430

When the leader encounters this problem, it will get stuck and no new election will occur. The result is the whole cluster will get stuck.

I think it's a serious problem. Could you have a look at it?

It's easy to reproduce the problem:
1. start two nodes in a 3-node cluster
2. kill the follower
3. restart the follower when leader has "io.aeron.cluster.client.ClusterEvent: WARN - inactive follower quorum"

If the previous leader becomes leader again, you will see the above problem. Starting the 3rd node doesn't help.

Thanks very much for you attention.

**Comment by spiritlcx** [comment]
> You will have to manage your port usage better. This is expected and we have no plans at the moment to change this.

Thanks very much. We solved this problem by setting random port for control endpoint of log channel.

**Comment by mjpt777** [comment]
Setting control endpoint on the log channel is not advised.
