### ISSUE TITLE
Subscriptions on multiple streams

### ISSUE THREAD

**Issue by alvinccc** [real-logic/aeron#1434]
In the sample codes of documents, it is always have one subscription at the client side. How do we handle polling for multiple subscriptions? Any better way to do it other than approach like below?
```
while (running)
{
  for (int i=0; i<num_of_subscriptions; ++i)
    subscriptions[i]->poll(handler, FRAGMENTS_LIMIT);
}
```

**Comment by tmontgomery** [comment]
That is the current way. We may add something like epoll at some point in the future for supported customers, though.
