### ISSUE TITLE
new subscription receive message published by publication long time before

### ISSUE THREAD

**Issue by kylejan** [real-logic/aeron#1439]
The case can be reproduced with the default pub/sub example using aeron::ipc channel.

1. Start running the publication to publish an integer
2. Start running the subscription to retrieve integers
3. Close the subscription process with ctrl-c and record the last integer it received
4. Wait some times for about several minutes or longer
5. Start a new subscription to the same channel to retrieve new integers, record the first integer it received
6. Repeat step3 to step5

And in step5, sometimes you can find the first integer received by subscription could have a large gap compared to the second integer it received.

For example, the integer we get in step3 could be 10000, and the first integer we get in step5 could be 10001, and the second integer we get in step5 could be 11000

**Comment by mikeb01** [comment]
Given the implementation of the BasicPublisher/BasicSubscriber (which is what I am assuming you mean by the default pub/sub example).  If you are disconnecting and reconnecting the subscriber then you will see gaps in the integer sequences.  The publisher will increment the value on a failed offer, this will create gaps in the sequence.

**Comment by ethan-wj** [comment]
the case is comparing integers on the same reconnected subscription in step 5. it means that the integers received by the new subscription will have gaps (10001, and then 11000, both of them are received by the new subscription which have large gaps)

do you mean this situation is normal?

**Comment by kylejan** [comment]
the case is comparing integers on the same reconnected subscription in step 5. it means that the integers received by the new subscription will have gaps (10001, and then 11000, both of them are received by the new subscription which have large gaps)

do you mean this situation is normal?
