### ISSUE TITLE
LocalSocketAddressIndicator.close()  have concurrent security issues

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1443]
Is there a bug? since aeron-1.40.0
Before version 1.40.0, this method was always called from a DriverConductor thread

![image](https://user-images.githubusercontent.com/13658946/228725999-bd0c3ec0-cd9f-4f65-ba08-09c74eb68ad2.png)

**Comment by WorkingChen** [comment]
Whether to use ConcurrentCountersManager can avoid this bug?  Will there be any performance impact？

**Comment by mjpt777** [comment]
Yes there could be latency spikes.
