### ISSUE TITLE
Is there any way to run archive use linux command?

### ISSUE THREAD

**Issue by liujingjun001** [real-logic/aeron#1446]
hi ~ 
I compiled the c++, and then I got a lots linux command, so I can test MediaDriver Pub/Sub very easy. such as use aeronmd, BasicPublisher, BasicSubscripter command.
And then, I want to learn how to use AeronArchive, I see the java class ArchingMediaDriver.launch(), it's startup a MediaDriver and startup a Archive. I use the outside aeronmd and startup Archive success.
so, I guess/want to startup Archive by linux command.
and also, I want to startRecording and startReplay by linux command for basic testing/learning.
How can I do this?
Because I don't find any command about Archive, so I don't know is it prosable.
Thanks for help.

**Comment by mikeb01** [comment]
Use the [archiving-media-driver](https://github.com/real-logic/aeron/blob/master/aeron-samples/scripts/archive/archiving-media-driver) script to start a media and archive.  The you can use the [recorded-basic-publisher](https://github.com/real-logic/aeron/blob/master/aeron-samples/scripts/archive/recorded-basic-publisher) to record data and [replayed-basic-subscriber](https://github.com/real-logic/aeron/blob/master/aeron-samples/scripts/archive/replayed-basic-subscriber) to replay it.

You will need to have a Java runtime installed as Archive service is only implemented in Java.  However, there is a C++ API for archive.

**Comment by liujingjun001** [comment]
emm I'm looking for a c++ version. Not run with Java. I think use java to testing is complex, the compiled linux command is simple to use.
