### ISSUE TITLE
Subscribed Applications on same channel stalls when application on server shuts down

### ISSUE THREAD

**Issue by alexkoon** [real-logic/aeron#1450]
We have an application on Server 1 publishing data.

Multiple applications (App A, B, C, D ,E for example) on Server 2 are subscribed and receiving this data. We need to upgrade one of the applications and so shutdown App E for example. This gracefully shuts down, closing the Subscription.

The other existing running applications seem to stall and recover during the shutdown. Aeron Stat shows flow control over runs. I couldn't find any good documentation explaining for the over runs mean and how to rectify/tune out the issue.

Can anyone explain and point to where to fix, tune, or alleviate the stalls in existing running apps on the same channel?

**Comment by mjpt777** [comment]
Please ask usage questions on Stackoverflow.
