### ISSUE TITLE
Nak counter belonging to channel

### ISSUE THREAD

**Issue by moyeanl** [real-logic/aeron#1451]
If there is network packet loss on a channel, the subscription will send nak messages to the publication. Then the publication will resend data in the sender thread, which would reduce the sending rate of other publications.I hope that if I can sense the number of naks in the channel, I can turn off the publication of the channel that generate a large number of naks to avoid having a worse impact.But I can not do that because the nak counter is the sum of all NetworkPublications, rather than belonging to a particular one.

**Comment by tmontgomery** [comment]
You should look into the loss reporter. i.e. the LossStat application.

**Comment by moyeanl** [comment]
> You should look into the loss reporter. i.e. the LossStat application.

The loss reporter is in the receiver of the channel，but not the sender.As a publication, if the subscription would not close itself, it can not close itself through check the network packet loss.
