### ISSUE TITLE
C media driver under real-time schedulers such as SCHED_FIFO?

### ISSUE THREAD

**Issue by shuhaowu** [real-logic/aeron#1462]
Hi! I'm interesting in use Aeron in a networked soft real-time system (robotics) under Linux with the `PREEMPT_RT` patchset. I've read through the docs and a bit of the code and I noticed that Aeron is trying to control the OS scheduler by using various idle strategies. Nowhere has things like real-time scheduling been mentioned. Searching through the internet also has not yielded anything. Looking [at the code](https://github.com/real-logic/aeron/blob/ea3d4c78af5908475fe02dd547cc04614bba7603/aeron-client/src/main/c/aeron_agent.c#L413-L438) seems to show that no real-time scheduling has been employed.

This is all fine. I'm wondering (1) if anyone has tried to use Aeron media driver with something like `SCHED_FIFO` or another real-time scheduler (see [sched(7)](https://manpages.ubuntu.com/manpages/focal/man7/sched.7.html)) under PREEMPT_RT, (2) what kind of performance to be expected there, and (3) what the general experience is like. If no one has done this before, that's fine too and I may investigate it on my own further. Any tips/suggestions would be highly appreciated tho.

Thanks.

**Comment by mikeb01** [comment]
We haven't done any specific testing with the real time scheduling.  However, feedback if you do so would be appreciated.  You may wish to look at the https://github.com/real-logic/benchmarks project to measure any differences.
