### ISSUE TITLE
failed to retrieve snapshot in ClusterBackupAgent

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1467]
Hi,

I encountered a failure of retrieving snapshot when using Aeron cluster and cluster backup with Aeron 1.41.2. The problem occurs occasionally in and after Aeron 1.40.0 and never happen before 1.40.0.

After reviewing the source code, I bet the reason is as follows
1. when cluster backup retrieved the first snapshot, the cluster leader started a replay with session-id, streamId and channel
2. the leader will create a pub. After finishing the replay, the leader will close the pub.
3. but the NetworkPublication is not destroyed immediately. There is some state transition in background. So the record in activeSessionSet is not removed.
4. when cluster backup retrieved the second snapshot, the cluster leader started a new replay with the same session-id, streamId and channel
5. the leader will create a new pub. But as the pub in the first snapshot retrieve is not closed, activeSessionSet.contains(new SessionKey(sessionId, streamId, channel)) will return true and the InvalidChannelException is threw

![image](https://github.com/real-logic/aeron/assets/1705403/995bf0b0-436b-4f44-8318-6257a8bbb071)

 exception in clsuter backup
![img_v2_4560d923-9ad2-42ce-9265-70aea05fc0ch](https://github.com/real-logic/aeron/assets/1705403/bb4c245b-8b6e-47ce-a3d2-697bec84f2e5)·

exception in cluster leader
![img_v2_7d7d438f-e797-4c1b-82b8-8fb8c3b7a50h](https://github.com/real-logic/aeron/assets/1705403/5072a0ee-d7a7-4a01-ae7b-2b4dc9bb2fa9)

**Comment by mikeb01** [comment]
If possible, when this has fails could you capture the output of `ArchiveTool describe` and `ClusterTool recording-log` for leader node and the backup and any other errors that may have occurred in the logs.  This should only occur if the same snapshot was downloaded multiple times.  The session-id gets set by the session-id on the recording so it would normally be unique to a recording.

**Comment by spiritlcx** [comment]
I think it's becuase it doesn't receive RecordingSignal.SYNC signal and poll snapshot again.

I tried to remove this line of code, and the problem can be reproduced.

![image](https://github.com/real-logic/aeron/assets/1705403/f667e480-c7f1-4670-85f3-aab3020beb7e)

![image](https://github.com/real-logic/aeron/assets/1705403/255f9c3e-ce8d-4662-9def-dae9e34574ff)

**Comment by mikeb01** [comment]
I've added fix that will use different session ids when retrying the replication of snapshots, this should prevent the error from occurring.
