### ISSUE TITLE
Is the protocol alignment correct here?

### ISSUE THREAD

**Issue by supergaga** [real-logic/aeron#1471]
under `aeron-archive-codecs.xml `file 

<img width="1245" alt="image" src="https://github.com/real-logic/aeron/assets/13994894/9aaa2100-6092-478d-b50c-2d304b4082e2">

Why is the offset between the two fields so large, and under what circumstances is the middle position useful?

**Comment by supergaga** [comment]
This should be to align 32 bits for easy system reading, but it seems that not all protocols have this kind of mandatory alignment. Can you introduce when it is necessary to force alignment when declaring the protocol, and when is it not necessary?

**Comment by mjpt777** [comment]
This is for alignment and not a bug.
