### ISSUE TITLE
fail to elect a new leader shortly after leader is closed gracefully

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1472]
We used the method described in stackoverflow question below to accelerate election of new leader

https://stackoverflow.com/questions/72871802/is-it-possible-to-reduce-the-timeout-10s-during-cluster-update-by-actively-sh

When closing leader node, consensus module is closed first, and media driver will be closed after 1s. It works fine in Aeron 1.40.0 and before. But in latest version, we find it often fails. 
The reason is as follows:
1. Although EOS has been sent by the pub, and has been received by the receiver, it is not polled by the logAdapter
2. After RecordingSession finds the log channel has been closed, it closes the AppendPosition counter
3. ConsensusModuleAgent will be called on onUnavailableCounter and isElectionRequired = true is set, but logAdapter.isLogEndOfStream() = false since logAdapter has not polled all data. It will have to wait leaderHeartbeatTimeoutNs which is 10s by default to start a new leader

Solution:
If we don't let onUnavailableCounter trigger the new election, but let logAdapter find the log channel has been the end, we can solve the problem.

![image](https://github.com/real-logic/aeron/assets/1705403/1c55ef5b-c591-4e67-8752-bc68840eed7e)

**Comment by fanlei1314** [comment]
Hi, I've encountered this problem with Aeron, and I'd like to enquire about when a fixed version of this Issue will be officially released!
