### ISSUE TITLE
Not able to compile on linux .

### ISSUE THREAD

**Issue by shrikantpalekar** [real-logic/aeron#1477]
In cppbuild/cppbuild file we have 
SOURCE_DIR="$(pwd)"
I just made  below change and everything started compiling .  Please fix it .  
SOURCE_DIR="$(pwd)/.."

**Comment by shrikantpalekar** [comment]
@tmontgomery  Please help to FIX it

**Comment by vyazelenko** [comment]
@shrikantpalekar The correct way to invoke the C/C++ build is by calling the `cppbuild` script from the root directory, e.g.:
```bash
$  cppbuild/cppbuild
```
