### ISSUE TITLE
replay continues when replayLimit counter is closed

### ISSUE THREAD

**Issue by spiritlcx** [real-logic/aeron#1478]
We have the problem of polling and consuming uncommitted raft log when using AeronCluster and a service boundedReplaying archive of the cluster

1. In leader node, ConsensusModule is closed before archive, causing commitPosition counter is closed before archive
![image](https://github.com/real-logic/aeron/assets/1705403/4dc3e290-0155-4c6f-8cb6-fc6d4d77e687)
2. ReplaySession is still working since archive is alive. But as the commitPosition counter has been closed, ReplaySession will replay data to stop position, which can be later than commit position.
![image](https://github.com/real-logic/aeron/assets/1705403/aed657a6-66bf-4a70-bcae-f358f601f97e)
3. If the raft log in previous leader node is truncated later, the consumed data will be invalid.

**Comment by mjpt777** [comment]
This has been fixed with https://github.com/real-logic/aeron/commit/ee7c0ed1d4a95f9a0b68e5249b7b7338d340b3ea and https://github.com/real-logic/aeron/commit/c59bdb710a64f0de7d7afcf64bde8fa0a91ba3e7
