### ISSUE TITLE
Kafka Connect for Aeron cluster

### ISSUE THREAD

**Issue by calinfonet** [real-logic/aeron#1486]
I am designing  Kafka Sink and Source connectors to stream messages in to and from Aeron cluster. Can Archiving Media Driver used a starting point for stream in message in to a Kafka topic from an Aeron clusters?

**Comment by JPWatson** [comment]
Using the Archive is a common option allowing you to rate adapt between the cluster and a downstream system. If you're interested in exploring options for your particular use case, please drop an email to info@aerion.io.
