### ISSUE TITLE
How do pod containers in k8s communicate with the outside world through aeron? 

### ISSUE THREAD

**Issue by qinglok** [real-logic/aeron#1491]
For example, a subscriber in k8s usually has a channel like this: aeron:udp?endpoint=${POD_IP}:20121,
Among them, ${POD_IP} is unknown to the outside world, so it will not work.
Another way, by deploying a k8s service, what should the endpoint of the subscriber look like?

**Comment by vyazelenko** [comment]
@qinglok This is a question on how to access k8s pod from the outside and is not Aeron-specific. It is best answered elsewhere (e.g. https://blog.frankel.ch/basics-access-kubernetes-pods/).
