### ISSUE TITLE
Image: Active Transport Count

### ISSUE THREAD

**Issue by kinghchan** [real-logic/aeron#1494]
Hello,

What exactly does the 'active transport count' mean in an Image object? I can see it is used in ReplayMerge, but I can't find much documentation on what it means.

Thank you.

**Comment by tmontgomery** [comment]
It indicates how many receive destinations (https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/Subscription.java#L461) are active within an Image. For more, check out the wiki on Multi-Destination Subscriptions (https://github.com/real-logic/aeron/wiki/Multiple-Destinations#multi-destination-subscriptions)
