### ISSUE TITLE
MDC subscriber ephemeral port increased network traffic

### ISSUE THREAD

**Issue by m4ce** [real-logic/aeron#1498]
Been playing with Aeron for the last couple of weeks and I believe the MDC subscription could be improved when using a random ephemeral port and multiple MDC subscribers (on the same host) receiving data from the same MDC publisher.

Take the following example:

Publisher:
- channel: aeron:udp?control-mode=dynamic|control=192.168.0.100:9000 | streamId: 1

Subscribers (same host):
- channel: aeron:udp?endpoint=192.168.0.101:10000|control=192.168.0.100:9000 | streamId: 1
- channel: aeron:udp?endpoint=192.168.0.101:10000|control=192.168.0.100:9000 | streamId: 1

In the above case, the media driver will bind to UDP 127.0.0.1:10000 which is where the MDC publisher will send data too. The second subscription will work too as it seems Aeron understands there's already a socket bound to that ip/port and just reuse it.

However, reality is that most people won't probably feel like managing the port on the subscriber's side when dealing with MDC, which is likely the reason why you added support for a random ephemeral port.

Publisher:
- channel: aeron:udp?control-mode=dynamic|control=192.168.0.100:9000 | streamId: 1

Subscribers (same host):
- channel: aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000 | streamId: 1
- channel: aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000 | streamId: 1

In the above case, Aeron media driver will actually create two UDP sockets on two different randomly selected ephemeral ports. I am not sure if this makes sense? What happens now is that the MDC publisher will now have to send data to the same host **twice**, increasing network traffic for no apparent reason.

IMHO, the media driver should re-use the existing UDP socket that was created by the first subscriber, on the same randomly selected ephemeral port. Or at least there should be a simple URI option to support that, like a reuse port type of thing.

Look forward to hearing your feedback on the above.

**Comment by m4ce** [comment]
I've also tried with tags, which seems like it does achieve some of what I outlined above but operationally is not great.

This works:

Publisher:
- channel: aeron:udp?control-mode=dynamic|control=192.168.0.100:9000 | streamId: 1

Subscribers (same host):
- channel: aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000|tags=1001 | streamId: 1
- channel: aeron:udp?tags=1001 | streamId: 1

However, it fails if I run the two subscribers as follows:

- channel: aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000|tags=1001 | streamId: 1
- channel: aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000|tags=1001 | streamId: 1

the 2nd subscribers fails with:

```"(-11) generic error, see message\n[aeron_async_add_subscription_poll, aeron_client.c:537] async_add_subscription registration\n== Driver Error ==\n(22) Invalid argument\n[aeron_driver_conductor_get_or_add_receive_channel_endpoint, aeron_driver_conductor.c:2189] matching tag=1001 has explicit endpoint or control - aeron:udp?endpoint=192.168.0.101:0|control=192.168.0.100:9000|tags=1001\n\n"
```

so now I find myself having to know whether I am the first subscriber or not, which is rather cumbersome operationally speaking. I would really want to run all subscribers with the same channel....

**Comment by mikeb01** [comment]
Using tags is the correct option here.  I will have to look at allowing the specification of parameters when using tags on an existing subscription.  It would be possible to allow it, but we need to make sure that all of the specified options match correctly.  If we find an tags with an existing subscription, but it has different URI parameters, then we still need to reject the second subscription.

**Comment by mikeb01** [comment]
I've just merged a PR that should allow this to work if you would like to test with the latest HEAD.

**Comment by m4ce** [comment]
sorry for the late reply but I have been away. I rebuilt the c client as well as the c media driver but I keep getting the same error?

```
Error: aeron_async_add_subscription_poll: "(-11) generic error, see message\n[aeron_async_add_subscription_poll, aeron_client.c:537] async_add_subscription registration\n== Driver Error ==\n(22) Invalid argument\n[aeron_driver_conductor_get_or_add_receive_channel_endpoint, aeron_driver_conductor.c:2189] matching tag=1001 has explicit endpoint or control - aeron:udp?endpoint=127.0.0.1:0|control=127.0.0.1:9000|tags=1001\n\n"
```

publisher: aeron:udp?control-mode=dynamic|control=127.0.0.1:9000
subscribers: aeron:udp?endpoint=127.0.0.1:0|control=127.0.0.1:9000|tags=1001, aeron:udp?endpoint=127.0.0.1:0|control=127.0.0.1:9000|tags=1001

The second subscriber fails. Am I doing something wrong?

**Comment by mikeb01** [comment]
I can't see anything obvious from the snippet posted, however the test we are using verification is here: https://github.com/real-logic/aeron/blob/master/aeron-system-tests/src/test/java/io/aeron/PubAndSubTest.java#L676.  This test passes on both the Java and C media drivers.

If you could provide a fuller example that triggers the problem then we can test with it in case we have missed something.

**Comment by m4ce** [comment]
@mikeb01 - my bad, as soon as I saw the UTs I knew it'd be my issue. I didn't rebase correctly. All good, works like a charm now. Thank you.
