### ISSUE TITLE
onStart is executed after doBackgroundWork in case snapshot exists

### ISSUE THREAD

**Issue by RostyslavBaldovskyi** [real-logic/aeron#1506]
Seems like after [this commit](https://github.com/real-logic/aeron/commit/1a6106dbd63405b940c30e5f84a9f952792ea973) **doBackgroundWork** became not stable. For case when there no snapshot (clean start) it is fine - **onStart** is executed first and **doBackgroundWork** after. For case when there is a snapshot it is opposite. In my case **onStart** initializes variables for **doBackgroundWork** and it gets NPE due to this order. On 1.42.0 all is okay.

**Comment by mjpt777** [comment]
Yes there was a change of behaviour but I would say it had become unstable. :-)

I've revisited the concept of when a service is active and that should be after a successful start so `ClusteredService.onStart` can be parted with `ClusteredService.onTerminate`. You should have more consistent behaviour after [this](https://github.com/real-logic/aeron/commit/6edc00e8e4ae9e437ddda883dc2922b0ec0c32e2) commit.
