### ISSUE TITLE
Message "Max Window length greater than socket SO_RCVBUF" could be improved

### ISSUE THREAD

**Issue by rolandyoung** [real-logic/Aeron#151]
The message “Max Window length greater than socket SO_RCVBUF” actually relates to the parameter `aeron.rcv.initial.window.length`, but this is hard to discover without reading the source code.
Also, the documentation for that parameter does not mention that its value must be <= SO_RCVBUF.

(I encountered this issue on Centos 6.6, where the default value for SO_RCVBUF is rather low.)

**Comment by tmontgomery** [comment]
Thanks! Will look into how to reword.

**Comment by matthewdowney** [comment]
Came across this error message—and subsequently this thread—and it still took me a minute to resolve because I wasn't familiar with how to set the `SO_RCVBUF` value. The error message could include a suggestion to use `sysctl` to set `net.core.rmem_max` and `net.core.rmem_default`.

Once I'd run 
```
$ sudo sysctl net.core.rmem_max=131072
$ sudo sysctl net.core.rmem_default=13107
```
Everything worked fine.

**Comment by rolandyoung** [comment]
I must admit I didn't even think of altering SO_RCVBUF (despite the fact that I was using a VM!) So I wanted to set an Aeron configuration parameter and thought that the error message should have told me which one was the problem. It would be tricky to provide a hint on changing SO_RCVBUF that would apply to all target platforms and fit in a reasonable error message, but maybe the template config file could provide some advice in the form of a comment on the parameter.

**Comment by mjpt777** [comment]
I've updated the error messages to indicate which properties should be changed in each case. 

With regard to how to set OS buffer sizes, I agree with @rolandyoung that doing this in an OS independent manner is not really possible. A basic level of networking configuration knowledge is required when working with UDP messaging system.

**Comment by mjpt777** [comment]
How to change the buffers sizes and startup properties are provided in the performance testing section on the Wiki.

https://github.com/real-logic/Aeron/wiki/Performance-Testing
