### ISSUE TITLE
How can the driver safely timestamp any fragment at an offset?

### ISSUE THREAD

**Issue by reissGRVS** [real-logic/aeron#1514]
Currently it seems the driver will timestamp the first fragment in any call to aeron_send_channel_send. This fragment could be a fragment in the middle of a published message.

How can the publisher have allocated space for this timestamp to be populated into?
I understand being able to do this for a fragment with the B flag set, as its trivial for the app to leave room at the start of a buffer for the timestamps. But dont understand how it could be achieved for non BEGIN fragments.

To me it seems like aeron_timestamps_set_timestamp should check for AERON_DATA_HEADER_BEGIN_FLAG being set

**Comment by mikeb01** [comment]
This should be fixed now.  There is a test to cover this as well.

**Comment by reissGRVS** [comment]
I think https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/c/media/aeron_send_channel_endpoint.c#L301-L308 needs fixed as well, either it shouldn't loop, or it should but only until it successfully sets the timestamp?

**Comment by mikeb01** [comment]
This isn't broken as it stands.  You can have multiple entries in those vectors consisting of non-fragmented packets.  It could be a little less efficient if you wanted to assume that two packets in the same vector would have the same timestamps.  Given that the iov in this case is generally fairly small (default is two), then optimising for an early exit from the loop is probably not worth the complexity.

**Comment by reissGRVS** [comment]
It’s currently accessing index 0 on each loop iteration, it’s not using i at all

**Comment by mikeb01** [comment]
I'd missed that part, it is fixed now
