### ISSUE TITLE
Publications lock up on re-using streamIds

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#152]
If Ping Pong is rerun in a 3 process configuration then if the Ping is stopped and shutdown then restarted it does not complete warmup. This is likely to be related to the publications changes for driver allocated sessions.

**Comment by tmontgomery** [comment]
I noticed that since the changes, one of the different behaviors is that if a Publication is closed and then restarted that the old Publication is re-used for the new Publication. This works fine.

However, PingPong waits on a latch that comes in, so re-using a Publication may not trigger the newImage callback and thus not countdown the latch.

**Comment by mjpt777** [comment]
I think the old publication should not be reused once all refs to it are gone. I thought I handled that but most have missed something.

**Comment by tmontgomery** [comment]
I am guessing that is what is going on.

But I did notice the behavior when I was playing with `BasicPublisher` and `BasicSubscriber`.

**Comment by mjpt777** [comment]
I'll have a look into it tomorrow.

**Comment by tmontgomery** [comment]
This is beyond Ping Pong. 

While trying to add proper support for `Publication.offer` returning `NOT_CONNECTED`, I've been chasing an odd behavior where re-used Publications would wedge. I thought it was definitely my changes. But it doesn't appear to be. And after taking out my changes, it still happens.

1. Start driver
1. Start RateSubscriber
1. Start StreamingPublisher with 500M 40 byte messages. Let it run to completion. Then don't continue.
1. Re-Start StreamingPublisher

I've been seeing the second invocation stop right after about 200K messages, then stopping on the send.

```
Streaming 500,000,000 messages of size 40 bytes to udp://localhost:40123 on stream Id 10
2.6e+05 msgs/sec, 1.0e+07 bytes/sec, totals 262143 messages 9 MB
0.0 msgs/sec, 0.0 bytes/sec, totals 262143 messages 9 MB
0.0 msgs/sec, 0.0 bytes/sec, totals 262143 messages 9 MB
```

There is something a little deeper than just the Ping/Pong app going wrong. I'll change the title.

**Comment by tmontgomery** [comment]
BTW, the messages sent show (200K of them) are simply filling up flow control window between the Publication and the Sender. They don't seem to make it out to the wire.

Which might partially explain what is happening.

**Comment by tmontgomery** [comment]
What I have found out... so you can use it as you progress.

- SMs are being sent and come in. There is plenty of flow control room.
- Plenty of data (I think) in the LogBuffer to be sent.
- Sender thread won't send. isActive seems to be set.

**Comment by hdw09** [comment]
great

At 2015-07-25 08:24:42, "Todd L. Montgomery" <notifications@github.com> wrote:


What I have found out... so you can use it as you progress.

SMs are being sent and come in. There is plenty of flow control room.
Plenty of data (I think) in the LogBuffer to be sent.
Sender thread won't send. isActive seems to be set.

**Comment by tmontgomery** [comment]
The change to eliminate re-using the Publication when it is removed is the best solution for many reasons.

However, I would love to know why re-using them in the first place was failing like it was.... only because it is a mystery that I didn't solve. :)
