### ISSUE TITLE
Does aeron support "ReadIndex Read" and "Lease Read"

### ISSUE THREAD

**Issue by liujingjun001** [real-logic/aeron#1520]
<img width="433" alt="image" src="https://github.com/real-logic/aeron/assets/51243472/e6c2836c-86ad-4df2-b7bc-5036bbb083cc">
<img width="428" alt="image" src="https://github.com/real-logic/aeron/assets/51243472/2596b579-f225-4add-9ae6-a491b9968a98">

If we have a lot of read request, so use raft log to implements read will cause disk space increase quilk.
so, does aeron cluster have any solutions?

thanks your help

**Comment by mjpt777** [comment]
Please ask usage questions on Stackoverflow or contact sales@aeron.io for commercial support.
