### ISSUE TITLE
Can use Cluster instead AeronCluster ?

### ISSUE THREAD

**Issue by liujingjun001** [real-logic/aeron#1521]
hi what's the difference between below method ? can use Cluster.offer() replace AeronCluster.offer() if offer() operation is on the same JVM process ?

io.aeron.cluster.client.AeronCluster.offer()

io.aeron.cluster.service.Cluster.offer()

**Comment by mjpt777** [comment]
Simple answer is no.

Please ask usage questions on Stackoverflow.
