### ISSUE TITLE
erase on const_iterator bug in gcc 4.8.2

### ISSUE THREAD

**Issue by alberthidalgo** [real-logic/Aeron#153]
I'm getting a compile error in aeron-client/src/main/cpp/ClientConductor.cpp:132 and believe it may be due to erase not being implemented for const_iterator: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57158

Not sure if I missed a minimum target gcc version or if you plan on a workaround for this.

**Comment by tmontgomery** [comment]
What version of gcc are you using and what platform are you compiling on?

**Comment by tmontgomery** [comment]
Ah. I see in the title. Clicking from gitter is always annoying.

I've only been trying gcc 4.9.2. Which seems fine.

**Comment by alberthidalgo** [comment]
Sorry, forgot to lookup and include that information:

gcc 4.8.3 on CentOS 7

**Comment by alberthidalgo** [comment]
I'll try installing gcc 4.9.2 in my home dir and building with that as well.

**Comment by tmontgomery** [comment]
Let me know what you see. Can change the iterators to be non-const as it isn't a big deal.

**Comment by alberthidalgo** [comment]
It builds successfully on my CentOS 7 distro after installing and building with 4.9.2, so this might be specific to gcc 4.8.x

For reference to anyone else, this is what I did to install 4.9.2 on CentOS 7
1. sudo yum install libmpc-devel mpfr-devel gmp-devel
2. cd ~/Downloads
3. curl ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-4.9.2/gcc-4.9.2.tar.bz2 -O
4. tar jxvf gcc-4.9.2.tar.bz2
5. cd gcc-4.9.2
6. ./configure --disable-multilib --enable-languages=c,c++ --prefix=$HOME/gcc-4.9.2
7. make -j <num cores>
8. make install
9. edit ~/.bashrc and/or ~/.bash_profile with:
export PATH="${HOME}/gcc-4.9.2/bin:${PATH}"
export LD_LIBRARY_PATH="${HOME}/gcc-4.9.2/lib64:${HOME}/gcc-4.9.2/lib:${lD_LIBRARY_PATH}"
export CC="${HOME}/gcc-4.9.2/bin/gcc"
export CXX="${HOME}/gcc-4.9.2/bin/g++"
10. source ~/.bashrc or logout/login on your desktop
11. gcc --version should show 4.9.2!

**Comment by tmontgomery** [comment]
Is gcc 4.8.3 the latest version for CentOS 7.

**Comment by alberthidalgo** [comment]
I believe it ships with 4.8.3 and no devtoolset currently exists for an upgraded version of gcc from a repo like 6.x or 5.x

**Comment by tmontgomery** [comment]
Hmmm. I'll remove the const iterator need. It isn't a latency critical path and it might be better to stay up to date with CentOS instead.

**Comment by tmontgomery** [comment]
Try this last commit with gcc 4.8.3 to see if it works and let me know.

**Comment by alberthidalgo** [comment]
That did the trick, it builds on gcc 4.8.3/CentOS 7 now. Thanks!

**Comment by tmontgomery** [comment]
No worries. Glad it works now with the default gcc! :smile:
