### ISSUE TITLE
Question regarding Live replay subscription

### ISSUE THREAD

**Issue by karensaldanha** [real-logic/aeron#1538]
https://aeroncookbook.com/aeron-archive/basic-sample/?h=replaying+archive#replaying-the-archive

In the example above, the replayed subscription starts reading from beginning of the file and starts following a live recording. Does it mean it starts reading a live publication or is reading a recorded live publication( from disk). We want to start reading a recorded file and then switch to a live publication(not from disk for latency purposes). Do we need to implement replay merge for what we want to achieve?

Thank you

**Comment by JPWatson** [comment]
Hey @karensaldanha Yes, ReplayMerge is what you need to be able to switch onto the live publication.
