### ISSUE TITLE
Cluster Follower's logChannel rejoin cost too much time 

### ISSUE THREAD

**Issue by moyeanl** [real-logic/aeron#1540]
We used MaxMulticastFlowControlSupplier. So, it would not stop the leader when there was network packet loss from the leader to one of the followers. It was expected. But when the loss was over, the follower would not receive message from leader immediately.     It took over 10 minutes to rejoin logChannel to replay raft log. How it works to cost too much time. Is there anything wrong?
![image](https://github.com/real-logic/aeron/assets/13097558/9db8ff76-e8f3-42c4-b745-94db0516c6cc)

**Comment by JPWatson** [comment]
I wouldn't expect it to take 10 mins to rejoin. Using max flow control on the log channel is an advanced use-case and we can provide commercial support to assist you with investigating this kind of issue. Please contact sales@aeron.io.
