### ISSUE TITLE
Multi-channel sends

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#155]
A logbuffer is a data structure that can be directly sent to a network or shared over a shared memory media. This basic functionality allows for a very interesting way to handle sending data to multiple receivers.

It should be possible to allow a Publication to send to multiple channels and stream ids without requiring the publication to multi-`offer` to each in turn. A single `offer` to a single logbuffer should be sent to multiple receivers.

In addition, it should be possible to allow a multi-unicast send with these semantics that appears to have the same late join and other semantics of the multicast channel, but without the multicast semantics.

Additionally, it would be excellent to optimize the use of Linux `sendmmsg` to enable sending to multiple destinations in a single syscall.

**Comment by mjpt777** [comment]
Multi-destination now implemented.
