### ISSUE TITLE
Cannot set thread affinity in shared or sharednetwork modes for c media driver

### ISSUE THREAD

**Issue by apmorton** [real-logic/aeron#1558]
`aeron_set_thread_affinity_on_start` does a simple strcmp on the agent role, which is not set to any of the expected values in shared or sharednetwork modes, and so thread affinity values don't take effect.

**Comment by mikeb01** [comment]
That is correct.  The assumption is that if you are running with shared or shared_network threading modes it is unlikely that much will be gained from using thread affinity.  Moving to dedicated mode will bring more latency improvements (especially in the long tail) over thread affinity.  We generally recommend that applying thread affinity to be one of the steps applied very late in the tuning process.

**Comment by apmorton** [comment]
The trouble is that in shared network mode `AERON_CONDUCTOR_CPU_AFFINITY` still applies, and because the conductor thread is the thread which _starts_ the shared network thread (and after the affinity is applied), you end up with both threads pinned to the same core.

It should either be possible to set affinity for the shared network thread, or the affinity applied to the conductor shouldn't also be applied to the shared network thread.

**Comment by mikeb01** [comment]
We may have a look into that case, but I think the original advice would still apply.  If you don't have the cores available to run in dedicated mode, then you shouldn't be pinning the conductor thread either.  This probably won't bring much benefit and could cause latency issues with other parts of your system.
