### ISSUE TITLE
big latency while transmit small packets cross different AWS zone over Aeron comparing with raw UDP

### ISSUE THREAD

**Issue by CharlieZhao2023** [real-logic/aeron#1572]
Hi, I got round trip latency number of 110 milliseconds (median) while transmit small packets(less than 1024 bytes) from AWS Tokyo to AWS Hong Kong.
my media driver setting is:
```
export AERON_TERM_BUFFER_SPARSE_FILE="0"
export AERON_SOCKET_SO_RCVBUF="4k"
export AERON_SOCKET_SO_SNDBUF="4k"
export AERON_RCV_INITIAL_WINDOW_LENGTH="4k"
export AERON_THREADING_MODE="DEDICATED"
export AERON_CONDUCTOR_IDLE_STRATEGY="noop"
export AERON_SENDER_IDLE_STRATEGY="noop"
export AERON_RECEIVER_IDLE_STRATEGY="noop"
export AERON_NETWORK_PUBLICATION_MAX_MESSAGES_PER_SEND="2"
export AERON_PRINT_CONFIGURATION="1"
export AERON_TERM_BUFFER_LENGTH=67108864
export AERON_IPC_TERM_BUFFER_LENGTH=67108864

/usr/local/bin/aeronmd &
```
I used the same setting on both sides(Tokyo and Hong Kong)
On the other hand, while I use raw UDP to send/receive data, the round trip latency is 70 milliseconds (median).
Are there any other optimization I could make to reduce the latency while transmit data with Aeron in this case?

**Comment by plokhotnyuk** [comment]
@CharlieZhao2023 Have you checked if it possible physically? https://www.cloudping.co/grid

**Comment by CharlieZhao2023** [comment]
@plokhotnyuk

Yes, actually the table is rather helpful. But because I could use raw UDP to achieve lower round trip number, I wonder whether it is expected that Aeron added around 30% overhead to raw UDP and if I could make more optimization in the configuration.

**Comment by mjpt777** [comment]
Some of the config here is not what we would recommend. We also have no idea how the machine is setup. Aeron when setup correctly will add a very small increment on raw latency (~1us). We can provide consulting services and support if you contact sales@aeron.io.
