### ISSUE TITLE
AeronCluster.AsyncConnect can forget to close subscription

### ISSUE THREAD

**Issue by fbaro** [real-logic/aeron#1574]
The `AeronCluster.AsyncConnect#createEgressSubscription` method starts an asynchronous creation of a subscription, and then waits for this creation to complete.
https://github.com/real-logic/aeron/blob/db7537435908665adc36892839bb5b791dc34351/aeron-cluster/src/main/java/io/aeron/cluster/client/AeronCluster.java#L1853-L1858
However, if creation fails to complete before the timeout, the `AsyncConnect.close` method is called. This method fails to cancel the asynchronous subscription.
This, combined with an external retry to connect to the same cluster, ends up with two subscriptions being made to the same stream - one of which is effectively lost, and never polled.

**Comment by vyazelenko** [comment]
@fbaro Thanks for reporting. I'll look into it.
