### ISSUE TITLE
ArchiveException: ERROR - response for correlationId=15, error: 59232 position not aligned to a data header

### ISSUE THREAD

**Issue by dengdaoping** [real-logic/aeron#1583]
environment:
  java: 17
  spring boot: 3.1.5
  aeron: 1.43.0
description:
  When we use aeron archive, after shutting down all services and restarting again, we get `ERROR - response for correlationId=15, error: 59232 position not aligned to a data header, recordingId=5, sessionId=27680399597.`
In the code, it seems that we are calling the following code to cause this, but I don't know why it is happening
```
sessionId = aeronArchive.startReplay(
          recordingId,
          lastProcessedPosition,
          Long.MAX_VALUE,
          publicationChannel,
          replayStreamId);
```

**Comment by JPWatson** [comment]
Hey @dengdaoping, the lastProcessedPosition you are using doesn't line up with a message boundary. Worth double-checking where you're getting that value from/making sure that you're replaying the correct recording.

**Comment by dengdaoping** [comment]
Hey @JPWatson 
    ```
  var ctx = new Aeron.Context().aeronDirectoryName(aeronDir);
    ctx.availableImageHandler(
        (image) -> {
         aeronImage = image;
        });
    aeron = Aeron.connect(ctx);
    aeronArchive = AeronArchive.connect(new AeronArchive.Context().controlRequestChannel(archiveRequestChannel)
        .controlRequestStreamId(archiveRequestStream)
        .controlResponseChannel(archiveResponseChannel)
        .controlResponseStreamId(archiveResponseStream)
        .aeron(aeron));
```
I'll get the image first, and then I'll get the position from the image.
     `  lastProcessedPosition = aeronImage.position()`

**Comment by JPWatson** [comment]
It looks like you're getting the latest recording ID with the provided stream ID/channel info (assuming there are fewer than 100 matching recordings). I can't say from the snippets you've shared whether the lastProcessedPosition is from that recording.

**Comment by dengdaoping** [comment]
For example, I start startReplay
  
```
    recordingId = findLatestRecording(aeronArchive, channel, streamId);
    sessionId = aeronArchive.startReplay(
        recordingId,
        lastProcessedPosition,
        Long.MAX_VALUE,
        channel,
        replayStreamId);
```

Whenever an application consumes from a recording, it stores the position into redis
`redis.set("lastProcessedPosition", aeronImage.position())`

The problem persists when the service is restarted
`ERROR - response for correlationId=15, error: 59232 position not aligned to a data header, recordingId=5, sessionId=27680399597.`

**Comment by vyazelenko** [comment]
If the `Image` is created as the result of starting a replay it will be receiving data from the recording (i.e. replay `Publication`). The `Image.position()` returns the currently consumed (polled) position from the published stream.

You can use `Image.position()` as the _latest processed position_ but only if you already have an `Image`. Which requires a `Subscription` which in turn relies on the replay being started.
The code to start a replay will be something along the lines:
```java
final Aeron aeron = ...;
final AeronArchive archive = ...;
final String replayChannel = ...;
final int replayStreamId = ...;
final long position = ...;
final int sessionId = (int)archive.startReplay(
    recordingId, position, Long.MAX_VALUE, replayChannel, replayStreamId);

final String replaySessionChannel = ChannelUri.addSessionId(replayChannel, sessionId);
final Subscription subscription = aeron.addSubscription(replaySessionChannel, replayStreamId);

Image image;
idleStrategy.reset();
while (null == (image = subscription.imageBySessionId(sessionId)))
{
    idleStrategy.idle();
}
...
```

There are multiple examples of this in Aeron code base (e.g. [BasicArchiveTest#shouldRecordThenBoundReplayWithCounter](https://github.com/real-logic/aeron/blob/051cd686a964c09f810b5d2903767ff15cf2a7c1/aeron-system-tests/src/test/java/io/aeron/archive/BasicArchiveTest.java#L624)).
