### ISSUE TITLE
Heartbeats being sent, despite no publishing.

### ISSUE THREAD

**Issue by yeetfield** [real-logic/aeron#1586]
I have a publishing application on one host and an instance of Aeron Archive running on another host. On the publishing host, I'm observing within `AeronStat` that `Bytes sent` and `Heartbeats sent` continue to increase, even after I've terminated the publishing program (`pub-pos` does not increase). This causes the recording within Archive to be considered active, which precludes it from deletion. I'm currently mitigating this by restarting `aeronmd`. 

Is there something I need to configure to have the publication deleted in the driver after some timeout where `pub-pos` isn't incremented? Thanks!

I've also got `ssc=True` and `fc=min` set on this channel.

**Comment by yeetfield** [comment]
Anecdotally, I'm also observing that this isn't happening when I reduce the publish rate of my application.

**Comment by mikeb01** [comment]
Do you still have an active subscription somewhere that hasn't reached the most recent published position.  This will result in a publication remaining active in the driver.

**Comment by yeetfield** [comment]
There wasn't an active subscription here, outside of the one that I imagine exists in the Archive.

**Comment by mikeb01** [comment]
How long did you see heartbeats being sent for?  There is also a linger timeout associated with publications before they get removed from the driver.  If it was indefinite, could you post a code example that demonstrates the problem?  Also did you check see if the publication is still visible in AeronStat?

**Comment by yeetfield** [comment]
We'll reopen if this become a priority again; it initially manifested when we were under an unrealistically high load.
