### ISSUE TITLE
Can't build because of unreleased Agrona dependency

### ISSUE THREAD

**Issue by erikvanoosten** [real-logic/Aeron#159]
Commit 3676b9f366b6c17e4bb41424df18b96786806f46 doesn't build because it requires `uk.co.real-logic:Agrona:0.4.3-SNAPSHOT` which is not available in a repository I know of. Downgrading to `0.4.2` didn't work; Aeron needs the new functionality.

**Comment by erikvanoosten** [comment]
Work around: clone [https://github.com/real-logic/Agrona] and build it.

**Comment by tmontgomery** [comment]
Agrona 0.4.3 has been released to maven central.

**Comment by erikvanoosten** [comment]
Thanks!
