### ISSUE TITLE
code examples for C or C++

### ISSUE THREAD

**Issue by kip3f** [real-logic/aeron#1596]
We are looking into using Aeron Transport for a Java / C++ mixed system.  I have reviewed the Cpp Programming Guide, but it would be very helpful to look at some pragmatic code samples.  E.g. on the java side you have example RPC server, example RFQ server.

**Comment by mikeb01** [comment]
C examples: https://github.com/real-logic/aeron/tree/master/aeron-samples/src/main/c
C++ examples: https://github.com/real-logic/aeron/tree/master/aeron-samples/src/main/cpp

**Comment by kip3f** [comment]
Hi, I've seen those already, thanks.  I was wondering if I could find any examples of standalone systems similar to what you have on the Java side.  The Java side of aeron transport is well-documented, but our developers are struggling with the C side.
