### ISSUE TITLE
[C Media Driver]: Custom poller and receiver functions

### ISSUE THREAD

**Issue by yafetn** [real-logic/aeron#1600]
Hello,

I'm experimenting with using eBPF XDP on the receive path for the C Media Driver. So far, I believe I understand the eBPF pieces, but I can't tell if the proper place to hook into Aeron would be via the poller or the receiver functions as bound in `aeron_udp_channel_transport_bindings.c`.

The basic flow is that when a packet first arrives on the wire, the eBPF program will, based on some condition `X`, either (1) let it traverse up the network stack, or (2) redirect it to some fd that the Aeron Media Driver in userspace would be able to read from. For now, the condition `X` is simply whether the packet is UDP or not, but I'll probably need to check that it has a header as specified in the [Transport Protocol](https://github.com/real-logic/aeron/wiki/Transport-Protocol-Specification#header-types).

To allow the media driver to read the redirected packets in (2) above, my intuition is that I'd need two custom implementations; one for `aeron_udp_channel_transport_recvmmsg_func_t`, and another for `aeron_udp_transport_poller_t`. However, the incoming packets will be in the above mentioned data structure that I can just `poll`, so I don't see where the receiver functions would come into play... Any hints appreciated!

(Sorry if this is a basic question btw, I'm a C noob :) )

**Comment by mikeb01** [comment]
The `recv_mmsg` function within the binding is not strictly necessary and you can pass the messages to the caller from the poll directly.

Note that the bindings are not a publicly supported API, so this is liable to change from version to version.
