### ISSUE TITLE
NOT_CONNECTED never returned from publication?

### ISSUE THREAD

**Issue by postulka** [real-logic/Aeron#161]
Hi guys,

first thank you for another awesome project you develop and open source. We are trying to use Aeron in our project and can't figure out one thing. When there is a Publication to which no Subscriber is connected we would understand (based on docs) that when we call offer method it will return NOT_CONNECTED constant (-1). But instead the offer call succeeds until the buffer is full and it starts returning BACK_PRESSURED constant (-2).

Very easy to reproduce when you start BasicPublisher from your samples folder and remove the Thread.Sleep() call in a for a loop.

Are we missing something here? We basically never saw NOT_CONNECTED returned from Publication.offer() call.

Thank you and kind regards,

Petr

Btw we are using Java API (the latest release 0.1.3) on Windows environment.

**Comment by tmontgomery** [comment]
Thanks! Glad you like it!

I don't see this. Seems to be working correctly.

Here is what I did. Default args.

- Start Media Driver
- Start `BasicPublisher`

output of publisher:
```
$ java -cp aeron-samples/build/libs/samples.jar uk.co.real_logic.aeron.samples.BasicPublisher
Publishing to udp://localhost:40123 on stream Id 10
offering 0/1000000Offer failed because publisher is not yet connected to subscriber
offering 1/1000000Offer failed because publisher is not yet connected to subscriber
offering 2/1000000Offer failed because publisher is not yet connected to subscriber
offering 3/1000000Offer failed because publisher is not yet connected to subscriber
offering 4/1000000Offer failed because publisher is not yet connected to subscriber
```
This is the application output when `Publication.offer` returns NOT_CONNECTED.

- Start `RateSubscriber` while publishing above.

output of publisher:
```
offering 5/1000000yay!
offering 6/1000000yay!
offering 7/1000000yay!
offering 8/1000000yay!
offering 9/1000000yay!
offering 10/1000000yay!
...
```

This is acting as expected. I believe what you might be expecting is that if all subscribers go away, that NOT_CONNECTED is returned. That is not the case. Once a subscriber is seen, NOT_CONNECTED will not be returned from offer again even if all subscribers die or go away.

**Comment by postulka** [comment]
Hi Todd,

thank you for your prompt response. I'm pretty sure that there was no subscriber connected before the publication.offer was called ... the only difference was that I used an embedded media driver, otherwise the code was copy-pasted from BasicPublisher sample. Could this be an issue only in case the embedded media driver is used? Also the test was done on Windows not on Linux ...

I will send the exact code tomorrow morning which should reproduce the behaviour described above.

Regarding the comment about NOT_CONNECTED never returned again after all subscribers die or go away. Is there any reason for such behaviour? What we want to implement is that the unsuccessful offer should be retried in case of BACK_PRESSURE (meaning that there is at least one subscriber connected) but should be ignored in case there is no subscriber connected because nobody is interested in the message.

Thanks again.

Petr

**Comment by tmontgomery** [comment]
I don't think this is due to platform or embedded driver. But can't rule it out. I did my test on Linux and Mac, BTW. Also, IIRC, some of the unit tests check for a 0 value on the limit (which is used for NOT_CONNECTED).

The behavior of `offer` is to aid in semantics with multiple subscribers on multicast. Until at least one subscriber is seen, the offer is not allowed. Once one is seen, it is opened up based on flow control. New subscribers see the latest position as they come and go. However, the existence of individual subscribers are not tracked by Aeron.

It is entirely possible (if not likely) that a publisher reaches the flow control boundary when all subscribers goes away before any tracking could assume to be timed-out. Setting NOT_CONNECTED in that case would be late and only helps give the application a new condition to check for. i.e. it should only handle BACK_PRESSURE which it must do anyway. And Aeron, by default, would have to do more work that adds really no value to the application.

However, the flow control strategy is exposed fully. So, if you wanted, you could add a flow control strategy that tracks subscribers and upon timeout of all subscribers could set the limit to 0 and have a publisher see NOT_CONNECTED again.

**Comment by postulka** [comment]
Hi Todd,

here is the class of Publisher we use to simulate the issue mentioned above - we basically start the publisher without any subscriber and we never receive NOT_CONNECTED as a result of offer call.

Tested on Windows 10 ...

Can you please try to launch the same thing to see whether you can reproduce on your side?

	package org.dett.prototypes.aeron;

	import uk.co.real_logic.aeron.Aeron;
	import uk.co.real_logic.aeron.Publication;
	import uk.co.real_logic.aeron.driver.MediaDriver;
	import uk.co.real_logic.agrona.CloseHelper;
	import uk.co.real_logic.agrona.concurrent.UnsafeBuffer;

	import java.nio.ByteBuffer;
	import java.util.concurrent.TimeUnit;

	public class BasicPublisher
	{
		private static final int STREAM_ID = 10;
		private static final String CHANNEL = "udp://localhost:5555";
		private static final long NUMBER_OF_MESSAGES = 1_000_000;
		private static final long LINGER_TIMEOUT_MS = 1000;
		private static final boolean EMBEDDED_MEDIA_DRIVER = true;
		private static final UnsafeBuffer BUFFER = new UnsafeBuffer(ByteBuffer.allocateDirect(256));

		public static void main(final String[] args) throws Exception
		{
			System.out.println("Publishing to " + CHANNEL + " on stream Id " + STREAM_ID);

			// If configured to do so, create an embedded media driver within this application rather
			// than relying on an external one.
			final MediaDriver driver = EMBEDDED_MEDIA_DRIVER ? MediaDriver.launchEmbedded() : null;

			final Aeron.Context ctx = new Aeron.Context();
			if (EMBEDDED_MEDIA_DRIVER)
			{
				ctx.dirName(driver.contextDirName());
			}

			// Connect a new Aeron instance to the media driver and create a publication on
			// the given channel and stream ID.
			// The Aeron and Publication classes implement "AutoCloseable" and will automatically
			// clean up resources when this try block is finished
			try (final Aeron aeron = Aeron.connect(ctx);
				 final Publication publication = aeron.addPublication(CHANNEL, STREAM_ID))
			{
				for (int i = 0; i < NUMBER_OF_MESSAGES; i++)
				{
					final String message = "Hello World! " + i;
					BUFFER.putBytes(0, message.getBytes());

					System.out.print("offering " + i + "/" + NUMBER_OF_MESSAGES);

					final long result = publication.offer(BUFFER, 0, message.getBytes().length);

					if (result < 0L)
					{
						if (result == Publication.BACK_PRESSURED)
						{
							System.out.println("Offer failed due to back pressure");
						}
						else if (result == Publication.NOT_CONNECTED)
						{
							System.out.println("Offer failed because publisher is not yet connected to subscriber");
						}
						else
						{
							System.out.println("Offer failed due to unknown reason");
						}
					}
					else
					{
						System.out.println("yay!");
					}

					Thread.sleep(TimeUnit.SECONDS.toMillis(1));
				}

				System.out.println("Done sending.");

				if (0 < LINGER_TIMEOUT_MS)
				{
					System.out.println("Lingering for " + LINGER_TIMEOUT_MS + " milliseconds...");
					Thread.sleep(LINGER_TIMEOUT_MS);
				}
			}

			CloseHelper.quietClose(driver);
		}
	}

Result from the test is: 

	Publishing to udp://localhost:5555 on stream Id 10
	offering 0/1000000yay!
	offering 1/1000000yay!
	offering 2/1000000yay!
	offering 3/1000000yay!
	offering 4/1000000yay!
	offering 5/1000000yay!
	offering 6/1000000yay!
	offering 7/1000000yay!
	offering 8/1000000yay!
	offering 9/1000000yay!

**Comment by postulka** [comment]
Regarding the implementation of our custom flow control strategy to be able to detect when all subscribers are gone. Can you please explain a little bit more how to implement such thing? Is there any code example we can look into? If not can you provide us some basic example?

Thanks a lot for all your help and effort ...

Petr

**Comment by tmontgomery** [comment]
The application works for me on Mac, Windows 8.1 (I don't have Windows 10 yet), and Linux (Ubuntu) with the latest HEAD. Not sure what to tell you. Could it be Windows 10 specific? Possible, but as I don't have access to Windows 10, I can't confirm that. I have a new Windows laptop on order, though. It will have Windows 10. I'll check once I have it (which won't be for a couple weeks). I will wait until I have a Windows 10 build (or maybe @mjpt777 or @RichardWarburton have Windows 10 and can try this out) to close the issue or confirm it.

For flow control strategies, it is straight forward. The flow control strategies return a long which is the position. A value of 0 means NOT_CONNECTED. Check the `FlowControl` interface javadoc. You can check how `UnicastFlowControl` and the max multicast one work. i.e. compute the position, add the window and return it. On idle, just return the position saved. For a NOT_CONNECTED being returned once subscriptions go away, just handle it as onIdle checking for SM liveness (this is where you would have to track each subscriber by InetSocketAddress) and return 0 as position if no subscriber was considered "alive".

**Comment by tmontgomery** [comment]
Actually, thinking about how best to implement a flow control strategy that sets NOT_CONNECTED when no subscribers are seen, I think it can be done without tracking.

Specifically, save the time each `FlowControl.onStatusMessage` is called (just call System.nanoTime()). When `onIdle` is called, if it has been over a set amount of time, then return 0 as the position. i.e. if enough time goes by without any SMs, then assume all subscribers are gone. And on the next Status Message, set the position back to normal. That should give you the semantics you desire.

**Comment by postulka** [comment]
Excellent ... we will try to implement the FlowControl as you suggest.

Regarding the issue with NOT_CONNECTED not returned even without subscribers - we will try to run the test on Linux and Windows Server to confirm whether the behavior is Windows 10 specific (btw we tried on 2 different laptops but both with Windows 10)

Thanks again for your help.

**Comment by postulka** [comment]
Just letting you know that I've tested the same code I pasted above on Windows 8 Pro and the behavior is same ... NOT_CONNECTED never returned.

**Comment by postulka** [comment]
My mistake ... I thought I was using 0.1.3 version but I had another reference in gradle for older version (0.1) and therefore it was using the old version. The issue was present in 0.1 but is not present anymore in 0.1.3 - everything works as expected. I'm really sorry for wasting your time ... you can close the issue.

Thank you for your help.

**Comment by mjpt777** [comment]
No worries. We welcome the feedback.
