### ISSUE TITLE
Offering I/O vectors for sending multiple messages

### ISSUE THREAD

**Issue by mmottl** [real-logic/aeron#1612]
Aeron already provides for functions like `aeron_publication_offerv` to combine multiple I/O vectors into a single message. Would it be possible to support operations that treat each I/O vector as an individual message?

In my case, I have an array of `iovec`s from a `writev` operation that persists message batches to disk before sending. Since those `iovec`s are identical to `aeron_iovec_stct`, it would be quite convenient and presumably more efficient if I could just hand them to Aeron in one call.

**Comment by mjpt777** [comment]
Aeron provides efficient batching into datagrams so this type of enhancement would not be as beneficial as with other messaging system. Multiple messages in single offers could also result in failures due to flow control windows. We do not see this is a good thing for Aeron.
