### ISSUE TITLE
Election cannot close due to Padding frame

### ISSUE THREAD

**Issue by NextToBe** [real-logic/aeron#1619]
Hi, sorry for disturbing.

we are using aeron cluster to build some low-latency application, and we found some puzzle when testing.

We killed our process and restarted it to simulate some extreme scenarios, and we found that our process could not work as expected, our aeron cluster based application has only 1 node, but the Leader cannot be elected sometimes.

After debugging, we found the problem. The appearance of this problem is Election was  blocked at LEADER_INIT state and was waiting for service ACK. But ClusteredServiceAgent was still polling LogAdaptor even though it cannot poll any data. So this election will never close and the application cannot work as expected.

```java
// ClusteredServiceAgent::doWork

if (null != logAdapter.image())
{
     final int polled = logAdapter.poll(commitPosition.get());
     workCount += polled;

     if (0 == polled && logAdapter.isDone())
     {
         closeLog();
     }
}
```

We found that `commitPosition` is less than `logAdaptor.maxLogPosition` so `logAdaptor.isDone` is always false.

And then we found the `commitPosition` will be updated at LEADER_REPLAY state.

```java
// ConsensusModuleAgent::replayLogPoll
final int fragments = logAdapter.poll(stopPosition);
final long position = logAdapter.position();

if (fragments > 0)
{
    commitPosition.setOrdered(position);
}
else if (logAdapter.isImageClosed() && position < stopPosition)
{
    throw new ClusterEvent("unexpected image close when replaying log: position=" + position);
}
```

The key is the code above, there is one **_padding frame_** in the tail of our REC file. So when there is only one frame left, the return value of `logAdapter.poll` will be 0 and the `commitPosition` will not be updated, but the `logReplay.isDone` will be true. And LEADER_REPLAY state will be transferred to LEADER_INIT state.

We're not sure whether this is a bug.

Our aeron version is **1.41.4**.

Thanks for any reply.

**Comment by mikeb01** [comment]
We have pushed a fix for this.  A couple of follow ups.  Do you still have the archive data from when this failed?  If so, if you could use `io.aeron.archive.ArchiveTool <dir name> describe` to output the values from within the archive.  This data would be helpful for confirming the issue.  Also could you let me know which file sync level you had configured for your archive.

**Comment by NextToBe** [comment]
Thanks for the replay！

Our file sync level setting is the default setting.

 `public static final int FILE_SYNC_LEVEL_DEFAULT = 0;`

**Comment by mikeb01** [comment]
Thank you, that is useful information.
