### ISSUE TITLE
Aeron vs. ZeroMQ

### ISSUE THREAD

**Issue by mlabour** [real-logic/Aeron#162]
Hello. Aeron looks awesome. How would you compare Aeron to ZeroMQ?

**Comment by RichardWarburton** [comment]
I'm not sure this is an "issue".

Do you want an FAQ entry that compares Aeron to ZeroMQ or a wiki page or something?

**Comment by tmontgomery** [comment]
Aeron and 0MQ are somewhat orthogonal. 0MQ is a messaging system and Aeron is a transport. Aeron could be used as a transport under 0MQ. And some have interest in seeing that happen. I think it would be awesome!

If an application has needs that are quite modest in terms of messaging semantics, then Aeron might be a great option. However, if a more fully featured messaging semantic is desired (specifically, topics/subjects, security, etc.) then 0MQ might be more desirable. Performance-wise, Aeron is quite a bit different then 0MQ.

**Comment by mlabour** [comment]
Thank you very much for your answer. I have 2 follow up questions:
1) How does Aeron compare to TIPC? If I understand TIPC properly it is also OSI Layer 4.
2) On AWS, some folks have enabled multicast using n2n, 0MQ and TIPC. https://www.buckhill.co.uk/blog/how-to-enable-broadcast-and-multicast-on-amazon-aws-ec2/2#.VecrA2TBzGc. Do you think n2n + Aeron could be a solution for multicast on EC2/AWS?
Thanks again for your help.

**Comment by tmontgomery** [comment]
From what I gather about TIPC, it is more in line with 0MQ in that it is a messaging system. It also provides auto discovery, etc. I believe it looks like a mesh, so latency-wise, it will likely have much more latency than Aeron and probably also have a great deal more variance in that latency.

If AWS supports multicast, then, yes, Aeron should be able to leverage it. However, not having played with it yet, I can't say if it will be very good or not. Loss rate and unknown latency can have a big impact.

**Comment by travis-leith** [comment]
@tmontgomery ,interestingly, the [dotnet client](https://github.com/AdaptiveConsulting/Aeron.NET) seems to refer to Aeron as a messaging system

<img width="559" alt="image" src="https://github.com/user-attachments/assets/8aa42067-4d0b-493a-aa1b-257b8397527a">

**Comment by mjpt777** [comment]
Aeron has been extended beyond a transport over the years and now has Archive, and Cluster plus premium extensions.
