### ISSUE TITLE
Dependency on agrona [1.21.2,2.0[

### ISSUE THREAD

**Issue by pcdv** [real-logic/aeron#1622]
Hi,

I'm wondering whether declaring a dependency from aeron-client to agrona [1.21.2,2.0[ is useful compared to using a simple dependency to 1.21.2 (which is the last version). This wouldn't prevent projects using aeron to depend on a more recent version.

Using a non-fixed version causes Gradle to constantly connect to remote repositories instead of using the cached version, and slows down the build.

Thanks

**Comment by vyazelenko** [comment]
Using a version range allows Aeron users to upgrade to a newer version of Agrona independent of Aeron version. The minimum version guarantees that Agrona version will work with Aeron.

**Comment by pcdv** [comment]
Not sure I follow. If you declare a dependency to 1.21.2 in aeron-client, it does not prevent users of aeron-client to use a more recent version of agrona. Gradle will automatically keep the more recent version when resolving dependencies of the client project.
