### ISSUE TITLE
Wiki: client concurrency model improvement

### ISSUE THREAD

**Issue by pveentjer** [real-logic/aeron#1641]
On the following wiki page:

https://github.com/real-logic/aeron/wiki/Client-Concurrency-Model

I'm suggesting a minor improvement for the following text:

```
Publications with a different channel and stream id are completely independent from each other and operate in parallel.
```

My suggestion:

```
Publications with a different channel and stream id are completely independent from each other and operate concurrently.
```

Parallel should be used when they are happening at the same time, which isn't required. Concurrent means that they are not ordered and may or may not be processed at the same time.

**Comment by mikeb01** [comment]
The existing sentence is a little clumsy as the Publications don't really operate, it is the client application that operates them.  I'll reword it.
