### ISSUE TITLE
Using Aeron Cluster Backup how to retrieve all snapshots from Cluster 

### ISSUE THREAD

**Issue by andyflury** [real-logic/aeron#1645]
When using `io.aeron.cluster.ClusterBackup` we noticed that while the entire recoding log gets retrieve only the last snapshot gets retrieved from the Cluster. For our use case we would like the ClusterBackup to retrieve all snapshots from the Cluster. Is there a setting that would allow for this, or is there a code change we would have to perform?

**Comment by vyazelenko** [comment]
@andyflury ClusterBackup was designed to only retrieve latest snapshots from a Cluster. That being said, if you have a ClusterBackup instance that is always running it will naturally replicate all the snapshots as they are taken by the Cluster nodes.
