### ISSUE TITLE
Have you considered implementing mutil raft

### ISSUE THREAD

**Issue by zxuanhong** [real-logic/aeron#1667]
1. Have you considered implementing mutil raft；
2. Is it more appropriate to use mutil raft for partitioning。

**Comment by mjpt777** [comment]
Yes we have looked at MultiRaft. It is not necessary for Cluster as most usecases do not require partitioning.

We are building a new sequencer product that can support service partitions but has the benefit of still maintaining a single total order log. This is much easier to reason about than multiple regions/partitions like in MultiRaft.

**Comment by zxuanhong** [comment]
@mjpt777 There is one leader for the entire cluster without partitioning. The pressure is very high. MultiRaft provides multiple leaders (i.e. cluster multi entry)

**Comment by zxuanhong** [comment]
@mjpt777 A cluster with a single entrance will not fully utilize cluster resources. And the pressure on a certain server is always very high.

**Comment by mjpt777** [comment]
@zxuanhong You can run multiple clusters on shared media driver and archive pairs. You can also run multiple services in a cluster that can be used for partitioning.

**Comment by mjpt777** [comment]
We do not have plans to support MultiRaft at this time.
