### ISSUE TITLE
Multicast slow consumer on same box behaviour

### ISSUE THREAD

**Issue by fquinner** [real-logic/aeron#1669]
I'm trying to evaluate Aeron to see if it is suitable for our use case, but I am finding it's treatment of slow consumers on the same box to be unexpected.

- I have an Aeron multicast publisher publishing over Aeron to a media driver on another box.
- On the subscribing box, the multicast data is then handled by a single media driver which relays the traffic via Aeron to multiple consumers on that same box.
- I have two consumers on this box. One simulating an unreasonably slow consumer, and the other keeping up with the traffic.
- I can adjust buffers to vary the tolerance, but ultimately, if a subscriber can't keep up and its window keeps filling, it begins to effect the fast consumer despite the max flow control setting enabled (and eventually the publisher too if this is the only media driver connected to the publisher's media driver).
- Ideally the slower consumer in this scenario would fall behind and go through Image offline etc recovery or at least there would be some mechanism in the subscription to help **identify this scenario** and the decision could be made there but I couldn't find anything without resorting to string parsing on counters to see where other subscribers on the same box are.

I have seen [this](https://github.com/real-logic/aeron/issues/139) (though it's from a while ago - packages, classes etc have all changed) which suggests multiple media drivers to try and isolate the slow consumer, but we are specifically trying to reduce NIC PCIe noise by using Aeron so we would want to avoid that route.

I tried playing with tether configuration too since that seemed like it was designed for this scenario but it did not seem to have any effect no matter what timeouts I tried. I do find the [documentation on this topic](https://github.com/real-logic/aeron/wiki/Flow-And-Congestion-Control#subscription-tethering) fairly difficult to get my head around though so perhaps I have misunderstood.

Am I missing something or is this expected behaviour?

**Comment by mikeb01** [comment]
Using max flow control should give you the desired behaviour.  If you could produce a code example that simulated the problem that you are seeing, then we could investigate in more detail.

**Comment by vyazelenko** [comment]
@fquinner Multiple subscribers to the same channel/stream on the same media driver will share a receiver endpoint. That means that they will all be treated as a single unit for the flow control purposes. If you want to treat those subscriber separately you'll need to set `tether=false` in the channel uri for the subscribers that you want to be disconnected if they fall behind.

**Comment by fquinner** [comment]
Unfortunately `tether=false` did not change behavior and I believe max flow control is on by default.

The code is literally just adding a sleep for 1 second here in one subscriber, and another without:

https://github.com/aeron-io/aeron/blob/master/aeron-samples/src/main/cpp/BasicSubscriber.cpp#L150

Then modify the publisher to publish every millisecond

https://github.com/aeron-io/aeron/blob/bc47c9fa1d290a3d17c60bfc9fcffcae2b7a2feb/aeron-samples/src/main/cpp/BasicPublisher.cpp#L174C18-L174C29

The fast subscriber gets updates immediately then stops, then the slow subscriber gets continuous slow updates.
