### ISSUE TITLE
Wiki Update - UntetheredWindowLimit

### ISSUE THREAD

**Issue by callmerockett** [real-logic/aeron#1684]
In Wiki [Flow and Control](https://github.com/real-logic/aeron/wiki/Flow-and-Congestion-Control#subscription-tethering) page is said that (emphasys mine):

> If a subscription is not a tether and it is in the **bottom 1/8th of the window,** when another consumer is at the top of the window, for the `aeron.untethered.window.limit.timeout` then subscription in the **bottom 1/8th** will be notified that the image is unavailable for them.

But in main branch driverConductor seems to consider the bottom 1/4th of the window to notify untethered subscriptions ([commit blame](https://github.com/real-logic/aeron/blame/master/aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java#L429)).

Could you update the wiki?

There is a way for the community to contribute with minor fixes to the Wiki pages as well?

**Comment by mjpt777** [comment]
Thanks. We use to have the wiki open to contributions but unfortunately we got lots of spam and inappropriate edits.
