### ISSUE TITLE
Aeron Archive stuck in startup on Linux when low on entropy

### ISSUE THREAD

**Issue by grddev** [real-logic/aeron#1689]
During startup, archive executes `SecureRandom.getInstanceStrong().nextLong()`, which can block reading from `/dev/random` on e.g. Linux for several minutes in a low entropy situation (e.g. because some other service is using up available entropy). Can we limit how long this blocks startup for, or allow configuring it to use a non-strong instance?

At the very least perhaps add some signal to make it more clear that this is what is going on, as I only identified this by sending SIGQUIT to the Archive process and noting that it was blocked inside the random generator, and since I've chased down similar issues in the past, I figured it was due to this.

For now, we're working around the issue by launching [haveged](https://github.com/jirka-h/haveged).

**Comment by pcdv** [comment]
I also feel this should be configurable. Systematic usage of getInstanceStrong() always creates problems eventually (in my experience).

For reference: #1560 + 
https://github.com/real-logic/aeron/pull/1560#discussion_r1495601260

**Comment by mikeb01** [comment]
I've added configuration options for specifying the RNG used by secure random.  The default is the native non blocking implementation or the Windows specific one depending on platform (https://github.com/real-logic/aeron/commit/f12165ebfc1a9800fe8f1a6d6a56ed798e31ecf5, https://github.com/real-logic/aeron/commit/b79e8287fdd0ef0ad53f608e411659a144e08f5c).
