### ISSUE TITLE
15 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [real-logic/aeron#1696]
See the [test log](https://freebsd.org/~yuri/aeron-1.44.6-tests-LastTest.log).

Version: 1.44.6
clang-18
FreeBSD 14.1

**Comment by mikeb01** [comment]
FreeBSD is not currently a supported platform for the native C media driver.  This may change in the future depending on demand.  In the interim using the Java driver would be the recommended approach.
