### ISSUE TITLE
C Driver

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#17]
A C version of the driver could use platform dependent optimizations for networking and access to specific CPU instructions. Specifically for Linux on x86:
1. `epoll`
2. `sendmmsg` & `recvmmsg`
3. `PAUSE` instruction on x86

**Comment by ohpauleez** [comment]
Just adding some support for this issue here.

I used Aeron in some UIO/kernel-bypess recently.  Having a C version of the Driver would allow for dropping in lower.  This change could give rise to using DPDK, Netmap, or plugging Aeron directly into virtio.  Let me know anyway I can help.

**Comment by mjpt777** [comment]
Currently in progress.
