### ISSUE TITLE
Hacking on Aeron - Working in Eclipse - Task 'eclipse' not found

### ISSUE THREAD

**Issue by zbhuang** [real-logic/Aeron#171]
Follow the instruction of "Working in Eclipse", and run ./gradlew eclipse.
It is complaining Task 'eclipse' not found.

Here is the detailed information
---------------------------------------
xxx@xxx_home /cygdrive/k/eclipse-java-luna-SR2-x64_workspace/backup/Aeron-master
$ ./gradlew.bat eclipse --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Task 'eclipse' not found in root project 'Aeron-master'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.execution.TaskSelectionException: Task 'eclipse' not found in root project 'Aeron-master'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)

**Comment by qed-** [comment]
I had the same problem, this should fix it: 
https://github.com/real-logic/Aeron/pull/172

**Comment by zbhuang** [comment]
I tested it and the fix works. Thank qed.
