### ISSUE TITLE
Allow the subscriber to control the position progress

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#173]
In some cases a subscriber would not want the position to advance when they poll for messages. This might be because an error or some other condition has occurred during the callback and they would like to try again later.

This could be handled by a return from the callback indicating of the position should advance or not.

**Comment by mikeb01** [comment]
Yay!  This will be really useful.  Also worth considering what should happen if a RuntimeException is thrown from a callback (advance or not).

**Comment by mjpt777** [comment]
I'm thinking that rather than return a boolean to indicate if the position should be advanced from a handler we could return an enum with semantics like the following:
```
Position.ADVANCE // Advance to next message but do not commit position yet
Position.REWIND // Stop further processing and rewind to position at the start of the message
Position.COMMIT // Commit the position as of the end of this message and continue processing
```

**Comment by mjpt777** [comment]
The first cut of this has been implemented and can be used by passing a `ControlledFragmentHandler` to the Subscription or Image controlledPoll method in the Java client.
