### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by orges** [real-logic/Aeron#174]
Hi there, Aeron looks very promising. I hope it becomes more popular and successful.
Could you please give some real benchmarks with other messaging systems for performance comparisons of real use case scenarios?  It sounds like there are many radical new approaches with Aeron's design but it is too complicated and low level for a developer who needs only a fast&reliable messaging system.

**Comment by mjpt777** [comment]
Comparison to other messaging systems is beyond the scope of this repository. We would be happy helping out if someone built this benchmark elsewhere.
