### ISSUE TITLE
Test fails on Windows but passes with a breakpoint

### ISSUE THREAD

**Issue by buybackoff** [real-logic/Aeron#176]
I have just tried to build Aeron for the first time. C++ build with CMake went almost smoothly. However, zlib dependency of hdr_hystogram is missing, but this is not a dealbreaker for the basic samples.

In Java, gradlew.bat failed with [this test](https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/test/java/uk/co/real_logic/aeron/driver/ReceiverTest.java#L171). Specifically, [this assertion](https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/test/java/uk/co/real_logic/aeron/driver/ReceiverTest.java#L226) fails.

I opened the project in IDEA, tried to debug it and the test also failed in Debug mode. However with a breakpoint on [this line](https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/test/java/uk/co/real_logic/aeron/driver/ReceiverTest.java#L221) the test passes after resuming execution. Kind of a heisenbug here.

Adding `Thread.sleep(1);` after the breakpoint helps. Running on a laptop with 4 logical cores with Windows 7. Java version 1.8.0_40.

And then... yay! BasicSubsciber/Publisher from C++ work with the Java driver :) Great project!

**Comment by mjpt777** [comment]
I cannot get the tests to fail on Windows 8.1 with both a dual core and a quad core machines. I'll try to mess with the timing in this test to see if I can trigger it.

**Comment by mjpt777** [comment]
I've pushed a potential fix. Does the test work now?

**Comment by buybackoff** [comment]
Yes, it does. Thanks!

**Comment by MKSoftechnician** [comment]
I have tried to build Aeron (C++) on windows server 8 64-bit using cppbuild-vs2015.cmd but test failed with 1 error and test completes 93%. Then I opened Aeron.sln in VS 2015 and built project and build failed with "cannot open include file 'unistd.h' for projects.

**Comment by tmontgomery** [comment]
@MKSoftechnician if this still occurs with the latest, please create a new issue for it so we can track it as this is a closed issue. Thanks!
