### ISSUE TITLE
repeated exception when close connection

### ISSUE THREAD

**Issue by robertroeser** [real-logic/Aeron#177]
Running a test that opens and closes a publication. After a few times the driver begins to print this message repeatedly:
`[486701.483894] EXCEPTION [526/526]: java.nio.channels.ClosedChannelException(exception message not set) sun.nio.ch.DatagramChannelImpl.ensureOpen DatagramChannelImpl.java:320 sun.nio.ch.DatagramChannelImpl.write DatagramChannelImpl.java:594 uk.co.real_logic.aeron.driver.media.UdpChannelTransport.send UdpChannelTransport.java:169 uk.co.real_logic.aeron.driver.NetworkPublication.heartbeatMessageCheck NetworkPublication.java:407 uk.co.real_logic.aeron.driver.NetworkPublication.send NetworkPublication.java:170`

**Comment by tmontgomery** [comment]
I pushed a change to ignore these exceptions. Let me know if this works.

**Comment by robertroeser** [comment]
That seems to have fixed the issue.
