### ISSUE TITLE
Back pressure on full term buffer

### ISSUE THREAD

**Issue by grzegorz-gierlach** [real-logic/Aeron#178]
If I set aeron.term.buffer.length to its minimum value of 65536 and I keep sending messages of exactly 2048 bytes, every 31 messages I got back pressured, immediate retry succeeds.
Is it by design? Should not Aeron swap term buffers underneath and actually return 'success' in such case? Maybe it should return different status code?
Basically, I'm not interested in retrying messages, however in above scenario I have to as a workaround as I can't distinguish between actual back pressure and the one caused by full term buffer.

**Comment by mjpt777** [comment]
This is currently by design. Rather than have a loop in a loop, the caller should be looping to deal with back pressure anyway. Similar behaviour happens in other network stacks to keep code simple.

Why are you "not interested" in retrying?

**Comment by grzegorz-gierlach** [comment]
I mean, I prefer dropping messages in case of too slow consumers/too fast producers.
Retrying, on each back pressure - if I would like to handle full term buffer case - would mean retrying also in flow control scenarios.

**Comment by mjpt777** [comment]
We could look at returning a different status code for this case.

**Comment by mjpt777** [comment]
I could add a new return code of `ADMIN_ACTION` that means the operation should be applied.

**Comment by grzegorz-gierlach** [comment]
If that fits Aeron design it would be more than enough for my case.

**Comment by mjpt777** [comment]
This is fairly easy to do. I had the case before and simplified it to keep the surface area down.

**Comment by mjpt777** [comment]
@grzegorz-gierlach Can you try if that works for you?

**Comment by grzegorz-gierlach** [comment]
Works like a charm. Thank you.
Closing the issue.
