### ISSUE TITLE
Aeron (C++) Debug failed 

### ISSUE THREAD

**Issue by MKSoftechnician** [real-logic/Aeron#179]
aeron doesn't create cnc file on machine. after manually creating and placing file in directory, memorymapping fails as file size is 0 bytes.
So my question is which project (Aeron-Subscriber, Publisher etc..) creates this file. or specify tests to run and debug aeron successfully at least.

Platform: Windows Server 2008
IDE: VS 2015

**Comment by mjpt777** [comment]
Have you built and run the Java Media Driver?

**Comment by MKSoftechnician** [comment]
Thanks for reply.
No, I haven't tried Java Media Driver as my requirement is for C++ . But I want to build in C++. After runnning cppbuild-vs2015.cmd, I have opened Aeron.sln in VS 2015 which opens all tests project. 
Isn't there any support for Media Driver in C++  as my requirement is specifically for C++?
Note: Kindly specify example with steps  for using Aeron in C++ if possible

**Comment by mjpt777** [comment]
We currently have the media driver in Java with clients in Java and C++. We may have a native media driver in the future if someone is willing to sponsor that.

If you follow the examples for Java and then swap a Java client for a C++ client it should work for you.

**Comment by MKSoftechnician** [comment]
Ok, I will give it a try.
Thank you.
