### ISSUE TITLE
Finally, is Aeron reliable or not?

### ISSUE THREAD

**Issue by DzmitryShylovich** [real-logic/Aeron#180]
After reading the documentation I have only one question: is Aeron reliable or not? :)
Reliable stays for: `"guarantee that a message sent by a sending application is indeed received at the other end, and received only once"`.

So what do you mean by words `Efficient reliable UDP unicast, multicast, and IPC message transport.`? Because according to [this](https://github.com/real-logic/Aeron/wiki/Protocol-Specification#design-assumptions) part of the documentation Aeron is not reliable.

```
Aeron is a transport protocol and may operate over unreliable media. For this reason, some additional assumptions must be embraced, such as:

Duplication of packets may occur
Packets may be lost
Packets may arrive out of order
```

Can I lose a package or not?

**Comment by mjpt777** [comment]
This part of the documentation refers to the packets on the network that might be lost or arrive out of order. Aeron will detect this and retransmit packets if necessary and assemble the messages in the order they where sent within streams before delivering them to the subscribers.

Aeron is "reliable" in a similar, but slightly better, way as TCP is reliable. While the stream is connected Aeron will ensure messages are deliver in order and only once.

**Comment by mjpt777** [comment]
I've put a clarification in the documentation.

**Comment by DzmitryShylovich** [comment]
Thank you.
