### ISSUE TITLE
What does "multicast" mean?

### ISSUE THREAD

**Issue by vontikov** [real-logic/Aeron#181]
Does multicast mean an ability to send messages in one-to-many manner.

If we have one sender which sends to aeron:udp?group=224.0.1.1:12345 channel 10  and several receivers on different boxes which connected to the same group/port/channel will all the receivers receive messages from the sender?

**Comment by mjpt777** [comment]
Yes, if the messages can be routed across a network between them.

**Comment by vontikov** [comment]
Thanks!

**Comment by vontikov** [comment]
Should the receivers be connected in particular order in this case?
Can we start for example first receiver then the sender and then other receivers with some delay?

**Comment by mjpt777** [comment]
Sender cannot send until at least one receiver is present. Receivers can join at any time but they will only see messages from the point they join onward.

BTW the Gitter group is a good place to ask general questions. https://gitter.im/real-logic/Aeron

**Comment by vontikov** [comment]
OK. Thank!
