### ISSUE TITLE
Debugging settings, tools and tricks

### ISSUE THREAD

**Issue by krisskross** [real-logic/Aeron#182]
I wanted to know if there any settings, tools and tricks that can be used for making debugging applications built on Aeron easier.

**Comment by mjpt777** [comment]
`AeronStat` is a useful little tool to understand media driver state that can be found in the samples.

It can also be useful to turn on event logging. This can be enabled with the following property.

`-Daeron.event.log=all`

The value can be `add`, `prod`, `admin`, or a comma separated list which can be found in `EventConfiguration`.

**Comment by krisskross** [comment]
Awesome tools! Thanks Martin.
