### ISSUE TITLE
Broadcast buffer style logging

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#184]
Rather than log events to a RingBuffer it might make more sense to do this to a BroadcastBuffer so that it could be always enabled and in the event of a issue the buffer could be used to see the recent history rather than output continuously.

**Comment by tmontgomery** [comment]
That sounds like a great idea to me as an option.

First thing is to use byte weaving to inject the tracing/logging. This could be one of the options to weave in. Going to assign this to myself.

**Comment by quixver** [comment]
Question: Will it be possible to roll the broadcast buffer logs so that instead of 1 massive (and continuously growing) file, there will be multiple sequentially numbered files?

**Comment by mjpt777** [comment]
The broadcast buffer is a circular buffer that is reused so it does not roll.
