### ISSUE TITLE
Use uncounted loops when idle to enable safepoint polling

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#185]
To ensure a subscriber or publisher does not get stuck with TTSP issues it should use uncounted loops when idle.

**Comment by nitsanw** [comment]
Problem here is that knowledge of the external loop is required to determine if a safepoint poll in the idle() method is required. Given a call to idle already implies we have time to spend it would be ideal if we could somehow force a safepoint poll cleanly (e.g. a ForceSafepointPoll method/loop annotation which would keep a safepoint poll in the face of inlining and/or loop optimizations). Sadly there is no such clean mechanism.
With no prior knowledge of callers we must work under the following assumptions:
 1. Call to idle has been inlined
 2. Call to idle is in a counted loop
It follows that the idle() implementation must somehow include a 'guaranteed' safepoint poll.
