### ISSUE TITLE
Change Data header and frame alignment to be 32 bytes

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#188]
This will allow for greater performance and simpler semantics.
 * Extra 8 bytes in the header can be for an optional field such as a timestamp
 * Alignment means that a header will always fit without extra checks. 
 * Small message writes are less likely to false share.
 * Copy performance can be improved be due to 32-byte alignment, pre Skylake favours 16-byte alignment, and Skylake favours 32-byte alignment. Current alignment is 8 bytes.
 * Forward scanning for rebuild completion and unblocking would be faster.

The additional cost would be an average of 12 bytes ((32 / 2) - (8 / 2)) for a message body plus 8 bytes in a header when the opaque header field is not in use. IPC should see more benefits than network comms.

**Comment by tmontgomery** [comment]
:+1:

**Comment by mjpt777** [comment]
As @RichardWarburton points out this would also be useful for storing a checksum such as a CRC when archiving a stream.
