### ISSUE TITLE
NullPointerException in ControlTransportPoller

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#192]
The following code from ControlTransportPoller:

```Java
selector.selectNow();

for (final SelectionKey key : selectedKeySet.keys())
{
    bytesReceived += ((SendChannelEndpoint)key.attachment()).pollForData();
}

selectedKeySet.reset();
```

Fails to use the size of the selecteKeySet as bounds on the loop.  Instead a pre-sized array is return that main contain null values.

**Comment by mjpt777** [comment]
Fixed in https://github.com/real-logic/Aeron/commit/c8f21e8d04a90cb1d891fcdab23c6be119dfa5bc
