### ISSUE TITLE
Per-Stream Term Buffer Sizes

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#193]
Would it be possible to have term buffer sizes set on a per channel/stream basis.  In our system some streams have significantly lower volume and don't need the same amount of resource as our busier streams.

**Comment by mjpt777** [comment]
Yes this could be possible. There could be a `Aeron.addPublication()` that takes a termLength argument.

**Comment by mjpt777** [comment]
Would this be better as a method argument when adding the publication or as a uri param on the channel. 

The method argument is more discoverable. Uri params allow for more flexibility in future usage.

**Comment by mjpt777** [comment]
Uri params also fits with the pattern established for multicast TTL. However it is stream specific and may be different by stream in the same channel.

**Comment by tmontgomery** [comment]
URI params could be for stream also. Just means that when canonicalized, they are ignored.

**Comment by mjpt777** [comment]
What should be the behaviour in the following scenario?

A publication is added and this sets up a channel. A term length is provided as a URI param and this is use for the first publication. Then two later publications are setup. One provides the same channel but with a different value for the term length as a URI param and the other provides no URI param. I suggest the second one that provides the URI param uses that one. What about the one without? Does it take one of the two previously supplied params?

**Comment by mikeb01** [comment]
Personally I think the other one (with unspecified term length) should use the value configured on the media driver's context as it keeps things simple and easy to predict what size it will use.

**Comment by mjpt777** [comment]
Also what should happen if a publication is added in one process with a term length and another is added with the same channel and stream but with a different length? Should the second one error?

**Comment by mikeb01** [comment]
That would make the most sense.  I wonder if the second should succeed if the length is unspecified?

**Comment by mjpt777** [comment]
Note that when using IPC if the subscription is created first then the length must be set via a channel param on the subscription. The creator of the subscription or publication wins. Later adds take the settings of the creator.
