### ISSUE TITLE
Exception at higher channels counts (ie > 64, 32 sub, 32 pub)

### ISSUE THREAD

**Issue by theiceguy** [real-logic/Aeron#200]
[8450250.467026] EXCEPTION [513/513]: java.nio.channels.NotYetConnectedException(exception message not set)
sun.nio.ch.DatagramChannelImpl.write DatagramChannelImpl.java:596
uk.co.real_logic.aeron.driver.media.SendChannelEndpoint.send SendChannelEndpoint.java:156
uk.co.real_logic.aeron.driver.NetworkPublication.setupMessageCheck NetworkPublication.java:387
uk.co.real_logic.aeron.driver.NetworkPublication.send NetworkPublication.java:164
uk.co.real_logic.aeron.driver.Sender.doSend Sender.java:113

**Comment by mjpt777** [comment]
What version of Aeron? Platform including JDK and OS?

**Comment by theiceguy** [comment]
<dependency>
      <groupId>uk.co.real-logic</groupId>
      <artifactId>aeron-all</artifactId>
      <version>0.9.2</version>
    </dependency>

**Comment by theiceguy** [comment]
svc_trad@pdk-pt2-uxfxmr-01 $ uname -a
Linux my_server 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
my_server $ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by tmontgomery** [comment]
Is this a multicast or unicast channel?

**Comment by theiceguy** [comment]
multicast

**Comment by mjpt777** [comment]
Was this the first exception in the log for that run?

**Comment by theiceguy** [comment]
No, I missed this one ...

[8464805.946096] EXCEPTION [650/650]: java.lang.RuntimeException(channel "aeron:udp?group=224.2.0.1:40162" : java.net.BindException: Address already in use)
uk.co.real_logic.aeron.driver.media.UdpChannelTransport.openDatagramChannel UdpChannelTransport.java:116
uk.co.real_logic.aeron.driver.media.ReceiveChannelEndpoint.openChannel ReceiveChannelEndpoint.java:123
uk.co.real_logic.aeron.driver.Receiver.onRegisterReceiveChannelEndpoint Receiver.java:108
uk.co.real_logic.aeron.driver.cmd.RegisterReceiveChannelEndpointCmd.execute RegisterReceiveChannelEndpointCmd.java:32
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:126

**Comment by theiceguy** [comment]
But, I've no idea why 40162 is already spoken for

**Comment by tmontgomery** [comment]
That explains the first exception. Not sure what would be on 40162 either....

**Comment by theiceguy** [comment]
k, please close

**Comment by mjpt777** [comment]
Happy to close. For reference you can close an issue yourself. Thanks.
