### ISSUE TITLE
How can I run ping and pong on separate hosts?

### ISSUE THREAD

**Issue by jangho-noh** [real-logic/Aeron#201]
Hello,

I'm trying to run Ping and Pong on different hosts.

Host A (172.16.21.27) runs Ping
Host B (172.16.20.144) runs Pong

I changed IP addresses in SampleConfiguration.java file.
PING_CHANNEL = System.getProperty(PING_CHANNEL_PROP, "aeron:udp?remote=172.16.21.27:40125");
PONG_CHANNEL = System.getProperty(PONG_CHANNEL_PROP, "aeron:udp?remote=172.16.20.144:40126");

Ping running on Host A cannot assign Host B's address.
Pong running on Host B cannot assign Host A's address.

How can I run ping and pong on separate hosts?

INFO: Aeron toDriver consumer heartbeat is 10191 ms old
[107.917163] EXCEPTION [664/664]: java.lang.RuntimeException(channel "aeron:udp?remote=172.16.20.144:40126" : java.net.BindException: Cannot assign requested address)
uk.co.real_logic.aeron.driver.media.UdpChannelTransport.openDatagramChannel UdpChannelTransport.java:116
uk.co.real_logic.aeron.driver.media.ReceiveChannelEndpoint.openChannel ReceiveChannelEndpoint.java:123
uk.co.real_logic.aeron.driver.Receiver.onRegisterReceiveChannelEndpoint Receiver.java:108
uk.co.real_logic.aeron.driver.cmd.RegisterReceiveChannelEndpointCmd.execute RegisterReceiveChannelEndpointCmd.java:32
uk.co.real_logic.aeron.driver.Receiver.accept Receiver.java:126

**Comment by mjpt777** [comment]
Are you able to write a simple Java program that binds to the appropriate sockets to see if your machines and network allows it?

**Comment by tmontgomery** [comment]
Ping binds to the PONG channel. And Pong binds to the PING channel. Looks like you might be running them the wrong way around.

**Comment by mjpt777** [comment]
Is this still an issue?

**Comment by Reinholdtsen** [comment]
I am very excited to try out Aeron, but I am also having trouble running ping and pong on separate hosts. 
I have two Windows 10 computers with Java 8 (64 bit) on a home network, one that I have named pinger (192.168.1.6) and the other ponger (192.168.1.12). Each have a generous firewall rule that enables all incoming UDP traffic.
I have built a jar with dependencies file that includes Aeron 0.9.4.
On each machine I run the media drive with the following command:
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar uk.co.real_logic.aeron.driver.MediaDriver

On ponger I run:
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -Daeron.sample.ping.channel=udp://ponger:40123 -Daeron.sample.pong.channel=udp://pinger:40124  uk.co.real_logic.aeron.samples.Pong # Run on ponger

On pinger I run:
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -Daeron.sample.ping.channel=udp://ponger:40123 -Daeron.sample.pong.channel=udp://pinger:40124 -Daeron.sample.messages=10000 uk.co.real_logic.aeron.samples.Ping # Run on pinger

The console on pinger hangs after outputting:
C:\Aeron>java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -Daeron.sample.ping.channel=udp://ponger:40123 -Daeron.sample.pong.channel=udp://pinger:40124 -Daeron.sample.messages=10000 uk.co.real_logic.aeron.samples.Ping # Run on pinger
Publishing Ping at udp://ponger:40123 on stream Id 10
Subscribing Pong at udp://pinger:40124 on stream Id 10
Message length of 256 bytes
Warming up... 5 iterations of 10000 messages
Available image: channel=udp://pinger:40124 streamId=10 session=-10105912

the ping pong sample is working if I ping and pong on the same machine:
# Run both on pinger
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=pinger:40124" -D"aeron.sample.pong.channel=aeron:udp?endpoint=pinger:40123" -Daeron.sample.messages=10000 uk.co.real_logic.aeron.samples.Ping # run on pinger
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=pinger:40124" -D"aeron.sample.pong.channel=aeron:udp?endpoint=pinger:40123" uk.co.real_logic.aeron.samples.Pong # run on pinger

# Run both on ponger
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=ponger:40124" -D"aeron.sample.pong.channel=aeron:udp?endpoint=ponger:40123" -Daeron.sample.messages=10000 uk.co.real_logic.aeron.samples.Ping # run on ponger
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=ponger:40124" -D"aeron.sample.pong.channel=aeron:udp?endpoint=ponger:40123" uk.co.real_logic.aeron.samples.Pong # run on ponger

I have also tried pointing the ping channel to pinger and the pong channel to ponger with no success in case I misunderstood the roles.

Does anyone have an idea what I might be doing wrong?

**Comment by tmontgomery** [comment]
@Reinholdtsen You should be using the new URI scheme and not mixing things. Take a look at Configuration to see the syntax or the wiki https://github.com/real-logic/Aeron/wiki/Channel-Configuration

You might want to change Pong to display the available Image to help see if Pong is seeing pingers channel.

From a quick look, the output of Ping looks like it should work. It seems to see the image for Pong as an available image. Which means that the channel from Pong to Ping seems to be OK. By adding a display of available image to Pong, you can see if Pong sees Ping.

When you mention it "hangs", how long are you waiting? Going over the network can be a lot longer than over localhost. So, you might want to lower the warmup number of messages and iterations to see if it truly is hanging or just slow.

**Comment by tmontgomery** [comment]
I have added the ability to have Pong display available/unavailable images. Just set `aeron.sample.info` to true.

**Comment by Reinholdtsen** [comment]
I may have had a mixture of 32 and 64 bit Java installations causing problems. After I reinstalled just 64 bit Java, the following startup commands worked:
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=ponger:40123" -D"aeron.sample.pong.channel=aeron:udp?endpoint=pinger:40124" -Daeron.sample.messages=200 -Daeron.sample.warmup.messages=10 uk.co.real_logic.aeron.samples.Ping # run on pinger
java -cp \Aeron\pingpong-0.x.0-jar-with-dependencies.jar -D"aeron.sample.ping.channel=aeron:udp?endpoint=ponger:40123" -D"aeron.sample.pong.channel=aeron:udp?endpoint=pinger:40124" -Daeron.sample.info=True uk.co.real_logic.aeron.samples.Pong # run on ponger

I got the following statistics:
#[Mean    =    34838.221, StdDeviation   =    15484.790]
#[Max     =   155189.247, Total count    =          200]
#[Buckets =           24, SubBuckets     =         2048]

Given the following regular ping results, do the Aeron ping/pong results seem reasonable?
C:\Aeron>ping ponger

Pinging ponger.home [192.168.1.12] with 32 bytes of data:
Reply from 192.168.1.12: bytes=32 time=3ms TTL=128
Reply from 192.168.1.12: bytes=32 time=5ms TTL=128
Reply from 192.168.1.12: bytes=32 time=2ms TTL=128
Reply from 192.168.1.12: bytes=32 time=33ms TTL=128

**Comment by tmontgomery** [comment]
The numbers would seem to be quite possible given the base ping times. Those times are quite high for a LAN, though.
