### ISSUE TITLE
Does Aeron suit for bulk transfers between two host?

### ISSUE THREAD

**Issue by nxtreaming** [real-logic/Aeron#202]
I wanna transfer reliable data (eg: big files) between two host by using Aeron.

Thanks.

**Comment by mjpt777** [comment]
Yes this can be possible. For messages over a few MB in size you will need to split it into chunks and then send a stream of chunks.

**Comment by nxtreaming** [comment]
Thanks.

I will try to slice my data into many small segments to use Aeron to transmit them between two hosts.

**Comment by mjpt777** [comment]
The most efficient way to do this will be to set the Aeron MTU to be 16KB or 32KB. Use the `Publication.tryClaim()` to copy in the MTU size minus a 24 byte header, this will avoid a double copy. Then it is a case of setting the SO_SNDBUF and SO_RCVBUF to account for the bytes in flight.

**Comment by nxtreaming** [comment]
why can the Areon MTU be 16K  or more? 
Because  Aeron is based on UDP, UDP's MTU should be very small ( eg: smaller than 1500)?

**Comment by mjpt777** [comment]
With UDP the datagram can be larger than the Ethernet MTU. UDP will fragment the datagram and reassemble it again. This is done in the kernel and saves on system calls. If one fragment is lost then the whole datagram must be retransmitted but this does not tend to happen often on local networks that are not congested. The main cause of loss is incorrectly sized socket buffers. Aeron will flow control and so loss is not common with properly sized socket buffers.

**Comment by nxtreaming** [comment]
I see.
Thanks.
