### ISSUE TITLE
Sender doSend implementaton question

### ISSUE THREAD

**Issue by kowalczm** [real-logic/Aeron#207]
Hello, 
I am reviewing great Aeron code and I'm wondering why this Sender [doSent](https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/Sender.java#L99) method splits iteration of NetworkPublications on two for loops? Can it be one iteration of all `NetworkPublication[] publications`?

**Comment by tmontgomery** [comment]
It can be written a number of ways, actually. And has been if you look at the commit log for the file. However, this seems to optimize well and is simple.

**Comment by kowalczm** [comment]
Thanks for quick response. I see now, it is for optimization.

**Comment by mjpt777** [comment]
The loops are written this way to help them benefit from bound check elimination on the arrays.
