### ISSUE TITLE
Allow a client to initiate connections to a server

### ISSUE THREAD

**Issue by Reinholdtsen** [real-logic/aeron#211]
Is it possible for a client to publish to and subscribe from a server without the server knowing a priori about the client. Potential applications include multiplayer games. I envision a client doing an unsolicited publish to which the server subscribes. In addition the server would add the client to its list of subscribers using the client's publishing port, which would allow the messages to get through home router firewalls. It is not clear to me if and how Aeron supports this scenario without modification. Thanks.

**Comment by tmontgomery** [comment]
This is something that others have built on top of Aeron a few times now.

When we get some time, we do plan to provide this built on top as well.

**Comment by krisskross** [comment]
@tmontgomery Are there examples of this on github?

**Comment by tmontgomery** [comment]
Somewhat, yes. Checkout the Aeron Archiver. https://github.com/real-logic/aeron/tree/master/aeron-archive
