### ISSUE TITLE
Aeron Built Before Agrona

### ISSUE THREAD

**Issue by MKSoftechnician** [real-logic/Aeron#212]
Hi,
 I have built Aeron first using "./gradlew eclipse" and then built agrona.
now it shows some  Agrona snapshot not found and other errors in Aeron.

Kindly help me.

Thanks

**Comment by mjpt777** [comment]
Aeron depends on Agrona. We have some changes in both at present. You need to build Agrona locally first. If you run the standard `gradlew` in each they will install into local Maven repository cache.

https://github.com/real-logic/Agrona
