### ISSUE TITLE
Multiple fragments

### ISSUE THREAD

**Issue by muc392** [real-logic/Aeron#213]
I understand that a large message needs to be fragmented for sending over a network and its header consists of (B)egin and  (E)nd flags. But if there are multiple fragments, how will only B and E flags help? what flags will be contained in between fragments? 
as per my understanding One Publication Image  is one complete message. guide me if I am incorrect.
e.g Messge1 -> M1F1, M1F2, M1F3
Message2 -> M2F1, M2F2, M2F3, M2F4
Data arrived is M1F1 M2F2 M1F3 M1F2 i.e. in an unordered way.
as per code it will keep on buffering based on stream ID and session ID in fragment assembler. so how does it know then that where to put respective fragment.

Eager to hear soon.

**Comment by mjpt777** [comment]
If a message is not fragmented then the Begin and End flags will both be set. All fragments have a term offset and length so we can determine exact position in a stream and thus can be reassembled in order.

For fragments between the begin and end then these flags are not set. The offset within the term is all that is required. Streams are reassembled purely on position via offset. The begin and end flags allow for demarking messages within the reassembled streams.

**Comment by muc392** [comment]
Thank you for reply.
then one Publication Image is one complete message am I correct?
or can one Publication Image contain multiple messages??
Kindly explain me with example if possible(about message not fragmentation).

**Comment by mjpt777** [comment]
One `PublicationImage` is a rebult image of a `NetworkPublication` containing many messages as a stream of rotating term buffers. 

The best way to understand is to read the code for full detail.

**Comment by muc392** [comment]
Thank you very much
