### ISSUE TITLE
multicast at LAN is not work

### ISSUE THREAD

**Issue by zhao141** [real-logic/Aeron#216]
i use java api. the multicast is ok at localhost ,but ,in LAN can not accept connection messag and protoc. why?  @tmontgomery

**Comment by mjpt777** [comment]
Can you provide more details of what you are doing and what failures you are seeing?

**Comment by tmontgomery** [comment]
You should try the sample BasicPublisher and BasicSubscriber and save the output.

What environment is this in? Are you sure both entities have multicast connectivity to each other?

**Comment by stanliberman** [comment]
Based on personal experience, I would also recommend setting multicast TTL as in 1a15b01dfe8b220d47500b1a8ec765236e39d752 to a higher than 0 value.

**Comment by zhao141** [comment]
thx all.I have to give up it.because my LAN and cloud server can`t multicast
