### ISSUE TITLE
about FramentHandler filter

### ISSUE THREAD

**Issue by zhao141** [real-logic/Aeron#217]
FragmentHandler is so ground, we are create filter handler. analogy netty.  are there or future

**Comment by mjpt777** [comment]
@zhao141 I don't quite understand what you are asking. Can you provide an example?

**Comment by zhao141** [comment]
netty protoc decoder and encoder filter. you donw?
FragmentHandler provides methods too bottom, I want to show my custom method parameters for developers

**Comment by mjpt777** [comment]
If you want to encode and decode messages with Aeron then SBE integrates well and is very efficient. 

https://github.com/real-logic/simple-binary-encoding
