### ISSUE TITLE
Is it possible to bind the data endpoint and the control endpoint with different media driver?

### ISSUE THREAD

**Issue by bianbian-org** [real-logic/Aeron#219]
such as:

data : one-way udp from sender to receiver,

control: one-way infiniband/or serial port if possible from receiver to sender

**Comment by mjpt777** [comment]
This is not currently supported nor do we have plans for such.

What would be the usecase?

**Comment by mjpt777** [comment]
There would also be issues with this like shared state. The control is used for things like status update and NAKs. One driver would not know what is the state of another driver.

**Comment by bianbian-org** [comment]
Thanks. wanna transfer a file from one computer to the other but because of the security reasons the UDP packages are one-way, i.e.  one can ONLY send and the other can ONLY receive.

**Comment by mjpt777** [comment]
Aeron is probably not the right solution for you then. It is not designed for such usage.
