### ISSUE TITLE
Low file space warning

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#221]
Add a warning if remaining space is low in the volume where the Aeron directory is configured. This is to ensure sufficient space exists for the CnC and log files. The `aeron.dir` should typically be somewhere like `/dev/shm/` which can have limited space.

**Comment by mjpt777** [comment]
This could be part of the duty cycle in the conductor so it is continuously monitored.

**Comment by lbradstreet** [comment]
This would be great. We are pretty tempted to start detecting this issue ahead of time so that our users get more helpful errors.

**Comment by mjpt777** [comment]
I'll see if I can get round to adding this before the next release.

**Comment by lbradstreet** [comment]
Thank you. There's no rush - I just wanted to let you know we'd find it useful too.

**Comment by mjpt777** [comment]
@lbradstreet Can you check if this meets your needs?
