### ISSUE TITLE
C++ publicationTest failing

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#222]
```
[       OK ] PublicationTest.shouldFailToOfferAMessageWhenLimited (0 ms)
[ RUN      ] PublicationTest.shouldFailToOfferWhenAppendFails
unknown file: Failure
C++ exception with description "Index Out of Bounds[0xfcc600]. Index: 65535 + 4 Capacity: 65536" thrown in the test body.
[  FAILED  ] PublicationTest.shouldFailToOfferWhenAppendFails (1 ms)
[ RUN      ] PublicationTest.shouldRotateWhenAppendTrips
[       OK ] PublicationTest.shouldRotateWhenAppendTrips (0 ms)
[ RUN      ] PublicationTest.shouldRotateWhenClaimTrips
```

**Comment by mjpt777** [comment]
It does not fail for me locally but I think there is a problem in the test. It should be checking end of buffer condition and not end of buffer - 1. I've pushed a change. @tmontgomery Can you confirm this makes sense?

**Comment by mikeb01** [comment]
I'm running with the Debug configuration.  If you are using the Release config the bounds checking is disabled.  That might be why it doesn't fail for you.

**Comment by mjpt777** [comment]
The tests for Java run in with bounds checking on. We should change the C++ to do the same.

**Comment by mikeb01** [comment]
As long as all of the bounds checking happens in header, we can just undef DISABLE_BOUNDS_CHECKING.  I'll have a look this evening.

**Comment by mikeb01** [comment]
Your change fixes the test.  I've made a change to the CMake build files so that the DISABLE_BOUNDS_CHECKS is only set on the production code, but not the tests.  Even in 'Release' configuration.

**Comment by tmontgomery** [comment]
BTW, the original idea was to undef DISABLE_BOUNDS_CHECKS for all tests, but keep the main code dependent on the build type. At some point, the bounds check undef didn't happen.

**Comment by tmontgomery** [comment]
@mjpt777 I can see that the fix for the test works. But why does it fail in the original version with a bounds check. Surely the original position of TERM_LENGTH - 1 is valid and shouldn't access out of bounds....

**Comment by mjpt777** [comment]
It is not valid as it is trying to read a 4 byte word at TERM_LENGTH - 1 which overruns by 3 bytes.

**Comment by mjpt777** [comment]
The test did not consider alignment which would have meant the situation could not have existed.

**Comment by tmontgomery** [comment]
ah, yes. The test should have set the initial position aligned instead. No coffee yet.
