### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by morriph** [real-logic/Aeron#223]
I note from a couple of other posts (56 and 137) that persistence has been a consideration for some time. Do you have any update on whether this is likely to be added, or not? (Issue 137: "Persistence is, in fact, on our TODO lists and something we have spent a good bit of time thinking about and designing already."). The use case that I am thinking about is around persistence for recovery and replay rather than persistence for late joining etc.

Many thanks.

**Comment by mjpt777** [comment]
It is being developed for a specific use case. This may prove to be sufficiently general. Time will tell. Sorry but we cannot provide concrete information at this stage.
