### ISSUE TITLE
Easier to catch channel errors

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#224]
When creating a channel that has an error on creation, such as a bind error, it would be nice to make finding the error in the app easier.

**Comment by tmontgomery** [comment]
A counter variable for a channel can be used. key is the channel. Value is 0 (creating), 1 (ok), 2 (errored, see error log).

**Comment by tmontgomery** [comment]
From @mjpt777 The id can be the the registration id of the subscription or publication that created it.

**Comment by mjpt777** [comment]
The counter id can be returned in the control protocol so the client can directly poll it when a Subscription or Publication is added.

**Comment by tmontgomery** [comment]
I've added some status indicators to the counters as mentioned. Right now, the app can look directly at the counters to see the status of a channel.

The values for the status are ([here](https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/status/ChannelEndpointStatusIndicator.java)):
* 0: initializing
* 1: active (OK)
* -1: errored (see ErrorLog)
* 2: closing

Adding the ability for the client to associate status via adding to the control protocol I am on the fence about.

An application might best check status via polling the stats and looking for the channel typeId and channel string. The only thing that might be odd is when channels get normalized and the string doesn't exactly match new strings. However, that only matters for the second pub/sub that uses the same  channel and normalizes to an existing channel differently. This would seem to be less useful in those cases.
