### ISSUE TITLE
.NET client port

### ISSUE THREAD

**Issue by buybackoff** [real-logic/Aeron#225]
I started porting the client to .NET. I mostly needed LogBuffers for IPC - it was too good to invent my own :)  LogBuffers already work in my Spreads library. I will eventually port the remaining parts of the client, but currently do not need it and won't touch the remaining parts this month. If someone is already working on open-source .NET client port, please let me know. Or please join or fork this project: https://github.com/Spreads/Aeron.NET.

**Comment by mjpt777** [comment]
Hi @buybackoff. Interesting timing. There is an official port of the Aeron client in .NET that will be released in the very near future. This will be a full client. Might be interesting to see if it works for your needs.

**Comment by buybackoff** [comment]
Cool! I wasn't going to proceed with the full client soon, so this is a good news! Since my LogBuffers implementation is binary compatible, it will be easy to switch. BTW, how much is "very near future"?

**Comment by mjpt777** [comment]
Weeks, possibly a month at the outside.

**Comment by buybackoff** [comment]
Timing indeed was interesting :) .NET version is now on par with Java in this PR https://github.com/AdaptiveConsulting/Aeron.NET/pull/37
