### ISSUE TITLE
Transparent IPC usage for Subscriptions on the same media driver

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#229]
It would be ideal if a `Subscription` could transparently use the same logbuffer for channel + streamIds that are on the same media driver. Very much akin to how IPC works, but smart enough to know that there are local (to the media driver) `Publications` and use the logbuffer directly.

This is different than the suggested _Spy_ semantics from #150 in that all external `Publication` can be received as normal.

While transparent, this may not always be desired, so there needs to be a configuration option to turn it off. `aeron.ipc.subscription.bypass` set to `true` or `false`.

Edit: change configuration setting to "bypass".

**Comment by mjpt777** [comment]
The main stand out from `aeron:ipc` is that these transparent IPC streams would be fragmented for MTU whereas normal IPC streams are not fragmented as MTU is effectively maximum message size.

I'm not sure on the name "transparent". I know it is used for the likes of "Transparent Huge Pages" in Linux for example but I prefer the something more like "bypass", whereby these streams bypass the network stack when local.

**Comment by tmontgomery** [comment]
"bypass" is good for me. Will update.

**Comment by tmontgomery** [comment]
After looking at this in depth, it can't be made totally transparent, in the multicast case, without requiring the driver to receive the data stream and filter. Additionally, for unicast streams, it requires some additional checks that are likely to have an adverse effect on performance.

Hence, tabling this enhancement for now until we can figure out a means to avoid the downside.
