### ISSUE TITLE
IPC spy subscription semantics

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#230]
As per the last point in #150. There should be a means to spy on a local `Publication` only.

Subscribe to a Channel + Stream ID for any publisher on the same media driver ("Spying" on a normal publisher for purposes such as local processing, archival, etc.). Ignoring external publishers.

This includes addition of methods to create "Spy" Subscriptions for specific Publications, `Aeron.addSpy(Channel, StreamID)`. This is a Subscription object and can be polled as normal and uses same semantics for data delivery as other Subscriptions.

**Comment by mjpt777** [comment]
In what cases would this be needed if we have #150 ?

**Comment by tmontgomery** [comment]
I was just preserving the enhancement since #150 is closed and most of it is done and in.

**Comment by mjpt777** [comment]
I guess having spy then means it can be programatically used whether the bypass is enabled or not. This is probably the desired behaviour for archiving/replicating.

**Comment by tmontgomery** [comment]
Indeed. My thoughts as well.

**Comment by tmontgomery** [comment]
To make usage nice and easy, we've decided to make the usage of a spy part of the URI.

A spy is designated by adding a prefix to the URI that is `aeron-spy:`. So, for example the following would be a URI for a spy Subscription:

```java
addSubscription("aeron-spy:aeron:udp?endpoint=localhost:40123", 10);
```

In all ways, a spy subscription acts like a normal subscription object. Support for languages should not require any specific interactions to use a spy.

**Comment by tmontgomery** [comment]
For the `sourceIdentity` of `Image` that are spies, they contain the original URI of the channel. This should aid in determining if an Image is a spy or not.

**Comment by tmontgomery** [comment]
With the addition of 170f8b2 this seems to be working well enough to start using.
