### ISSUE TITLE
Client server capabilities

### ISSUE THREAD

**Issue by erikvanoosten** [real-logic/Aeron#232]
It would be great if client-server capabilities can be layered on top of current Aeron capabilities.

With these capabilities it would be very easy to 1) set up a subscription/publication pair (for clients), and 2) send a message to the sender of an incoming message without manual publisher bookkeeping.

**Comment by mjpt777** [comment]
Could you provide a worked example of how the API would function?

**Comment by tmontgomery** [comment]
This is the spirit of #211

**Comment by erikvanoosten** [comment]
@mjpt777 I am a bit vague on purpose because I do not have a deep enough understanding of the Aeron model to suggest something more concrete.

@tmontgomery Ah, missed that one. I'll close this one then.
