### ISSUE TITLE
Support finer grained system counters

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#233]
Currently useful counters like: 'NAKs sent', 'NAKs recevied', 'Sender flow control limits applied' are only available at media driver level.  However it would be helpful if is possible to see these counters at a per-channel or per-stream level where appropriate.

**Comment by mjpt777** [comment]
We could add an option to add a number of optional counters per channel/stream so this could be enabled when needed and not crowd out the counters when not. Not sure if this is best but worth considering.

**Comment by mjpt777** [comment]
A more holistic approach to detecting loss is now available with the `LossReport`.

https://github.com/real-logic/Aeron/wiki/Monitoring-and-Debugging#loss-reporting
