### ISSUE TITLE
Wireshark Disector

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#236]
Add a Wireshark Disector as a module to the main project so it is easily discovered for the UDP network protocol.

https://github.com/real-logic/Aeron/wiki/Protocol-Specification

**Comment by maseev** [comment]
Sorry for bringing this up. I was looking for a Wireshark dissector the other day and stumbled upon this issue. After that, I found the following [dissector](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-aeron.c), which apparently is now a part of Wireshark. 
Do I understand this correctly that this particular dissector is good enough and should be generally used for analyzing the Aeron protocol?
