### ISSUE TITLE
Code sample for multiplexing topics onto Channel and Stream

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/aeron#238]
Provide a code sample(s) and re-usable construct(s) to multiplex topics onto a single Channel and Stream.

**Comment by mjpt777** [comment]
There are lots of examples of this in the archive and cluster code with publishers on the producer side and adapters on the consumer side.

https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/service/ServiceControlPublisher.java

https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/service/ServiceControlAdapter.java

**Comment by feribg** [comment]
Those links are no longer valid, can you please share an up to date sample ?

**Comment by mjpt777** [comment]
https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/LogPublisher.java

https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/LogAdapter.java

**Comment by feribg** [comment]
Thanks
