### ISSUE TITLE
Question: Aeron between data centres

### ISSUE THREAD

**Issue by rodneyparnell** [real-logic/Aeron#242]
Hi, thanks for Aeron.

I want to use Aeron for service requests between processes that may be deployed in different data centres in different countries. There are restrictions that limit communications to TCP rather than UDP and ports are tightly firewalled. In the Aeron overview TCP is mentioned as a possible transport for Aeron. Is this feature ready? Or can you make an alternative suggestion for inter-process service requests via Aeron?

**Comment by mjpt777** [comment]
We do not have plans to support TCP for Aeron streams. TCP in many ways goes against the spirit of Aeron. I'm not sure how we gave the impression that was going to be supported? Is there some source we need to correct?

For sending between data centres then a gateway and tunnelling solution would be best, if UDP cannot be routed. We have discussed building such a gateway with some clients that would tunnel Aeron streams down a TCP connection. So far these have only been discussions. If you would be interested in sponsoring such a feature then we can discuss it. The buffering and connect requirements are different for such situations compared to UDP on a LAN.

**Comment by rodneyparnell** [comment]
I may have misinterpreted the information on https://github.com/real-logic/Aeron/wiki/Protocol-Specification where it says:

_"The Aeron protocol is designed to be run directly over many different types of transmission media, including shared memory/IPC, InfiniBand/RDMA, UDP, TCP, Raw IP, HTTP, WebSocket, BLE, etc. This means that the following assumptions are made:
Transmission Media may be a stream media, such as TCP or RDMA without inherent frame boundaries.
........."_

I will talk to my employer about the gateway tunnelling possibility although it is a longshot.

Thanks nevertheless for the innovations the team has achieved with Aeron. It will be big!

**Comment by tmontgomery** [comment]
Probably should tighten up the language in the spec. The intent was to define media very broadly. Should narrow it down now.
