### ISSUE TITLE
build fails "Could not resolve: org.agrona:Agrona:0.5.2-SNAPSHOT"

### ISSUE THREAD

**Issue by philgentric** [real-logic/Aeron#246]
just cloned , then
./gradlew eclipse
(half) fails... 
it says BUILD SUCCESSFUL in the end but there is an error as follows:

....
Download https://repo1.maven.org/maven2/org/objenesis/objenesis/2.1/objenesis-2.1-sources.jar
:aeron-agent:eclipseJdt
:aeron-agent:eclipseProject
:aeron-agent:eclipse
:aeron-all:eclipseClasspath
:aeron-all:eclipseJdt
:aeron-all:eclipseProject
:aeron-all:eclipse
:aeron-client:eclipseClasspath
Could not resolve: org.agrona:Agrona:0.5.2-SNAPSHOT
.....

I tried to manually download agrona but I got 0.5.1 and then adding the dependencies in Eclipse does not help

**Comment by mjpt777** [comment]
You need to build [Agrona](https://github.com/real-logic/Agrona) locally as the current version of Aeron depends on the SNAPSHOT build of Agrona.

**Comment by philgentric** [comment]
I cloned Agrona (in the AERON dir) and gradlew it successfully, then for aeron gradlew eclipse works, but when I retry (after erasing) to import in eclipse, I still get errors:
"Access restriction: The type 'Signal' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/rt.jar')"

can you document the exact procedure that works for you ?

**Comment by mjpt777** [comment]
@philgentric I don't use Eclipse, I use IntelliJ IDEA. Eclipse complains that things like Unsafe and Signal are not supported APIs. This is true by they are necessary for an application like Aeron. Come Java 9 we should be getting alternatives to Signal and Unsafe.

**Comment by philgentric** [comment]
Thanks.

May I suggest you could update the eclipse section in https://github.com/real-logic/Aeron/wiki/Hacking-on-Aeron to document that and avoid bad surprises ?-)

in the meantime I will try InteliJ IDEA...

**Comment by mjpt777** [comment]
@mikeb01 Can you pick this up as a Eclipse user?

**Comment by philgentric** [comment]
Done

**Comment by mjpt777** [comment]
Thanks

**Comment by mikeb01** [comment]
@mjpt777 I haven't been an Eclipse user for over a year.  I've removed the Eclipse instructions as they are out of date.
