### ISSUE TITLE
C++ stream position counters metadata layout declarations

### ISSUE THREAD

**Issue by sthornington** [real-logic/aeron#250]
It would be helpful if the C++ port had struct declarations for the layouts of the counter metadata maintained by the driver for the stream positions.  This is necessary when programmatically looking for a specific stream counter by stream id, as currently (as of 0.9.9) the stream position counter metadata is only declared on the Java end.

**Comment by tmontgomery** [comment]
Just for reference, the Java side is specified in `StreamPositionCounter` which is something like the following.

```cpp
struct
{
    std::int64_t registrationId;
    std::int32_t sessionId;
    std::int32_t streamId;
    std::int32_t channelLength;
    // channel up to channelLength in size encoded as UTF-8
}
```

**Comment by mjpt777** [comment]
This is captured in the C media driver.

https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/c/aeron_position.c

Maybe we could extract to a header file.

**Comment by tmontgomery** [comment]
Client API does not depend on the driver. So, would be best to just add a struct for the layout directly. As we have a few layouts, be good to do a struct for each that is expected to be read by the API. RecordingPos is already done in the Archive C++ API.

**Comment by tmontgomery** [comment]
Pulled out into the client now with fb7bc3f1da9ee677bea
