### ISSUE TITLE
Possible Race Condition on Driver Startup

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#251]
If a process running a client and a media driver start at roughly the same time, it is possible for the client's `Aeron.connect(Aeron.Context)` call to succeed, but have the driver in an invalid state.  This will manifest in the format of a heartbeat timeout exception being passed to the error handler that is attached to the client context and all subsequent addPublication requests will also timeout.  It never recovers from this state.

**Comment by mjpt777** [comment]
We should make the creation of the CnC file atomic. That is, create it under another name then rename it when sized and initialised.

**Comment by mjpt777** [comment]
What should the behaviour be if a client starts and the driver has not yet started? Should it fail immediately or should it retry for a period?

**Comment by tmontgomery** [comment]
The CnC file is the one that needs to be handled carefully. It should be the last thing to create and moving it into place (rename) is the last thing to do.

**Comment by mikeb01** [comment]
My preference would be for there to be some way to wait for a driver to have started.  At the moment I have a loop that catches the `IllegalStateException` thrown when trying to construct Aeron client and retries until it succeeds or times out.

If you want to have it fail immediately for simplicity's sake, then that would be okay too.  However, for that case a checked exception like `DriverUnavailable` would be better than `IllegalStateException`.

**Comment by mjpt777** [comment]
It throws an `IllegalStateException` when the version is not correct. You get an `IOException` if the file is not there.

An approach we could take is to write the version field last with an ordered write in the driver. If the file is there then the client will spin with a timeout on this field. This way the file does not need renamed.

**Comment by mjpt777** [comment]
@mikeb01 You should be able to start up the client and driver in whatever order now.

**Comment by mikeb01** [comment]
Will it timeout if the driver never starts?

**Comment by mjpt777** [comment]
@mikeb01 It will timeout using the normal driver timeout.
