### ISSUE TITLE
FAQ: why is the Media Driver written in Java?

### ISSUE THREAD

**Issue by epsitec** [real-logic/Aeron#253]
This was the first question that crossed my mind: you are playing pretty low level tricks to have high performance in the media driver. So why do you stick to a Java implementation (which requires that the JRE has to be deployed on the host) rather than going native?

**Comment by mjpt777** [comment]
Java is the primary platform for our client who sponsored this work. Sure a native driver could be even higher performance but it is nice to have a Java implementation that is lower and more predictable latency than the native competitors which have expensive licences :-)

Also Java is a faster to develop in. In time someone may be willing to sponsor a native driver. We'd be very happy to take that work on.

**Comment by epsitec** [comment]
Thank you for explaining the context. And congratulations on the work you have done!
