### ISSUE TITLE
cppbuild warning for compare signed & unsigned

### ISSUE THREAD

**Issue by dlintw** [real-logic/Aeron#26]
git code version: 71b0f300

Building CXX object aeron-common/src/main/cpp/concurrent/CMakeFiles/concurrentTests.dir/tests/testCountersManager.cpp.o
In file included from /var/abs/local/libaeron-git/src/Aeron/aeron-common/src/main/cpp/command/tests/testCommand.cpp:18:0:
/var/abs/local/libaeron-git/src/Aeron/aeron-common/src/main/cpp/3rdparty/gmock-1.7.0/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]’:
/var/abs/local/libaeron-git/src/Aeron/aeron-common/src/main/cpp/3rdparty/gmock-1.7.0/gtest/include/gtest/gtest.h:1485:30:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int; bool lhs_is_null_literal = false]’
/var/abs/local/libaeron-git/src/Aeron/aeron-common/src/main/cpp/command/tests/testCommand.cpp:81:5:   required from here
/var/abs/local/libaeron-git/src/Aeron/aeron-common/src/main/cpp/3rdparty/gmock-1.7.0/gtest/include/gtest/gtest.h:1448:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (expected == actual) {
                ^

**Comment by tmontgomery** [comment]
This is not dangerous and does not give a false positive. So, it should be OK.

All the same, expect a cleaner build in the future anyway.
