### ISSUE TITLE
Support passing in a ThreadFactory to Aeron.start()

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#260]
Or setting in on Aeron.context().  This will allow users to have a bit more control over the thread that is created, e.g. the ability to set the thread into daemon mode and custom naming.

**Comment by tmontgomery** [comment]
We did an Executor version early on and dropped it (both client and driver). But ThreadFactory might be more appropriate. Also, we have more experience now.

**Comment by mjpt777** [comment]
Where does the responsibility for starting the thread or calling run() exist in this approach?

**Comment by mikeb01** [comment]
In the same place, check out pull requests #261 and real-logic/Agrona#68.
