### ISSUE TITLE
Documentation covering failure scenarios

### ISSUE THREAD

**Issue by jiteshvassa** [real-logic/Aeron#262]
Is there any documentation around failure scenarios?

Lets say you have the following setup where a client is sending messages to a subscriber:

Client -> Media Driver -> UDP -> Media Driver -> Subscriber

I would be particularly interested in what would happen in the case of either Media Driver failing and how to go about dealing with recovery.

**Comment by mjpt777** [comment]
What do you mean by recovery? What state do you return to?

**Comment by jiteshvassa** [comment]
I'd like to understand a bit more around how either of the Drivers going down would manifest itself in the client / subscriber.  I saw that there's an Aeron.Context.errorHandler, would a notification come through there?

In addition if the Driver was started back up, is there any re-connection logic within Aeron or would that need to be handled externally?  If it's the later, then it would be good to know which of the Aeron constructs should be cleared up and recreated.

**Comment by karypid** [comment]
> A client application should therefore handle this as a serious error and totally restart. Cleaning up all Publications, Subscriptions, and the Aeron client itself and then restarting.

Is there any reason why a media driver being restarted is so dramatic in Aeron? What problems could arise if you installed an error handler that caught the `DriverTimeoutException` and simply switched to 'recovery' mode?

What I mean by that, is have applications periodically try to reconnect, waiting for the media driver to come back. When they succeed, thy can re-create subsrciptions/publications and resume operation.

**Comment by mjpt777** [comment]
> Is there any reason why a media driver being restarted is so dramatic in Aeron? What problems could arise if you installed an error handler that caught the `DriverTimeoutException` and simply switched to 'recovery' mode?

Determining the exact state of a system under failure is tricky. There is no "simply" to it usually. You can handle this yourself and try to reconnect. We provide the basics if you use:

https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/java/io/aeron/CommonContext.java#L374
