### ISSUE TITLE
Subscription stops delivering messages

### ISSUE THREAD

**Issue by grzegorz-gierlach** [real-logic/Aeron#268]
Hi, I believe I have found an issue related to publications going off and on again.

The situation is pretty easily reproducible - start the subscriber and publisher, then stop all threads in a publisher's process for more than image timeout, resume publishers threads again.
The subscriber(s) will stop delivering messages in 9 out of 10 tries.

What is interesting subscriber sends SMs. Publisher sends heartbeats, however stream processing cannot advance - publisher is getting back pressured.

Of course I use 1.0 for both ends.

UPDATE: I cannot prove it does work, however I cannot prove it doesn't either... If I revert recent changes to PublicationImage.trackRebuild it seems to work.

UPDATE: I think it might be something with cleanPosition not being initialized properly?

**Comment by tmontgomery** [comment]
There is both a client liveness detection on the driver and an inter service timeout in the client. If a client conductor thread is stopped, the driver and the client will determine it is dead and not allowed to continue. So, stopping the threads for this long is not supported behavior.

**Comment by grzegorz-gierlach** [comment]
Before running the test I have increased both (driver & client) timeouts to some larger value. Stopping the threads is just one of the ways to quickly replicate the issue - having 2 boxes you can  partition the network for instance and you should see similar results.

**Comment by tmontgomery** [comment]
As there are other timeouts involved, chances are just upping those might not be enough to still be on the right side of what you are trying to replicate.

A network partition that lasts longer than Image timeout means the image will become unavailable. If that subscription is the last subscription, it will back pressure the publication when the flow control window fills up. This is by design.

If/when the partition is healed and the publication is still active, this will create a new Image on the subscription.

Simulating this behavior by changing timeouts and pausing threads will add in all kinds of other undesired behaviors. If you want to test network spurious connectivity, a better way is to use firewall rules.

**Comment by grzegorz-gierlach** [comment]
I'll try to do that tomorrow with some decent network between the boxes.

However, purely theoretically... driver-conductor thread calls PublicationImage.trackRebuild(), what if before it does for the first time (for a recreated publication image) receiver thread kicks in and inserts packets into the log buffers. Won't trackRebuild have a chance to zero out the data just received?

**Comment by tmontgomery** [comment]
The incremental cleaning is cleaning behind the current point that data would be coming in on. So, not seeing how it could stomp on it off hand.

**Comment by mjpt777** [comment]
The  Image log buffer is zero'ed out behind the slowest subscriber. Packets coming in are only inserted if they are within the receive window that has been advertised via the status messages. The receive window is ahead of the slowest subscriber.

**Comment by grzegorz-gierlach** [comment]
Run the test on 2 boxes with iptables dropping and letting the packets through again.
As expected getting same results - it was only slightly harder to replicate it; stopping the publishers threads is not a factor here, it's just a handy way to quickly create some load.

Maybe I'm completely wrong with that cleanPosition being not initialized but...

In most cases I'm getting empty subscriber's log buffers, all terms being zeroed out.
Once I got this:
```
Index 0 Term Data

0: DATA Header{frame_length=0 version=0 flags=00000000 type=0 term_offset=0 session_id=0 stream_id=0 term_id=0 reserved_value=0}
0000
%n======================================================================
Index 1 Term Data

0: DATA Header{frame_length=1429 version=0 flags=11000000 type=1 term_offset=0 session_id=-167296996 stream_id=1 term_id=-1871178989 reserved_value=0}
0300
...
Index 2 Term Data

0: DATA Header{frame_length=4096 version=0 flags=10000000 type=1 term_offset=0 session_id=-167296996 stream_id=1 term_id=-1871178991 reserved_value=0}
0300
...
```
If you look at term ids something is clearly wrong - entire -1871178990 which should be in term 0 is missing.

Publisher log buffers looks fine at the same time.

On a rare occasion subscriber's fragment handler is being called with a view onto the buffer which is zeroed out as well.

And finally here is the excerpt from one of the runs from subscriber's AeronStat:
```
07:39:27 - Aeron Stat
=========================
  0:                    0 - Bytes sent
  1:       24,968,410,976 - Bytes received
  2:                    0 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:                    0 - Failed offers to DriverConductorProxy
  5:               29,518 - NAKs sent
  6:                    0 - NAKs received
  7:              645,274 - Status Messages sent
  8:                    0 - Status Messages received
  9:                    0 - Heartbeats sent
 10:              103,665 - Heartbeats received
 11:                    0 - Retransmits sent
 12:              248,793 - Flow control under runs
 13:              175,682 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:                    0 - Short sends
 17:                8,621 - Client keep-alives
 18:                    0 - Sender flow control limits applied
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    1 - recv-channel: aeron:udp?endpoint=10.2.3.68:40123
 23:                    0 - sub-pos: 1 2026399379 1 aeron:udp?endpoint=10.2.3.68:40123 @0
 24:                    0 - rcv-hwm: 2 2026399379 1 aeron:udp?endpoint=10.2.3.68:40123 
 25:                    0 - rcv-pos: 2 2026399379 1 aeron:udp?endpoint=10.2.3.68:40123 
 26:                    0 - sub-pos: 1 -509907085 1 aeron:udp?endpoint=10.2.3.68:40123 @0
 27:                    0 - rcv-hwm: 3 -509907085 1 aeron:udp?endpoint=10.2.3.68:40123 
 28:                    0 - rcv-pos: 3 -509907085 1 aeron:udp?endpoint=10.2.3.68:40123 
 32:        3,357,621,376 - sub-pos: 1 31588087 1 aeron:udp?endpoint=10.2.3.68:40123 @3,357,621,376
 33:        3,471,277,568 - rcv-hwm: 25 31588087 1 aeron:udp?endpoint=10.2.3.68:40123 
 34:        3,357,621,376 - rcv-pos: 25 31588087 1 aeron:udp?endpoint=10.2.3.68:40123
```
In this specific case there are lot of NAKs reported - however it's not a rule, sometimes just SMs are being sent through.

Let me know if I can test/provide anything else.

**Comment by grzegorz-gierlach** [comment]
More tests and some conclusions...

Correct me if I'm wrong.
Uninitialized cleanPosition results in starting the cleaning from the very beginning of the stream, it does not take into account the fact we can join in the middle of the stream.
For a @0 image that's fine, however for a off/on image it can screw everything up and produce the results I have been seeing.
For instance, minSubscriberPosition for a recreated stream can map to the first term buffer which will be cleaned by driver conductor...

I have created a PR (https://github.com/real-logic/Aeron/pull/270) that seems to fix the issue (unless I'm missing something else).

**Comment by mjpt777** [comment]
Thanks for tracking this down. I believe you found an interesting bug. This would have been introduced by the incremental cleaning.

**Comment by grzegorz-gierlach** [comment]
Becoming an Aeron expert ;)

**Comment by mjpt777** [comment]
It is great seeing others help :-)
