### ISSUE TITLE
Possible memory visibility issue in  PublicationImage

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#271]
We believe we found some misbehavior with respect to the memory visibility of the buffer that Aeron returns while polling a subscription. We are also linking a barebones setup that is able to reproduce the misbehavior, can be found here.

https://github.com/dkonik/AeronTesting

The Behavior:

We observe that the bytes inside the buffer that is passed to the FragmentHandler while polling seem to (on occasion) change inside the handler. More specifically, at the beginning of the FragmentHandler we call buffer.getLong(offset), then we do some work, then at the end of the FragmentHandler we call buffer.getLong() again and the value that is returned is not the same as the first time getLong was called. For example, with the following code in the FragmentHandler:

```java
final long receivedIndex = buffer.getLong(offset);

if (receivedIndex != previous + 1) {
	System.out.println("MISSED MESSAGE AT INDEX: " + previous + "->" + receivedIndex);
	System.out.printf("%x %x %x %x %x %x %x %x\n", buffer.getByte(offset), buffer.getByte(offset + 1),
			buffer.getByte(offset + 2), buffer.getByte(offset + 3), buffer.getByte(offset + 4),
			buffer.getByte(offset + 5), buffer.getByte(offset + 6), buffer.getByte(offset + 7),
			buffer.getByte(offset + 8));
	System.out.println("Offset(again): " + buffer.getLong(offset) + "\n");
}

++messageNum;
previous = receivedIndex;
```

We get output of:

```
MISSED MESSAGE AT INDEX: 188610->96091
c3 e0 2 0 0 0 0 0

Offset(again): 188611


MISSED MESSAGE AT INDEX: 96091->188612

c4 e0 2 0 0 0 0 0

Offset(again): 188612


MISSED MESSAGE AT INDEX: 371101->278582

9e a9 5 0 0 0 0 0

Offset(again): 371102


MISSED MESSAGE AT INDEX: 278582->371103

9f a9 5 0 0 0 0 0

Offset(again): 371103
```

As you can see, for the first one, you would expect the returned value to be 188610 + 1, but the first time getLong is called a different number is returned (96091). Afterwards, when getLong is called again, the correct value is returned, implying that Aeron is giving us a buffer before the memory contained by that buffer is fully visible in all threads.

Additionally, we have only observed this while sending 5-10 packets back to back as fast as possible (as opposed to say, a one packet at a time ping-pong style). 

System Configurations:

Both boxes are Haswells with a direct connection between them (no switch), and rhel 7 version 3.10.0-327.22.2.el7.x86_64

**Comment by dkonik** [comment]
We are using the Oracle JRE 1.8.0_92-x86_64 (bug also manifests itself on the JDK of the same verison) and we’re building the latest HEAD of Aeron (25ab0b382c4784636929ce032c897d2c41e23562).

**Comment by franz1981** [comment]
Hi guys,

Only as hint...
The producer in the test put the new values using:

atomicBuffer.putLong(0, i);

or inlined:

UNSAFE.putLong(byteArray, addressOffset + index, bits);

At the end of the producer loop there is no esplicit release of the unsafe buffer, hence no direct usage of the byteBuffer reference (nor for reading/wrinting) between the instantiation and the end of the call.  
I do not see (and i can be wrong!) any good reason why the compiler has to retain that (direct) ByteBuffer and probably there are chances it will be released at some point.
Maybe the issue is not on the consumer side...but on the producer...

**Comment by mjpt777** [comment]
@franz1981 I don't get your point on the producer side. The code looks fine to me. The direct buffer is referenced from within the atomicBuffer and it is used repeatedly within the test.

What do you mean by "no esplicit release of the unsafe buffer"?

**Comment by franz1981** [comment]
@mjpt777 Sorry, i need to explain it better. 
About the explicit release of the unsafeBuffer I mean a call on Cleaner::clean against the direct buffer referenced into the unsafeBuffer.
AFAIK any usage of the byteBuffer field (including the mentioned "release" of it) after the loop is fine to tell the compiler to not collect it between all the puts and copyMemory inside the producer loop, because even if the unsafeBuffer instance is used,its byteBuffer field doesn't seem to have other uses after its instantiationn.
I'm reading all the source code with a smart phone and maybe I've missed other usages of that field or misunderstood how the liveness analysis of the compiler work for unused instance fields...

**Comment by mjpt777** [comment]
I've been able to recreate this once in an independent test. I have found a few issues in the referenced test. For example there are 9 bytes, and not 8, read in the printf output. Also System.exit is not a great way to shut down such a system. These issues should be independent.

**Comment by mjpt777** [comment]
@franz1981 I can make this test fail with the srcBuffer stored in a field of the class. See the commit https://github.com/real-logic/Aeron/commit/e22c98935ab94d892ffc3aad7bbb455d9442a9ee .

**Comment by mjpt777** [comment]
I've been playing with the test and if I create messages that align on rotation, i.e. 96 byte message length, then the bytes observed are the value in the term buffer from 3 terms previous. This suggests we have a problem with cleaning and observing the previous value within a message. Term length is 16MB.

```
Issue at message number transition: 534670 -> 141455
offset: 1329056
length: 96
expected bytes: 0 0 0 0 0 2 28 8f
received bytes: 0 0 0 0 0 0 28 8f
messageValue on second read: 534671
messageValue on third read: 534671
```

**Comment by franz1981** [comment]
@mjpt777 Thank you Martin to have used your time to test it! 
It is so aleatory to be sure at 100% and is difficult to say how long these "tricks" could work with a very smart compiler
They belong to the same family of the "padding tricks" :(

**Comment by mjpt777** [comment]
@franz1981 To be clear the issue does not seem to be what you have suggested. I don't see that as the problem. This is not a "trick".

**Comment by mjpt777** [comment]
For another data point, I cannot make the test fail on Windows 10.

**Comment by franz1981** [comment]
@mjpt777 I apologize, I have to be more precise with the terms! :)

**Comment by tmontgomery** [comment]
And another data point, I can't make the system test fail on Mac.

**Comment by mjpt777** [comment]
Also it does not seem to manifest if the driver is run in SHARED or SHARED_NETWORK threading mode which might mean a resource starvation issue.

**Comment by mjpt777** [comment]
I don't think it is a partial write problem given this failure.

The difference between the expected message and the first read is exactly 3 terms worth of messages.

Three terms:
1024 * 1024 * 16 * 3  = 50,331,648

Message number difference:
736981 - 343765 = 393216
393216 * 128 = 50,331,648

```
Issue at message number transition: 736980 -> 343765
offset: 10447520
length: 96
expected bytes: 0 0 0 0 0 2 3e d5
received bytes:  0 0 0 0 0 1 3e d5
expected bits: 10110011111011010101
received bits:    1010011111011010101
messageValue on second read: 736981
messageValue on third read: 736981
```

**Comment by mjpt777** [comment]
Had another failure with exactly 3 terms difference again.

```
Issue at message number transition: 787265 -> 394050
offset: 106784
length: 96
expected bytes: 0 0 0 0 0 3 3 42
received bytes: 0 0 0 0 0 1 3 42
expected bits: 11000000001101000010
received bits: 1100000001101000010
messageValue on second read: 787266
messageValue on third read: 787266
```

**Comment by tmontgomery** [comment]
Same here.

**Comment by tmontgomery** [comment]
The last time the buffer was read is the value there. So, it definitely looks like a stale value. Although, you would think it would have been cleaned.

**Comment by mjpt777** [comment]
If I rewrite the `TermRebuilder` code to do the following it still fails which further suggests it is the zeroing out of the memory which is the culprit or the getLong returning a stale value.

```java
    public static void insert(final UnsafeBuffer termBuffer, final int termOffset, final UnsafeBuffer packet, final int length)
    {
        /*
        final int firstFrameLength = packet.getInt(0, LITTLE_ENDIAN);
        packet.putInt(0, 0);
        UnsafeAccess.UNSAFE.storeFence();

        termBuffer.putBytes(termOffset, packet, 0, length);
        frameLengthOrdered(termBuffer, termOffset, firstFrameLength);
        */

        for (int i = 8; i < length; i += 8)
        {
            termBuffer.putLong(termOffset + i, packet.getLong(i));
        }

        termBuffer.putLongOrdered(termOffset, packet.getLong(0));
    }
```

```
Issue at message number transition: 560123 -> 166908
offset: 4587040
length: 96
expected bytes: 0 0 0 0 0 2 8b fc
received bytes: 0 0 0 0 0 0 8b fc
expected bits: 10001000101111111100
received bits: 101000101111111100
messageValue on second read: 560124
messageValue on third read: 560124
```

**Comment by tmontgomery** [comment]
@kdkavanagh With the latest change and release, this is worth retesting.

**Comment by kdkavanagh** [comment]
Thanks, will give it a try in the next few days and report back here

**Comment by kdkavanagh** [comment]
Apologies for the delayed feedback - Looks good.  Thanks guys.

**Comment by mjpt777** [comment]
@kdkavanagh Thanks for re-testing.
