### ISSUE TITLE
C++ compilation fails on Windows

### ISSUE THREAD

**Issue by andrey-lv** [real-logic/aeron#273]
Attempt to build C++ API of Aeron (version 1.0.1) fails on Windows. I have tried both Visual Studio 2013 and 2015.

Here is the part of the cppbuild.cmd output:

> d:\dev\libs\aeron\aeron\aeron-client\src\main\cpp\concurrent\CountersReader.h(160): error C2070: 'unknown': illegal sizeof operand [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> d:\dev\libs\aeron\aeron\aeron-client\src\main\cpp\concurrent\CountersReader.h(161): error C2070: 'unknown': illegal sizeof operand [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> d:\dev\libs\aeron\aeron\aeron-client\src\main\cpp\concurrent\CountersReader.h(104): error C2070: 'unknown': illegal sizeof operand [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\concurrent/CountersManager.h(71): error C2070: 'unknown': illegal sizeof operand [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]

and here is the part of the cppbuild-vs2015.cmd output:

> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(83): error C2511: 'aeron::util::MemoryMappedFile::ptr_t aeron::util::MemoryMappedFile::mapExisting(const char *,off_t,size_t)': overloaded member function not found in 'aeron::util::MemoryMappedFile' [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
>   d:\dev\libs\aeron\aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.h(31): note: see declaration of 'aeron::util::MemoryMappedFile'
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(180): error C2065: 'fd': undeclared identifier [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(180): error C2228: left of '.handle' must have class/struct/union [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
>   D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(180): note: type is 'unknown-type'
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(183): error C2065: 'filename': undeclared identifier [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(183): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'aeron::util::IOException' [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
>   D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(183): note: No constructor could take the source type, or constructor overload resolution was ambiguous
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(190): error C2065: 'fd': undeclared identifier [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(195): error C2065: 'filename': undeclared identifier [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
> D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(195): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'aeron::util::IOException' [D:\Dev\libs\aeron\Aeron\cppbuild\Release\aeron-client\src\main\cpp\aeron_client.vcxproj]
>   D:\Dev\libs\aeron\Aeron\aeron-client\src\main\cpp\util\MemoryMappedFile.cpp(195): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by tmontgomery** [comment]
Windows is a low priority platform at the moment. So, will get to it when we can.

**Comment by nicklauslittle** [comment]
#315 should fix this.

**Comment by helmesjo** [comment]
Still fails (version 1.10.1) on VS 12.
