### ISSUE TITLE
Application error recovery best practices

### ISSUE THREAD

**Issue by rodneyparnell** [real-logic/Aeron#274]
Hi

My scenario has multiple linux hosts: one host has a server process accepting subscriptions via aeron:udp from multiple client processes on remote hosts. The central host then publishes data updates to those clients (publish / subscribe) via aeron:udp. In this question, I am using the term pub/sub subscriber to distinguish application level subscriber from Aeron's Subscriber.

I would like to understand the best way to detect and handle process-level error recovery properly. Scenarios such as

- the pub/sub publisher process restarts - how do the pub/sub subscribers detect it, and what cleanup should be done before resubscribing?
- a pub/sub subscriber process restarts - how does the pub/sub publisher detect the lost subscription, and what cleanup should be done for that subscription?
- the media driver gets shut down - should all processes start polling for media driver presence then reestablish pub/sub subscriptions

This all comes down to error handling patterns. I would prefer for my processes to be able to recover and reconnect under these scenarios rather than require process restarts.

Can you point me to code samples or words that cover this kind of recovery best practice?
Thanks.

**Comment by tmontgomery** [comment]
For Aeron media driver shutdown, the best way to handle that is to restart the Aeron instances and that means restarting the Publications and Subscriptions they use as well. Consider it a hard error and a total restart. The Aeron errorHandler will deliver errors for media driver liveness, etc. so the application does not have to.

For application pub/sub process death, it depends on the applications semantics that are required. If the application must know about live/dead publications, then application level heartbeats are needed. If the application must know about live/dead subscriptions, then application level group membership semantics should be provided. Both of those are best handled as protocols on top of Aeron.

Aeron will work just fine with Subscriptions and Publications that go away. Unless the Subscription application is doing Image polling directly, it does not need to do anything special. All new instances of pubs and subs are handled internally just fine. Depending on the timing of the Publication process death and restart, a Subscription may or may not see the restart as a new Publication. A Subscription is not tracked by a Publication, so there are no concerns for a Publication application with a Subscription that goes away.

**Comment by rodneyparnell** [comment]
Thank you Todd for your guidance. If I may probe you further, what is your opinion on the paradigm? My feeling is that it brings a lot of stateful handing in the server, tracking subscribers and their last-sent offset in the notification stream. Plus monitoring subscriber health and then removing the dead - a bit like writing a garbage collector, and we all know easy that is to get right! 

I am tempted therefore to move to a polling model with the 'subscriber' passing the last-sent offset back to the server to ask for more. Of course there are network overheads with redundant polling but on the other hand no heartbeats or monitoring is required and the server can become stateless, or at least hold no client state. Plus the polling paradigm is inherently self-limiting - the client only polls as often as it is able.

What do you think. Do the advantages of polling outweigh the networking impact?
Many thanks!!

**Comment by tmontgomery** [comment]
From my experience, if you are tracking subscriber state in the publisher, you are most likely too tightly coupling them together.

The polling model you mention can work fine. Would very much depend on what you are trying to achieve.

Often the desire to know the state of something and track it somewhere else doesn't pay for itself in any real way. i.e. it's just wasted work in the grand scheme of the system itself.

**Comment by rodneyparnell** [comment]
By tracking subscriber state, I meant only keeping a list of subscribers and where they are up to. In my app I can't use a multicast publication mechanism since each subscriber will be at a slightly different point in the notification stream. But even though it is only a small amount of state, it still brings in the need for monitoring subscriber health and garbage collecting them :(  I think I will go with the polling mechanism and use batching of notifications in response to the poll - ie all notifications since last time.

Thanks for your thoughts.
