### ISSUE TITLE
cnc.dat is not fully unmapped and hence it cannot be removed until JVM exit

### ISSUE THREAD

**Issue by drewhk** [real-logic/Aeron#276]
According to my investigation with VMMap (https://technet.microsoft.com/en-us/sysinternals/vmmap.aspx) it looks like `cnc.dat` is not fully unmapped which prevents deletion on Windows. 

According to the source (https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/MediaDriver.java#L1229) not every part of the file is unmapped (unless I missed something).

Can this be fixed somehow? Maybe make this behavior configurable? The main issue is that in our test suite it generates garbage files on all Windows test systems and there is no gain in keeping the CNC file for the tests.

**Comment by mjpt777** [comment]
The MediaDriver and AeronClients map the same file. Have they all unmapped it?

**Comment by drewhk** [comment]
`close()` has been called on both, yes. The tool I used cannot give me more information as it can only report the JVM itself but not say what holds it inside...

**Comment by drewhk** [comment]
do you map multiple regions separately from that file?

**Comment by mjpt777** [comment]
It should be a single mapping for the whole file. It is not that large.

**Comment by drewhk** [comment]
![cnc_mapped](https://cloud.githubusercontent.com/assets/932285/18349354/459e74dc-75d1-11e6-98e6-3d35bf651714.png)

Above is the screenshot. It is taken after both the mediaDriver and client have been closed. I put in there a Thread.sleep() after those calls when I took the screenshot. All other files were properly unmapped. (There are multiple clients and drivers running in the test, hence the multiple files)

**Comment by mjpt777** [comment]
I've looked at the code and the MediaDriver does unmap the file in the close() operation. The system tests need to unmap for this to work, and it does on windows.

Is it possible create a standalone test case?

**Comment by drewhk** [comment]
It is definitely weird. I am reusing your same mapping support for a different purpose. I unmap my stuff and things work fine (file is deleted). What is even weirder is that the cnc.dat mapping *is* dropped after the test itself exits. Which is in the same JVM (sbt REPL). It is also true that both `close()` calls have been invoked. Investigating further, if I find a reproducer I will keep this ticket posted.

**Comment by drewhk** [comment]
Ok, confirmed there is some other stuff holding on to the cnc.dat file. Nothing to see here :)
