### ISSUE TITLE
[C++]: Publication class destructor terminates the whole process when MediaDriver is inactive

### ISSUE THREAD

**Issue by andrey-lv** [real-logic/Aeron#282]
In C++ client application I am trying to recover from the MediaDriver shutdown situation. I've looked at the advise given in #274 and my code attempts to clean its publication and Aeron instances. But destructor of aeron::Publication class throws an aeron::DriverTimeoutException which leads to the immediate termination of the process.
Is there a way to handle the MediaDriver shutdown situation without the process termination happening?

**Comment by tmontgomery** [comment]
what about catching the exception?

**Comment by BardurArantsson** [comment]
Exceptions in destructors automatically abort the program. (Per spec.)

**Comment by andrey-lv** [comment]
It is impossible to catch the exception since user-defined destructors in C++11 are noexcept(true) by default. The program aborts immediately.

**Comment by tmontgomery** [comment]
I think I have a way to handle this a little cleaner. Will self-assign and look when I can.

**Comment by tmontgomery** [comment]
Should not throw now. Instead calls the error handler. So, should be fine.
