### ISSUE TITLE
Document the semantics of multiple subscriptions

### ISSUE THREAD

**Issue by lbradstreet** [real-logic/aeron#286]
I found it quite intuitive to understand the single subscription case, and the documentation was sufficient, however I think it would be useful to include a short description of the multiple subscription case (for same channel / stream / media driver).

Some points I would have found useful include:
1. When a new image is added to the subscriptions, at what position does it start?
   For the single subscriber case, this is the beginning of the image since the publication's offer will not succeed until the image has a subscriber?
   For the multiple subscriber case, it joins at the position of the publisher (skipping any messages received before the image was made available to the subscription). 
2. If you have two subscriptions, and an image becomes available, is it possible that they will join at different positions?
   I believe the answer here is yes, because the image will become available to each at different times. 
3. How does flow control work in the multiple subscriber case?
   This is fairly intuitive, but it might be helpful to state that the position of the slowest subscriber is important.

Thanks

**Comment by nitsanw** [comment]
@mjpt777 please add a new issue tag for documentation

**Comment by mjpt777** [comment]
@nitsanw Added the issue label.
