### ISSUE TITLE
C++ Publication::tryClaim max payload length check bug

### ISSUE THREAD

**Issue by ancapdev** [real-logic/Aeron#291]
I haven't used this API yet, but reading over it in preparation I think I've discovered a bug in the max payload length check.

```checkForMaxMessageLength()``` checks, as the name suggests, ```m_maxMessageLength```, but prints in the error message ```m_maxPayloadLength```.
```Cpp
    void checkForMaxMessageLength(const util::index_t length)
    {
        if (length > m_maxMessageLength)
        {
            throw util::IllegalStateException(
                util::strPrintf("Encoded message exceeds maxMessageLength of %d, length=%d",
                    m_maxPayloadLength, length), SOURCEINFO);
        }
    }
```

More seriously, unless I've missed something, ```tryClaim()``` only calls ```checkForMaxMessageLength()``` (https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/cpp/Publication.h#L337) which will not check for max payload length as documented. I don't know what happens here when this calls into ```TermAppender::claim()```, but this inconsistent use of max message length and max payload length doesn't seem right.

**Comment by mjpt777** [comment]
Yes you are correct. This code did not reflect the same semantics at the Java client. Thanks!

**Comment by ancapdev** [comment]
No worries. Thanks for the quick fix!
