### ISSUE TITLE
Callback hook in addition to `offer()` at al.

### ISSUE THREAD

**Issue by drewhk** [real-logic/Aeron#295]
Is it possible to add an additional API that allows registration of a callback after several failed `offer()` calls? In particular, in an idle period, polling over `offer()` has its costs even with exponential backoff. It would be nice if after certain rounds of spinning I could register a callback that is called once offer() has a chance again to succeed (does not need to _guarantee_ that it succeeds, races are fine as it will start spinning for a while again).

The benefit is that any old spinning code will keep working and will likely not suffer penalties, while less aggressive strategies could be implemented for other use cases using the explicit readiness signal. 

I am not sure if providing such a callback is possible internally, but it would be nice if it could be done with minimal cost.

Btw, the same is also useful for the `poll()` side, too.

**Comment by mjpt777** [comment]
Doing something like this is difficult without a performance impact. On the offer side you are being back pressured and thus should do other work or sleep/yield until the backlog drains. If this is a regular problem then you have an imbalanced system and need to look at your design more holistically.

The poll side is more interesting. With the current design it is difficult to do this efficiently. However it would be possible to build a lightweight client for this type of implementation that follows the Aeron media protocol. This could be less resource intensive but with performance costs. Unless someone is willing to sponsor such an implementation then we are unlikely to do it.
