### ISSUE TITLE
Tips/docs to identify no connectivity between publisher and subscriber

### ISSUE THREAD

**Issue by JatinderSingh** [real-logic/Aeron#298]
I was trying simple publisher/subscriber example between 2 servers in aws.
Subscriber listening on ip "0.0.0.0" and publisher sending on public ip of same. 

I have established that connectivity between those instances is present by sending texts on udp through netcat on same port, Which worked as expected. Initially i thought this might some os/config related issue netcat on udp should also not be working in that case. Any hint to identify the problem here.

**Comment by JatinderSingh** [comment]
Hi issue can be reproduced with ami id CentOS-6.5-GA-03.3-f4325b48-37b0-405a-9847-236c64622e3e-ami-6be4dc02.2 (ami-8997afe0).

Settings included iptables off.
selinux off 
with above nc was able to reach to server on udp but Aeron was generating not connected errors. 

I had moved to different ami where things aeron connectivity is working for me, But it would be nice to know steps to identify/debug the issue in general.

**Comment by mjpt777** [comment]
Support can be purchased for Aeron.
