### ISSUE TITLE
about, aeron performance

### ISSUE THREAD

**Issue by zhao141** [real-logic/Aeron#299]
at LAN. 2w/sec msg. embed server has 300ms delayed. is normal?

**Comment by zhao141** [comment]
local  has 14ms delayed

**Comment by mjpt777** [comment]
What do you mean by "2w/sec"?

The latency of message transfer is effected by idle strategies and if they are backing off. With spinning strategies and sufficient CPU resource Aeron adds less than 1 microsecond to one way latency between machines.

https://github.com/real-logic/Aeron/blob/master/aeron-samples/src/main/java/io/aeron/samples/LowLatencyMediaDriver.java

**Comment by tmontgomery** [comment]
If you mean latency while sending at a certain throughput rate (like 2M msgs/sec), then latency will increase slightly. But it depends on if the Publication is being flow controlled. If flow controlled, latency will increase quite a bit because the Subscription(s) are not keeping up.

**Comment by zhao141** [comment]
sorry. aeron is good! ntp time server is delayed
