### ISSUE TITLE
Review potential length for a channel string given projected usage

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#303]
The current potential length for a channel string representation may not be sufficiently long to encode the typical hostnames and additional URI parameters.

**Comment by nitsanw** [comment]
In archiver there's an assumption that channel length is sub (4K - change).

**Comment by mjpt777** [comment]
It has been increased to 380 with this commit to Agrona.

https://github.com/real-logic/Agrona/commit/645f4f3ad91039cf76b71fe5d27fb135739862a3
