### ISSUE TITLE
Any way to close a subscription - what if subscriber needs to exit?

### ISSUE THREAD

**Issue by julianrz** [real-logic/Aeron#304]
I have set up a publication-thread and two subscription-threads, working off a embedded media driver in the same process

When one of the subscriber threads stops polling, publication.offer() starts returning BACK_PRESSURED

Suppose the thread is dead, or in a more complex case, subscriber is a process that has crashed. What is the recovery mechanism? I want other subscribers to continue getting messages...

Also, found no way to unsubscribe, closing subscription causes offer() to return CLOSED?? It is not the publication that is closed, but a one of two subscriptions... Unsubscribe would be a way to implement a graceful shutdown...

**Comment by mjpt777** [comment]
If a process crashes and it is external to the media driver then it will timeout and resources will be garbage collected. 

You can call `Subscription.close()` in Java and it will reduce the reference count in the driver and if no remaining references exist then it will be reaped. The C++ client does similar with the RAII pattern.

**Comment by julianrz** [comment]
I will try with external process, but still feels odd that it behaves differently when subscriber is external. Also I do see subscription.close() have an unintended effect on publication - causing publish() return CLOSED when one of the subscribers is still actively polling - is this also different with external subscriber?

**Comment by mjpt777** [comment]
The close behaviour is the same if the media driver is embedded or external. The liveness tracking is on the client process, not individual threads which would not be possible. Can you provided a worked example that illustrates the problem you are observing?

**Comment by julianrz** [comment]
I cannot reproduce the CLOSE status, maybe I was playing in debugger and publisher has timed out on me. But it is interesting that I can reproduce publisher being able to publish long after all subscriptions are closed. I expected NOT_CONNECTED returned in this case. In the implementation code it is not checking subscriptions till position reaches positionLimit, which is large (in my case 8519552, while current position 985248). Calling code will assume that all those messages have reached consumers, but they reached nobody. Sample code attached
Also, when you comment out the 100ms delay in publisher loop, it starts returning BACK_PRESSURED in a loop. It thinks there are subscribers, but there are none...

**Comment by julianrz** [comment]
Attched code 
[Main.java.zip](https://github.com/real-logic/Aeron/files/706204/Main.java.zip)

**Comment by mjpt777** [comment]
You cannot assume that a message will reach a subscriber just because it was successfully offered. At high rates you could fill the buffer before a timeout was even reached with the subscriber already well dead. If you want to be sure you need an application level protocol. TCP would have similar but slightly different issues.

We could look at clamping back the positionLimit to 0 if is over a timeout on getting status messages which would detect it a sooner at slow rates. However the fundamental issue still exists that you need an application level protocol to ensure liveness at that level.

**Comment by julianrz** [comment]
Perfectly understandable, and a silly assumption on my side. I find aeron to be a very interesting toolkit, would be nice to have a writeup on the use cases, limitations and best practices, so that it captures a wider audience
