### ISSUE TITLE
about aeronEmbedServer

### ISSUE THREAD

**Issue by zhao141** [real-logic/Aeron#305]
server is not have isStart method?.
 i create embedServer. use client connetion,occasionally can not connection to server. publication status is not_connetion.

**Comment by zhao141** [comment]
@mjpt777  help me?

**Comment by mjpt777** [comment]
Please provide a worked example. This is insufficient information to recreate.

**Comment by zhao141** [comment]
**client create:**
       `final Aeron.Context actx = new Aeron.Context();
        if (embedded) {
            actx.aeronDirectoryName(EmbeddedMediaDriver.getInstance().aeronDirectoryName());
        }
        actx.availableImageHandler(this::availableImageHandler);
        actx.unavailableImageHandler(this::unavailableImage);
        actx.errorHandler(t -> error("an exception occurred", t));
        aeron = Aeron.connect(actx);`
        `aeron.addPublication(channel, streamId)`

**Comment by zhao141** [comment]
> 

```
public static void offer(Publication publication, BufferFiller fillBuffer, int length, int timeout,
                             TimeUnit timeUnit) {
        if (publication.isClosed()) {
            throw new NotConnectedException();
        }

        final MutableDirectBuffer buffer = getDirectBuffer(length);
        fillBuffer.fill(0, buffer);
        final long start = System.nanoTime();
        do {
            final long current = System.nanoTime();
            if ((current - start) > timeUnit.toNanos(timeout)) {
                throw new TimedOutException();
            }

            final long offer = publication.offer(buffer);
            if (offer >= 0) {
                break;
            } else if (Publication.NOT_CONNECTED == offer) {
                throw new NotConnectedException();
            }
        } while (true);

        recycleDirectBuffer(buffer);
    }
```


this method, throw NotConnectedException

**Comment by mjpt777** [comment]
This will be the result of no Subscribers being yet connected. Publishers need to have one or more Subscribers before they can publish.

**Comment by zhao141** [comment]
i can`t known my subscribers is up. although ,i create.

appear this exception, i`m try restart subscriber. publisher still not connection.

subscriber not stop, try restart publisher. connection is ok.

**Comment by mjpt777** [comment]
Messages can only flow when both the publisher and subscriber are connected. This is normal behaviour and very similar to TCP. Aeron is not a messaging system that allows messages to be sent when a connection is not in place.
