### ISSUE TITLE
BasicPublisher not noticing removal of all active subscribers

### ISSUE THREAD

**Issue by nikkekin** [real-logic/Aeron#306]
Hey,

First, thanks for a great project.

I just noticed yesterday that after migrating from release 1.0.4 to 1.0.5 a publisher doesn't seem to anymore notice when all clients have been removed and a publication is not anymore receiving Status Messages from subscribers.

I have checked that this can be replicated on Windows 7 by just running the BasicPublisher and BasicSubscriber as follows

java -cp aeron-all-1.0.4.jar -Daeron.sample.embeddedMediaDriver=true io.aeron.samples.BasicPublisher

and 

java -cp aeron-all-1.0.4.jar -Daeron.sample.embeddedMediaDriver=true io.aeron.samples.BasicSubscriber

When disconnecting the BasicSubscriber, with release 1.0.4 the publisher will after five seconds notice and print "No active subscribers detected":

offering 7/1000000yay!
offering 8/1000000yay!
offering 9/1000000yay!
offering 10/1000000yay!
offering 11/1000000yay!
offering 12/1000000yay!
offering 13/1000000yay!
offering 14/1000000yay!
No active subscribers detected
offering 15/1000000yay!
No active subscribers detected

While with release 1.0.5 it will just not do so. I did also try running without embedded media driver, and that seemed to behave in a similar manner.

I have looked into the cnc.dat using the AeronStat from samples as well and it shows how the Publisher does stop receiving the status messages when the subscriber disconnects, so that part appears to be working correctly.

I also debugged it, and to me it looked like that in io.aeron.Publication method isConnected() seems to be getting a flawed time from the call to 

clientConductor.isPublicationConnected(timeOfLastStatusMessage(logMetaDataBuffer))

Could be also that I have understood something wrong being new to working with the project, so I would appreciate hearing what you think about this.

-niklas

**Comment by lightyang** [comment]
I can confirm the issue. This seems to be originated from 0ff5c26, which introduced nanosecond-precision time, while the ClientConductor (and maybe other part of the system) still uses ms precision.
```java
    boolean isPublicationConnected(final long timeOfLastStatusMessage)
    {
        return epochClock.time() <= (timeOfLastStatusMessage + publicationConnectionTimeoutMs);
    }
```

**Comment by nitsanw** [comment]
Thanks for reporting, I have reproduced the issue and can see the mismatch in time source as reported by @lightyang .
I'll fix shortly.

**Comment by tmontgomery** [comment]
Unless I am missing something, the commit only removed the unused epochClock. Something else before then removed using the epochClock itself on SMs.

The key is the use of wall clock time between the client and driver. The SM time must be in wall clock time.

**Comment by sthornington** [comment]
Does this have any relation to seeing orphaned deleted images?  I mentioned my issue in glitter but haven't been able to reproduce outside of our lossy environment...

**Comment by tmontgomery** [comment]
@sthornington I don't think it would, no.

**Comment by nikkekin** [comment]
Thanks for looking this fast, and the fact that the problem is in the timeOfLastStatusMessage makes sense to me at least.

I only saw the problem with the recent 1.0.5 release, so @sthornington unless you've been on 1.0.5 then I doubt it has anything to do with the orphaned deleted images.

**Comment by tmontgomery** [comment]
@nikkekin correct. The reason I tracked down the commit was to see what was impacted. 1.0.5 should be the only release effected. Aside from the head.

**Comment by sthornington** [comment]
We did switch to 1.0.5, but I couldn't confirm that the issue we have didn't happen on 1.0.4 without downgrading, which I am considering.
