### ISSUE TITLE
bug: in rancher use hostname can`t connection

### ISSUE THREAD

**Issue by zhao141** [real-logic/Aeron#307]
use rancher manage docker,channel use hostname can`t connection.but use rancher LAN ip is ok.
rancher:[https://github.com/rancher/rancher](url)

**Comment by nitsanw** [comment]
Can you please provide a procedure for reproducing the issue as well as further details? From description it is not clear that this is an Aeron issue at all.

**Comment by zhao141** [comment]
details?
just only use rancher hostname not connection. if use LAN ip connection success.
i use my project.and aeron example ping/pong.and simplePub/Sub. the issuesis still

i`m use netty udp try. use hostname is success. so.i guess is aeron issues

**Comment by nitsanw** [comment]
OK, I'm not familiar with rancher.
Can you reproduce issue outside of rancher? alternatively can you provide an example I could run to reproduce issue?
Thanks
