### ISSUE TITLE
Can't set aeron directory using the aeron-stat script

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/aeron#308]
You need to pass a -Daeron.dir in order to specify the directory for `AeronStat` to look at, but if I'm looking at the aeron-stat script correctly all arguments passed are forwarded on after the main class. Java doesn't pass -D properties on the commandline after the classname of the main class to be run. So there appears to be no way of setting it using the script. Am I missing something?

Happy to submit a fix, just want to make sure I'm not being dumb first.

**Comment by mjpt777** [comment]
The script is there as a simple example. If we want to separate out the system params for Java from the real args then please submit a fix.

**Comment by mjpt777** [comment]
This can now be done by setting a `JVM_OPTS` environment variable. This gets added at the end of the jvm options in all the sample scripts for both bash and windows script files.

```bash
    $ export JVM_OPTS=-Daeron.dir=path/to/aeron/directory
    $ aeron-stat
```
