### ISSUE TITLE
Image availability handlers on a subscription level

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Aeron#312]
It would be good to have a means to be notified on new images and handle their created/closed events from some sort of drain/poll API. E.g.
```
 subscription.pollNewImages(newImageHandler);
```
The usecase I have is where I need to handle images as sessions for a service request listener.

**Comment by RichardWarburton** [comment]
I appreciate that this isn't exactly what you're looking for, but just in case you aren't aware of it there is an AvailableImageHandler that can be registered on a per-client basis. You should be able to implement the desired functionality on top of that.

**Comment by nitsanw** [comment]
I'm aware of it and using it, but it's a bit clumsy.

**Comment by mjpt777** [comment]
+1

Maybe a signature more like

`Subscription.availableImageHandler(handler)` to be more consistent with existing API in the context.

**Comment by nitsanw** [comment]
The semantics I'm looking for are single consumption, so an image is not processed twice. Since subscriptions are not meant for concurrent usage it's not a big overhead. This implies a further managed list of available images...

**Comment by tmontgomery** [comment]
@nitsanw would it be better to have the calling thread be the `Subscription.poll` thread?

**Comment by nitsanw** [comment]
@tmontgomery I think that since ```Subscription``` is not thread safe we can assume it's the same thread.

**Comment by mjpt777** [comment]
In addition to calling the registered handler in the context, we could iterate over the active subscriptions and call the handler of any that are registered when new image comes in which match the subscription.

**Comment by nitsanw** [comment]
@mjpt777 the context handler is a callback, this API is easy to match (no extra data structure to match). It does introduce a race with Subscription creation:
```
s = aeron.addSubscription();
// an image became available
s.availableImageHandler(handler);
```
Are we happy to go with the callback approach?
To avoid the race above we would need to have the handler on construction.

**Comment by mjpt777** [comment]
We could provide an overload to `addSubscription()` that takes the handler to avoid the race and it can be a final field this way.

**Comment by nitsanw** [comment]
Calls to the handler happen from an "arbitrary" thread. I think it needs to be made obvious in the docs for the global call back as well.

**Comment by mjpt777** [comment]
Agreed.

**Comment by nitsanw** [comment]
This has been implemented (twice due to real world concurrency issue):
https://github.com/real-logic/Aeron/commit/dd8556292d899a6e9e2e696d2c77d58a4ea86ab0
https://github.com/real-logic/Aeron/commit/919064df7e9189d0f6df6005e7f2ccbb72cbd7d9
