### ISSUE TITLE
Notify of NOT_CONNECTED sooner on a low throughput connection

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#314]
Notify a low throughput publisher that it is no longer connected to its subscribers sooner.

This can be achieved by setting the publication limit to 0 if status message timeout has been reached.

**Comment by mjpt777** [comment]
@tmontgomery it would be good to get a review of this.

**Comment by tmontgomery** [comment]
This should be fine. Looks good. 👍
