### ISSUE TITLE
Timing issue in BasicPublisher

### ISSUE THREAD

**Issue by aslondon** [real-logic/Aeron#321]
Hi,

I'm totally new to Aeron so apologies if it's a silly question (I did search through the issues but I couldn't find anything relevant and I can't access gitter from behind my company firewall).

Just started playing around with the examples and I found that when running `BasicPublisher`, the first message is always lost, after which all the others go through successfully:

![BasicPublisher](https://cloud.githubusercontent.com/assets/25531708/23548352/081a0352-ffff-11e6-9a2d-dfcda4a3eca0.png)

![BasicSubscriber](https://cloud.githubusercontent.com/assets/25531708/23548520/ca6df7c4-ffff-11e6-9821-b6f755d12c07.png)

If however I add a `sleep` in between `addPublication` and the first `offer` everything works fine:

![CodeWithSleep](https://cloud.githubusercontent.com/assets/25531708/23548128/f878afb2-fffd-11e6-9412-390c4e98c21e.png)

![BasicPublisherWithSleep](https://cloud.githubusercontent.com/assets/25531708/23548487/a7595d3c-ffff-11e6-9021-2d124fa37c07.png)

This happens whether or not I use an embedded media driver.

Is this expected behaviour?

I'm running on my Windows 7 box, Java 1.8.0_101. I've literally just pulled from the repo so should be the very latest Aeron version.

Many thanks
AS

**Comment by mjpt777** [comment]
Are you checking the return code from the offer call? You cannot publish until a subscriber has connected.

**Comment by cesaref** [comment]
I'm going to guess that the publication hasn't been setup yet - addPublication is async, so you get an immediate return with the registration_id, but that doesn't mean it's available yet. You'll get a callback to the context with newPublication when it appears, which is likely to be a few ms after your addPublication call.

So, the first calls to offer are likely to return 'NOT_CONNECTED' until the publication is available. Spinning on the offer call waiting for a non-negative answer will resolve this, but by installing a context to handle the actual async callbacks you'll get something a little more understandable (in my opinion).

**Comment by cesaref** [comment]
I should add that this is why various examples instead go for the 'findPublication' route, waiting for it to succeed. It makes a sync call for test programs:

        // Find our request_publication
        while (!(publication_ = aeron_->findPublication(publication_id_)))
        {
            sleep(1);
        }

**Comment by mjpt777** [comment]
The Java is synchronous in setting up the Publication object, C++ is asynchronous. Nether is connected until a subscriber has sent a status message.

**Comment by aslondon** [comment]
Thanks both. 

@mjpt777 yes I am checking the return value, but I'm just printing it for now (as per Aeron's samples). You mention status messages but in my understanding no such message is sent from the receiver until the first publication.

So what is the recommended approach to avoid losing messages even when there are subscribers already listening? Shall I just capture the return value and retry the offering until it's no longer `NOT_CONNECTED` (or times out)? Or shall I come up with a "setup phase" of sorts before starting the actual publication?

Thanks again

**Comment by mjpt777** [comment]
If the offer returns a negative number then you try again. Keep trying until your first success. If you want to be explicit you could try something like the following:

```java
    while (!publication.isConnected())
    {
        Thread.sleep(1);
    }

    // Then continue but keep checking the return code
    // to see if you are back pressured or need to try again.
```
