### ISSUE TITLE
Aeron Java API - Publisher always gets BACK_PRESSURED error after ~500k messages

### ISSUE THREAD

**Issue by ilveraldino** [real-logic/Aeron#324]
I have a Publisher and Subscriber application using Aeron Java API on a Windows box.
They establish a communication via aeron:ipc protocol.

The Publisher keeps sending messages onto the channel successfully. 
After ~500k messages, BACK_PRESSURED error is returned and the Publisher is not able to sent any more messages. Every attempt afterwards will return a BACK_PRESSURED error.

The Subscriber is able to receive all the messages using the BusySpinIdleStrategy():

        final IdleStrategy idleStrategy = new BusySpinIdleStrategy();
        (new Thread(new Runnable() {
            public void run() {
                while (connection.isOn()) {
                    idleStrategy.idle(subscription.poll(fragmentHandler, 100));
                }
            }
        })).start();

The FragmentHandler simply gets the message bytes and does nothing:

        final FragmentHandler fragmentHandler = new FragmentAssembler(new FragmentHandler() {
            public void onFragment(DirectBuffer buffer, int offset, int length, Header header) {
                try {
                    final byte[] data = new byte[length];
                    buffer.getBytes(offset, data);
                    //Do nothing
                } catch(Exception e) {}
            }
        });

It seems the messages sent over the channel remain in there and prevents the Publisher to push new data.

Am I missing something?

**Comment by RichardWarburton** [comment]
There might be a few things going on here, without seeing your entire code its hard to know what exactly is wrong.

1. Do you have another subscription to the same stream? if you're not polling this subscription or it isn't making progress then you might get back pressured.

2. If you receive a back pressure message at your publisher then you need to retry that operation. Are you repeatedly retrying the offer? Does it eventually publish a message or is it just blocked?

**Comment by ilveraldino** [comment]
Hi, Richard.
Thanks for the input. At a closer look, I do have multiple subscriptions on the same stream, by mistake,
and this was creating the BACK_PRESSURE at Publisher side.

Thanks for your help!

**Comment by RichardWarburton** [comment]
Happy to be of help.
