### ISSUE TITLE
Monitor subscription pool from publisher

### ISSUE THREAD

**Issue by thagemann89** [real-logic/Aeron#325]
Hi,

Is there a way to monitor the pool of subscribers from the publishing side? Ideally I want to cache messages if a subscriber drops and start publishing once a subscriber connects again.

Thanks.

**Comment by tmontgomery** [comment]
You can use the NOT_CONNECTED return value from offer/tryClaim as a means to determine connectivity. However, if you need to know that a publisher is listening in a more detailed way, this is best handled as a protocol at the application layer.
