### ISSUE TITLE
Use cached clock values to reduce time system calls

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#330]
Update the clock times for epoch and nanos in a cached clock once per duty cycle to reduce calls to get the timestamp.

**Comment by mjpt777** [comment]
Complete with this commit. https://github.com/real-logic/aeron/commit/ed3901f3c80e627833f3092b16bd413055c2756c

**Comment by tmontgomery** [comment]
Still needed for C media driver, BTW.
