### ISSUE TITLE
Mark API intended for internal use (but marked public for any reason) with an @Internal annotation

### ISSUE THREAD

**Issue by nitsanw** [real-logic/aeron#332]
See the following:
https://poi.apache.org/apidocs/org/apache/poi/util/Internal.html

But it would be good to make this a source level only annotation, as to not bloat the bytecode.

**Comment by RichardWarburton** [comment]
+1 - mentioned this to @mjpt777 the other day.

I think its worth thinking about whether to mark things as internal that have to be public, or to mark things as exported and declare anything else internal.

**Comment by mjpt777** [comment]
Good idea.

**Comment by RichardWarburton** [comment]
Come to think of it, There is a pattern that I've used for this. Suppose you've got a class called `Foo` that has a method call `bar()` that you want to invoke from another package within your project, but not outside. You can make `bar()` package scoped, then create public class `FooAccessor`.

```
public class FooAccessor
{
  public void bar(Foo foo)
  {
    foo.bar();
  }
}
```

You need to make sure that you can only create FooAccessor from within your project - for example by taking a class literal of a package scoped class from your project and validating its name + package id in FooAccessor's constructor or by getting FooAccessor to register a reference to its constructor somewhere internal to your project but keeping a private constructor. It's a bit gnarly, but it does enable you to fake "friend" classes.

**Comment by tmontgomery** [comment]
How odd is it that C has a much better solution for this than Java....
