### ISSUE TITLE
Aeron performance help

### ISSUE THREAD

**Issue by GenuineJyn** [real-logic/Aeron#333]
According to https://github.com/real-logic/Aeron/wiki/Performance-Testing, I develop a c++ publisher and run it on a host, and develop a c++ subscriber on another host.  Then the performance is not very good. the size of  communication data is 5845200, and Retransmission is serious！ as follows is my ubuntu configuration:
net.core.rmem_default = 33554432
net.core.rmem_max = 33554432
net.core.wmem_default = 33554432
net.core.wmem_max = 33554432
net.ipv4.igmp_max_memberships = 20
net.ipv4.tcp_mem = 8388608      8388608 8388608
net.ipv4.tcp_rmem = 4096        87380   6291456
net.ipv4.tcp_wmem = 4096        65536   8388608
net.ipv4.udp_mem = 382437       509919  764874
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096

and media driver arguments as follows:
java -cp aeron-samples/build/libs/samples.jar \                                                     
     -Daeron.term.buffer.sparse.file=false \                                                        
     -Daeron.threading.mode=DEDICATED \                                                             
     -Daeron.conductor.idle.strategy=org.agrona.concurrent.BusySpinIdleStrategy \                   
     -Daeron.receiver.idle.strategy=org.agrona.concurrent.BusySpinIdleStrategy \                    
     -Daeron.sender.idle.strategy=org.agrona.concurrent.BusySpinIdleStrategy \                      
     -Daeron.term.buffer.length=536870912 \                                                         
     -Daeron.publication.term.window.length=536870912 \                                             
     -Daeron.rcv.initial.window.length=134217728 \                                                  
     -Daeron.mtu.length=16384 \                                                                     
     -Daeron.socket.so_sndbuf=134217728 \                                                           
     -Daeron.socket.so_rcvbuf=134217728 \                                                           
     -Dagrona.disable.bounds.checks=true \                                                          
     -Daeron.publication.unblock.timeout=1000 \                                                     
     -Daeron.publication.linger.timeout=1000 \                                                      
     -XX:BiasedLockingStartupDelay=0 \                                                              
     -XX:+UnlockDiagnosticVMOptions \                                                               
     -XX:GuaranteedSafepointInterval=300000 \                                                       
     io.aeron.driver.MediaDriver

**Comment by mjpt777** [comment]
What are throughput rate you are seeing? Can you provide a capture from AeronStat? How did you come up with the configuration options above as they are quite unusual? Please provide more information to the usage pattern.  Without more detail we cannot help.

**Comment by GenuineJyn** [comment]
publisher：
15:30:33 - Aeron Stat (CnC v5), client liveness 5,000,000,000 ns
===========================
  0:        5,165,587,488 - Bytes sent
  1:                    0 - Bytes received
  2:                    0 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:                    0 - Failed offers to DriverConductorProxy
  5:                    0 - NAKs sent
  6:                  522 - NAKs received
  7:                    0 - Status Messages sent
  8:                  284 - Status Messages received
  9:                   78 - Heartbeats sent
 10:                    0 - Heartbeats received
 11:                  469 - Retransmits sent
 12:                    0 - Flow control under runs
 13:                    0 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:           33,408,734 - Short sends
 17:                   90 - Client keep-alives
 18:                    1 - Sender flow control limits applied
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    0 - ControllableIdleStrategy status
 23:                    0 - Loss gap fills
 24:                    1 - snd-channel: aeron:udp?endpoint=10.160.113.243:40456
 25:        5,469,244,000 - pub-lmt: 1 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 
 26:        5,200,808,544 - snd-pos: 1 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 
 27:        5,335,026,272 - snd-lmt: 1 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 

java -cp aeron-samples/build/libs/samples.jar \
     -Daeron.term.buffer.sparse.file=false \
     -Daeron.term.buffer.length=536870912 \
     -Daeron.publication.term.window.length=536870912 \
     -Daeron.rcv.initial.window.length=134217728 \
     -Daeron.mtu.length=16384 \
     -Daeron.socket.so_sndbuf=212992 \
     -Daeron.socket.so_rcvbuf=212992 \
     -Dagrona.disable.bounds.checks=true \
     -XX:BiasedLockingStartupDelay=0 \
     -XX:+UnlockDiagnosticVMOptions \
     -XX:GuaranteedSafepointInterval=300000 \
     io.aeron.driver.MediaDriver

subscriber：

15:32:30 - Aeron Stat (CnC v5), client liveness 5,000,000,000 ns
===========================
  0:                    0 - Bytes sent
  1:        5,168,282,144 - Bytes received
  2:                    0 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:                    0 - Failed offers to DriverConductorProxy
  5:                  522 - NAKs sent
  6:                    0 - NAKs received
  7:                  335 - Status Messages sent
  8:                    0 - Status Messages received
  9:                    0 - Heartbeats sent
 10:                   81 - Heartbeats received
 11:                    0 - Retransmits sent
 12:                   23 - Flow control under runs
 13:                    0 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:                    0 - Short sends
 17:                  161 - Client keep-alives
 18:                    0 - Sender flow control limits applied
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    0 - ControllableIdleStrategy status
 23:                    0 - Loss gap fills
 24:                    1 - rcv-channel: aeron:udp?endpoint=10.160.113.243:40456
 25:        5,200,808,544 - sub-pos: 1 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 @0
 26:        5,200,808,544 - rcv-hwm: 2 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 
 27:        5,200,808,544 - rcv-pos: 2 543133268 10 aeron:udp?endpoint=10.160.113.243:40456 

echo "Start Media Driver..."                                                                        
java -cp aeron-samples/build/libs/samples.jar \                                                     
     -Daeron.term.buffer.sparse.file=false \                                                        
     -Daeron.threading.mode=DEDICATED \                                                             
     -Daeron.term.buffer.length=536870912 \                                                         
     -Daeron.publication.term.window.length=536870912 \                                             
     -Daeron.rcv.initial.window.length=134217728 \                                                  
     -Daeron.mtu.length=16384 \                                                                     
     -Daeron.socket.so_sndbuf=134217728 \                                                           
     -Daeron.socket.so_rcvbuf=134217728 \                                                           
     -Dagrona.disable.bounds.checks=true \                                                          
     -XX:BiasedLockingStartupDelay=0 \                                                              
     -XX:+UnlockDiagnosticVMOptions \                                                               
     -XX:GuaranteedSafepointInterval=300000 \                                                       
     io.aeron.driver.MediaDriver 



        uint32_t total_times = 1000;
        uint32_t time = 0;

        auto begin = std::chrono::system_clock::now();
        //buffer_len = 5845200;
        while (time < total_times) {
            const std::int64_t result = publication->offer(src_buffer, 0, buffer_len);
            if (result < 0) {
                if (NOT_CONNECTED == result) {
                    std::cout << " not connected yet." << std::endl;
                } else if (BACK_PRESSURED == result) {
                    std::cout << " back presured." << std::endl;
                } else {
                    std::cout << " ah?! unknown " << std::endl;
                }
            }
            ++time;
            std::this_thread::sleep_for(std::chrono::milliseconds(40));
            //std::this_thread::sleep_for(std::chrono::microseconds(800));
        }
        auto end = std::chrono::system_clock::now();


PUB  publish 1000times * 5845200， every 40 milliseconds， and there are many BACK_PRESSURED  in return values. About 110 packages are lost.

**Comment by RichardWarburton** [comment]
Responding specifically to the data loss issue - I think the problem is that you aren't retrying when something gets BACK_PRESSURED. I would have another look at the example code in the Aeron project that does this. If you get back pressured then the fragment that you've offered won't be sent.

**Comment by mjpt777** [comment]
The unknown are likely ADMIN_ACTION which is expected on log rotation. Simply offer again.

The short sends a a give away. This is likely due to incorrectly set buffer lengths. I asked before why you choose the buffer sizes in your config but you have not answered this.

**Comment by GenuineJyn** [comment]
the size of Communication data is 5845200, so the buffer sizes is as shown. if the buffer sizes is small, the question is more serious.

I know  likely ADMIN_ACTION
static const std::int64_t BACK_PRESSURED = -2;
static const std::int64_t ADMIN_ACTION = -3;
static const std::int64_t PUBLICATION_CLOSED = -4;

add offer again,  but about 50 package is still lost. and what size should buffer lengths be set, there is a empirical value?

        uint32_t total_times = 1000;
        uint32_t time = 0;

        auto begin = std::chrono::system_clock::now();
        //buffer_len = 5845200;
        while (time < total_times) {
            std::int64_t result = publication->offer(src_buffer, 0, buffer_len);
            if (result < 0) {
                if (NOT_CONNECTED == result) {
                    std::cout << " not connected yet." << std::endl;
                } else if (BACK_PRESSURED == result) {
                    std::cout << " back presured." << std::endl;
                    do {
                        result = publication->offer(src_buffer, 0, buffer_len);
                        std::this_thread::sleep_for(std::chrono::milliseconds(40));
                    } while (result == 0);
                } else {
                    std::cout << " ah?! unknown " << std::endl;
                }
            }
            ++time;
            std::this_thread::sleep_for(std::chrono::milliseconds(40));
            //std::this_thread::sleep_for(std::chrono::microseconds(800));
        }
        auto end = std::chrono::system_clock::now();

**Comment by RichardWarburton** [comment]
As Martin said in his reply you need to retry when you get an admin action as well.

**Comment by RichardWarburton** [comment]
Also the condition on your retry loop is wrong - you're looping while the result == 0, not == BACK_PRESSURED and == ADMIN_ACTION.

**Comment by GenuineJyn** [comment]
if (result < 0) {
                if (NOT_CONNECTED == result) {
                    std::cout << " not connected yet." << std::endl;
                } else if (BACK_PRESSURED == result) {
                    std::cout << " back presured." << std::endl;
                    do {
                        result = publication->offer(src_buffer, 0, buffer_len);
                        std::this_thread::sleep_for(std::chrono::milliseconds(40));
                    } while (result == 0);
                } else {
                    std::cout << " ah?! unknown " << std::endl;
                    do {
                        result = publication->offer(src_buffer, 0, buffer_len);
                        std::this_thread::sleep_for(std::chrono::milliseconds(40));
                    } while (result == 0);
                }
            }


the data loss still exists!

**Comment by GenuineJyn** [comment]
while (result == 0);   Sorry, It's my fault!!!   thanks a lot!!!

**Comment by GenuineJyn** [comment]
The problem seems to be solved. I'll seriously take a look at the buffer length. Thank All again.

**Comment by mjpt777** [comment]
Also note with performance testing that you need to give the Java driver time to warm up and JIT the code otherwise it is just running in the interpreter. A few short runs of 15000+ messages should do that.

**Comment by GenuineJyn** [comment]
what you have said i do not understand. Can you be more specific?

**Comment by mjpt777** [comment]
The Java Media Driver needs to warm up. You need to look into how a Just In Time (JIT) compiler works. We are working on a C Media Driver but for now there is only Java.

**Comment by GenuineJyn** [comment]
I'm not familiar with Java，OK.

**Comment by mjpt777** [comment]
@GenuineJyn If you are enjoying the benefits from using a free OSS project then maybe you should at least invest the time to understand what it is built on and maybe contribute back where possible.

**Comment by GenuineJyn** [comment]
OK, I‘ll do that.
