### ISSUE TITLE
Question: why the aeron could design a typical pub-sub pattern?

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#336]
Aeron unicast design is that subscriber bind port, when publisher comes online, send message to the subscriber.
My question is why not design a typical pub-sub pattern, one to many, do not want to achieve through the multicast mode. I think a typical pub-sub is that the publisher bind port, subscriber send messages to the publisher when it's online?

**Comment by jordanxlj** [comment]
I think the multi destination control is not a good way for one to many.

**Comment by mjpt777** [comment]
I don't understand the question. Can you try to rephrase it?

**Comment by jordanxlj** [comment]
I have many messages, each message has only one producer, but many consumers. I could not use the unicast mode with mdc for the consumer number is not specified, and could not use the multicast mode for the performance and connection management. So I want to modify the aeron to let the unicast support one to many, maybe add another message before the setup message.

**Comment by mjpt777** [comment]
Have you considered using MDC with the `control-mode` being dynamic, i.e. don't set it? Then allow subscribers to dynamically connect. For try true one-to-many multicast is a much better solution.

**Comment by jordanxlj** [comment]
I have read the source code, only the SendChannelEndpoint's method onStatusMessage could add destination dynamically, how to satify my requirement? If try multicast, the performance is the same as the unicast? I would have many channels more than 50, I am afraid of the bandwidth limit. I have already tested, the multicast of aeron is only 10 percent of the unicast.

**Comment by mjpt777** [comment]
Subscribers get added automatically when the control-mode is dynamic. The publisher will get a status message that sets up the connection if it goes to the control address.

Multicast has pretty much the same performance as unicast. Sounds like you have some issue in your network setup. Multiple unicast streams will use much more bandwidth than a single multicast stream.

**Comment by jordanxlj** [comment]
Martin, thanks a lot. I have another question, if using dynamic MDC, how to use archiver to record and replay?

**Comment by mjpt777** [comment]
The Archiver is not complete yet. That is coming in a future release.
