### ISSUE TITLE
Improve docs on addSubscription()

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#337]
When calling calling addSubscription and providing the available and unavailable image handlers you may want to provide one and not the other. It looks from the code like its safe to just pass in null as an argument here, but that's not documented. I think it would help to clarify this by stating that a null argument is ok for this case.

**Comment by mjpt777** [comment]
👍

**Comment by mjpt777** [comment]
The docs already say this. I'll expand that so hopefully it will be more clear.

**Comment by RichardWarburton** [comment]
Thanks.
