### ISSUE TITLE
timeout await for agent: driver-conductor. Retrying...

### ISSUE THREAD

**Issue by patriknw** [real-logic/Aeron#338]
After updating Akka from 1.2.3 to 1.2.4 one of our tests went haywire. Endless loop of "timeout await for agent: driver-conductor. Retrying...".

It's not reproducible every time but failed several times in our nightly tests.

Here is the test and the problem is in the shutdown after the actual successful tests: https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/AeronStreamConcistencySpec.scala#L89-L91

**Comment by mjpt777** [comment]
I've tried to recreate this but with no luck. Seems like there might be a race condition in the start stop logic. 1.2.4 is more efficient for startup and shutdown. I'm made a change to Agrona that should avoid any potential race conditions in this area.

**Comment by patriknw** [comment]
[stacks.zip](https://github.com/real-logic/Aeron/files/916180/stacks.zip)

Here are some thread dumps, 2 different processes, 3 dumps for each.

**Comment by mjpt777** [comment]
This is very helpful. There is a race on shutdown which I have addressed.

**Comment by patriknw** [comment]
great, thanks
