### ISSUE TITLE
Multicast: first subscriber gets full message replay, following subscribers not ?

### ISSUE THREAD

**Issue by RuedigerMoeller** [real-logic/Aeron#34]
(Setup: your BasicXX example classes using multicast addresses [JDK 1.8_11 Ubuntu 14.04, AMD Opteron]).

Observation:
1) Start publisher sending "Hello world". Let it run for a while
2) Start 1st BasicSubscriber
=> Subscriber receives all messages starting at sequence 0
3) Start 2cnd Subscriber:
=> Subscriber receives a sequence near the current sequence of sender

How large will the replay for the 1st subscriber become ? In case of a high volume publisher e.g. started some hours before the first subscriber, 1st subscriber might get flooded with messages. Can I suppress replay upon join somehow ?

**Comment by strangelydim** [comment]
I ran into the behavior reported in the original issue report today... and was similarly perplexed.  Seems odd that the behavior a new receiver gets is different if it was the first receiver vs. a subsequent receiver.  Not what I would have expected to see.

**Comment by tmontgomery** [comment]
After some discussion, the plan is to disallow `Publication.offer` to succeed unless at least one subscriber is known.

**Comment by RuedigerMoeller** [comment]
Actually this seems like an elegant and low effort solution. Sounds like a
good idea to me :)

2015-03-31 19:52 GMT+02:00 Todd L. Montgomery <notifications@github.com>:

**Comment by RuedigerMoeller** [comment]
On the other hand, can a sender distinguish this from backpressure being
applied by slow receivers ?

2015-03-31 21:45 GMT+02:00 Rüdiger Möller <moru0011@gmail.com>:

**Comment by tmontgomery** [comment]
We might be able to. Initial thought was to mask it so that it is just a window of 0. Are you thinking the app should be informed this is different than a normal flow control?

**Comment by mjpt777** [comment]
When we change the offer to return the position, 0 can mean not yet connected, -1 is back pressure, and any positive value is the new position. Would that work?

**Comment by RuedigerMoeller** [comment]
@mjpt777 & @mjpt777 
I think this could work. From a sender perspective, if there are no subscribers, the rejected message can be discarded. In case of block caused by backpressure, a sender might want to either "alarm" or apply kind of adaptive netting to reduce send rate.

**Comment by mikeb01** [comment]
@mjpt777 As a variant on your suggestion, perhaps negative values can be a series of errors codes, e.g:
* -1 Not connected
* -2 Back pressure
* -3 some other error...

Feels more consistent and extensible.

**Comment by tmontgomery** [comment]
0 for most POSIX stuff means success. So, I would reserve it for returning position 0  (as in the first message to a stream). Then as @mikeb01 suggests, negative values for different errors.

Then the normal pattern of error checks is like it is with most syscalls for POSIX.

```c
if (Publication.offer(...) < 0)
{
     // handle error
}
```
