### ISSUE TITLE
Performance issue with Subscription::poll()

### ISSUE THREAD

**Issue by bedding** [real-logic/Aeron#340]
I'm using Aeron to send and receive a large number of objects, so I did a simple perf test on the Subscription::poll and I found that polling more fragments per Subscription::poll() doesn't bump up the performance very much -- I'm sending 500k objects every 30ms, and one object is about 20 bytes. So that each object can be wrapped in exact one fragment. The objects are sent over IPC.

I counted the time taken by my fragment handler and polling from the aeron subscription object. 
It turns out that polling 100k per poll() call (5 polls in total) takes about 380ms to finish receiving all 500k objects, while polling 1 per call (500k polls in total) takes 500ms. And the time taken by running my own fragment handler is about 300us in total, which is only about 0.1%. Also, I was expecting the performance improvement of batching poll() will be much more than just ~30%. Following are the code snippet of my test, can anyone throw some lights on this? I'm wondering if I'm doing something wrong here

```cpp
void FragmentHandler(aeron::concurrent::AtomicBuffer &buffer, aeron::util::index_t offset,
                     aeron::util::index_t length, aeron::Header &header, 
                     std::int64_t& handlerTime)
{
    Timer timer;
    timer.Start();

    // do stuff

    handlerTime += timer.Stop();
}

void Receive(std::shared_ptr<aeron::Subscription> sub, int numberOfObjects)
{
    Timer timer;
    timer.Start();

    std::int64_t handlerTime = 0;

    aeron::fragment_handler_t handler = std::bind(FragmentHandler,
                                                  std::placeholders::_1, std::placeholders::_2,
                                                  std::placeholders::_3, std::placeholders::_4,
                                                  std::ref(handlerTime));
    
    for (int i = 0; i < numberOfObjects; )
    {
        // change the number here doesn't help much on performance
        int objectRead = sub.poll(handler, 1);
        i+= objectRead;
    }

    auto duration = timer.Stop();
    
    std::cout << handlerTime << ", " << duration << ", " 
       << double(handlerTime) / duration << std::endl;
}
```

Thanks!

**Comment by tmontgomery** [comment]
The performance of IPC batching will depend on the bursting done by the publication as well as the max fragments per poll. But this is not a situation where "little is good, so more must be better". In this type of test, it is a little tricky to set this up so that the publication can fully burst so that the subscription isn't blocked. Also, there should be no difference between 20 bytes and 32 bytes for payload length as 20 bytes will align out to what 32 bytes would be.

To get a full burst, you should set the term length to be enough to not back pressure the burst. 500K messages at 64 bytes each message is 32MB. Default term length is 16MB. So, likely your burst is being effected by flow control much more than you realize. And flow control is effected by poll fragment count because it means how big a jump the subscriber position makes. You want it to move on some chunks, but 100K is almost assuredly too big and will probably introduce some back pressure on the burst. You might want to try 1, 10, 100, and 250 instead of a huge value like 100K.

And you probably want to measure reception throughput instead of time spent in poll. Measuring the time taken by the poll call itself isn't very useful. In either case (poll 1 fragment 500 times or poll 500 fragments 1 time), the calls to the fragment handler will be the same (500 calls). What gets effected more, as I mentioned, is how the subscriber positions are moved forward for flow control.

You might take a look at Throughput.cpp and try different fragmentCountLimits to see what happens.

**Comment by bedding** [comment]
Thank you very much for the timely reply! I think I need to explain the way my test works a little further because I don't think the problem I've seen is related to back pressure, yet I do need to dig into how flow control works.

In my test, the publisher first puts 500k objects onto an IPC stream by calling offer(), it counts the number of successful call, which is the actual number of object sent. The number, say N, is usually less than 500k because of back pressure, but there are still a few hundred thousands of them. Then it tells the subscriber, "Hey! I published N objects for you.". Then the subscriber will go head to poll from the IPC stream. And I'm measuring how fast I can poll these N objects in order to make sure the subscriber can do a certain amount of work before a given deadline. It turns out the number on my side is at least 200ms for a couple of hundred k objects, which is definitely not suitable for my use case. So I am wondering if where is better configuration or a different way to use Aeron to make it more efficient?

P.s. I think the default term length is 64MB for IPC, correct me if I'm wrong.

**Comment by tmontgomery** [comment]
Correct. For IPC, 64MB is the default. My mistake. However, this puts the burst at just the end of the flow control window. Which will likely still flow control.

Flow control is more than just back pressure. It has a lot to do with how Aeron works for position tracking.

For your test, I would do several things:
- make sure each call to poll returns max fragment count. If not, then the test is being artificially blocked. Thread scheduling, flow control, etc. can all have an impact.
- make sure the Media Driver is setup for this type of benchmark. Look at the Java versions of `EmbeddedBufferClaimIpcThroughput`. Off the top of my head, SHARED threading model and NoOp shared idle strategy. Disable bounds checking.
- make sure your receive loop has a pause idle strategy (C++ BusySpinIdleStrategy). Or pin the receive thread so it is not bothered with.
- make sure C++ bounds checking is turned off when you build your application.
- make sure you have sufficient CPUs available for the entire test.
- try various smaller max fragment counts 10, 20, 100 as well as larger ones.

**Comment by bedding** [comment]
Could you point me to docs that explain how flow control works in Aeron? Most of them I found on the Wiki are about back pressure, and not very much in detail.

I forgot to mention in my previous reply that I'm also counting how many fragments received on the subscriber side and make sure it matches N, which is the number of successful send. In addition, the subscriber will not start polling until the publisher finishes all the offer() calls and tells it it's good to go. So I'm expecting that at the point when polling starts, the data should be already on the stream. I'm only timing on how long the polling takes, not the time of receiver busy waiting more data to come. I expected the polling will be super fast because the data are already there, I'm confused on the where the latency could come from.

I also tried your recommended settings, I didn't see much different in the stats.

**Comment by mjpt777** [comment]
This seems a very odd way to benchmark. Messaging is about flow and for flow the producer and consumer are both active at the same time for concurrent exchange. What you are describing will just test your memory controller as it gets paged out of the cache and back in again. There is no concurrency. Can you explain what you are trying to achieve with this test?

**Comment by mjpt777** [comment]
The flow control you are experiencing is effectively just a limit on how much buffer you are using. It is not an active thing whereby the producer(s) is being kept within a window of space ahead of the consumer(s).

**Comment by mjpt777** [comment]
Also are you taking a time measurement in each fragment handler callback? If so, the timing cost is much greater than poll cost per fragment.

**Comment by bedding** [comment]
The test was ran on a workstation with 32-cores cpu and about 50GB memory. But what I'm trying to do is just publishing a bunch of objects every certain period of time, and then let the subscriber to pull them down and do some work. Although the publisher and subscriber may be on different thread, they need not to be, I don't see any correlation with concurrency problem with what I saw from my test. 

The point is if polling 500k objects that are already in the buffer (as I think it is) always takes so long, even if I make the publisher and the subscriber running fully concurrently, the subscriber could still never finish its work on time (should be way less than 380ms).

I did count the timing of my fragment handler callback, as you can see from the original post. It only takes about a few hundreds of microseconds.

**Comment by mjpt777** [comment]
For reference two threads exchanging memory via the L3 cache concurrently have significantly more bandwidth available than when the writes and reads are separated in time and the data is written out to main memory when evicted from the cache. This may not be the issue you are seeing but it is very relevant for concurrent exchange. It is the reason why modern network cards use DDIO.

**Comment by mjpt777** [comment]
Can you post your whole benchmark in a gist so we can have a better understanding?

**Comment by tmontgomery** [comment]
@mjpt777 makes a good point about the timing cost in the fragment handler. Not the time in the fragment handler. In other words, the additional time it takes in the fragment handler to grab the time twice. Depending on what your `Timer` actually is this could be significant.

**Comment by mjpt777** [comment]
Note that with a 32-core machine you will have multiple sockets. It could be that your data is not just going to memory, it could be going to memory on a remote socket and needs to cross the QPI link. If your machine is old it might not have pre-fetch support across the QPI link and this will really hurt throughput. Without the full benchmark it is difficult to tell what is happening.

**Comment by mjpt777** [comment]
If you run your test with Linux "perf record" it should give a good idea to where the time is spent.

**Comment by bedding** [comment]
+ Timer implementation

```
class Timer
{
public:
    inline void Start()
    {
        m_start = std::chrono::high_resolution_clock::now();
    }

    inline std::int64_t Stop()
    {
        auto end = std::chrono::high_resolution_clock::now();
        auto timeElapsed = end - m_start;
        return std::chrono::duration_cast<std::chrono::microseconds>(timeElapsed).count();
    }

private:
    std::chrono::high_resolution_clock::time_point m_start;
};

void FragmentHandler(aeron::concurrent::AtomicBuffer &buffer, aeron::util::index_t offset,
                     aeron::util::index_t length, aeron::Header &header, 
                     std::int64_t& handlerTime)
{
    Timer timer;
    timer.Start();

    // do stuff

    handlerTime += timer.Stop();
}

// Receive() is not called until all objects are sent.
void Receive(std::shared_ptr<aeron::Subscription> sub, int numberOfObjects)
{
    Timer timer;
    timer.Start();

    std::int64_t handlerTime = 0;

    aeron::fragment_handler_t handler = std::bind(FragmentHandler,
                                                  std::placeholders::_1, std::placeholders::_2,
                                                  std::placeholders::_3, std::placeholders::_4,
                                                  std::ref(handlerTime));
    
    for (int i = 0; i < numberOfObjects; )
    {
        // change the number here doesn't help much on performance
        int objectRead = sub.poll(handler, 1);
        i+= objectRead;
    }

    auto duration = timer.Stop();
    
    std::cout << handlerTime << ", " << duration << ", " 
       << double(handlerTime) / duration << std::endl;
}
```

**Comment by mjpt777** [comment]
Try removing the timer use in your fragment handler and see how it performs. :-)

**Comment by tmontgomery** [comment]
On Linux for me running TimeTests which is in the repo, `high_resolution_clock::now` takes about 600ns each call. So, each fragment handler call would take 1.2 micros due to timing.

**Comment by bedding** [comment]
So the timer inside fragment handler was added because I found the performance issue without timing the cb itself... I removed it and tried again, the time didn't shrink much as I've seen before.

**Comment by mjpt777** [comment]
Then either profile or post the whole benchmark. We are just guessing based on partial information otherwise.

**Comment by sthornington** [comment]
For what it's worth, I've seen std::chrono taking (allegedly) ~25ns on real
machines and much more in VMs.

**Comment by tmontgomery** [comment]
Depends on the lib in use.

**Comment by bedding** [comment]
The hardware that is running this test is an AWS EC2 c3.8xlarge instance. From a different point of view, the test is just doing memory copying of 20MB of data each time, given the fact that IPC streaming is using shared memory. I can't image that can take 380ms.

**Comment by bedding** [comment]
I probably can't post the all the code here because there are so many of them. But main loop is very similar this,

```cpp
int main(int argc, char** argv)
{
    // ...initialize Aeron stuff...
    while (true)
    {
        int objectsSent = 0
        for (int i = 0; i < 5000000; i++)
        {
            std::uint8_t buffer[20];
            // ...wrap it in AtomicBuffer...
            if (pub.offer(atomicBuffer) > 0)
            {
                objectsSent++;
            }
        }

        Receive(objectsSent);
    }

    return 0;
}
```

**Comment by mjpt777** [comment]
Can you try removing the code from your fragment handler so that it is just a counter tracking calls? This way you are isolating the Aeron usage and not what's in your handler that we cannot see.

**Comment by mjpt777** [comment]
To address QPI and NUMA issues you could try running with `numactl -m 1 -N 1 <app>` to see if that is involved.

**Comment by mjpt777** [comment]
If we don't have more detail about what you are doing in the callback handler or a profile then we cannot help.
