### ISSUE TITLE
Archiver write disk is slowly

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#341]
I use the archiver to record, publisher send a 5MB message per 30ms, but I found the performance of disk writing is below than 2MB. Use iotop to find jbd2/sda7 use up 95.63% of IO.
I have tried the performance test(https://mechanical-sympathy.blogspot.co.uk/2011/12/java-sequential-io-performance.html), the random access file writing on my machine can up to 100MB per second.
Is any race condition in the archive recording?

**Comment by mjpt777** [comment]
The archiver is not yet released. Why are you using it?

**Comment by jordanxlj** [comment]
My project need record & replay function. Martin, I want to give some advices about archiver.
1. should support through record.properties file to record and replay, messaging is inconvenient.
2. I have see you replace the stream instance with stream key, I think why not use streamId as filename directly, such as 10.meta and 10.0.aaf
3. I think the same archive file size for all stream is improper.
