### ISSUE TITLE
Some advices about archiver.

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#342]
I want to give some advices about archiver.

1. Should support through record.properties file to record and replay, messaging is inconvenient.
2. I have see you replace the stream instance with stream key, I think why not use streamId as the filename prefix directly, such as 10.meta and 10.0.aaf
3. I think the same archive file size for all stream is improper
4. how to align the many different stream messages?

**Comment by jordanxlj** [comment]
How to reduce the archive storage space, but not sacrifice performance. It's really hard.

**Comment by jordanxlj** [comment]
I currently met the archive performance bottleneck, I used the ssd hard disk, but the io writing speed only have 10MB. I thought the key point is the logbuffer transferTo the archive file. Because I have a project to use the record and replay function, I cannot wait for the feature releasing. I wanna to write a recorder in c++, I wish the writing speed is closer to the limit of the hard disk. But something bothered me is if the SBE support c++?

**Comment by mjpt777** [comment]
Try the archive now. I'm going to focus on this in more detail beginning next week.

**Comment by mjpt777** [comment]
SBE does support C++.

**Comment by jordanxlj** [comment]
Thanks a lot for your timely response, I would try it tomorrow.

**Comment by jordanxlj** [comment]
I have tried the archiver without DSYNC, the throughput is up to 120MB, maximum is 200MB, thanks.
