### ISSUE TITLE
Exception handle should be optimized?

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#343]
I configure the recv initial windows length is larger than the socket recv buffer length, the sender send the SETUP message, but the Receiver failed to create Publication Image for the exception. So the Receiver thread terminated, could not response. I wish to see some notification about the exception.

**Comment by mjpt777** [comment]
What was the exception in the error log?

https://github.com/real-logic/Aeron/wiki/Monitoring-and-Debugging#errors

**Comment by mjpt777** [comment]
How was the receiver thread terminated? There is a top level exception handler for all agents so the log and continue.

**Comment by jordanxlj** [comment]
Martin, sorry, I previous not see the debugging chapter, thanks and close it.
