### ISSUE TITLE
unresolved reference to clock_gettime

### ISSUE THREAD

**Issue by btorpey** [real-logic/aeron#344]
On Linux systems with glibc < 2.17 (e.g., RH6), the google benchmark build fails with an undefined reference to clock_gettime.  

This is apparently fixed in the master branch of google bench (https://github.com/google/benchmark/issues/338) , but not in the version packaged with  Aeron.

I don't have time to create a "real" fix, but for others who may be in the same predicament, the following Q&D change to Aeron's master CMakeLists.txt (adding CMAKE_ARGS) appears to work:

ExternalProject_Add(
    google_benchmark
    URL ${CMAKE_CURRENT_SOURCE_DIR}/cppbuild/benchmark-1.1.0.tar.gz
    URL_MD5 66b2a23076cf70739525be0092fc3ae3
    INSTALL_COMMAND ""
    **CMAKE_ARGS -DBENCHMARK_CXX_LINKER_FLAGS="-lrt"**
)

**Comment by mjpt777** [comment]
Google Benchmark upgraded to 1.4.0.
