### ISSUE TITLE
When the publication offered message of 2mb length, fault occured.

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#345]
I meet a problem. I have set the message length to 2mb, term buffer length to 128mb, pub window size to 128mb, recv initial window to 4mb, then start ping pong test. But after 1700 messages, sometimes several hundreds messages, reach pub limit of both sides. I haven't found the reason.

I found when the publication offered message, fault occured.

The fault and the code is in the attachment.

<img width="1192" alt="2017-04-20 12 27 36" src="https://cloud.githubusercontent.com/assets/4532524/25190991/a36c870e-2560-11e7-8f73-366e2f9ce66b.png">
<img width="948" alt="2017-04-20 12 34 02" src="https://cloud.githubusercontent.com/assets/4532524/25191123/2f4d3ba6-2561-11e7-8423-0cd1c672125e.png">

**Comment by mjpt777** [comment]
Is this the standard ping pong test? What JDK and OS are you running on?

**Comment by mjpt777** [comment]
Are you able to post the code that can recreate it?

**Comment by mjpt777** [comment]
Is there a low file space warning output from the driver?

**Comment by mjpt777** [comment]
This is an interesting possibility. http://bugs.java.com/view_bug.do?bug_id=6244515

**Comment by jordanxlj** [comment]
I have tried mac and ubuntu, jdk version is 1.8.021, aeron version is 1.2.5, used the standard ping pong sample code.

**Comment by jordanxlj** [comment]
I haven't see low space warning on the media driver.

**Comment by jordanxlj** [comment]
I am sorry, jdk version is 1.8.0121.

**Comment by mjpt777** [comment]
BTW the publication term window length will be minimum of what you provide and the half the term buffer length so providing one larger than half the term buffer length is not necessary.

**Comment by mjpt777** [comment]
I think the issue is with the test. I'm investigating now.

**Comment by tnjohansson** [comment]
Hi, we are seeing the same issue but in our own code (i.e. not the ping-pong test). I don't think we have seen this issue with previous versions of Aeron. We are currently on version `1.2.4`.

```
2017-04-20T11:16:36.493+0200: 4738.752: [GC (Allocation Failure) [PSYoungGen: 759997K->9103K(789504K)] 1069811K->318941K(1545216K), 0.0160098 secs] [Times: user=0.02 sys=0.00, real=0.01 secs]
Uncaught error from thread [Valo-cluster.presence.dispatcher-9] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Valo]
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at io.aeron.Publication.offer(Publication.java:335)
        at io.aeron.Publication.offer(Publication.java:311)
        at com.itrsgroup.cluster.PublicationLogic$class.offer(PublicationLogic.scala:119)
        at com.itrsgroup.cluster.InstrumentedPublication.offer(InstrumentedPublication.scala:20)
        at com.itrsgroup.cluster.PublicationLogic$class.offer(PublicationLogic.scala:97)
        at com.itrsgroup.cluster.InstrumentedPublication.offer(InstrumentedPublication.scala:20)
        at com.itrsgroup.cluster.network.PresenceActor$$anonfun$receive$1$$anonfun$applyOrElse$9.apply(PresenceActor.scala:143)
```
Our setup is;
OS: CentOS Linux 7 (Core)
OS Arch: amd64
Java Version: 1.8.0_51

We are trying to replicate with a smaller test and will keep you posted if we make progress.

**Comment by mjpt777** [comment]
There was a bug in the samples that did not account for messages larger than MTU length reliably. Can you try with the latest?

**Comment by mjpt777** [comment]
@tnjohansson The java.lang.InternalError can happen in a low memory situation.  Are you low on memory and maybe using sparse term buffers?

**Comment by jordanxlj** [comment]
I have tried the latest, and the problem disappeared, thanks.

**Comment by jordanxlj** [comment]
Martin, I cannot understand your modification, I have tried the message of 512KB, it is larger than MTU length, why not the problem occur?

**Comment by mjpt777** [comment]
Race condition. It had to be sufficiently larger to make it happen more repeatably.

**Comment by mjpt777** [comment]
@tmontgomery This is just a reminder that we need to pick up the same change for C++. Whichever of us gets to it first.

**Comment by jordanxlj** [comment]
thanks Martin, I close the issue.
