### ISSUE TITLE
How to optimize the performance on i7 cpu

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#346]
I compare the performance on the different hardware. I just Send and Recv the message of 2mb. First is Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz, the throughput is about 2GB or 3GB per second, so cool. But I tried another hardware, Intel(R) Core(TM) i7-2655LE CPU @ 2.20GHz, the throughput is about 60MB per second. I have tried use SHARED thread mode, the throughput is up to 100MB.
[performance.txt](https://github.com/real-logic/Aeron/files/941993/performance.txt)

**Comment by jordanxlj** [comment]
I suspected the CPU usage of Media Driver is so high, should it affect the throughput?

**Comment by jordanxlj** [comment]
I change LowLatencyMediaDriver into MediaDriver, the throughput on i7 is up to 500MB. E5 is 8 core and 16 hyper-threads, i7 only 2 cores and 4 hyper-threads. So the throughput of E5 is 4 times than i7. So the difference is reasonable.

**Comment by RichardWarburton** [comment]
It might have been that the problem you were encountering with a two core processor is that a LowLatencyMediaDriver will be burning three cores hot in a spin-loop. This model of operation gives great throughput and latency but required that you have at least 3 cores dedicated to processing the media driver threads as well as cores for whatever else your machine is running on.

You can more generally spot this kind of problem from looking at the context switching rates on your machine. If you're context switching like there's no tomorrow and burning all your cores to the max then your probably don't have enough cores to run in low latency mode.
