### ISSUE TITLE
Requirement: Should provide the topology management?

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#349]
I have used the ROS platform, it has the concepts as the Node, Namespace, Topic. It provided the topology management. It depended the ROSCORE management all Node and Pub Sub relationship. [http://wiki.ros.org/rqt_graph](url)

I thought should the AERON provide the dynamic topology tool?

**Comment by mjpt777** [comment]
The current product direction for Aeron is to be a message transport and not a general purpose messaging system. It is designed so that it can be foundational for building other services on top. Please feel free to build whatever you like on top of Aeron.
