### ISSUE TITLE
Send EOF/EOS during linger when a publication is closed

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#350]
After a Publication is closed the heartbeats during the linger period can can set a new flag in the header to indicate the stream has ended and no further data will be following. Receivers can then reclaim resources sooner rather than waiting for timeout. The client can also know no data will follow on a stream.

**Comment by tmontgomery** [comment]
This is simple enough at the protocol level.

One thing to realize is that EOF markers like this act slightly differently than TCPs FIN. A receiver could have persistent tail loss or loss can be long in duration. So, in that case, a timeout would be seen. Thus an EOF is not an assured thing to rely on. Just like TCP FIN is not assured. It's an optimization.

However, the API needs to understand this as well on the poll side. I think a simple `Header` method of `isEndOfStream` with a length of 0 in the callback might work.

**Comment by mjpt777** [comment]
Totally agreed it is an optimisation and not something to be relied on. We could also have the callback pass a length of -1 to indicate EOF so it is in keeping with socket based APIs.

**Comment by tmontgomery** [comment]
Actually, `recv()` returns 0 on a clean EOF (from FIN). A RST can cause a -1 return (or SIGPIPE in some cases). So, not quite the same.

A return of -1 from a `Subscription.poll` is a little hard to handle with EOF being a per Image concept.

**Comment by mjpt777** [comment]
Good point. I forgot about that. Returning a length of 0 makes more sense.

**Comment by mjpt777** [comment]
BTW I meant the callback getting a length of -1 not the return of Image.poll.

**Comment by tmontgomery** [comment]
Oh. I see. `length` for the handler being passed as 0. Yeah, that could work. And `Header.flags` could also be set (as it would be from the protocol).

**Comment by mjpt777** [comment]
Yes the flag could be set on the last frame in the log buffer when a heartbeat has been received with the flag for EOF/EOS.

**Comment by tmontgomery** [comment]
Some of the initial machinery is in e0bb87c4538125c577a653f20f5865a6d6d8dc95 . I will be updating the protocol spec shortly. The CnC version has been bumped.

Missing pieces:
- C++ API support
- EOS for IPC publications

But I wanted to discuss the API usage.

I think we can do callbacks for notification of End of Stream. Somewhat similar to the (un)available Image handlers. However, this just somehow just doesn't feel right. And it also would require that all applications are checking EOS periodically internally.

What feels more correct might be to use the C `feof` approach to query for EOS. This is what I have so far implemented with `Image.isEndOfStream` and Subscription.isEndOfAllStreams`. This way the application can query anytime it desires. This also makes it more like checking connectivity on the Publication side.

Thoughts?

**Comment by tmontgomery** [comment]
Made a change to be callback based that feels right. Replaced `Subscription.isEndOfAllStreams` with a callback based poll instead. This feels right for the Subscription and leaves the Image to check based on a boolean. This feels better. The check/poll can be done in the same thread as normal polls for fragment handling and can be done by the application logic when it makes sense.

**Comment by mjpt777** [comment]
I was thinking that it might be a nicer way to think of completion rather than EOS. That is have an onComplete(Image) handler and Image.isComplete() method. It is complete from a consumption point of view like in RX. Thoughts?

**Comment by tmontgomery** [comment]
There are a couple problems with using a comparison of `onComplete` and the Rx semantics. And some limitations to consider.

- The EOS is triggered by initiation of linger. Which can result from a remove or from a client timeout. There is no means for the application to signal a clean vs. timeout EOS currently. Which means it isn't necessarily an `onComplete`. It could also be an `onError` instead. The semantics are more dependent on the expected payload. This is one reason why ReactiveSocket is needed in this type of scenario to be able to distinguish app intentions.
- From the API standpoint, it would be great to specify the EOS handler on the `poll` call. That way the app can, in comparison, pass the handlers for `onNext` and `onComplete` and `onError` all in one go. However, this means the signature for a poll-type method has 3 callbacks (that can be lambdas) or 1 non-functional (thus non-lambda-able) interface with 3 methods (or 2 if just using `onNext` and `onEos` for example). Language limitations do make this less than ideal (you can work around it in C++ via a struct, though).

I did consider making new overloaded poll methods that take 2 args (`FragmentHandler` and `EndOfStreamHandler`) that check for EOS whenever no fragments delivered. Simply overload and call the original, capture the return value, and check if return value was 0. These also feel OK to me.

**Comment by mjpt777** [comment]
Good points. Just a thought on my side :-)

**Comment by tmontgomery** [comment]
It's good to think about. What do you think about overloaded `poll` methods with the EndOfStreamHandler?

**Comment by mjpt777** [comment]
I think the `EndOfStreamHandler` is best invoked from within the poll operations when no data is available and it is set on the `Subscription` during the `addSubscription` call. This way it is not a separate polling operation for EOS and it just happens when the poll for data is complete. Passing the handler on the poll calls feels too messy with too many overloads.

**Comment by tmontgomery** [comment]
Here is my thinking.

The standard way of handling EOF in Java is a `-1` on the `InputStream.read`. `SocketChannel` is similar. For C on most UNIXes, `read` and `recv` both return 0 for EOF. For C portable `fread`, the return of error and EOF needs to be distinguished via `feof`. All of this tends to lead to logic that involves checking for EOF as a condition of return value or from state of the object/connection in the same specification of the message handling logic.

For Rx-style operation, the specification of `onComplete` is combined with the specification of `onNext`, `onError`, etc. usually via a single class implementing the interface. This means the logic for handling the end of the stream via complete or error is in the same specification as handling the messages and often can or does access the same state. However, often users of Rx never see this detail since they often only combine operators instead of building their own.

`EndOfStreamHandler` being instantiated at `addSubscription` time instead of at `poll` time feels awkward to me. The actions of handling the end of a stream depends on the stream and state and often the previous message state. With the action of handling EOS being specified at a different instantiation time than normal message processing, this seems harder to do without creating additional coupling (in time) or limiting the `poll` specification to be at instantiation time.
