### ISSUE TITLE
[Archiver] Consider sharding of archiver load across threads

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Aeron#351]
Should we have replay and record on same thread?
Should we allow the allocation of more threads to these tasks assuming slow storage/sufficien traffic/sufficient replay load?
Leaving as an open design question for now to be evaluated based on experimental data and feedback.

**Comment by mjpt777** [comment]
Replay and recording can be done on different Agents. Initially we can schedule them as composite agent on the same runner.
