### ISSUE TITLE
[Archiver] Allocate ahead archive files            

### ISSUE THREAD

**Issue by nitsanw** [real-logic/aeron#352]
Note: This is a place holder item, which may or may not be worth doing.
Will prevent hiccups.
Will also give early indication to low storage.

**Comment by tmontgomery** [comment]
Allocating ahead by some chunk/file size? i.e. number of terms...?

**Comment by nitsanw** [comment]
The archiver currently creates the file as needed, rolling into next file when a file is full. File size is a multiple of term buffer size. The files are sized on creation. It may be helpful to allocate ahead files to avoid this allocation cost on a hot path. This is a place holder item, which may or may not be worth doing, should have made that clearer in the description.

**Comment by tmontgomery** [comment]
Makes sense. What about an idle strategy that has a hook for only doing work when idle? Then hook in and do allocate ahead when idle? If not idle and need to allocate, do it in the hot path.

**Comment by mjpt777** [comment]
Allocating ahead can provide benefits when reusing the file. Do you have a case where it benefits when it will just be written once and not resident in memory?

Regularly checking for available space is a different thing and worth its own feature.

**Comment by mjpt777** [comment]
This tends to be file system specific. I'm closing for now and it can be reconsidered in the future if the specific requirement arises.
