### ISSUE TITLE
[Archiver] Add CRC as option, per fragment, use session id to store CRC

### ISSUE THREAD

**Issue by nitsanw** [real-logic/aeron#353]
Note: This is a place holder item, which may or may not be worth doing.
This is on write to file. This will produce overheads as currently we do not parse fragments on write. The overwritter sessionId is not used on read since the fragment header is replaced on replay.

**Comment by tmontgomery** [comment]
Session ID is a good thing to use. This is consistent and metadata.

**Comment by nitsanw** [comment]
See re-edit of first comment.

**Comment by jordanxlj** [comment]
I thought the CRC is bad option for the record corruption. It decrease the performance for reliability. I think the proper method is close and start recording a new data file.

**Comment by RichardWarburton** [comment]
How do you mean "close and start recording a new data file"? CRCs let you detect whether a file has been corrupted by some underlying mechanism such as a faulty SSD, Hard Disk or Controller.

**Comment by jordanxlj** [comment]
@RichardWarburton , For example, if you have an apple fell to the ground broke, how can effectively mark the broken apple, not to give each apple to be marked.

**Comment by nitsanw** [comment]
@jordanxlj I am failing to understand what you mean. Can you please explain via an example, or point to an article which demonstrates your point?

**Comment by mjpt777** [comment]
The archive should have a context option to enable CRC checks on fragments with the CRC stored in the session-id field. This can be added when the stream is recorded and checked when loaded for replay or via the verify option to CatalogTool.
