### ISSUE TITLE
In the absence of other node subscription, should it send multicast packets?

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/Aeron#354]
I use the multicast channel, for my network switch limit multicast, I locate the subscription and publication on the same host. I read the code and found although no subscription on other host, it would send multicast packets. And the other host received and dropped it.

**Comment by mjpt777** [comment]
Can you please refine the question? It is not clear what you are asking.

**Comment by cesaref** [comment]
I think he is saying that multicast traffic is published to all interfaces from the publishing host, even if the only subscriber is on the localhost loopback?

**Comment by jordanxlj** [comment]
Thank cesaref for your clarification.

**Comment by tmontgomery** [comment]
No. IP Multicast does not go out all interfaces. It goes out only one. When sending IP multicast, the kernel looks at the sockets IP_MULTICAST_IF and then at the routing table and it goes out the indicated interface.

http://www.tldp.org/HOWTO/Multicast-HOWTO-6.html

However, there is no loopback only multicast interface.... unless you configure one for this explicit purpose in the OS and explicitly make it the default multicast interface.

So, what you are observing.... multicast traffic going out to a multicast address outside the machine, is the intended TCP/IP socket behavior for multicast. If a multicast receiver is listening to that multicast address and port, and a network switch supports multicast, then it will forward all traffic to that machine that matches that address and port.

**Comment by jordanxlj** [comment]
@tmontgomery , I understand your meaning, but I just  unfortunately encountered the situation that the switch not support multicast well. But I thought under the situation, is it reasonable to give way to ip protocol stack? From the angle of the design, should we design more efficiently?

**Comment by jordanxlj** [comment]
@tmontgomery, I have already changed my switch to support multicast well.

**Comment by tmontgomery** [comment]
Well, Aeron is restricted to the IP multicast semantics of the kernel. Changing some of that is not possible. And in some cases, not really advised. It is simpler and cleaner to go with the IP multicast semantics that are well understood instead of hiding them, in my experience.

BTW, if you want only loopback behavior, you are much better served by using IPC than by using multicast.

**Comment by jordanxlj** [comment]
@tmontgomery , I could not use IPC, for my case is one-pub and multi-sub on multi-hosts, for the reason of the switch, I temporarily adjust deployment.

**Comment by mjpt777** [comment]
@jordanxlj For the local to avoid loopback have you considered using a spy subscriptions?

**Comment by jordanxlj** [comment]
@mjpt777 , In my mind, Spy Subscription is just not copy publication term buffer, without back pressure. It is transparent to the publication, so it is useless.

**Comment by tmontgomery** [comment]
@jordanxlj Spies apply back pressure to the publication just as normal IPC subscriptions would.
