### ISSUE TITLE
C++ BitUtil::numberOfTrailingZeroes return 0 when capacity is (1 << 21)

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#356]
I'm compiling Aeron in C++ using VS2017.

Following is the change I made to the Image's constructor to avoid having BitUtil::numberOfTrailingZeroes return 0 when capacity is (1 << 21).

Image.h:

Image(
        ...)
    {
       ...
        m_positionBitsToShift = BitUtil::numberOfTrailingZeroes(**static_cast<uint32_t>(**capacity**)**);
    }

**Comment by tmontgomery** [comment]
Feel free to send this change as a PR.

**Comment by goglusid** [comment]
Already fixed.
