### ISSUE TITLE
Support configurable Buffer construction in ControlledFragmentAssembler/BufferBuilder

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#357]
Raising an issue to track this - I'm happy to make the change at some point this week if people are happy with it.

If you're sending Aeron messages via some other messaging transport (eg, writing to TCP with a framing protocol) you want to be able to receive an UnsafeBuffer that is wrapping a DirectByteBuffer in order to avoid Nio copying your heap byte buffer to a DirectByteBuffer to send it over TCP. This is normally fine with Aeron since poll() method calls pass MappedByteBuffers which are a form of DirectByteBuffer.

At the moment any use of the *FragmentAssembler hands you an UnsafeBuffer that wraps a byte[] in your callback. The byte[] is probably more desirable for use-cases where you're processing the data. Really the *FragmentAssembler objects should optionally take a factory or a flag to control what the UnsafeBuffer instances wrap.

**Comment by mjpt777** [comment]
This has been done. You pass a flag to the appropriate fragment assembler to indicate what type of buffer you would like. It was also a good opportunity to not allocate any buffer until needed.
