### ISSUE TITLE
Error in 'Monitoring and Debugging' page?

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#360]
In the [Monitoring and Debugging](https://github.com/real-logic/Aeron/wiki/Monitoring-and-Debugging) page under Log Inspection, the command contains:
```
  -Daeron.log.inspector.data.format=assci \
```
Should that instead be:
```
  -Daeron.log.inspector.data.format=ascii \
```

**Comment by mjpt777** [comment]
Thanks. Fixed.
