### ISSUE TITLE
Utilizing a large number of streams

### ISSUE THREAD

**Issue by Msqs** [real-logic/Aeron#361]
The wiki says:

> Aeron assumes some operational conditions, such as:
> 
> Low number of Streams. As each Term is a buffer for the Media Driver, and a Stream has a number of terms, the number of assumed Streams is assumed to be less than 1000 or even less than 100.

What are some of the effects that we can expect to see if we start utilizing a large number of streams?

What if we have 100 streams? 500 streams? 1000 streams? 5000 streams?

**Comment by mjpt777** [comment]
The Sender has to linearly search over streams for sending the data and the subscribers will do similar when receiving data. The higher this number then the larger the latency. 

I've seen customers run with 100s or even a 1000 streams and be happy with the results.
