### ISSUE TITLE
Unable to run BasicPublisher/BasicSubscriber - cnc.dat file not found

### ISSUE THREAD

**Issue by ppolukonda** [real-logic/Aeron#366]
Hi, 
I am trying to run BasicPublisher/BasicSubscriber from Aeron-samples on my Windows 7 pc. It is throwing the following exception: 

`Publishing to aeron:udp?endpoint=localhost:40123 on stream Id 10
Exception in thread "main" io.aeron.exceptions.DriverTimeoutException: CnC file not found: cnc.dat
	at io.aeron.Aeron$Context.connectToDriver(Aeron.java:920)
	at io.aeron.Aeron$Context.conclude(Aeron.java:391)
	at io.aeron.Aeron.<init>(Aeron.java:101)
	at io.aeron.Aeron.connect(Aeron.java:147)
	at io.aeron.samples.BasicPublisher.main(BasicPublisher.java:65)`

I have tried by creating an empty file but it was throwing some other exception. Does it require any setup?

**Comment by RichardWarburton** [comment]
Hi,

Have you got the media driver running in the background? If not then you need to start it, or get one of the samples to start an embedded media driver by passing -Daeron.sample.embeddedMediaDriver=true.

Hope that helps.

**Comment by ppolukonda** [comment]
Thanks! That really helps. What is the recommended approach on running media driver? embedded or separate instance? Take scenario: Many Pubs Vs Many Subs.

Thanks!

**Comment by RichardWarburton** [comment]
No problem.

I think it depends how you want to use Aeron. Media Driver instances sit on a box an send/receive UDP packets over the network, whilst ensuring that the mapped files and cleaned and rotated. If you've got multiple publishers or subscribers sitting in different processes on the same box then probably your best bet is to run separate a instance of the media driver and have it manage all the processes.

If you're going to just have a single process on a machine with the publishers and subscribers inside then its probably easiest to just keep it embedded within the process. Just my opinion of course ;)

**Comment by ppolukonda** [comment]
Yes agree. Thats how we have been using chronicle HFT solution at the moment. I can see MediaDriver is more like a broker instance running in the back ground. I am exploring aeron for using in one of our low-latency application. 

Is it possible to share a sample properties file(s) that MediaDriver can use? 

Thanks in advance!

**Comment by ppolukonda** [comment]
I think I can look into one of properties files here: https://github.com/real-logic/Aeron/tree/master/aeron-driver/src/main/resources

Thanks!

**Comment by RichardWarburton** [comment]
Happy to help. Looks like you've found the examples and that this query is resolved so I'll close the issue.
