### ISSUE TITLE
Is there a user forum for Aeron? [question]

### ISSUE THREAD

**Issue by karypid** [real-logic/Aeron#367]
As far as I can tell, apart from the wiki and the issues tagged with [question](https://github.com/real-logic/Aeron/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Aquestion%20) here, there is no forum for (new) users to simply fire off questions and share experiences.

I find this sort of group chat becomes a valuable resource over time, as many questions can be answered by searching there. Why not create a google group (they're easy, highly accessible even from within corporate firewalls) for discussing usage?

**Comment by RichardWarburton** [comment]
I appreciate that its not the same thing, but there is a gitter chat room for asking ad-hoc questions - gitter.im/real-logic/Aeron.

**Comment by nitsanw** [comment]
hi @karypid!
There's a gitter channel for informal chats, and the issues and wiki as further searchable resources. I understand your preference for mailing groups, but in the presence of these 3 existing locations I'm not sure adding a mailing list will help.
I think the process should be:
* Search wiki (offer feedback on anything lacking or confusing)
* Search issues/questions (perhaps useful content from here can be promoted to wiki?)
* Raise question on GH if you feel it's a clear enough omission from either resource, or pop it on gitter to discuss with users and contributors. These interactions in turn should feed back into wiki/GH items.
Thanks,
Nitsan
