### ISSUE TITLE
Why does a media driver restart require that all client processes also restart? [question]

### ISSUE THREAD

**Issue by karypid** [real-logic/aeron#368]
Hello,

In issue #274 , you state:

> For Aeron media driver shutdown, the best way to handle that is to restart the Aeron instances and that means restarting the Publications and Subscriptions they use as well. Consider it a hard error and a total restart. The Aeron errorHandler will deliver errors for media driver liveness, etc. so the application does not have to.

Why is a media driver restart so 'dramatic' (for lack of a better word)?

I would like to toy with the concept for having clients that interact via the external media driver "recover". Basically if another JVM that connects to the media driver loses that connection, it would close all publications/subscriptions, close the connection with Aeron.close(), then re-establish a new one by periodically calling Aeron.connect(ctx).

Is it really impossible to survive a media driver restart and what is the reason behind that?

**Comment by karypid** [comment]
So, I did a test in Windows as follows:

- A client is in a loop trying to connect.
- When connected the client creates a publication.
- Client then enters a loop waiting for a subscriber to appear.

I noticed that the following sequence causes the driver to not be able to run:

1. Start test client
Wait to see it try to connect a few times unsuccessfully...

2. Start media driver
Wait to see client manage to connect; it will create the publication and enter the inner loop waiting for a subscriber to arrive.

3. Kill media driver
Wait for client to notice. It closes the publication and connection context.

4. Start media driver again
This fails!

```
package playground;


import java.util.concurrent.atomic.AtomicBoolean;

import org.agrona.CloseHelper;

import io.aeron.Aeron;
import io.aeron.Publication;

public class RunPublisher {
    private final AtomicBoolean failed = new AtomicBoolean(false);

    private final String uri;
    private final int streamId;

    public RunPublisher(String uri, int streamId) {
        this.uri = uri;
        this.streamId = streamId;
    }

    public static void main(String[] args) throws Exception {
        new RunPublisher(args[0], Integer.parseInt(args[1])).run();
    }

    private void run() {
        final Aeron.Context ctx = new Aeron.Context();

        ctx.errorHandler((Throwable error) -> {
            error.printStackTrace(System.out);
            System.out.println("Connection died... Will try to re-establish...");
            failed.set(true);
        });

        Aeron aeron = null;
        Publication publication = null;

        while (true) {
            aeron = null;
            publication = null;

            try {
                System.out.println("Reconnecting...");
                failed.set(false);
                aeron = Aeron.connect(ctx);
                try {
                    System.out.println("Connect succeeded! Add publication...");
                    publication = aeron.addPublication(uri, streamId);
                    try {
                        System.out.println("publication added! Wait for subscriber...");
                        while (!failed.get() && !publication.isConnected()) {
                            System.out.println("No active subscribers detected");
                            Thread.sleep(1000);
                            continue;
                        }
                        if (!failed.get()) {
                            System.out.println("Subscriber arrived! Goodbye!");
                            break;// success!
                        }
                    } catch (Exception e) {
                        e.printStackTrace(System.out);
                        System.out.println("Error waiting for subscriber... Resetting...");
                        continue;
                    }
                } catch (Exception e) {
                    e.printStackTrace(System.out);
                    System.out.println("Add publication failed... Resetting...");
                } finally {
                    System.out.println("close(publication)");
                    CloseHelper.quietClose(publication);
                }
            } catch (Exception e) {
                e.printStackTrace(System.out);
                System.out.println("Connect failed... Will retry...");
            } finally {
                System.out.println("close(aeron)");
                CloseHelper.quietClose(aeron);
            }
        }
    }
}
```

Apparently when the driver dies, a file handle is left open for the publication on the CLIENT side. This prevents the driver from being able to restart. The exception I get is:

```
WARNING: C:\Users\karypid\AppData\Local\Temp\aeron-karypid already exists.
INFO: Aeron CnC file C:\Users\karypid\AppData\Local\Temp\aeron-karypid\cnc.dat exists
INFO: Aeron toDriver consumer heartbeat is 30035ms old
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Users\karypid\AppData\Local\Temp\aeron-karypid\publications\UDP-00000000-0-7f000001-40123-cee8cf5a-a-1.logbuffer
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.agrona.IoUtil.delete(IoUtil.java:137)
	at org.agrona.IoUtil.delete(IoUtil.java:128)
	at org.agrona.IoUtil.delete(IoUtil.java:128)
	at io.aeron.CommonContext.deleteAeronDirectory(CommonContext.java:318)
	at io.aeron.driver.MediaDriver.ensureDirectoryIsRecreated(MediaDriver.java:424)
	at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:163)
	at io.aeron.driver.MediaDriver.launch(MediaDriver.java:285)
	at io.aeron.driver.MediaDriver.launch(MediaDriver.java:274)
	at io.aeron.driver.MediaDriver.main(MediaDriver.java:144)
```

I will try in Linux and post back, but it seems to me that a handle is left lingering...

**Comment by mjpt777** [comment]
Try closing all clients, i.e. `Aeron.close()` before restarting the driver.

**Comment by karypid** [comment]
The problem is in class Publication I think:

```
    void releasePublication(final Publication publication)
    {
        verifyActive();

        if (publication == activePublications.remove(publication.channel(), publication.streamId()))
        {
            lingerResource(publication.managedResource());
            awaitResponse(driverProxy.removePublication(publication.registrationId()), null);
        }
    }
```

verifyActive() throws an exception and publication.channel() is never touched...

Disclaimer: I literally just started looking into this code; I may be way off...

**Comment by mjpt777** [comment]
You should just ignore closing the publications and subscriptions and just close the Aeron client. This is more forceful. I'll update the release as it does not need the driver check.

**Comment by karypid** [comment]
Thank you, it works after commenting out:

```
                    // System.out.println("close(publication)");
                    // CloseHelper.quietClose(publication);
```

The change for IllegalStateException should steer users in the right direction. I will add actual subscribers and continue testing (also on Linux) and report here if I run into any other issues.

**Comment by karypid** [comment]
Related question(s):

1) Driver timeout milliseconds.

The description reads "The timeout in milliseconds after which the driver is considered dead if it does not update its C'n'C timestamp." In my testing I lowered this value in order to speed up detection of a "dead driver". 

- Are there any guidelines on its value? 10 seconds seems quite high. How does this affect Aeron if set to (say) 1 second?
- Obviously the timeout needs to be set to the same value in all processes using this driver. Unfortunately there is there no system property for it? It's a pity one has to use a custom launcher to set it on the driver side. Would you consider adding one? (I could create a pull request, though it's ridiculously simple).

2) Ensuring same driver incarnation

I noticed that a new driver will wait until driver timeout milliseconds before trying to take over an existing directory (which makes absolute sense). Still, is there something in Aeron's protocol that discriminates between instances of the driver (to ensure no data is intermixed between an old and new incarnation)? I added a "sessionId" in the application layer protocol that increases monotonically every time I connect to a new driver. This ensures that receiving clients can detect a "new" incarnation sending data. I suspect there's already something available to do this but is it accessible to subscribers/publishers via the API?

**Comment by mjpt777** [comment]
I've added the ability to set the driver timeout in milliseconds via the `aeron.driver.timeout` system property. 

Due to garbage collection, page cache flushing, zone reclaims, scheduling starvation, etc. it is unwise to set a timeout less than a few seconds unless you have a very well tuned and setup machine.

**Comment by tmontgomery** [comment]
The CnC file contains the client liveness timeout that the driver will use. This needs to be communicated to the clients. The timeout that the clients should use for the driver depends on how often the driver updates the timestamp.

Driver incarnation is a black hole that adds no value. Each time the driver starts it starts with a clean state. If a client knows it is communicating with an "old" driver, it will make assumptions that can not hold. There is no real value to making assumptions like this.

**Comment by karypid** [comment]
@mjpt777 thanks for this change. Your points about GC/OS pauses is noted.

**Comment by karypid** [comment]
@tmontgomery That was precisely what I wanted to ensure: that all previous data "from the wire" is discarded. I was worried the new media driver may deliver messages the previous instance received, so therefore the application code needs to defend against it. Based on your explanation I see this is not a concern.

**Comment by karypid** [comment]
Unfortunately reconnecting in Linux seems to be unstable. Basically, when I restart the media driver, the publisher connects and then tries to add the publication, but I sometimes I get a SIGSEGV.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7721a879ef, pid=26194, tid=140149143889664
#
# JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 6135 C2 io.aeron.ClientConductor.doWork()I (59 bytes) @ 0x00007f7721a879ef [0x00007f7721a87860+0x18f]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /server/hs_err_pid26194.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by mjpt777** [comment]
Do you have a line number for the SIGSEGV in the core dump?

**Comment by karypid** [comment]
`# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again`

I've turned that on and will chase it. Unfortunately it's just hard to reproduce.... Only got it twice in the past 8 hours. Will have more time to fiddle so I'm sure I'll manage to track it.

**Comment by karypid** [comment]
Just a quick update - it seems to me that the SIGSEGV is not the result of some native code but a direct buffer access:

```
Stack: [0x00007f75e8037000,0x00007f75e8138000],  sp=0x00007f75e8136290,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 5767 C1 org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.write(ILorg/agrona/DirectBuffer;II)Z (110 bytes) @ 0x00007f76312bba11 [0x00007f76312bb6a0+0x371]
j  io.aeron.DriverProxy.addPublication(Ljava/lang/String;I)J+49
j  io.aeron.ClientConductor.addPublication(Ljava/lang/String;I)Lio/aeron/Publication;+26
j  io.aeron.Aeron.addPublication(Ljava/lang/String;I)Lio/aeron/Publication;+15
j  playground.aeron.AeronConnectionManagerImpl.addPublication(Ljava/lang/String;I)Lio/aeron/Publication;+22
j  playground.aeron.FxPriceAeronPublisher.onConnected()V+42
j  playground.aeron.AeronConnectionManagerImpl.notifyOnConnected()V+16
j  playground.aeron.AeronConnectionManagerImpl.fireOnConnected(Lio/aeron/Aeron;)V+32
j  playground.aeron.AeronConnectionManagerImpl.run()V+121
j  playground.aeron.AeronConnectionManagerImpl$$Lambda$32.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68c616]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x68cb21]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
V  [libjvm.so+0x68cfc7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x723d80]  thread_entry(JavaThread*, Thread*)+0xa0
V  [libjvm.so+0xa69dcf]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0xa69efc]  JavaThread::run()+0x11c
V  [libjvm.so+0x91d9d8]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x7aa1]  start_thread+0xd1
```

I am going to switch back to my test publisher and see if I can reproduce this with a snippet.

I am also considering a different approach: have a custom media driver launcher that picks a new aeronDirectory every time (e.g. /dev/shm/aeron-${pid}) so that a fresh location is used. Clients that notice the driver heartbeat timed out will call Aeron.close() and open a connection to the new directory. I can have the custom launcher lock a file (e.g. /dev/shm/current) and overwrite the content with the name of the new location, so that clients know where to try and reconnect (as soon as content changes).

**Comment by mjpt777** [comment]
If you try with the latest build it should close the client on a driver timeout.

**Comment by mjpt777** [comment]
I'm going to close this for now. Any follow up can be opened as specific issues.
