### ISSUE TITLE
Using Eclipse

### ISSUE THREAD

**Issue by karypid** [real-logic/aeron#369]
Hello,

I'm opening this issue to discuss using Eclipse with Aeron+friends. Hope others will chip in.

# Summary

1. Aeron and some core dependencies (Agrona, SBE) use Gradle for their build system. It is recommended you install the [Buildship Gradle Integration plugin](https://marketplace.eclipse.org/content/buildship-gradle-integration).
2. Aeron uses snapshot dependencies for [real-logic/agrona](https://github.com/real-logic/agrona) and [real-logic/simple-binary-encoding](https://github.com/real-logic/simple-binary-encoding). Before trying to import Aeron itself you should also close these 2 projects and install them locally.

## Setting up the environment

Prepare Eclipse:

- Install [Buildship Gradle Integration plugin](https://marketplace.eclipse.org/content/buildship-gradle-integration) if you don't already have it.
- Go to "Window -> Preferences -> Java -> Compiler -> Errors/Warnings" and under "Deprecated and restricted API" make sure the "Forbiden reference (access rules)" drop-down is anything other than "Error". Both Aeron and Agrona otherwise Eclipse will flag or accesses to Java's Unsafe class as errors.

Next, install the pre-requisites:

- Clone  [real-logic/agrona](https://github.com/real-logic/agrona) locally and run "gradlew install" for it. You do not need to import this into Eclipse necessarily.
- Clone [real-logic/simple-binary-encoding](https://github.com/real-logic/simple-binary-encoding) locally and gradlew install" for it. You do not need to import this into Eclipse necessarily.

Now import Aeron:

- Clone Aeron and import it into your workspace using Buildship (File -> Import ->Gradle -> Existing Gradle Project).
- At this point aeron-archiver-codeces will show errors dues to missing classes. These are generated by SBE so go to the root folder of your Aeron git local clone and run "gradlew generateMessages"
- Back in Eclipse refresh the project aeron-archiver-codecs  and then go to its properties and under "Java Build Path" in the "Source" tab, click on "Add Folder..." and tick the check-box next to "aeron-driver-codecs/build/generated-src"

At this point everything should should be set. You may occasionally need to pull updates from Agrona or SBE and run "gradlew install", or (if the archiver codecs change) run "gradlew generateMessages" to recreate the generated sources.

It is also worth noting that: **If you import Agrona into Eclipse, do not expect Eclipse to associate the two and link against the "live" code in the workspace.** Buildship does not yet do that because of limitations in the Gradle tooling. There is work along this front base on [this IDE-integration tooling proposal](https://github.com/gradle/gradle/blob/master/design-docs/ide-integration.md#story---expose-workspace-concept-for-eclipse).

# Historical information

So, from my perspective this is also the first time I'm using Gradle which means that this is mostly about using eclipse+gradle but with the twist of "to work with aeron".

I'm on latest - as of now - Neon (4.6.3) relase and a quick search revealed that the [Buildship plugin](https://projects.eclipse.org/projects/tools.buildship) seems to be the most popular way to import gradle projects into eclipse, so that's what I installed.

Importing Aeron revealed that it is using snapshot versions of Agrona and SBE-tool. The first one I came across was Agrona (SBE discussed later)

## Snapshot dependencies and Gradle in Eclipse
**(AKA Agrona and Aeron in Eclipse)**

Imported the project using the Gradle wizard (next -> next -> next as defaults rule). First thing Eclipse complained about was being unable to find the snapshot dependency on agrona (0.9.7-SNAPSHOT at the time I write this).

My first reaction was to change the build.gradle `def agronaVersion = '0.9.6'` which is in maven central but alas this lead to compilation errors so I went back.

I therefore cloned Agrona.git and tried to import it into the workspace.

### Here comes the first nuance:  import failed revealing that Eclipse is case-insensitive in project names

It complained that a resource already exist with a different case (Agrona vs agrona).

This happens because the repository is Agrona.git and the artifacts inside are "agrona" and "agrona-agent". Apparently this is a no-no for Eclipse as it has one project per artifact PLUS one for the root of the git working directory which is called "Agrona" and clashes with "agrona".

**SOLUTION: rename the local git repository to 'Agrona-local' and the import will. You will get 3 projects: Agrona-local, agrona and agrona-agent**.

So with that out of the way I refreshed my workspace and Agrona was built successfully, but Aeron was STILL complaining that 0.9.7-SNAPSHOT was nowhere to be found.

### Here comes the second nuance: gradle is not yet smart enough to resolve dependencies via the Eclipse workspace

People using m2eclipse are used to never deploying to the local repository. If you have project A and B for which A depends on B x.y.z-SNAPSHOT, then importing the source of B that has x.y.z-SNAPSHOT into the workspace will cause m2eclipse to have workspace project A depend on workspace project B. There is no need to install locally.

Anyway apparently Buildship does not do that, so I had to 'break protocol' (I hate installing local snapshots because if I change something I need to re-install) and decided to just install Agrona locally.

**SOLUTION: run 'graldew' in your Agrona root and you will get a local installation.

### Here comes the third nuance: aeron-archiver-codecs require that you run SBE tool to generate sources using a snapshot version

I guess I can download SBE and do the same thing I did for agrona but I had a feeling I could succeed by just using 1.7.0 instead of 1.7.1-SNAPSHOT. I changed the build.gradle file and used Buildship to run the "build" task but it failed on "Execute task action 4/4 for : aeron-archiver-codecs:checkstyleGenerated".

In contrast, running "gradlew" from command line succeeded. Haven't got to the bottom of what's going on here yet, I'll post an update when I figure things out.

**Comment by mjpt777** [comment]
I've renamed the git project from Agrona to agrona. I'm looking at doing the Aeron one next.

**Comment by karypid** [comment]
I don't think that will help. It's really more of an Eclipse/Buildship problem

To describe it better: you have a repository called Agrona (or agrona, doesn't matter).

Inside it there's a gradle project that has two modules:

project(':agrona')
project(':agrona-agent')

Now, when Buildship imports this it creates N+1 projects in eclipse: one per gradle porject/module and then an extra "special" one for the root folder of the git clone. So it will map:

git clone https://github.com/real-logic/agrona.git --> Root local dir: agrona
git clone https://github.com/real-logic/Agrona.git --> Root local dir: Agrona

project(':agrona') --> agrona
project(':agrona-agent') --> agrona-agent

So the project agrona clashes with the default local directory "Agrona" (or agrona after your rename). It's really a Buildship issue. 

I'll reach out to Buildship later (got to get access to their repo) to suggest they "detect" this and if the local git clone is named after one of the modules inside, they should automatically generate a different eclipse project name for the repo. Maybe:

/path/to/local/git/Agrona --> Agrona-Buildship
project(':agrona') --> agrona
project(':agrona-agent') --> agrona-agent

Or they could just prompt the user explaining that they need that extra project and he has to pick some new name to avoid the clash...

**Comment by mjpt777** [comment]
Thanks, that is interesting to know. I think going to lowercase is useful anyway as I've seen issues with case on windows.

**Comment by karypid** [comment]
So, I stand corrected; this DID help. Apparently Buildship is aware of potential clashes so it does check whether one of the modules matches the git directory name, only it does that in a case-sensitive manner.

Therefore, using "agrona" for the git URL will create a local "agrona" git clone, meaning Buildship detects this and imports successfully.

Using "Agrona" for the git URL will create a local "Agrona" git clone, meaning Buildship does NOT detect this and fails to import...
