### ISSUE TITLE
Join position is not equal 0, when I replay the file, subscriber blocked for the invalid frame.

### ISSUE THREAD

**Issue by jordanxlj** [real-logic/aeron#370]
I have used archiver to record and replay. I recorded a channel which join position is not equal 0, when I replay the file, the subscriber blocked for the invalid frame.

My frame payload length is 256 bytes, total length is 288 bytes. So the next frame should be started from 0x664E0, but the next frame is all with zero.

![image](https://user-images.githubusercontent.com/4532524/27730935-aeb62170-5dbd-11e7-829f-deda34c24752.png)

**Comment by jordanxlj** [comment]
The screen is from the share memory imag file.

**Comment by jordanxlj** [comment]
I use the master trunk version of 2017.6.8.

**Comment by jordanxlj** [comment]
I have already check recording file content, it's OK. The block position is not fixed.

**Comment by jordanxlj** [comment]
I add some log, buffer claim is committed.

![image](https://user-images.githubusercontent.com/4532524/27731460-96fc5020-5dbf-11e7-9718-65fff2b780fa.png)

**Comment by jordanxlj** [comment]
Subscriber have already processed term(-1134055397) termOffset(@27c0c0), but why it send NAK termOffset(@83fa0)?

The debug info is below, thanks.
[debug.txt](https://github.com/real-logic/aeron/files/1117216/debug.txt)

**Comment by nitsanw** [comment]
Hi @jordanxlj,
Archiver is under active development, not yet ready for use. Having said that, if you are keen to test it out and give us feedback that is great.
I'm looking into the issue you described and managed to reproduce for the case where ExclusivePublication is recorded with a starting position such that```termId != initialTermId``` which is not 0. I hope to have the issue resolve by EOD.
Thanks for reporting!

**Comment by nitsanw** [comment]
I've narrowed this down to what seems like an ExclusivePublication bug.

**Comment by nitsanw** [comment]
With @mjpt777 fix I can no longer reproduce this issue. Closing for now, but @jordanxlj please re-open if it doesn't fix your case.
Thanks again for reporting.
