### ISSUE TITLE
Question: BufferClaim wrt cleanBuffer

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#375]
Can you please confirm that the following is indeed an issue?

Following is a scenario showing a possible issue:

0) We setup two process so that one is a IPC subscriber and the other one an IPC publisher.

1) IPC publisher: Gets a BufferClaim via the Publication::claim. At this point the producerPosition is advanced but the header's frame-length < 0. This prevents the subscribers from moving past the start of the BufferClaim.

2) In the mean time, the IPC Subscriber deletes its subscription.

3) The Media Driver then stops calling cleanBuffer. At this point the consumerPosition is at most at the start of the BufferClaim.

4) A new subscriber comes back and join the stream at producerPosition. Meaning past the start of the BufferClaim...not commited yet.

5) The Media Driver then starts to call cleanBuffer. However, the memory region that it sets to zero
is overlapping with the BufferClaim region. If at this point we call BufferClaim::commit we are writing ahead of the producer position or  concurrently with the cleanBuffer.

It seems that a possible way to avoid this would be for the MediaDriver to wait untill all the frames length are set to > 0 between the consumerPosition and the new joinPosition prior to move on and drive the cleanBuffer based on the new set of subscribers. On the other hand, if the application crashed then these frameLength will never be set to zero. However this would mean the publisher is dead so I guess the MediaDriver would detect it. 

Sorry it is not easy to describes those threading issues.

**Comment by goglusid** [comment]
Thinking of of we could create a subscriber in the publisher process just to protect the claim buffer. Maybe we could have a built-in subscriber position within a publisher, when we call offer we would set it to the producer position and when we call the bufferclaim we would not advance it untill the BufferClaim::commit is called. This is just a thought.

**Comment by tmontgomery** [comment]
I think if you simplify the scenario, it might make more sense.

1 - producer claims message (claims spot in stream)
2 - current subscriber goes away, meaning no subscribers
3 - new subscriber comes in. Join position is _after_ last claimed message. I.e. claim message has no consequence and no consumers waiting on it.

Right at that point, anything before the producer position at the time of the new subscriber isn't going to be consumed by anyone. When a claim is done, it is claiming a spot in the stream. The commit is simply marking it safe to consume. The claim is the critical spot in the stream. Not the commit. The claim happened _before_ the new consumer was added to the stream.

The cleaning doesn't really matter to the message, honestly. It will never be consumed anyway. But also, the cleaning is held back from the trip-limit and proposed limit. Which prevents the cleaning from running over the consumers.

**Comment by goglusid** [comment]
My understanding is that the memory needs to be zeroed prior to be available for use by the publication.  Otherwise a consumer might read a garbage value among other thing for the frame-length. 

Committing a claimed message after the execution of the cleaning will set the frame length bytes to at least 32. 

When the publication wrap around and reuse that memory, a consumer may read a message that is not valid. That is if the frame length falls on the same term offset.

**Comment by mjpt777** [comment]
Thanks for reporting this. Initially @tmontgomery used the consumer position for this and I now believe his instincts were right. I later thought it made more sense to use the producer position to join at.

The main issue here is that in the case you describe it is possible to miss a blocked publisher that would be skipped over or worse they could come back as a zombie and corrupt the log.

**Comment by tmontgomery** [comment]
@goglusid ah. yes. Did not see the issue initially. 

Just something to point out. The cleaning position only moves with cleaning. This is the left edge of the cleaning window. The change that @mjpt777 put in keeps the edge from skipping over any non-committed messages.

**Comment by goglusid** [comment]
@tmontgomery  Indeed, joining at the consumerPosition prevents stepping over any uncommited messages. 

@mjpt777 I shall say thank you very much indeed! ;)
