### ISSUE TITLE
Closing Publication causes SEGV_MAPERR

### ISSUE THREAD

**Issue by tkowalcz** [real-logic/aeron#378]
We are running Aeron in production since a few days. It's a small setup with 100 TPS. So far we had two crashes on client machines (in almost the same time):

```
#  SIGSEGV (0xb) at pc=0x00007f4584f16917, pid=42614, tid=0x00007f350a469700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_112-b15) (build 1.8.0_112-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.112-b15 mixed mode linux-amd64 )
# Problematic frame:
# J 29382 C2 io.aeron.ClientConductor.onCheckTimeouts()I (218 bytes) @ 0x00007f4584f16917 [0x00007f4584f16620+0x2f7]

[...]

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 30137 C2 io.aeron.ClientConductor.doWork(JLjava/lang/String;)I (56 bytes) @ 0x00007fa5555d2bb1 [0x00007fa5555d2a60+0x151]
j  io.aeron.ClientConductor.awaitResponse(JLjava/lang/String;)V+47
j  io.aeron.ClientConductor.releasePublication(Lio/aeron/Publication;)V+44
j  io.aeron.Publication.close()V+43

```

The `Publication` was being closed during normal application operation (not shutdown) in respose to `Publication.isConnected()` returning false. So there must have been some timeouts or other communication problems?

Looking at our code it is entirely possible that while one thread was closing the publication other threads might have also tried the same or tried to offer data.

We are using Aeron 1.3.0.

**Comment by tmontgomery** [comment]
@tkowalcz A `Publication.close` lingers the Publication around a little while to avoid trampling from an offer. So, you have a short period of time to keep an offer/tryClaim thread from doing any harm. Although, it is a good practice anyway to avoid having another thread sending while trying to shutdown.

The stack looks like it is awaiting a response from the driver when it fails. And not in the offer/tryClaim calls stack. Are you doing any other cleanup when this type of situation occurs?

**Comment by mjpt777** [comment]
If a inter service timeout occurs in 1.3 then it quite aggressively closes down the client which can cause this issue if you have threads aggressively offering or using tryClaim.  The next release will have a linger on close to help avoid this. A long GC pause can cause the issue you are seeing with 1.3.

**Comment by tkowalcz** [comment]
@mjpt777 You are probably referring to #368? When can we expect new release?

@tmontgomery The `Publication` is held in a map keyed by destination address (right now there is only one configured). There are many threads trying to retrieve it from the map in order to `offer`. Before that call every thread will check if the publication is connected. If not then it will close it and do some reconnect stuff (may include closing the Aeron and MediaDriver).

**Comment by mjpt777** [comment]
@tkowalcz yes I am referring to the some of the changes to resolve issue #368. Maybe this week if all goes well.

**Comment by tkowalcz** [comment]
@mjpt777 Thank you. And indeed there was ~6s full gc.
