### ISSUE TITLE
C++ client: Subscription::poll does not check return value of Image::poll for IMAGE_CLOSED

### ISSUE THREAD

**Issue by lukeocamden** [real-logic/aeron#380]
Hello, it looks like a closed image will currently cause Subscription::poll to decrement fragmentsRead (since IMAGE_CLOSED is -1).

Should the return value be checked first? Or perhaps Image::poll should return 0 in case it is closed? It's hard to know why a caller would want to distinguish these cases.

**Comment by mjpt777** [comment]
It should return 0 to be consistent with the Java implementation.
