### ISSUE TITLE
No driver heartbeat detected

### ISSUE THREAD

**Issue by GenuineJyn** [real-logic/aeron#384]
when media driver run a period time,  run a pub or sub client as follows may occur:
 
No driver heartbeat detected. : aeron::util::MemoryMappedFile::ptr_t aeron::Aeron::mapCncFile(aeron::Context&) : /home/huawei/workspace/Aeron-master/aeron-client/src/main/cpp/Aeron.cpp : 131

I saw the media driver and client source code, the driver write a heartbeat every second,  there perhaps is some problems, but i don't know the reason.

**Comment by nitsanw** [comment]
Hi @GenuineJyn ,
Can you please give the following details:
- Aeron version(or git hash if you are building from source)
- I see you are running the C client, are you also running the C media driver
It would also be good if you can include the source code for a minimal reproduction of the issue, or a snippet of the relevant client code.
Thanks for reporting!

**Comment by GenuineJyn** [comment]
CNC_VERSION = 7;
I run a java media driver and a C++ client.
int Aeron.cpp:
116         while (0 == ringBuffer.consumerHeartbeatTime())                                             
117         {                                                                                           
118             if (currentTimeMillis() > (startMs + context.m_mediaDriverTimeout))                     
119             {                                                                                       
120                 throw DriverTimeoutException(std::string("No driver heartbeat detected."), SOURCEINFO);
121             }                                                                                       
122                                                                                                     
123             std::this_thread::sleep_for(IDLE_SLEEP_MS_1);                                           
124         }                                                                                           
125                                                                                                     
126         const long long timeMs = currentTimeMillis();                                               
127         if (ringBuffer.consumerHeartbeatTime() < (timeMs - context.m_mediaDriverTimeout))           
128         {                                                                                           
129             if (timeMs > (startMs + context.m_mediaDriverTimeout))                                  
130             {                                                                                       
131                 **throw DriverTimeoutException(std::string("No driver heartbeat detected."), SOURCEINFO);**
132             }                                                                                       
133                                                                                                     
134             cncBuffer = nullptr;                                                                    
135                                                                                                     
136             std::this_thread::sleep_for(IDLE_SLEEP_MS_100);                                         
137             continue;                                                                               
138         }

**Comment by mjpt777** [comment]
I'm going to close this for now as it cannot be recreated. If a test that reproduces it can be created then we will investigate.
