### ISSUE TITLE
Programmatically increase logbuffer size?

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#386]
Is there any way in Aeron to programmatically increase the size of a logbuffer? I'd like to offer a certain amount of data to a stream as a whole in my project, so when the receiver starts to read them it is guaranteed that all data are delivered and ready - nothing is not sent or on the fly. However if I don't know how much data I'm going to sent, they can be much more than the size of the logbuffer I set when the media driver is started. And looks like the size of the logbuffer is only configuration when I start the driver.

**Comment by tmontgomery** [comment]
The term length can be set on a per publication basis by passing it in the URI. At the moment, it is only documented in the Javadoc, though. Take a look at https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/ChannelUriStringBuilder.java

**Comment by bedding** [comment]
Dug into the API for a bit. Looks like I need to call addPublication/addSubscription to pass in the new size. As far as I can tell from the name of these two functions, they are going to create a new stream. So what's happening under the hood if I call addPublication on an existing stream and give it a new term buffer size? Does it close the old stream and create a new one? If not, how does it resize the buffer?
 By extending the existing buffer or reallocating a new one? And what will happen to the data in the buffer that has not been consumed by the subscriptions?

Sorry about so many questions ^_^ Response will be highly appreciated!!

**Comment by tmontgomery** [comment]
I would suggest you try it yourself for the exact case you want.

First, though, you can't call addPublication on an existing stream. Each time addPublication is called, it creates a Publication object. So, 2 calls creates 2 Publication objects. So, the second call has no impact on the first call. i.e. the existing Publication will be fine in all cases. Under the hood, the same logbuffer for both Publications may be used, though. And I suspect that is your real question.

The question is how does the second __non-exclusive__ addPublication with the same streamId and channel, but different term buffer size, get handled. The answer to that is that if the MTU or Term Length is different than the existing publication, then the addPublication will fail with an error back on the client.

`addExclusivePublication` is available for those situations where you have a single Publication and desire to not use any existing Publications. In this case, it will be 2 different Publications and logbuffers.

Resizing a term is not done after creation and not something we support.

**Comment by bedding** [comment]
Thank you for the reply! I will use a different approach to solve the problem.
