### ISSUE TITLE
:aeron-driver:test FAILED

### ISSUE THREAD

**Issue by maoxianfly** [real-logic/Aeron#39]
:aeron-driver:test

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldOnlyRemoveSubscriptionMediaEndpointUponRemovalOfAllSubscribers                                       FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldOnlyRemoveSub
scriptionMediaEndpointUponRemovalOfAllSubscribers(DriverConductorTest.java:287)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldNotTimeoutSubscriptionOnKeepAlive                                                                    FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldNotTimeoutSub
scriptionOnKeepAlive(DriverConductorTest.java:409)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldKeepSubscriptionMediaEndpointUponRemovalOfAllButOneSubscriber                                        FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldKeepSubscript
ionMediaEndpointUponRemovalOfAllButOneSubscriber(DriverConductorTest.java:262)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldTimeoutSubscription FA
ILED
    Wanted but not invoked:
    receiverProxy.addSubscription(<any>, 10);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyReceiverSubscr
ibes(DriverConductorTest.java:433)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyReceiverSubsc
ribes(DriverConductorTest.java:433)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldTimeoutSubscr
iption(DriverConductorTest.java:393)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToAddSingleSubscription                                                                        FAILED
    Wanted but not invoked:
    clientProxy.operationSucceeded(1429);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddSingleSubscription(DriverConductorTest.java:177)

    However, there were other interactions with this mock:
    -> at uk.co.real_logic.aeron.driver.DriverConductor.onClientCommand(DriverConductor.java:333)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddSingleSubscription(DriverConuctorTest.java:177)
Results: FAILURE (77 tests, 72 successes, 5 failures, 0 skipped)

77 tests completed, 5 failed
:aeron-driver:test FAILED

**Comment by tmontgomery** [comment]
Closing for now as lots has changed.
