### ISSUE TITLE
Aeron appender compatible with jul/slf4j/log4j/logback

### ISSUE THREAD

**Issue by krisskross** [real-logic/aeron#391]
Hi

Does anyone know of any project that have implemented an Aeron appender compatible with either of  jul/slf4j/log4j/logback?

Cheers,
-Kristoffer

**Comment by tmontgomery** [comment]
I don't know of any public ones.  Aeron is used in some internal logging frameworks that I know of that are not public.

Best place to ask would be on [gitter](https://gitter.im/real-logic/Aeron)
