### ISSUE TITLE
Gathering offer for Publications

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#394]
Add an `offer` method to `Publication` and `ExclusivePublication` that takes an array of buffers, offsets, and lengths for doing gathering sends. 

This allows for protocol encapsulation whereby a header(s) can be added to a payload without needing to copy the data to an intermediate buffer. This is particularly important for payloads larger than MTU as `tryClaim` cannot be used in this case.

**Comment by mjpt777** [comment]
Complete for Java and now need to add c++.

**Comment by nicklauslittle** [comment]
Can you make it an iterator for C++ rather than an array? I have a commit if you are interested in taking a look.

**Comment by tmontgomery** [comment]
I'll be looking at this this week. Porting of all the things!

**Comment by tmontgomery** [comment]
In terms of an iterator, maybe. Not a huge fan of anything but an array for this. But feel free to toss a PR and I will look at it.

**Comment by nicklauslittle** [comment]
Submitted PR #401
