### ISSUE TITLE
Excuse me， about  C/S Module！

### ISSUE THREAD

**Issue by cx421774557** [real-logic/aeron#395]
If the client is inside the LAN and publishes the message to the service side of the public network, how does the server publish the message to the client? Thanks for your help！

**Comment by tmontgomery** [comment]
I'm not following what you are referring to. Can you be more specific?

**Comment by cx421774557** [comment]
I'm sorry, my English is poor, I mean, how to push the message from the public network to the Intranet (the machine inside the LAN)?

**Comment by cx421774557** [comment]
Thank you vary much, i will try it. Have a nice life.
