### ISSUE TITLE
windows vs2015   gettimeofday not support

### ISSUE THREAD

**Issue by GenuineJyn** [real-logic/aeron#397]

**Comment by mjpt777** [comment]
Can you provide a better explanation and test case if possible?

**Comment by GenuineJyn** [comment]
compile cannot pass

**Comment by tmontgomery** [comment]
I'm not sure what you are referring to here. Aeron does not use `gettimeofday`. Google Mock/Test and/or Benchmark might, but they should be smart enough to know what platform they are on and act accordingly.

**Comment by GenuineJyn** [comment]
So sorry， I found One of my colleagues has modified the code and used gettimeofday().
