### ISSUE TITLE
Audience scope

### ISSUE THREAD

**Issue by thhart** [real-logic/aeron#398]
Hi, first of all thanks for this big framework and work on Aeron, however I wish more focus for Java application developers. IMHO the Wiki is mainly focused on network specialists and core developing of aeron. I give you a simple example: FragmentHandler - nowhere is the ImageFragmentAssembler mentioned, but as I see it is an important adapter to handle fragmented data delivered.
Further more the whole subscription/publishing scheme is very rare documented from a application point of view. And last but not least I would wish to be more in control of the network interfaces in use. It is absolutely transparent which interface is finally used. This is only a very short list of things without going to much in detail, but I think it might help to get a bigger audience for the framework at all.

**Comment by mjpt777** [comment]
We would welcome any help on this.
