### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by thhart** [real-logic/aeron#399]
I can see a constant CPU utilization ~10-20% on a i7 4 core no matter what IdleStrategy I use. I tested with BackoffIdleStrategy and a custom Strategy for context and subscriberLoop like this:

`new BackoffIdleStrategy(1024, 512, TimeUnit.MILLISECONDS.toNanos(10), TimeUnit.MILLISECONDS.toNanos(250))`

If I debug the system it turns out the AgentRunner constantly triggers BackoffIdleStrategy with a workload of 32 which results in a reset. What might be the reason for this?

Aeron version: 1.4.1

**Comment by mjpt777** [comment]
The focus for Aeron so far has been low-latency and high-throughput. We are beginning to look at ways of better supporting lower resource systems but this is not a priority. I'll have a look later this week to see what I can find if I can replicate your test.

**Comment by mjpt777** [comment]
There are many threads and idle strategies that can be applied in Aeron. Can you provide more details on which thread this is applied to? I'm struggling to recreate what you are seeing.

Also can you explain how you came up with figures you passed to the `BackoffIdleStrategy`? The number for yields seems very high.

**Comment by guidomedina** [comment]
I had the same issue when I started using `akka-remote` based on Aeron, here is how I resolved it, using the following function which uses a parameter called `IDLE_CPU_LEVEL` which is between 1 and 10 where one is sleeping, from 2 to 9 is using a back off and 10 a busy spin:

https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/TaskRunner.scala#L93

Here is my shared driver, code, I use it on development environment, UAT which are virtual machines and production, hope it helps, for your case start at 2 and see how's that look for you:
```
import com.typesafe.config.Config;
import io.aeron.driver.MediaDriver;
import io.aeron.driver.ThreadingMode;
import org.agrona.concurrent.*;

import java.io.File;

import static com.typesafe.config.ConfigFactory.parseFile;
import static java.util.concurrent.TimeUnit.MICROSECONDS;
import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.agrona.BitUtil.findNextPositivePowerOfTwo;

public class MediaDriverMain {

  public static IdleStrategy createIdleStrategy(int idleCpuLevel) {
    switch (idleCpuLevel) {
      case 1:
        return new SleepingIdleStrategy(MILLISECONDS.toNanos(1));
      case 10:
        return new BusySpinIdleStrategy();
      default:
        return new BackoffIdleStrategy(
          1100 * idleCpuLevel - 1000,
          5 * idleCpuLevel,
          1,
          MICROSECONDS.toNanos(280 - 30 * idleCpuLevel));
    }
  }

  public static void main(String[] args) {
    final Config config = parseFile(new File(args[0])).getConfig("aeron");
    final int idleCpuLevel = config.getInt("idle_cpu_level");
    if (idleCpuLevel < 1 || idleCpuLevel > 10) {
      System.out.println("Invalid IDLE_CPU_LEVEL, valid values are from 1 to 10.");
      return;
    }
    final int termBufferSize = findNextPositivePowerOfTwo(config.getInt("term_buffer_size"));
    if (termBufferSize < 2 || termBufferSize > 16) {
      System.out.println("Invalid TERM_BUFFER_SIZE, valid values are 2, 4, 8 or 16.");
      return;
    }
    System.out.println("Starting media driver with IDLE_CPU_LEVEL = " + idleCpuLevel + " and TERM_BUFFER_SIZE = " + termBufferSize);
    try (MediaDriver ignored = MediaDriver.launch(new MediaDriver.Context().
      aeronDirectoryName("/dev/shm/aeron").
      termBufferSparseFile(false).
      threadingMode(ThreadingMode.DEDICATED).
      conductorIdleStrategy(createIdleStrategy(idleCpuLevel)).
      receiverIdleStrategy(createIdleStrategy(idleCpuLevel)).
      senderIdleStrategy(createIdleStrategy(idleCpuLevel)).
      publicationTermBufferLength(termBufferSize * 1024 * 1024).
      dirsDeleteOnStart(true))) {
      System.out.println("Media driver started successfully - waiting for a SIGTERM to exit.");
      new ShutdownSignalBarrier().await();
    } finally {
      System.out.println("Media driver has been shutdown.");
    }
  }
}
```

I'm using https://github.com/typesafehub/config for the configuration passed to that executable and here is a sample configuration:
```
aeron {
  idle_cpu_level = 5
  term_buffer_size = 8
}
```

Hope that helps, @mjpt777 ideas on tuning this example shared driver are very welcome ;-)

**Comment by guidomedina** [comment]
The reason for `term_buffer_size` is because such environments have little RAM, so for example, I have 5 JVMs using the same shared driver which the default which is 16m will consume too much shared memory, hence the tune-ability of the buffer.

**Comment by tmontgomery** [comment]
@guidomedina You might look at [`ControllableIdleStrategy`](https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/ControllableIdleStrategy.java) and it's usage in Aeron. It's an idle strategy that can be controlled via a status indicator. So, it is possible to have something else signal to the strategy what mode it should be operating in.
