### ISSUE TITLE
Multiple interface support

### ISSUE THREAD

**Issue by thhart** [real-logic/aeron#400]
I am looking to be able to broadcast (multicasted) to all network interfaces in a host. Is this possible or should I subscribe manually to each interface?

**Comment by mjpt777** [comment]
The question seems conflated. Maybe I'm misunderstanding. If you are sending then you can add routes for each of the interfaces you want to send to. This is a Linux, or other OS thing, and not a specific Aeron question. If you are talking about receiving then you can do a default subscribe, or you can subscribe on a specific interface with Aeron, i.e. add the interface param to the channel configuration.

Can you provide more details on the usecase you are trying to address?

**Comment by mjpt777** [comment]
Closing due to no follow up.
