### ISSUE TITLE
hi, i'm complie have  some error, 

### ISSUE THREAD

**Issue by cx421774557** [real-logic/aeron#405]
this file <aeron-client/src/main/cpp/util/MemoryMappedFile.cpp>  line 176， if  PAGE_SIZE has defined, i will have a error , so i think i should set a Macro switch.

**Comment by cx421774557** [comment]
but now i have a new error, if complie for GCC arm, i think the aeron inline asm is x86 instruction set，

**Comment by tmontgomery** [comment]
I've changed the member name to avoid macro substitution going wild here.
