### ISSUE TITLE
checkTerm wrt Publication's Limit

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#407]
@mjpt777 

I would like your feedback on the following:

It seems to me (still not sure) that checkTerm(activeTermId, termId) {...if (termId != expectedTermId)...}

could be improved to fail less often by a re-validation of the publication's limit:

if (termId != expectedTermId)
{
  const std::int64_t limit = m_publicationLimit.getVolatile();
  const std::int64_t position =
                LogBufferDescriptor::computeTermBeginPosition(
                    termId, m_positionBitsToShift, m_initialTermId) + termOffset + alignedLength;

  if (position > limit) {... fail}
}

Indeed, not having the same termId isn't a problem has long as the slowest consumer has consumed the messages and
that the media driver has reset to zeroes the memory about to be touch. Which is the definition of the pub limit.

Assuming it is the case then, this would leave an unset messages (all zeroes), this would be later unblocked by the media driver.

**Comment by mjpt777** [comment]
If this happens then the publisher is at least 3 terms behind and expectations of latency are seriously in question. I'd prefer to keep it simple and notify that system is under resourced. If you care about performance then running on machine with insufficient cores to run active threads is not a good place to be. 

All that being said it is best to reduce the potential states and instruction where possible and rechecking the publication limit and trying to make progress goes against that.

**Comment by tmontgomery** [comment]
This also would create coupling between flow control and TermAppender. Which is not desirable.

**Comment by goglusid** [comment]
Todd, Martin, 

I concur with you. It is after all an abnormal situation and increasing coupling and state/instructions is not worth it. 

When a publication is at least 3 terms behind and happens to be in the current active term then incrementing the rawTail will reserve a space that will stay uninitialized untill the media driver unblocks it. This would delay the associated subscriptions by the unblock period. Validating against the pub limit would avoid this additional delay but would require even more code. :s And subscriptions threads aren't probably running anyway if a publication is 3 term behind!

Thank you very much for answering rapidly. Kindest Regards

Sidney
