### ISSUE TITLE
C++ Client: ${HDRHISTOGRAM_LIBS} -> hdr_histogram dependency is not delcared

### ISSUE THREAD

**Issue by lukeocamden** [real-logic/aeron#411]
Hello, PingPong depends on ${HDRHISTOGRAM_LIBS} but these are not declared to depend on hdr_histogram so PingPong may erroneously be built before hdr_histogram. I guess you would need something like:

```
foreach(hdrhistogram_lib ${HDRHISTOGRAM_LIBS})
    add_dependencies(${hdrhistogram_lib} hdr_histogram)
endforeach()
```

Alternatively you could say add_dependencies(PingPong hdr_histogram) like you do for Ping.

Does that make sense?

**Comment by tmontgomery** [comment]
Dependency added for PingPong. Thanks for pointing this out.
