### ISSUE TITLE
Publication's Limit condition

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#413]
Shouldn't we check for the Publication and ExclusivePublication's backpressure condition in the following way? Otherwise, we could write beyond the publication limit.

inline std::int64_t offer(
        concurrent::AtomicBuffer& buffer,
        util::index_t offset,
        util::index_t length,
        const on_reserved_value_supplier_t& reservedValueSupplier)
{
...

const std::int64_t limit = m_publicationLimit.getVolatile();
...

if (position **+ length** < limit)

**Comment by mjpt777** [comment]
It was an arbitrary decision but we decided to limit on beginning and not end of a message.

**Comment by goglusid** [comment]
But the limit isn't the slowest subscription? Writing past the pub limit will overwrite data not yet read by at least one subscription. No?

**Comment by mjpt777** [comment]
The limit is only 1/2 a term greater than slowest consumer and we have 3 terms.

**Comment by mjpt777** [comment]
1/2 term is the case for network publication and 1 term for IPC.

**Comment by goglusid** [comment]
Indeed! sorry ;[
