### ISSUE TITLE
Potential archive segment filename collision

### ISSUE THREAD

**Issue by zyulyaev** [real-logic/aeron#414]
Because of a typo in this line:
https://github.com/real-logic/aeron/blob/b55b005d6210f0622585793d8f80ef1a5488db6c/aeron-archive/src/main/java/io/aeron/archive/Archive.java#L756
one may get the same filename for different recordingId and segmentIndex pair. E.g. recordingId=1, segmentIndex=2 and recordingId=2,segmentIndex=1 gives you the same filename.

Solution is to replace single quotes with double quotes, so the line looks like:
```
return recordingId + "-" + segmentIndex + Configuration.RECORDING_SEGMENT_POSTFIX;
``` 
I believe this is what it was intended to be.

**Comment by mjpt777** [comment]
Thanks. Yes you are correct. I've pushed a fix.
