### ISSUE TITLE
Aeron-archive JAR file does not contain SBE-generated classes

### ISSUE THREAD

**Issue by kudryashov** [real-logic/aeron#416]
aeron-archive JAR (I checked versions 1.4.1, 1.5.0, 1.5.1) does not contain the SBE-generated classes, such as  io.aeron.archive.codecs.RecordingDescriptorDecoder. This makes aeron-archive not usable out of the box - one has to use the aeron-all artifact that luckily contains everything.

It looks like this is due to a typo in the build.gradle: in the aeron-archive project configuration instead of:
```
    jar {
        from("${buildDir}/classes/generated") {
            include '**/*.class'
        }
    }
```

there probably should be 
```
    jar {
        from("${buildDir}/classes/java/generated") {
            include '**/*.class'
        }
    }
```

**Comment by mjpt777** [comment]
Yes you are right they are not in the archive JAR. They are in the archive-all.jar and aeron-all.jar.  However this should be fixed.
