### ISSUE TITLE
Spotted spikes with Publication::offer()

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#419]
I have seen spikes with Publication::offer() in my project, in order to verify that I wrote a simple test with 1 IPC publication thread and 1 IPC subscription thread running concurrently. The publisher puts 5MB data by calling offer() 5 times every 30ms, so that's 1MB data per offer() call. The subscriber is running an infinite loop to poll data off of the stream as soon as it as can. And I observed that time spent on offer sometimes spikes to 100+ ms and the worst case I've seen is 470 ms. I wonder if there is something I did wrong. code is here: https://gist.github.com/bedding/edb18c7926e9caac8dc52e7fc8697cc3

I edited a little bit so there might be some syntax errors if you try to run it.

Following is the aeron media driver setting I used in this test,
`aeron.ipc.threading.mode=DEDICATED`
`aeron.shared.idle.strategy=org.agrona.concurrent.NoOpIdleStrategy`
`aeron.ipc.term.buffer.length=134217728`

The hardware it's running has 60GB memory.

Thanks!

**Comment by mjpt777** [comment]
Have you run JHiccup on your machine at the same time to see if it is suffering any systemic pauses?

https://www.azul.com/downloads/jhiccup/

**Comment by bedding** [comment]
I can give it a try. Just FYI, the hardware is a c4.8xlarge EC2 instance.

**Comment by bedding** [comment]
So I ran jHiccup by attaching it to the media driver. Following is the generated diagram,
![capture](https://user-images.githubusercontent.com/3995964/31838332-315dd264-b591-11e7-969b-aefd123d9e80.PNG)

The gap the the beginning is because the test has been running for a while before I attach jhiccup to the driver process.

**Comment by mjpt777** [comment]
During that run did you have offer times greater than 4ms? If so, what filesystem is containing the aeron directory? Are you seeing IO latency there? Have you profiled the IO to ensure you are not getting page faults on those memory mapped files? It maybe some odd issue with Aeron but given the magnitude of those pauses it is more likely something in that environment that needs discovering and tuning. If not on native OS then these things can be difficult to track down.

**Comment by bedding** [comment]
It is the problem of the aeron directory I used with the test! I set it to be under a regular file system not tmpfs. I'm not seeing any spikes now. Thanks for the help!
