### ISSUE TITLE
LogBufferUnblocker::unblock activeTermCount/expectedTermCount 

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#424]
For the following function, if the following situation happens then the blockedoffset is used with the wrong term id.

IF 

blockedPosition is within TermId = 0 (the second half because otherwise the pub=lmt doesn't cross two terms)
activeTermCount is now at 1

Then

index = 1
termId = 1

However given that blockedOffset refers to term 0, working with termBuffers[index] doesn't make sense. 

It seems like we should use the expectedTermCount to compute the index instead.

LogBufferUnblocker::unblock()
{
        final int termLength = termBuffers[0].capacity();
        final int positionBitsToShift = Integer.numberOfTrailingZeros(termLength);
        final int activeTermCount = activeTermCount(logMetaDataBuffer);
        final int expectedTermCount = (int)(blockedPosition >> positionBitsToShift);
        final int index = indexByTermCount(activeTermCount);
        final long rawTail = rawTailVolatile(logMetaDataBuffer, index);
        final int termId = termId(rawTail);

...

        final int tailOffset = termOffset(rawTail, termLength);
        final int blockedOffset = computeTermOffsetFromPosition(blockedPosition, positionBitsToShift);

}

**Comment by tmontgomery** [comment]
You are talking about the Java code and not the C++ code, correct... the use of "::" had me confused.

If I follow your logic, there are some tests for this case. Specifically, doesn't `shouldUnblockWhenPositionHasNonCommittedMessageAndTailPastEndOfTerm` work how you mention? Or at least the spirit of it.

If I don't understand the test case, it should be straight forward to construct it in `LogBufferUnblockTest.java`.

**Comment by mjpt777** [comment]
I think this is an issue in the Java code. I've been testing and about to push a fix. It has been a typo when I realised a missing case and my solution is not right.

**Comment by mjpt777** [comment]
It would be good to review if what I pushed makes sense.

**Comment by mjpt777** [comment]
That last push has an issue. I'm fixing.

**Comment by tmontgomery** [comment]
Let me know when you are happy and I will review and reflect on the C side.

**Comment by goglusid** [comment]
The reported issue is applicable to Java and C. 

For the unblock section of the code I think we should use expectedTermCount.

For the rotateLog sections, I think we should still use the activTermCount though.

**Comment by goglusid** [comment]
Sorry I replied too rapidly I will review the latest changes later and post my feedback

**Comment by tmontgomery** [comment]
@goglusid I'm jetlagged badly, so it takes very little to confuse me. ;)

**Comment by goglusid** [comment]
The latest changes resolved the issue. ;) Thanks
