### ISSUE TITLE
[C++] Have a version of Aeron::connect that take a unique_ptr<Context>

### ISSUE THREAD

**Issue by mikeb01** [real-logic/aeron#425]
So that the Aeron client takes ownership (and the ownership is explicitly stated) of the Context and its lifecycle does not need to be managed separately.

**Comment by lukepalmer** [comment]
Interested as well. Similar to #529, where @tmontgomery  says:

> I would like to make this cleaner. But changing the API has some issues for current users.

**Comment by mjpt777** [comment]
`Context` is copied after conclude so no need for `unique_ptr`.
