### ISSUE TITLE
ExclusivePublication wrt MediaDriver's rotateLog

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#428]
My understanding is that the ExclusivePublication assumes that it is the only one to drive its rawTail and activeTermCount.

As such, it uses non-atomic local variables such as the activePartitionIndex, m_termId and m_termOffset.
It also changes its rawTail using LogBufferDescriptor::initializeTailWithTermId(m_logMetaDataBuffer, nextIndex, nextTermId); which doesn't use the ordered version or a CAS to do so.

However, because the media driver can now rotateLog, it is not the case (that it is the only one driving rawTail and activeTermCount).

It is seems to me that allowing any thread to deal with term tripped is problematic for the ExclusivePublication.

**Comment by mjpt777** [comment]
This is a good observation. However consider what can happen. When I considered it the log is only rotated by one publisher. This means that if the publisher pauses and the driver rotates by unblocking then the publisher will set it to the same same value it is. If the publisher wins then the driver is CAS'ing and so will make no difference. I went with this to keep the code consistent. Do you think I missed something?

**Comment by goglusid** [comment]
Indeed, having a rawTail going forward (driver's rotateLog and then backward (publication) could happen. I will go through the code again to see what side effects this would have. I will comment again later with my conclusion.

That being said, shouldn't we use the ordered version of put for the LogBufferDescriptor::initializeTailWithTermId? I'm not sure about a normal write wrt CAS.

**Comment by mjpt777** [comment]
It should not go forward and then back. The only race is to set it to the same value. It is a race but should be a benign race.

**Comment by goglusid** [comment]
It must be the Halloween effect...I see bug's ghost everywhere! ;)
