### ISSUE TITLE
[Java] Misleading Publication javadoc

### ISSUE THREAD

**Issue by zyulyaev** [real-logic/aeron#429]
Publication's javadoc [line](https://github.com/real-logic/aeron/blob/c9f8eb13dcc6766f382230d3066e21ff93d1b3d9/aeron-client/src/main/java/io/aeron/Publication.java#L31) and [line](https://github.com/real-logic/aeron/blob/c9f8eb13dcc6766f382230d3066e21ff93d1b3d9/aeron-client/src/main/java/io/aeron/Publication.java#L33) are misleading as there is ExclusivePublication extending Publication for which these statements are incorrect.

**Comment by mjpt777** [comment]
Yes. Thanks for spotting that.
