### ISSUE TITLE
How to publish big msg zero copy?

### ISSUE THREAD

**Issue by hank-whu** [real-logic/aeron#432]
publication.tryClaim(2 * 1024 * 1024, bufferClaim) 

java.lang.IllegalArgumentException: Claim exceeds maxPayloadLength of 4064, length=2097152

**Comment by mjpt777** [comment]
The largest claim is `Publication.maxPayloadLength()` which is the MTU length minus header. MTU defaults to 4KB but can be up to just under 64KB. This is the length of a Aeron fragment.

**Comment by hank-whu** [comment]
so there is noway to send zero-copy big msg (e.g 2mb) ?

**Comment by mjpt777** [comment]
No because it needs to be fragmented and have headers applied to each fragment.
