### ISSUE TITLE
Performance comparison between Linux and Windows

### ISSUE THREAD

**Issue by Jsky1989** [real-logic/aeron#433]
I did a simple test between Linux and Windows by samples, both java client.

Throughput is very good in Linux, about 2.5kw msg/sec, but under the windows only 200w msg/sec.

What is caused by the operating system?

PS:  I set SO_SNDBUF and SO_REVBUF to 1M in Windows, but it doesn't work. 
[HKEY_LOCAL_MACHINE \SYSTEM \CurrentControlSet\Services\Afd\Parameters]
DefaultReceiveWindow = 1048576
DefaultSendWindow = 1048576

**Comment by mjpt777** [comment]
Is this between machines or over local loopback? If loopback then I see Windows achieve about 50-60% the throughput of Linux if Windows 10 and Linux 4+ kernel. Older Windows is much slower. Linux has a highly optimised stack for loopback compared to Windows in default mode. Windows has SIO_LOOPBACK_FAST_PATH  for TCP which can be enabled per socket and got added in Java 8 update 60.

If I'm reading you correctly you are suggesting it is more than an order of magnitude slower which suggests something more serious is going on.

**Comment by Jsky1989** [comment]
Thank you for reply, the above result tested in local loopback. I re-tested local loopback in Windows server 2008, throughput about 700w msg/s. The result of several other scenes is (Linux 4+ kernel local loopback : 2.5kw msg/sec), (Linux 4+ - between machines : 200w msg/sec), (Windows server 2008 between machines: 100w msg/sec).

In addition, is there a plan to official support aeron golang client? 
I find this project(https://github.com/lirm/aeron-go), but it does not seem very active, Cnc file version only support up to 5.

**Comment by mjpt777** [comment]
I hear there is interest in advancing the Go client again from @stanliberman. Good to encourage it. A lot of contributions happen on peoples own time.  I know a number of people are interested in this one.
