### ISSUE TITLE
Allow ArchiveContext to be configured with an instance of AeronContext

### ISSUE THREAD

**Issue by BrassyPanache** [real-logic/aeron#443]
I hope to start an `ArchivingMediaDriver` with an non-default Aeron directory.  I can't do this using only Java code by way of building the required contexts (`Archive.Context` and `MediaDriver.Context`).  I believe I can change the directory using command-line provided properties, however I'd like to be able to do the former.

Using `Aeron.Context`, the directory can be changed with the call `Aeron.Context().aeronDirectoryName("/tmp")`. However when trying to create an `ArchivingMediaDriver`, the only mechanism to supply this setting is by passing in an already instantiated instance of `Aeron` as follows: `new Archive.Context().aeron(aeron)`.  As there is currently no `MediaDriver` running (remember the aim is to start one), calling `Aeron.connect()` fails.

I believe allowing an instance of `Archive.Context` to be configured with an instance of `Aeron.Context` would solve the issue.  This would allow `Archive.Context` to create an instance of Aeron with the provided settings.

**Comment by mjpt777** [comment]
This was addressed with the following commit and will be in the next release.

https://github.com/real-logic/aeron/commit/ef13afbd1cdd21d8e89af2e60b7c2cb15ec86f63

**Comment by BrassyPanache** [comment]
Thanks for the quick reply.
