### ISSUE TITLE
aeron-driver would generate a segment fault while removing subscriber

### ISSUE THREAD

**Issue by rayqi36** [real-logic/aeron#446]
![image](https://user-images.githubusercontent.com/13432546/34025498-227050a8-e18b-11e7-923d-b650c15c3a96.png)

The aeron-dirver version I used is 1.6.0. I start a aeron-client program which including 2 subcribers  to subscribe to the driver and stop it immediately . Try this several times, the driver would generate segment fault. The channel is IPC.

the image below is trying to print this process
![image](https://user-images.githubusercontent.com/13432546/34025650-fc235160-e18b-11e7-9f8f-aef449caa8fd.png)

everything is ok until the counter id skip the 40.

The problem seems to happen by chance , not every time.

**Comment by rayqi36** [comment]
The code in my program is below

std::int64_t subid = aeron->addSubscription(recvchannel, recvstream);
std::shared_ptr<Subscription> subscription = aeron->findSubscription(subid);
subscription = aeron->findSubscription(subid);

while (!subscription)
{
    std::this_thread::yield();
    subscription = aeron->findSubscription(subid);
}
fragment_handler_t handler = AeronMessageHandler();                                                                                                                                        



subid = aeron->addSubscription(recvchannel, recvbpstream);
std::shared_ptr<Subscription> bpsubscription = aeron->findSubscription(subid);
bpsubscription = aeron->findSubscription(subid);
while(!bpsubscription){
    std::this_thread::yield();
    bpsubscription = aeron->findSubscription(subid);
}

fragment_handler_t bphandler = BPMessageHandler();

while(running){
     int fragmentsRead = subscription->poll(handler, 100);
     fragmentsRead = bpsubscription->poll(bphandler,100);
}

**Comment by tmontgomery** [comment]
Try with the latest. fefc259b6613175946bc07fa4172fffe249f6fe6 is a change that should address this.

**Comment by rayqi36** [comment]
I will try it and write the feedback. Thanks

**Comment by rayqi36** [comment]
I have run the driver for a week and have never found it core dump again
