### ISSUE TITLE
Add the ability to create a subscription for a channel, stream id, and session id triplet

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#449]
Rather than subscribe for all sessions on a stream id and channel paring it would be useful to be able to create a subscription for a specific session. This would be useful for setting up the recording of a specific publication or could be used for the subscribing to the replay of a specific recording.

Later the ability to create a publication with a specific session could be added for pairing up request and response channels.

**Comment by tmontgomery** [comment]
This should be fairly straight forward. It does change a couple checks, but it should not require new state be added. It will require a new tombstone in the data packet dispatcher for the possibility of unwanted session Ids.

**Comment by mjpt777** [comment]
The `session-id` can be a filter as a channel param so the API does not need to be modified.

**Comment by mjpt777** [comment]
This is done now for the Java driver and needs porting to C.
