### ISSUE TITLE
Invalid pointer errors in aeron_uri_test.cpp

### ISSUE THREAD

**Issue by JeffGreen** [real-logic/aeron#450]
Hello!  

The `shouldNotParseInvalidUriScheme` and `shouldNotParseInvalidUriScheme` tests in aeron_uri_test.cpp fail with invalid pointer errors when running cppbuild -b.  

I'm far from an expert in C++ or Aeron, but with my limited understanding I'm wondering if this is due to an attempt to aeron_free() / free() of an uninitialized URI in the UriTest destructor:

[aeron_uri_close(&m_uri);](https://github.com/real-logic/aeron/blob/539df260b3cfe662ef848035f3b33e8b1246cab7/aeron-driver/src/test/c/aeron_uri_test.cpp#L45)

Since the URIs are invalid I'm guessing they don't get initialized to valid values and that this causes an issue with [aeron_uri_close](https://github.com/real-logic/aeron/blob/25a5858d5359752c6c0e7a3b0701db04b7feebc4/aeron-driver/src/main/c/uri/aeron_uri.c#L96)?

**Comment by tmontgomery** [comment]
Thanks! This is now addressed by initializing the type to UNKNOWN.
