### ISSUE TITLE
[Feature Request] Blocking poll()

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#453]
All the poll() functions in Subscription class are non-blocking. I think it would be very helpful if Aeron can provide a blocking version of poll() function, which is only waken up when a new fragment is available. This can save the CPU time that is wasted by the client application on busy waiting for new fragments to come.

I understand that one of the design principles of Aeron is to avoid blocking I/O in the message path, but it would be super useful to offer both APIs for developers to choose from. For example, they can use the blocking API to give resources to other processes when there is no new fragment if the application is running in a multi-tenancy environment.

Thank you!

**Comment by mjpt777** [comment]
A number of people have requested this but no one has been willing to sponsor the development. It is not something we would add without a major client that sponsored the development.

**Comment by bedding** [comment]
As far as I know, poll() checks frameLength from the term buffer to determine whether new fragment has arrived. How would you recommend to implement this blocking API if we wanted to do it ourselves?

**Comment by mjpt777** [comment]
Sorry but I don't have time at present to go into the details of a possible design. I'll close this now and it can be reopened if someone is willing to sponsor the development.
