### ISSUE TITLE
Question: Java Vs C++ IPC Throughput

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#457]
Hi,

I just ran the following 3 tests with the Java and C++ version of  Aeron:

a) Aeron Java 64 bits: ~23 M msg/s  with 96 Bytes/Frame   (using Publication::offer) 
b) Aeron Java 64 bits: ~43 M msg/s  with 96 Bytes/Frame   (using ExclusivePub::offer) 
c) Aeron Java 64 bits: ~900 K msg/s with 8032 Bytes/Frame (using ExclusivePub::offer) 

a) Aeron C++ 32 bits: ~6.3 M msg/s with 96 Bytes/Frame   (using using Publication::offer) 
b) Aeron C++ 32 bits: ~11 M msg/s with 96 Bytes/Frame   (using using ExclusivePub::offer)                      
c) Aeron C++ 32 bits: ~700 K msg/s with 8032 Bytes/Frame (using using ExclusivePub::offer)             

I also tested with a Aeron C++ 64 bits and got similar results. My compiler is VS2017.

In both cases, the java media driver is using a busy spin strategy.

**Is this difference in performance between Java and C++ what you expected?** 

Regards

**Comment by tmontgomery** [comment]
Why use 32-bit C++?

**Comment by mjpt777** [comment]
By similar do you mean that the 64-bit C++ is similar to Java 64-bit?

**Comment by tmontgomery** [comment]
I don't think the build optimizes for VS2017 compiler options by default. You would have to pass them in via the cmake command or do it via the IDE after project generation.

Also, the msvc atomic methods are fairly totalitarian. i.e. they could be made less restrictive and let code flow more. Enabling better optimizations.

**Comment by goglusid** [comment]
I meant C++ in 32/64 bits have similar results.

I ran the tests again but this time using different CPU using the affinity of the driver/test application.

a) Aeron C++ 32 bits: ~10 M msg/s with 96 Bytes/Frame   (using using Publication::offer) 
b) Aeron C++ 32 bits: ~26 M msg/s with 96 Bytes/Frame   (using using ExclusivePub::offer)                      
c) Aeron C++ 32 bits: ~620 K msg/s with 8032 Bytes/Frame (using using ExclusivePub::offer)     

I compiled with /O2 using VS2017 Pro.

**Comment by tmontgomery** [comment]
The `thread_fence()` in https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp/concurrent/atomic/Atomic64_msvc.h is probably strangling some optimizations. Also, /O2 may not be the best option.

**Comment by goglusid** [comment]
Thanks for the hint. If I find a way to speed up that thing, I'll comment.

**Comment by tmontgomery** [comment]
Thanks! Please do!

**Comment by goglusid** [comment]
@tmontgomery I tested with an empty thread_fence (no readwrite barrier) and it didn't affect the performance. It is not this. I also ran two thread publishing on the same stream id with one subscription.  I almost double the throughput. So it appears to be the publication that is too slow compared to the Java counterpart...on the same PC!

**Comment by mjpt777** [comment]
@goglusid Are you testing 32 or 64 bit C++ and compared to what word size for Java?

**Comment by goglusid** [comment]
@mjpt777 I am testing both C++ in 32/64 bits but I don't see a major difference between these two. The ~2X difference in throughput is between C++ 32/64 bits and Java. 

I assume Java is in 64 bits. I don't know how to check that except by using the following command:

java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by mjpt777** [comment]
You are running 64-bit Java.

> Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by goglusid** [comment]
Ok I now lost all possible credibility. :s Don't ask what happened before...it is too silly. I re-ran the "real" 64 bits Aeron C++ executables and this is what I got. This issue is definitely closed! Sorry.

a) Aeron Java 64 bits: ~23 M msg/s  with 96 Bytes/Frame   (using Publication::offer) 
b) Aeron Java 64 bits: ~43 M msg/s  with 96 Bytes/Frame   (using ExclusivePub::offer) 
c) Aeron Java 64 bits: ~900 K msg/s with 8032 Bytes/Frame (using ExclusivePub::offer) 

a) Aeron C++ 32 bits: ~10 M msg/s with 96 Bytes/Frame   (using using Publication::offer) 
b) Aeron C++ 32 bits: ~16 M msg/s with 96 Bytes/Frame   (using using ExclusivePub::offer)                      
c) Aeron C++ 32 bits: ~620 K msg/s with 8032 Bytes/Frame (using using ExclusivePub::offer)                     

a) Aeron C++ 64 bits: ~19 M msg/s with 96 Bytes/Frame   (using using Publication::offer) 
b) Aeron C++ 64 bits: ~37 M msg/s with 96 Bytes/Frame   (using using ExclusivePub::offer)                      
c) Aeron C++ 64 bits: ~630 K msg/s with 8032 Bytes/Frame (using using ExclusivePub::offer)

**Comment by mjpt777** [comment]
On a quite review a number of these approaches are out of date. I'll look at updating which should give more performance.

**Comment by mjpt777** [comment]
@goglusid Please try with the latest build and see if it improves things.

**Comment by goglusid** [comment]
:D Thanks!

a) Aeron C++ 64 bits: ~[18, 19] M msg/s with 96 Bytes/Frame   (using using Publication::offer) 
b) Aeron C++ 64 bits: ~[38, 39] M msg/s with 96 Bytes/Frame   (using using ExclusivePub::offer)                      
c) Aeron C++ 64 bits: ~ 1 M msg/s with 8032 Bytes/Frame (using using ExclusivePub::offer)

**Comment by tmontgomery** [comment]
@mjpt777 the changes are what I suggested above. Also, msvc could use a few other changes. But they get a little more invasive.

**Comment by goglusid** [comment]
I assume similar changes using aeron_acquire/release  are also needed in the C media driver.

**Comment by tmontgomery** [comment]
The C media driver isn't ported to MSVC yet. When it does, we'll use compatible operations.
