### ISSUE TITLE
Question: What is the correct way to configure subscriptions and publications for NAT traversal?

### ISSUE THREAD

**Issue by io7m** [real-logic/aeron#459]
Hello.

I've been putting together a small client/server example in an attempt to gain an understanding of the API. I have a basic example working that sets up a pair of publications and subscriptions in order to have two-way communication between the client and server. It works as follows:

1. Server creates a subscription `ss` with address/port `10.8.0.1:9999`. This subscription is used to read messages from clients. It configures `AvailableImageHandler` and `UnavailableImageHandler` implementations to handle new client connections (explained in step `4`).

2. Client creates a subscription `cs` with address/port `10.2.0.1:9999`. This subscription is used to read response messages from the server.

3. Client creates a publication `cp` with address/port `10.8.0.1:9999`. It sends an introductory message to the server containing the address/port of `cs`.

4. The server's `AvailableImageHandler` receives the client message containing `cs` and creates a new publication using the address/port of `cs`. From this point on, all messages addressed to this client will be sent to the address/port of `cs` by the server.

At this point, both the server and client have a pair of publications and subscriptions that they can use to talk to each other. Multiple clients are not a problem; the image handlers are provided with the subscriptions of new clients (via `Image.subscription()`) and create matching publications based on the introductory messages sent by clients.

This is all fine, but it obviously breaks if the client is behind NAT: Firstly the client can't know what its *public* address is (because it's behind NAT) so it can't tell the server where replies should go. Secondly... Even if it could tell the server, the server's response packets wouldn't make it through NAT unless their destination address/port just coincidentally happened to match the source address/port of packets sent by the client. Todd mentioned to me on Gitter that a (minor) limitation of the current Aeron implementation is that a single address/port can't be used for both reading and writing as is traditional in UDP programming.

Martin advised me briefly on Gitter to look at MDC for NAT traversal. There's also this ticket where Todd mentions MDC for NAT traversal:

https://github.com/real-logic/aeron/issues/395#issuecomment-327554784

Unfortunately, I've been unable to work out from the (minimal) documentation, the JavaDoc, or the `MultiDestinationCastTest`, how MDC helps with NAT traversal and how I should be configuring it to get me something analogous to the client/server example above but with server responses able to traverse NAT.

If I assume that I've got a server on a public IP address (let's call it `1.2.3.4`) and I have a range of clients on arbitrary private addresses behind NAT (let's assume each client has some address in `10.2.0.0/16` [0]), what channel URIs do I need to configure on both the client and server so that both clients and server get the appropriate publications and subscriptions needed to talk to each other? The programming model I want to end up with is that the server has one subscription/publication pair per client to read from/write to each client independently, and each client has a subscription/publication pair used to read from/write to the server. Clients are responsible for initiating the connections and the server doesn't care who it talks to. I'm using only unicast and have no need for multicast.

[0] In the real world, clients might be anywhere and some may not even be behind NAT, but let's assume for this example that they all are.

**Comment by tmontgomery** [comment]
MDC isn't explicitly for NAT traversal. It just so happens that dynamic MDC allows a Subscription to be behind a NAT. i.e. on the private side. The reason is that dynamic MDC on the Subscription side sends a periodic SM that can initiate data flow back.

To set that up in the setup above requires a dynamic MDC as the connect request response information (`cs`). And the server to setup a Publication for MDC. The client needs to setup a dynamic MDC Subscription.

But back to the normal setup (sans MDC) with a client with a Subscription. The connect request can include the public IP (if known)... or the server can get the public IP as the source identity of a new image. This combined with a port forward can allow NAT traversal. This is already being done by at least a couple users, I believe. It means more control of the NAT (for port forwarding), but it is possible.

**Comment by io7m** [comment]
> MDC isn't explicitly for NAT traversal. It just so happens that dynamic MDC allows a Subscription to be behind a NAT. i.e. on the private side. The reason is that dynamic MDC on the Subscription side sends a periodic SM that can initiate data flow back.

Yes, I understand. The fact that it can do NAT traversal is just a happy consequence of how it works.

> To set that up in the setup above requires a dynamic MDC as the connect request response information (cs). And the server to setup a Publication for MDC. The client needs to setup a dynamic MDC Subscription.

Could you give me some example channel URIs (and an indication of whether those are subscriptions or publications) for a server at `1.2.3.4` and a client at `10.2.0.1` (behind NAT)?

If I'm understanding correctly, I _think_ the client does this:

`p = addPublication("aeron:udp?endpoint=1.2.3.4:9999")`

That's for sending messages to the server. Then the client calls:

`s = addSubscription("aeron:udp?endpoint=10.2.0.1:10000|control=1.2.3.4:10001")`

That's what the client uses to get response packets from the server. The server has a control port at `1.2.3.4:10001` and the above causes the client to send packets to the server such that the server will respond with packets destined for port `10000` on the client.
The client sends messages to the server via `p` and receives responses via `s`.

Is this correct?

I'm unsure as to what I'd need to specify in terms of publications and subscriptions on the server, though.

> But back to the normal setup (sans MDC) with a client with a Subscription. The connect request can include the public IP (if known)... or the server can get the public IP as the source identity of a new image. This combined with a port forward can allow NAT traversal. This is already being done by at least a couple users, I believe. It means more control of the NAT (for port forwarding), but it is possible.

Yes, I understand how that could work. Unfortunately in my case, it wouldn't be acceptable. It's acceptable for server operators to have to understand how to set up port forwarding and so on, but it would be unacceptable for users running clients to have to set up port forwarding just to be able to talk to a remote server. No multiplayer game that I'm aware of requires this of their clients. Some games use a separate NAT traversal mechanism involving an intermediary, but I'd prefer to keep things simple and direct (and given that the servers are player-run anyway, requiring an intermediary might be counter to that).

**Comment by io7m** [comment]
I was pulled away from this to work on something else, but I've spent the last couple of days trying to get this working. I've succeeded (including testing that data does actually traverse NAT) with one show-stopping caveat.

In my test network, the server lives at `10.2.17.1` and the client lives at `10.10.0.5` on the private side of a NAT router (the router is at `10.10.0.1` and does translation between `10.2.0/16` and `10.10.0/16`). The server opens a "control" port (for MDC) `9000` and a "data" port `9001`.

The server creates the following publication and subscription:

https://github.com/io7m/aerontest/blob/9bdc3e57d15e9b6accd922e8676b7af4bcc617e9/src/main/java/com/io7m/api_exp2_nat/Server.java#L95

In other words, it makes these calls:

```
sp = addPublication("aeron:udp?control=10.2.17.1:9000|reliable=true|mtu=1216");
ss = addSubscription("aeron:udp?endpoint=10.2.17.1:9001|reliable=true|mtu=1216");
```

`sp` is used to send messages to connected clients, `ss` is used to receive messages from connected clients.

The client creates the following publication and subscription:

https://github.com/io7m/aerontest/blob/9bdc3e57d15e9b6accd922e8676b7af4bcc617e9/src/main/java/com/io7m/api_exp2_nat/Client.java#L111

In other words, it makes these calls:

```
cs = addSubscription("aeron:udp?endpoint=10.10.0.5:8000|control=10.2.17.1:9000|control-mode=dynamic|reliable=true|mtu=1216")
cp = addPublication("aeron:udp?endpoint=10.2.17.1:9001|reliable=true|mtu=1216")
```

`cs` is used to receive messages from the server, `cp` is used to send messages to the server. The client binds to the local port `8000` and this is the port that effectively receives responses from the server.

Now this all appears to work correctly. In the example code, the server and client simply exchange UTF-8 strings periodically. I've verified that the server never knows the IP of the client behind NAT, and responses from the server do manage to traverse NAT and make it back to the client.

The major caveat: The server has a single publication that it can use to send messages to clients. It _doesn't_ get one publication per client, so all it can do is broadcast the same set of messages to _all connected clients_. The API doesn't appear to expose a way to individually address clients. How do I get one publication per client on the server?

**Comment by mjpt777** [comment]
You can have one publication per client if you use exclusive publications. With the current master you can also specify a session-id on the publication and subscription side as a channel param. Session ids are normally automatically assigned but the next release will support a reserved range of ids that can be manually assigned by the publication.

**Comment by io7m** [comment]
> You can have one publication per client if you use exclusive publications.

I assume you don't mean simply use `addExclusivePublication` to create the initial publication on the server? The example code already does this (I shortened `addExclusivePublication` to `addPublication` in the quoted example because I thought [according to the JavaDoc] that an exclusive publication was merely a non thread-safe version of an ordinary publication). If I post messages to the server's exclusive publication all clients receive the messages.

I've tried creating publications in the server's "image available" handler, both using the source ID of the image passed to the handler, and also by trying to create a new publication based on the existing server publication channel string but with a `session-id` parameter manually appended. Neither work. In fact the latter still results in all clients receiving the same messages, but has the apparent effect of causing the media driver to time out about ten seconds after the publication creation is attempted.

> Session ids are normally automatically assigned but the next release will support a reserved range of ids that can be manually assigned by the publication.

Does this mean that clients pick their own session IDs in my case? That sounds like a security risk...

**Comment by mjpt777** [comment]
Exclusive publications are not just single threaded there is a new log buffer created for each. If you are using master and provided a `session-id` param in the subscription for the matching publication then you receive only that session. That is if the subscription and publication have the same session-id then traffic only goes between them providing no wild card (default) session id subscriptions exist on the same channel and stream pairing.

**Comment by mjpt777** [comment]
Closing the discussion. We can reopen another for further exploration of specific points.

**Comment by io7m** [comment]
Agreed, I will try again with the latest `master` soon.
