### ISSUE TITLE
Archive and Cluster need a CnC file for their directories

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/aeron#460]
Archive and Cluster need to have a CnC file to hold information about being active. And also perhaps some active state.

For the Archive, the catalog is the CnC file equivalent. But needs some more information.

- timestamp for activity
- version
- archive: current recordingId counter
- cluster: recordingId of active log
- location of active Aeron driver in use
- cluster: location of active local archive
- cluster/archive: channel URI and streamIds for local and remote clients
- PID of the process running

Additional capabilities:
- cluster tool to print out state and service information

**Comment by mjpt777** [comment]
> - archive: current recordingId counter

I think you mean:
 * cluster: recordingId of active log

For the cluster it will have a channel URI and stream id for the local archive but not the directory.

**Comment by tmontgomery** [comment]
Actually, I was thinking that the max recordingId could be kept. I know we can go from what is read, though. But I was thinking to keep from reusing Ids after trimming and restarting. Even, though, that is fine.

**Comment by tmontgomery** [comment]
All in now. Naming of "Mark" files instead of CnC files.
