### ISSUE TITLE
Could not find org.agrona:agrona:0.9.13-SNAPSHOT

### ISSUE THREAD

**Issue by jamesbond00** [real-logic/aeron#463]
Date: 30 Jan 2018

https://github.com/real-logic/aeron/blob/83b5094acf64790ab50f1c89b5176c86d15a0d26/build.gradle#L174

Hello,

I just cloned Aeron today. I am getting "Could not find org.agrona:agrona:0.9.13-SNAPSHOT" when running gradlew on Mac OS. Apparently the snapshot does not exist in the Maven repo https://repo.maven.apache.org/maven2/org/agrona/agrona.

Thanks,
Alex

--------
Maven:
https://repo.maven.apache.org/maven2/org/agrona/agrona/

org/agrona/agrona
../
0.9.10/                                           2017-11-01 19:49         -      
0.9.11/                                           2017-11-15 20:31         -      
0.9.12/                                           2017-12-15 01:25         -      
0.9.2/                                            2017-01-23 16:51         -      
0.9.3/                                            2017-02-23 01:43         -      
0.9.4/                                            2017-04-06 15:50         -      
0.9.5/                                            2017-04-12 20:13         -      
0.9.6/                                            2017-05-14 04:15         -      
0.9.7/                                            2017-08-21 16:44         -      
0.9.8/                                            2017-10-11 19:27         -      
0.9.9/                                            2017-10-16 15:16         -      
maven-metadata.xml                                2017-12-15 01:27       638      
maven-metadata.xml.md5                            2017-12-15 01:27        32      
maven-metadata.xml.sha1                           2017-12-15 01:27        40 

--------------
System: 
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6

--------------
Logs:
$ ./gradlew 
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':aeron-client:compileClasspath'.
> Could not find org.agrona:agrona:0.9.13-SNAPSHOT.
  Searched in the following locations:
      https://repo.maven.apache.org/maven2/org/agrona/agrona/0.9.13-SNAPSHOT/maven-metadata.xml
      https://repo.maven.apache.org/maven2/org/agrona/agrona/0.9.13-SNAPSHOT/agrona-0.9.13-SNAPSHOT.pom
      https://repo.maven.apache.org/maven2/org/agrona/agrona/0.9.13-SNAPSHOT/agrona-0.9.13-SNAPSHOT.jar
      file:/<local_dir>/.m2/repository/org/agrona/agrona/0.9.13-SNAPSHOT/maven-metadata.xml
      file:/<local_dir>/.m2/repository/org/agrona/agrona/0.9.13-SNAPSHOT/agrona-0.9.13-SNAPSHOT.pom
      file:/<local_dir>/.m2/repository/org/agrona/agrona/0.9.13-SNAPSHOT/agrona-0.9.13-SNAPSHOT.jar
  Required by:
      project :aeron-client

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
10 actionable tasks: 1 executed, 9 up-to-date

**Comment by mjpt777** [comment]
The current master for Aeron requires Agrona and SBE to be be cloned and built locally. 

https://github.com/real-logic/agrona
https://github.com/real-logic/simple-binary-encoding
