### ISSUE TITLE
Session Id specific recordings can incorporate some new efficiencies

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/aeron#464]
Session Id specific recordings should close automatically on the image becoming unavailable.

**Comment by mjpt777** [comment]
They can also be stopped early if necessary by the normal API. This may be because multiple publishers are keeping it active when not wanted.

**Comment by tmontgomery** [comment]
Renamed to open up any new semantics we can come up with.

**Comment by mjpt777** [comment]
Archive recording that are session specific can be marked as such and when the Image closes then the recording subscription can be removed by tracking this in the session.

**Comment by mjpt777** [comment]
Close this for now as not immediately required. Can be reopened in the future if required.
