### ISSUE TITLE
Reconnected subscription does not receive messages

### ISSUE THREAD

**Issue by arpmipg** [real-logic/aeron#466]
Steps to reproduce:

1. Start media driver. All publishers and subscribers should use same media driver.
2. Start publisher on CHANNEL (any udp) and STREAM_1
3. Start subscription1 on CHANNEL (same) and STREAM_2 (!= STREAM_1)
4. Start subscription2 on CHANNEL (same) and STREAM_1
5. All good, subscription2 gets messages from publisher.
6. Close subscription2 and sleep for some time (10 seconds).
7. Recreate subscription2.

subscription2 does not receive message from publisher any more.
Only reproduced if single media driver is used and there are at lease 2 subscriptions on same channel with different streams.

This case is from our failover implementation. Different streams on same channel are used for resending.

**Comment by mjpt777** [comment]
What version of the Aeron, client and media driver type?

**Comment by arpmipg** [comment]
aeron 1.7.0
I reproduced issue using io.aeron.driver.MediaDriver (no changes), io.aeron.samples.BasicPublisher (no changes), io.aeron.samples.BasicSubscriber (just added logic with second subscription and reconnection)

**Comment by arpmipg** [comment]
[BasicSubscriber.zip](https://github.com/real-logic/aeron/files/1707804/BasicSubscriber.zip)

Please see changes in BasicSubscriber.

If you commented lines 72-75 - all good.

**Comment by tmontgomery** [comment]
With the head, I do not see this occurring. Can you try it with the latest head of the repo?

**Comment by arpmipg** [comment]
Awesome!
Thank you.
Does not work in 1.7.0 but works fine in head.

When do you plan next release?

**Comment by tmontgomery** [comment]
@mjpt777 and I have talked about a release soon. Want the current round of archive and cluster changes to be in, though.

**Comment by arpmipg** [comment]
Works fine with 1.8.0.
Thank you.
