### ISSUE TITLE
C++: Image's m_logBuffers wrt Move in Subscription::add/remove Image

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#472]
I would like to have your opinion on the following. Is it an issue?

**Note:** I haven't tried to make the following situation happens. At this point, I just suspect this is an issue.

Following is a series of steps leading to the suspected issue:

1) Application Thread calls:
```cpp
    inline int pollEndOfStreams(F&& endOfStreamHandler)
    {
      const ImageList * imageList = std::atomic_load_explicit(&m_imageList, std::memory_order_acquire);
```
Application Thread is somehow interrupted...

2) Conductor Thread calls:
```cpp
    Subscription::removeImage/addImage
```
 Because it executes the following code: `newArray[j++] = std::move(oldArray[i]);`
 which calls: `m_logBuffers = std::move(image.m_logBuffers);`
 
imageList now contains at least one image where image.m_logBuffers is nullptr. 

3) Application Thread resumes its execution of pollEndOfStreams
```cpp
      const std::size_t length = imageList->m_length;
      Image *images = imageList->images();
      int numEndOfStreams = 0;

      for (std::size_t i = 0; i < length; i++)
      {
        if (images[i].isEndOfStream()) // **<<< This would crash because m_logBuffers is nullptr**
        {
          numEndOfStreams++;
          endOfStreamHandler(images[i]);
        }
      }

      return numEndOfStreams;
    }
```

**Comment by tmontgomery** [comment]
I think you are correct. Would probably be better to use copy semantics instead for add/remove.

**Comment by mjpt777** [comment]
The same issue applies to the poll methods.

**Comment by tmontgomery** [comment]
Move semantics in now. Feel free to examine it. Feedback always welcome.

**Comment by goglusid** [comment]
As usual you are very fast to respond! The changes are fine with me and do resolve the issue I found. Thank you very much!
