### ISSUE TITLE
Subscriber backlog tool

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#482]
Create a tool which reads the counters to track the queue length for backlog between the receiver and the subscribers based on position counters. The tool can take into account the high-water-mark and the rebuild position.

**Comment by tmontgomery** [comment]
This has been requested a few times. And thus would be fairly nice to have.

**Comment by QIvan** [comment]
all my yesterday questions were because of this issue. So i think it would be nice to have the answers here for future information. 

##### Martin Thompson @mjpt777
> The rcv-pos can be behind sub-pos as there is a race between the conductor tracking the rebuild position and subscribers consuming the contiguous data. M more correct way to view it would be
> pub-pos >= snd-pos >= rcv-hwm >= (rcv-pos || sub-pos)


##### Todd L. Montgomery @tmontgomery 

> one thing to also remember is that some of the stats are updated on other threads. And so, may be out of date if they are not holding something back. A Subscription for example, is only interested in the messages being contiguous and will happily continue processing further than rcv-pos. While rcv-pos is only updated by the conductor for tracking loss. For most of the time, the things that matters the most is counters values across time. And instantaneous snapshot of counters is like looking at a waterfall in a photo. Lots of motion, but very little information. The real magic happens when you look at the water in video form.


##### Ivan Zemlyanskiy @QIvan 
> What do you think does the difference rcv-hwm - rvc-pos make sense? 


##### Martin Thompson @mjpt777 
> Not quite. More the max of sub-pos will influence the rcv-pos. rcv-pos is the max for the confirmed rebuild of an image that uses the max of sub-pos and the conductor tracking forward.

**Comment by QIvan** [comment]
could you share your thoughs what is the formula for calulcation subscriber's backlog? 
Is it `rvc-hwm - sub-pos` ?

**Comment by mjpt777** [comment]
Yes that is a good measure of backlog on the receiver side. It gets more complicated in the case of loss but that should be an uncommon event.

**Comment by QIvan** [comment]
ok. Is it the idea that you meant here
> The tool can take into account the high-water-mark and the rebuild position.

**Comment by mjpt777** [comment]
Possibly. I wrote that so long ago that I might do it different now.

**Comment by QIvan** [comment]
oh yes, regard to @tmontgomery words: 
> And instantaneous snapshot of counters is like looking at a waterfall in a photo. Lots of motion, but very little information. The real magic happens when you look at the water in video form.

May be does it make sense to have the tool in "loop mode" like AeronStat?

**Comment by mjpt777** [comment]
It could be an option.
