### ISSUE TITLE
Add the ability to truncate a stopped recording

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#487]
A recording used for clustering may need to be truncated to match an elected leader when late joining the cluster again.

This can be done by truncating the end of a recording. The position will need to be validated as being on a message fragment boundary in a similar way to how replays are validated.

**Comment by tmontgomery** [comment]
Presumably, this would need to also handle truncating on a previous segment than the last and unlinking the segment file.

**Comment by mjpt777** [comment]
Added with this commit. https://github.com/real-logic/aeron/commit/d07ede1c0df8353121143ddf5e408039936141aa
