### ISSUE TITLE
C MediaDriver Publication Link wrt Publication Registration Id

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#489]
Could you  please confirm that the following is a bug?

In function aeron_driver_conductor_get_or_add_ipc_publication:

publication links are taking a pointer to a managed resource that is set to the original Registration Id of a publication.

**client->publication_links.array[client->publication_links.length++].resource =
                        &publication->conductor_fields.managed_resource;**

However, in function aeron_driver_conductor_on_remove_publication:

The command contains a registration id specific a client and not the original registration Id. 
This causes the following if to always fail. (except for the client that created the publication)

**if (command->registration_id == resource->registration_id)**

I looked at the Java media driver and it seems okay because PublicationLink are created with correlationId.

**Java: publicationLinks.add(new PublicationLink(correlationId, getOrAddClient(clientId), publication));**

**Comment by tmontgomery** [comment]
Yes, this is a problem. Fix incoming.

**Comment by tmontgomery** [comment]
I believe this is now fixed with 9935f6204

**Comment by tmontgomery** [comment]
To be clear what was effected. Shared publications (non-exclusive, same streamId+channelId) would miss track reference count when clients would close publications, but keep clients active.

**Comment by goglusid** [comment]
Indeed that was the issue. Thank you!

**Comment by tmontgomery** [comment]
No problem. Thanks for the details! Was very clear.
