### ISSUE TITLE
C++ Image availability handlers on a subscription level

### ISSUE THREAD

**Issue by denizevrenci** [real-logic/aeron#496]
#312 discusses the addition of image availability handlers per subscription as opposed to per client. While Java client library has gotten this update, C++ client library has not been changed limiting the implementation of a pure async subscription handler.

**Comment by tmontgomery** [comment]
The C++ API has this functionality.

https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp/Aeron.h#L180

**Comment by denizevrenci** [comment]
Thank you. That was what I was looking for.

If you could allow a follow-up, I understand that `on_available_image` is telling that a new session has been established with the publisher. I might be missing this one as well but there does not seem to be a method to register a callback in the C++ API for messages (or fragments) received. Methods in both `Image` and `Subscription` are polling based. I assume this is not an issue for continuous high throughput scenarios. But, in the cases where messages in a session are spread thin, polling sounds inefficient compared to being notified when a message arrives.

**Comment by tmontgomery** [comment]
Currently, reception is poll based and delivered via a fragment handler. For low rate streams, using something like `SleepingIdleStrategy` between polls will be more than friendly to the OS and other threads.

**Comment by denizevrenci** [comment]
That answers my question. Thank you.
