### ISSUE TITLE
`aeron::Context::newExclusivePublicationHandler()` is not in the API

### ISSUE THREAD

**Issue by denizevrenci** [real-logic/aeron#500]
Without having a separate callback for `ExclusivePublication`s, the users of the Aeron API have to keep a list of registration IDs to identify whether they result from a call to`addPublication()` or `addExclusivePublication()` and call `findPublication()` or `findExclusivePublication()` accordingly.

Addition of `newExclusivePublicationHandler()` breaks existing code if `on_new_publication_t handler` does not get called for `ExclusivePublication`s. A possible solution could be adding a third call `newSynchronizedPublicationHandler()` for `Publication`s and deprecating the existing functionality of `newPublicationHandler()` until a breaking change gets introduced in a later release.
Another possible solution is to make `Context` detect if `newExclusivePublicationHandler()` has been set to a non-default handler and wire the calls only in that case.

**Comment by tmontgomery** [comment]
Thanks for pointing this out.

I've added a handler for exclusive publications. The semantics of using the existing new publication handler if this new handler is not set, makes sense to me anyway. This also has the behavior of being compatible with existing applications as pointed out.
