### ISSUE TITLE
Archive codec specs include SBE Cpp keyword `position`

### ISSUE THREAD

**Issue by denizevrenci** [real-logic/aeron#501]
In `aeron-archive/src/main/resources/aeron-archive-codecs.xml`, several message types use the field name `position`. However,  C++ code generator of SBE uses this name for a private data member and also provides public accessor and mutator methods which have the same signature as the one generated for the field with the same name. The generated class, therefore, has two `position()` members, violating overloading rules of C++.

**Comment by mjpt777** [comment]
This method should have been sbePosition which has now been renamed. This will be breaking for those who used this method which should not have been a common occurrence. 

https://github.com/real-logic/simple-binary-encoding/commit/1e7a70e2a8a467ef411f9abb18be86726871db3d
