### ISSUE TITLE
[C++] build issue Linux

### ISSUE THREAD

**Issue by manishbaphna** [real-logic/aeron#506]
Tried building latest version /C++11 on linux, faced few issues
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

1. It complained of duplicate definition of mmsghdr.
Somehow this section didn't do what it's supposed to do so I commented them in all relevant files
#if !defined(HAVE_STRUCT_MMSGHDR)
struct mmsghdr
{
    struct msghdr msg_hdr;
    unsigned int msg_len;
};
#endif

2. Then linker cribbed
/usr/bin/ld: cannot find -luuid
Though system has this lib
/usr/lib64/libuuid.so.1 -> libuuid.so.1.3.0

**Comment by tmontgomery** [comment]
What is the output of CMake at the beginning? You should see something akin to:

```
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of struct mmsghdr
-- Check size of struct mmsghdr - failed
-- Looking for recvmmsg
-- Looking for recvmmsg - not found
-- Looking for sendmmsg
-- Looking for sendmmsg - not found
```

**Comment by manishbaphna** [comment]
Yes, it did give that.  Though I can see sys/socket.h is available and has the definition.

**Comment by tmontgomery** [comment]
What is the actual output you see?

**Comment by manishbaphna** [comment]
exactly how you typed.

**Comment by manishbaphna** [comment]
Here's error for #1 
[ 63%] Building C object aeron-driver/src/main/c/CMakeFiles/aeron_driver.dir/aeron_driver_sender.c.o
/home/mb13808/workspace/aeron-master/aeron-driver/src/main/c/aeron_driver_sender.c:26:8: error: redefinition of âstruct mmsghdrâ
 struct mmsghdr
        ^
In file included from /home/mb13808/workspace/aeron-master/aeron-driver/src/main/c/aeron_driver_sender.c:22:0:
/usr/include/sys/socket.h:102:8: note: originally defined here
 struct mmsghdr
        ^
gmake[2]: *** [aeron-driver/src/main/c/CMakeFiles/aeron_driver.dir/aeron_driver_sender.c.o] Error 1
gmake[1]: *** [aeron-driver/src/main/c/CMakeFiles/aeron_driver.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by manishbaphna** [comment]
Error for #2 
[ 49%] Built target Throughput
[ 50%] Built target TimeTests
[ 50%] Linking C shared library ../../../../lib/libaeron_driver.so
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
gmake[2]: *** [lib/libaeron_driver.so] Error 1
gmake[1]: *** [aeron-driver/src/main/c/CMakeFiles/aeron_driver.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by tmontgomery** [comment]
The output I showed is from Mac where mmsghdr doesn't exist and thus falls back to defining it. As you mention that sys/socket.h has the definition and it appears to be finding it, I'm not sure how the CMake output is exactly what is shown, but the compilation fails on the struct being already defined.

Linux gcc/glibc versions are a little odd in that the flags vary quite a bit for compat. As gcc 4.8 is a bit behind, it might be better to use a newer gcc.

**Comment by manishbaphna** [comment]
I have tried with gcc version 6.1.0 but issue persists. 
While #1 is not a show stopper,, #2 is . Any suggestion how can we work it around ? Tried playing with CMake files but it's not helping.

**Comment by cesaref** [comment]
It's not clear to me what you are now seeing - does it build with gcc 6.1 but you have some runtime issues?

**Comment by manishbaphna** [comment]
It's still not able to resolve libuuid issue

**Comment by ayubsayyad** [comment]
@manishbaphna :
workaround:
comment out these lines with ${AERON_LIB_UUID_LIBS} in aeron-driver/src/main/c/CMakeLists.txt

target_link_libraries(
     aeron_driver
...
     #    ${AERON_LIB_UUID_LIBS}
...

 target_link_libraries(
     aeronmd
     aeron_driver
...
     #    ${AERON_LIB_UUID_LIBS}
  ...
 target_link_libraries(
     aeron_driver_agent
  ...
     #    ${AERON_LIB_UUID_LIBS}
....

**Comment by tmontgomery** [comment]
Glad it can be worked around.

@manishbaphna can you paste the output of CMake where it does its configure? It is the start of the build and contains the lines I mentioned as well as compiler, etc.

It's strange that uuid must be found int the CMake find_library, but the final link fails. And would like to see if something is missed here.

**Comment by tmontgomery** [comment]
Actually, the build tries to find libuuid and the uuid functions/headers separately. I would bet that the functions and headers are not found, but in the process, the library is found. But something else is not allowing it to be linked correctly. Probably a path is not correct for this setup as your original output mentions libuuid is found in a different directory (`/usr/lib64`).

If uuid can't be used, it falls back to a pure random generation for the receiver id. That is probably what is happening. But because CMake has found the lib, it tries to link the lib anyway. And fails. That is why when you remove the UUID libs, it works.

BTW, you might try installing libuuid and libbsd. But since it looks like you are using a non-standard compiler, things might not be in the correct configuration to make everything work.

**Comment by ayubsayyad** [comment]
we can do somethinh like below ?, where uuid path will always be taken from where cmake found it.
```
get_filename_component(UUID_LIB_PATH "${LIBUUID_EXISTS}" DIRECTORY)
link_directories(${UUID_LIB_PATH})

```

**Comment by mjpt777** [comment]
Closing this due to no further activity.
