### ISSUE TITLE
Thread Names

### ISSUE THREAD

**Issue by LordNacho** [real-logic/aeron#508]
Hi,

I've found it useful to name the thread in Agentrunner.h. This allows devops to identify the thread and pin it to a core. Should I do a pull request, or has someone already thought about this?

pthread needs to be included.

`            
std::string name("Aeron Agent");
#ifdef  __APPLE__
            pthread_setname_np(name.c_str());
#else
            pthread_setname_np(pthread_self(), name.c_str());
#endif
`

**Comment by mjpt777** [comment]
The threads are named in the Java implementation and this helps with debugging. Feel free to submit a PR for this.
