### ISSUE TITLE
FAILED: (99) Cannot assign requested address: unicast bind  : Cannot assign requested address

### ISSUE THREAD

**Issue by stonetang** [real-logic/aeron#519]
Ping -C "aeron:udp?endpoint=10.2.237.167:40124" -c "aeron:udp?endpoint=10.2.117.81:40123"

the err happened , while do it;  please help!

**Comment by mjpt777** [comment]
Please provide more details and a repeatable example.

**Comment by stonetang** [comment]
while  communicating  in the tow host, one is pub,  another is sub, this err happened.

i  find sub channel bind socket, while  reading the code,  and why bind remote address?

**Comment by stonetang** [comment]
FAILED: (99) Cannot assign requested address: unicast bind [10.2.237.167:40124] : Cannot assign requested address : std::shared_ptr<aeron::Subscription> aeron::ClientConductor::findSubscription(int64_t) : /home/tangminghong/msg-bus/aeron-src/aeron/aeron-client/src/main/cpp/ClientConductor.cpp : 273

**Comment by stonetang** [comment]
please help me;  why Subscription  need to bind  remote address ?  the only locale address band socket

**Comment by tmontgomery** [comment]
Try setting the BasicPublisher and BasicSubscriber channels to communicate in each direction, then try transposing those addresses into Ping and Pong channels.
