### ISSUE TITLE
BroadcastTransmitter

### ISSUE THREAD

**Issue by goglusid** [real-logic/Aeron#52]
Hello,

I don't see what prevents BroadcastTransmitter::transmit from overwriting it's underlying buffer in such a way that CopyBroadcastReceiver::receive returns invalid messages.

In more details: 
 
BroadcastTransmitter::transmit stamps each message it transmits with the tail (tail stamp) counter then increment its tail.

CopyBroadcastReceiver::receive (via BroadcastReceiver::receiveNext) make sure it doesn't run over the tail then validates the message length, copy the message and check again if the message just copied is still valid by checking the message's (tail stamp).

I see a problem with that if memory gets overwrite by a new message while we copy the message in the receiver scratch buffer.In particular if the memory region associated with a message's (tail stamp) is now part of a new message's content. I don't see what prevents this memory region to contain the right (tail stamp) value. Meaning BroadcastReceiver::validate would return true.

Did I missed something or this isn't thread safe?

Sidney

**Comment by tmontgomery** [comment]
If I understand your concern, how is the case handled where an overwrite could write just the correct thing into the tail offset field of the record header while it is being copied out. Correct?

Assuming you mean an overwrite after the `receiveNext` validate step.

**Comment by goglusid** [comment]
Indeed, what prevents the transmitter to wrap around and overwrite the memory pointed to by the message record offset in such a way that the length is < capacity and the tail stamp == cursor. If all messages would be of equal size then a tail stamp would always be at the same offsets in the buffer but otherwise I don't see how it would work given a previous tail stamp could later be part of a new message. I hope this clarify my point. Not that easy to discuss threading issues.

**Comment by tmontgomery** [comment]
I don't see that anything stops the case you mention. I very vaguely remember talking about this with @mjpt777 a long time ago.... but can't remember what, if anything, we came to a conclusion on.

The case of reading when already overwritten is protected some better. But the receiver being interrupted after receiveNext and before validate is not as protected.

**Comment by mjpt777** [comment]
Yes this is a possibility. With data being aligned and need to match exactly 8 bytes it is highly unlikely. The likelihood further reduces with each additional message having to match the exact pattern all over again. It also requires the receiver not being able to keep up with a very low volume stream of messages.

The broadcast data in Aeron is not critical so this can be considered a pragmatic solution. 

Having said all that I may put in another solution that is totally safe and just a little less efficient. I'm aware of a few ways to do this.

The current approach never impacts the producer at all and that is why it was chosen. These sorts of pragmatic approaches are often employed in network protocols.

**Comment by goglusid** [comment]
I agree it is very unlikely but still possible.  

Possible Fix: Forcing messages to always start at given offsets in the buffer would work given the headers would always be at the same places in the buffers. All of this at the expense of wasting space in the buffer.

**Comment by mjpt777** [comment]
A simple fix is for the producer to write a counter of the total bytes it has written then delta this after the copy to ensure the read is in buffer range. This will cause one additional cache misses when a new message is read, and possibly another in burst scenarios.

**Comment by tmontgomery** [comment]
Daydreaming of SSE4 CRC32 access in Java....

**Comment by mjpt777** [comment]
Don't @tmontgomery ! You'll only annoy me...
