### ISSUE TITLE
ArchiveException errorCode is not always provided

### ISSUE THREAD

**Issue by zyulyaev** [real-logic/aeron#523]
https://github.com/real-logic/aeron/blob/276e10758b094b41dc563ad789cbe64683600527/aeron-archive/src/main/java/io/aeron/archive/ControlSession.java#L268

0 must be replaced by relevantId on the linked line

**Comment by mjpt777** [comment]
Thanks.

**Comment by zyulyaev** [comment]
@mjpt777 Looks like you've fixed same bug, but on a different line.
