### ISSUE TITLE
ClusterTool throws IllegalStateException on service container's custom directory

### ISSUE THREAD

**Issue by benwimpory** [real-logic/aeron#527]
The tool expects the CM mark file to be in the same directory.

Exception impacts ClusterTool.describe and likely to impact ClusterTool.errors too.

**Comment by tmontgomery** [comment]
0d16bf360 should make this cleaner.

The initial behavior was to wait for a file for a timeout. This behavior can now be customized by setting `aeron.ClusterTool.timeoutMs`. This allows startup of a cluster to be waited on if desired. The default is not to wait.
