### ISSUE TITLE
Proposal: shared_ptr for C++ client dependencies

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#529]
The C++ client has some implicit dependencies. For example, Aeron contains a reference to Context. Subscriber needs Aeron to remain in existence throughout its life.

This is not much of a problem when writing a C++ application, though it could be a minor annoyance if you want to do something like pass around a shared_ptr\<Subscription\> and not worry about the lifecycle of the rest.

When wrapping the C++ API for use in a language that wants to do its own Garbage Collection, this does get somewhat hard to express cleanly without writing my own wrapper classes (or creating intentional memory leaks).

What would the maintainers think of a PR that expressed these dependencies using shared_ptr? Specifically, it'd need to include something like:

- Context is available as a shared_ptr
- Aeron keeps a shared_ptr to Context instead of a reference
- Subscriber, Publisher, and relatives get a shared_ptr to Aeron (even though they don't need it for anything). Very open to ideas about how to better express this particular one.

Please let me know what you think. Thanks in advance.

**Comment by lukepalmer** [comment]
I ended up finding a usable workaround, but happy to revisit if there's a good reason.

**Comment by tmontgomery** [comment]
I would like to make this cleaner. But changing the API has some issues for current users.

**Comment by mjpt777** [comment]
The context is now copied so a `shared_ptr` is not necessary. Publication, subscriptions, and counters are found by and returned by `shared_ptr`. Images as of 1.20.0 are manged as `shared_ptr`.
