### ISSUE TITLE
compilation failure on linux

### ISSUE THREAD

**Issue by pdavydov108** [real-logic/Aeron#53]
Hi, thanks for this very interesting project! I tried to compile it (master branch, at commit 1c252f2a1ef006a2044bc5cecd9b207f6a93d6cd)  on Debian linux with gcc 4.9.1, and the compilation failed:

Linking CXX executable ../../../../binaries/BasicPublisher
../../../../lib/libaeron_client.a(Aeron.cpp.o): In function `std::thread::thread<aeron::common::common::AgentRunner<aeron::ClientConductor, aeron::common::common::BusySpinIdleStrategy>::start()::{lambda()#1}>(aeron::common::common::AgentRunner<aeron::ClientConductor, aeron::common::common::BusySpinIdleStrategy>::start()::{lambda()#1}&&)':
/usr/include/c++/4.9/thread:136: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

Adding -pthread flag to CMAKE_CXX_FLAGS fixed the issue.

**Comment by tmontgomery** [comment]
Odd. The addition of `find_package(Threads)` should add that naturally.

When you run cppbuild, what is the output of the cmake part? i.e. the initial bit from a clean build.

**Comment by pdavydov108** [comment]
That's the cmake part, including the one generated by gtest:

-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pablo/Aeron/cppbuild
Scanning dependencies of target gmock
[  3%] Creating directories for 'gmock'
[  6%] Performing download step (verify and extract) for 'gmock'
-- verifying file...
     file='/home/pablo/Aeron/aeron-common/src/main/cpp/3rdparty/gmock-1.7.0.zip'
-- verifying file... done
-- extracting...
     src='/home/pablo/Aeron/aeron-common/src/main/cpp/3rdparty/gmock-1.7.0.zip'
     dst='/home/pablo/Aeron/cppbuild/gmock-prefix/src/gmock'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 10%] No patch step for 'gmock'
[ 13%] No update step for 'gmock'
[ 16%] Performing configure step for 'gmock'
-- The CXX compiler identification is GNU 4.9.1
-- The C compiler identification is GNU 4.9.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.8") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pablo/Aeron/cppbuild/gmock-prefix/src/gmock-build

**Comment by tmontgomery** [comment]
I think `${CMAKE_THREAD_LIBS_INIT}` might be needed for the aeron-samples `target_link_libraries`. That's a guess based on the error and what I see.

This does not seem to be a problem for CentOS 7 with gcc 4.8.2 and things build and test fine there.

Could you try adding that to your copy and see if it works? Adding to the flags directly is a bit uglier since it might break some other systems later if/when ported.

**Comment by pdavydov108** [comment]
I added this flag and the build succeded on Debian. Also, on Fedora 21 it builds just fine without any modifications (without adding `${CMAKE_THREAD_LIBS_INIT}`). So, maybe it's some issue with debian... `FindThreads.cmake` and `cmake` versions are same on both systems. By the way, do you plan FreeBSD support?

**Comment by tmontgomery** [comment]
Yesterday I added the libs as well. So, the Debian build should be OK now. Seems to be OK on Mac & CentOS. Windows is not happy at this moment with one usage, but I will be cleaning that up soon.

FreeBSD, I would love to support. But will have to be done as time allows right now. The C++ API is still under a good deal of change and won't be feature complete for a little bit.

**Comment by tmontgomery** [comment]
Going to close this. Seems to currently build fine on CentOS. And I think Windows builds OK for the moment. C++ still in a state of flux and under active change, though.
