### ISSUE TITLE
Gradle build: cound not find com.github.johnrengelman.shadow 2.0.4

### ISSUE THREAD

**Issue by cliveseldon** [real-logic/aeron#530]
./gradlew
Downloading https://services.gradle.org/distributions/gradle-4.9-all.zip
............................................................................................................

Welcome to Gradle 4.9!

Here are the highlights of this release:
 - Experimental APIs for creating and configuring tasks lazily
 - Pass arguments to JavaExec via CLI
 - Auxiliary publication dependency support for multi-project builds
 - Improved dependency insight report

For more details see https://docs.gradle.org/4.9/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '2.0.4', apply: false]
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:2.0.4
      > Could not get resource 'https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/2.0.4/com.github.johnrengelman.shadow.gradle.plugin-2.0.4.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/2.0.4/com.github.johnrengelman.shadow.gradle.plugin-2.0.4.jar'.
            > Read timed out

**Comment by mjpt777** [comment]
Try running the build again. Sometimes things fail to fetch from maven central.

**Comment by cliveseldon** [comment]
Thanks. Worked 3rd time.

**Comment by mjpt777** [comment]
Seems that sometimes plugins.gradle.org is not available. Once cached locally then it tends to be OK.
