### ISSUE TITLE
Latency with C driver and multiple NICs

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#534]
I have a bit of unexplained behavior that I was hoping for comment on.

Machines A and B are Centos 7 with an Intel GbE NIC. I see expected behavior with Aeron multicast.

Machines C and D are the same as A and B but additionally have 2 each solarflare NICs. On these machines: using the java driver I see very good latency. Using the C driver I see 10ms added latency consistently added to multicast. It doesn't matter which NICs I use or whether or not onload is in use.

I don't have ideas about why additional NICs seem to make the C driver unhappy.  I'm glad to test theories though. Please comment if you have ideas.

**Comment by tmontgomery** [comment]
you mean 10 milli or 10 micro?

**Comment by lukepalmer** [comment]
10 milliseconds. The good news with that is that hopefully it's just one specific issue.

I did a quick strace on the C driver which was showing delays and noticed only occasional clock syscalls.

**Comment by tmontgomery** [comment]
What do you mean the C driver was showing delays?

**Comment by lukepalmer** [comment]
On machines C and D in the setup above I was seeing 10ms latency specifically using the C driver. I ran 'strace aeronmd' just to see if it was making any unexpected syscalls. It was not.

**Comment by tmontgomery** [comment]
Ah. The wording made it sound that strace was showing something.

Does the stats show any loss on either machine?

**Comment by lukepalmer** [comment]
I'll check that and get back to you. Thanks for the response!

**Comment by mjpt777** [comment]
Are the files all stored in /dev/shm? If in the normal file system then page faults could explain the difference.

**Comment by tmontgomery** [comment]
BTW, my best guess here would be that there is something odd with recvmmsg and sendmmsg going on with those machines. But loss needs to be ruled out first since that is much more likely.

**Comment by lukepalmer** [comment]
@mjpt777 Not that I could easily see. I was running aeronmd with no options and checked that /dev/shm was tmpfs as usual. 

Will check on the loss and get back to you, but note that the java driver worked very well on the same machines. This reproduced 100% of the time.

**Comment by mjpt777** [comment]
Does it make a difference if you run with and without onload?

**Comment by lukepalmer** [comment]
@mjpt777 I saw the 10ms added latency in the C driver both with and without onload (as well as when specifying the unaccelerated intel NIC). Using the java driver I saw the expected improvement using onload.

**Comment by tmontgomery** [comment]
@lukepalmer yes, perfectly normal strace.

**Comment by lukepalmer** [comment]
Ok! Got some info. It's still a mystery but I have some data.

The reason the C driver behaves differently than the java driver is only because of the default wait strategies. If I configure the java driver to busy spin on sender, receiver, and conductor then it also shows the same unexplained 10ms delay.

I notice that both the C and java drivers will only spin on 2 cores on the machines where the problem occurs. I would expect 3. Further, if I change *any* one of the three wait strategies to backoff, it still spins on 2 cores. This is weird.

I also tested write speed to /dev/shm using dd just to make sure nothing strange is going on there. It looks fine.

Happy to try anything else if folks have ideas.

**Comment by tmontgomery** [comment]
Interesting.

The C driver will use PAUSE on a busy spin. Java on Java 8 will do an actual busy spin (no PAUSE).

Is there any CPU differences between the machines? especially between hyperthreads vs. physical threads?

**Comment by lukepalmer** [comment]
I did my setting-changing with the java driver only, but am happy to on the C driver if interesting.

The machines have identical CPUs, both E5-2667V4.

**Comment by mjpt777** [comment]
Are these setups starved of CPU cores in some way? HT turned off? Containers used?

If sched_yield() = 0 is called then this suggests they are not busy spinning.

**Comment by lukepalmer** [comment]
They're physical machines that were otherwise empty at the time. I didn't see anything unusual with HT but will check again. 

On Monday I'll do an strace comparison between good/bad machines. Let me know if you think of anything else to check

**Comment by mjpt777** [comment]
Closing due to no further information.
