### ISSUE TITLE
Can position values be shared across processes?

### ISSUE THREAD

**Issue by mikeb01** [real-logic/aeron#540]
I have a scenario where I have 2 processes using the same media driver.  One with a subscription and another with a spy on that subscription.  If I get the last read position from an image within the subscription.  E.g. `subscription.images().get(0).position()` and pass the value to the other process running the spy. Assuming the same channel, streamId, sessionId triple can I use that position value as a parameter to `Image.controlledPeek()` for that image within the spied subscription?

**Comment by tmontgomery** [comment]
Yes. The position can be filled however you like for the poll. Can come in via another channel, etc. Or could be computed, etc.

**Comment by mikeb01** [comment]
Excellent.
