### ISSUE TITLE
C++ client orderly shutdown

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#545]
I'd like to have an application using an Aeron client operate in a degraded state (without Aeron) if the driver becomes unreachable.

I can prevent an immediate exit by specifying an error handler to the context, but it seems that without the driver the client will eventually become unhealthy and segfault. I think that this is because the client conductor will continue trying to do work (such as writing keepalives indefinitely without buffer maintenance) even after it knows the driver is gone. 

Is there a good way to handle shutting down the C++ client? 

I suspect some changes to ClientConductor may be needed. If the maintainers have some breadcrumbs for me for an enhancement, I may be able to give it a try.

**Comment by mjpt777** [comment]
How about just letting the Aeron client go out of scope and it will clean itself up? When you detect the exception then delete the client.

**Comment by lukepalmer** [comment]
I think your idea is good, but I had some trouble. If I delete the client I observe that join() throws when the conductor thread attempts to stop. I'm going to try and make a minimized test case.

I was able to work around this by using a agentinvoker, which of course I can just stop invoking when I want to.

**Comment by mjpt777** [comment]
Best to not call close from within the error handler. You should set some state to indicate that the system is in error and be closed by separate action.

**Comment by lukepalmer** [comment]
Well that seems obvious now that you say it.  :)

Works fine and I now have two ways to shut down. Appreciate the help.
