### ISSUE TITLE
Java – Excess InetAddress objects created after receiving Status Messages

### ISSUE THREAD

**Issue by warnesey333** [real-logic/aeron#546]
I am currently running into an issue whereby the Media Driver is garbage collecting ~150mb every 2 – 3 hours. After looking at a few heap dumps, it appears that there are a number of InetAddress and InetSocketAddress objects being created whenever a StatusMesage is received. I’ve tried debugging and my current findings are:

- Media Drivers send out a StatusMessage every 200ms to a publisher of a stream

- When the MediaDriver receives the StatusMessage, it attempts to read the message using the DatagramChannelImpl

- Within the **receive0** method of the DatagramChannelImpl.c there is a comparison of the Sender Address and CachedSenderInetAddress

- _If these do not match, new instances of the InetAddress and InetSocketAddress are created and the cachedSenderInetAddress is updated_

- If the Media Driver is receiving Status Messages from multiple different sources, then the cachedInetSenderAddress will keep flipping between the addresses

- **Each time a Status Message is received, the comparison fails and a new object is created**

<br /><br /><br />

Aeron Version
-	First experienced on 1.8.1
-	Upgraded to 1.10.5 and still experiencing

JAVA Version
-	1.8.0_171

Kernel Version
-	3.10.0-862.9.1.el7.x86_64

<br /><br />
**Steps to reproduce:**
-	Run Media Driver on machines A, B and C
-	Publish on stream 1 from Machine A
-	Subscribe on stream 1 from Machine B and C
-	Observe InetAddress/InetSocketAddress objects created on Machine A after each received Status Message from B and C

<br /><br />
Any help would be much appreciated, please let me know any more information is needed.

**Comment by mjpt777** [comment]
I've raised this issue on the NIO mailing list but there seems to be little appetite at present to address it.

http://mail.openjdk.java.net/pipermail/nio-dev/2018-September/005404.html

We are hoping for improvements to NIO in future Java releases but if that does not happen we will focus more on making the C Media Driver the primary implementation.

**Comment by nicholassm** [comment]
Are there any updates or suggested work-arounds for this issue?
I've tried with OpenJDK 14 and the problem still exists.
Any chances that a fix will go into Java 16 or later?

**Comment by mjpt777** [comment]
Java 14 improved the efficiency of the code but not the allocation. The solution to this is to use the C media driver.

**Comment by nicholassm** [comment]
Thanks - I'll look into using that.
