### ISSUE TITLE
Java vs C media driver question

### ISSUE THREAD

**Issue by jmazar** [real-logic/aeron#549]
What is the difference between the java and c media driver? I've tried looking around on the wiki without much success.

You'd still be able to use the c++ 11 interface with the java driver correct? Is it for people who don't want any java running? Performance differences?

Thank you,
Jeffrey

**Comment by tmontgomery** [comment]
They are essentially the same and you should be able to mix and match Java, C++, Go, .NET clients with either just fine.

The C media driver has some advantages over the Java media driver in terms of usage of sendmmsg/recvmmsg on Linux which can make it very efficient throughput-wise. Going forward, the ef_vi support as well as security will use the C media driver.

Currently, the C media driver is lacking the very latest commands added to support clustering and archiving. However, we will be adding this support as we have time.
