### ISSUE TITLE
Invalid archive RecordingDescriptor SBE response length

### ISSUE THREAD

**Issue by LiuZhihai** [real-logic/aeron#550]
Hi, there. I am currently working on implementing the archive client in C++. While implementing *listRecording* feature, our test program crashed due to malformed SBE message. After few hours of investigation, I think the following line of code caused the problem,

https://github.com/real-logic/aeron/blob/51d1998e80ab7c2927c5140593d806f2342d673b/aeron-archive/src/main/java/io/aeron/archive/ControlResponseProxy.java#L58

The `- HEADER_LENGTH` part should be removed.

**Comment by mjpt777** [comment]
There was a bug but the fix is different to what you suggest. Should be fixed now.
