### ISSUE TITLE
Local multicast doesn't connect using interface

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#552]
I have multiple processes per machine with a single driver on each machine. I'm specifying a channel using 'udp' and 'interface' with a subnet, e.g. interface=3.4.5.0/24.

I observe that a publication and subscription on the local machine will never become connected, whereas publications and subscriptions using the same channel across machines work as expected.

I tried adding a few cases to UdpChannelTest but haven't yet found the problem. Suggestions appreciated!

**Comment by mjpt777** [comment]
Without a test case I'm going to close this for now. Also there is not indication of what version or language this involves.
