### ISSUE TITLE
[Clarification Required] - on IdleStrategy (TTSP behavior)

### ISSUE THREAD

**Issue by NiinS** [real-logic/aeron#553]
This is not an issue but I'm looking for more clarification on the documentation of IdleStrategy interface which mentions few lines highlighted below:

![image](https://user-images.githubusercontent.com/3360301/45594525-94cb5800-b9df-11e8-8906-394f98cde9eb.png)

I want to understand the following things:

1. Is it possible that a JVM implementation may not have a safe-point polling?
2. Lets assume if there is one such JVM impl, how will that cause a TTSP behavior?
3. And how will that be resolved by not allowing the method to be JIT compiled using that JVM flag?

**Comment by nitsanw** [comment]
Regrading : "Is it possible that a JVM implementation may not have a safe-point polling?"
It's possible, but not a reality for any JVM. If a JVM does not have safe point polling though, TTSP is a non-issue.
