### ISSUE TITLE
Archive: simulate connection only if there is an active replay subscription

### ISSUE THREAD

**Issue by ratcashdev** [real-logic/aeron#554]
With the current setup it seems difficult to for a Consumer to figure out if the lack of data on a (live) replayed stream with length=Long.MAX_VALUE is because no data is published, or because there are no (primary) subscribers for the stream. Hence it can't decide whether to quit the live replayed stream and subscribe for the primary publisher or not.

aeron-archive allows setting `aeron.spies.simulate.connection=true`, however, there are situations where it may not be desired to record/archive streams when all the (primary) receivers are out of order. Sometimes it's better, when the publisher receivers the error of no consumer being connected.

It would be great to be able to tell aeron-archive to only simulate a connection for a given channel and streamId (`aeron.spies.simulate.connection`) when there is only at least one active replay subscription for the given channel and streamId.

In this way, archive would become the first-hand consumer of the published data and all other consumers would just subscribe for replays. Whenever such replays become active, archive would start simulating connection and publishers will still receive the standard behavior of not being able to publish when there are no real (except archive) subscriptions.

**Comment by mjpt777** [comment]
This feature would be fairly easy to add. Would your company be interested in sponsoring the development?

**Comment by mjpt777** [comment]
If you want to sponsor development and contribute back for the benefits you get from Aeron then please reach out.

**Comment by ratcashdev** [comment]
Right. I may be able to submit a PR.

**Comment by mjpt777** [comment]
I'm going to close this for now as no sponsored work is being proposed.
