### ISSUE TITLE
How to Put Aeron On a mobile phone /android applicaiton

### ISSUE THREAD

**Issue by AlphaMufasaOmega** [real-logic/aeron#556]
I am interested in putting Aeron into a mobile application on andorid is there a way to accomplish this?

**Comment by mjpt777** [comment]
No clients have requested support for Aeron on android. We have no idea if it works or not.

**Comment by ratcashdev** [comment]
Average WIFI latency is 2-4ms - well above what Aeron is able to achieve on a wired connection:
https://www.quora.com/What-is-the-average-latency-of-a-WiFi-network

I wonder what would be the advantage of using Aeron in such circumstances compared to, say, KryoNet over TCP - assuming we need a reliable medium.

**Comment by lukepalmer** [comment]
...not to mention the near-impossibility of multicast on a carrier network, or that compilers available for mobile platforms are likely to be modern enough. I think you'll do much better with other solutions.

**Comment by tmontgomery** [comment]
Others are using Aeron for low bandwidth wireless on small devices as a research topic. And others have used Raspberry Pis with Aeron Cluster running.

Aeron is somewhat unique in that it's easy to experiment with flow and congestion control in a multicast setting. Also, the logbuffer structure opens up some interesting FEC options over higher loss environments. And Multi-Destination-Cast has some advantages over serial TCP connections.
