### ISSUE TITLE
SEGV when closing a handle to the Media Driver

### ISSUE THREAD

**Issue by kdoherty2** [real-logic/aeron#564]
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 695 C2 org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(Lorg/agrona/concurrent/MessageHandler;)I (160 bytes) @ 0x00007f4df90a80c1 [0x00007f4df90a8040+0x81]
J 668 C1 io.aeron.DriverEventsAdapter.receive(J)I (21 bytes) @ 0x00007f4df909c01c [0x00007f4df909bf80+0x9c]
j  io.aeron.ClientConductor.service(J)I+15
j  io.aeron.ClientConductor.awaitResponse(J)V+45
j  io.aeron.ClientConductor.releasePublication(Lio/aeron/Publication;)V+67
j  io.aeron.Publication.close()V+12
j  com.mlp.stark.services.aeron.AeronPublication.close()V+36
j  com.mlp.stark.services.aeron.Util.quietClose(Ljava/lang/AutoCloseable;)V+28
j  com.mlp.stark.services.aeron.Util$$Lambda$37.accept(Ljava/lang/Object;)V+4
j  java.util.HashMap$Values.forEach(Ljava/util/function/Consumer;)V+69
j  com.mlp.stark.services.aeron.Util.quietClose(Ljava/util/Collection;)V+13
j  com.mlp.stark.services.aeron.Util.quietClose(Ljava/util/Map;)V+10
j  com.mlp.stark.services.aeron.AeronConnector.close()V+18
j  com.mlp.stark.services.aeron.AeronConnector$$Lambda$31.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x695b96]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056

**Comment by mjpt777** [comment]
What version did this happen on? In 1.10.5 I made some changes that improved the clean up code on close.

**Comment by tmontgomery** [comment]
1.11.2

**Comment by mjpt777** [comment]
If multiple threads are entering the Aeron client then a lock must be used. In the case of a lock being used I've added detection of an interrupt when waiting for a response from the driver to avoid this issue on a forced closed with https://github.com/real-logic/aeron/commit/d1eea2eb5e8b600ba227556286737038a34ae1d4 and https://github.com/real-logic/aeron/commit/fc0511c4219834b6a015e4d50509bb63de573ca0.
