### ISSUE TITLE
Aeron C Media Driver limitations

### ISSUE THREAD

**Issue by kdoherty2** [real-logic/aeron#570]
C Media Driver might not support sessions. 
Session is an association between single publication and one or more subscriptions for that publication.
When service starts a replay it is assigned with session ID. 
When two services start a replay at the same time they might receive duplicates cause the C Media driver will mix up these sessions together.

**Comment by mjpt777** [comment]
At some stage we would like to bring the C media driver up to feature parity with the Java media driver. This will be driven by clients wishing to sponsor the work.
