### ISSUE TITLE
In my C++ project, Publication.offer starts returning large negative numbers after successfully sending ~24 million messages

### ISSUE THREAD

**Issue by go4speed** [real-logic/aeron#574]
The StreamingPublisher and RateSubscriber sample projects using tag 1.11.2 seem to be working fine in a similar test scenario (sending batches of 65 million randomly sized messages under 100 bytes). But when performing that test within my own project, things suddenly appear to start failing after 24 million or so successful messages. Publication.offer will abruptly start returning a large negative numbers (eg. -214748720) instead of the usual positive number, or the expected enumerated constants (eg. the occasional BACK_PRESSURED or ADMIN_ACTION). 

I don't see any issues with /dev/shm free space, and AeronStat looks completely normal. I'm not sure what is wrong here, but under what conditions will Publication.offer suddenly start behaving this way? Once it starts failing, it never recovers for me.

Thanks in advance for any insights or tips!

**Comment by mjpt777** [comment]
Could you be doing something like using an exclusive publication from many threads? Is bounds checking enabled in your app in case some thread is writing outside the bounds of a buffer and corrupting the system?

**Comment by mjpt777** [comment]
Closing due to no further followup.
