### ISSUE TITLE
Multiple instances on the same machine eats too much temp space.

### ISSUE THREAD

**Issue by Sraw** [real-logic/aeron#577]
I'm using akka with aeron udp potocol. And I cannot launch over three instances due to exhausted temp space although I have 4G temp space in /dev/shm. The situation is:
1 instance: eats few KBs
2 instance: eats few MBs
3 instance: eats few hundred of MBs
4 instance: don't know how much is enough at all.

I've heard that It can be solved by using "Shared media driver" or reducing the message buffer size. But I didn't find anything about how to config a shared media driver.

So here are two questions:
1. Why it eats so much temp space when creating multiple instance on the same machine?
2. How to solve it?
3. Is this a bug? Or this is an expected behavior?

**Comment by Sraw** [comment]
@mjpt777 Thank you for clarification. So I understand this is not a bug but an expected behavior. But how to config a shared media driver? Do you mean we just need to config `aeron.dir` to the same directory then shared media driver will be used automatically?

**Comment by mjpt777** [comment]
Start the media driver on its own and then use the same `aeron.dir` for it and all the clients.

**Comment by Sraw** [comment]
Thanks, I understand.
