### ISSUE TITLE
Is publication offer function thread safe?

### ISSUE THREAD

**Issue by longwallstreet** [real-logic/aeron#578]
Use scenarios as follows:
Thread1: pub = Aeron.AddPublication(Channel1, StreamID1),   pub.Offer(.....)
Thread2: pub = Aeron.AddPublication(Channel1, StreamID2),   pub.Offer(....)
Channel1 = Channel2 and StreamID1 = StreamID2
Is this usage thread safe? Thanks.
PS: The version is 1.4.0

**Comment by mjpt777** [comment]
I assume this is C# given the code sample? If so then best addressed to https://github.com/AdaptiveConsulting/Aeron.NET.

It is not clear what part you are asking is thread safe. Publications and the Aeron client are threadsafe.

1.4.0 is a very old version and no longer supported.

**Comment by longwallstreet** [comment]
Thanks. C# code.
