### ISSUE TITLE
Array index out of bounds exception on Java driver with many clients killed at once

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#58]
Start the driver:

$ java -cp aeron-samples/build/libs/samples.jar -Dagrona.disable.bounds.checks=true uk.co.real_logic.aeron.samples.LowLatencyMediaDriver

Start a bunch (10-20 or so) of these:

$ java -cp aeron-samples/build/libs/samples.jar -Dagrona.disable.bounds.checks=true -Daeron.sample.frameCountLimit=1024 uk.co.real_logic.aeron.samples.BasicSubscriber &

and a bunch of these (around 10-15):

java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.messageLength=40 -Daeron.sample.messages=500000000 -Dagrona.disable.bounds.checks=true uk.co.real_logic.aeron.samples.BasicPublisher &

Let them get set up and start sending/receiving messages for a few seconds, then murder all the sources and receivers at once with something like this:

$ jps |grep Basic|cut -d ' ' -f 1|xargs kill

On the driver, I get an exception similar to the following:

[35015.120825] EXCEPTION [444/444]: java.lang.IndexOutOfBoundsException(Index: 45, Size: 43)
java.util.ArrayList.rangeCheck ArrayList.java:653
java.util.ArrayList.get ArrayList.java:429
uk.co.real_logic.aeron.driver.DriverConnection.updateSubscribersPosition DriverConnection.java:504
uk.co.real_logic.aeron.driver.DriverConductor.doWork DriverConductor.java:215
uk.co.real_logic.aeron.common.AgentRunner.run AgentRunner.java:85

Same exception from another run, with slightly different Index and Size:

[35299.517062] EXCEPTION [443/443]: java.lang.IndexOutOfBoundsException(Index: 11, Size: 7)
java.util.ArrayList.rangeCheck ArrayList.java:653
java.util.ArrayList.get ArrayList.java:429
uk.co.real_logic.aeron.driver.DriverConnection.updateSubscribersPosition DriverConnection.java:504
uk.co.real_logic.aeron.driver.DriverConductor.doWork DriverConductor.java:215
uk.co.real_logic.aeron.common.AgentRunner.run AgentRunner.java:85

**Comment by tmontgomery** [comment]
Thanks! This is great stuff to follow up on.

Pretty clear evidence that something is not right with how ArrayList handles multiple operations somehow. Worth a look.
