### ISSUE TITLE
Documentation: Rationale for Receiver Window default size

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#580]
I'd be interested to understand why the default Receiver Window is 128kB. This seems small compared to Aeron's other buffers. Can anyone comment?

(I think this is correct, please tell me if not) I also think it's important to understand that if you specify MinMulticastFlowControl you need to think about this setting. If it's possible that a Subscription frequently does not stay inside of the Receiver Window, and more than one such Subscription exists, the stream as a whole can become unintentionally rate-limited.

I'm happy to submit a PR with documentation changes for whatever useful info comes up here.

**Comment by lukepalmer** [comment]
To venture a guess: is 128kB the size that will work on most all linux distributions without having to adjust the kernel UDP receive buffer size?

**Comment by tmontgomery** [comment]
Yes, this is because of the RCVBUF sizes on most Linux distributions.
