### ISSUE TITLE
aeronmd consumes 300% CPU in idle state

### ISSUE THREAD

**Issue by yfinkelstein** [real-logic/aeron#584]
I noticed that just starting aeronmd causes it to spin and consume exactly 300% CPU (3 cores). I observed this on 2 different machines: ubuntu 16 and ubuntu 18. 

Is this expected, and if yes - why? if no, what could be special about my (vanilla) linux boxes?

Thanks.

**Comment by mjpt777** [comment]
What idle strategies have you configured?

**Comment by yfinkelstein** [comment]
Thanks for mentioning this. I was not having any idle strategy settings specified, which means a noop policy as I understood after looking at the code. It would be good to mention existence of these codes for C++ programs in your documentation:
```
#strategies: sleeping, spinning, yielding, noop
strategy=sleeping
export AERON_CONDUCTOR_IDLE_STRATEGY=$strategy
export AERON_SENDER_IDLE_STRATEGY=$strategy
export AERON_RECEIVER_IDLE_STRATEGY=$strategy
export AERON_THREADING_MODE=DEDICATED
```
However, even with `sleeping` an no workload the driver app is using ~30% of a single core on linux and ~80% of a core on my mac laptop. 
So, is there a way to not consume CPU in idle state?

**Comment by yfinkelstein** [comment]
![screen shot 2018-11-17 at 10 11 18 pm](https://user-images.githubusercontent.com/166346/48669270-d8147680-eab5-11e8-8799-0ac33ac9fe98.png)
Note the number of idle wake-ups on mac

**Comment by mjpt777** [comment]
You can use a shared, or shared network threading mode to further reduce CPU usage. However you are trading off responsiveness for CPU resource. Aeron is a not a system that will use no CPU at idle. If this is a concern for you then Aeron is maybe not such a good fit as a solution.

**Comment by mjpt777** [comment]
BTW these idle strategies use less CPU on Linux that what you are seeing on OS X.

**Comment by yfinkelstein** [comment]
It does not have to be so binary. Looking at this code: ```static void aeron_idle_strategy_sleeping_idle(void *state, int work_count)
{
    if (work_count > 0)
    {
        return;
    }

    nanosleep(&(struct timespec){.tv_nsec=1}, NULL);
}```

**Comment by mjpt777** [comment]
Java has a progressive backoff strategy and I've raised a [issue](https://github.com/real-logic/aeron/issues/585) for this.
