### ISSUE TITLE
Driver should catch incorrect MDC subscription URI

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/aeron#587]
The media driver should catch and report incorrect MDC URIs for Subscriptions. Subscriptions must specify `endpoint` if specifying `control`. A URI of this form `aeron:udp?control=192.168.86.241:45678` should generate an error on both C and Java.

Currently, the C driver reports an unknown error and Java succeeds.

**Comment by tmontgomery** [comment]
with 095fb9ff8 the C media driver and Java media driver both use 0.0.0.0:0 for endpoint when not set. So, this works the same. However, error checking should be added to ensure `endpoint` is set on the Subscription side for both C and Java media drivers.

**Comment by tmontgomery** [comment]
Would rather enforce that a Subscription _MUST_ specify `endpoint` if it specifies `control` even if `endpoint` uses `0.0.0.0:0`. Just makes it clear. This must work with `tags` as well.

**Comment by mjpt777** [comment]
@tmontgomery I agree. I found it confusing that it was not a requirement.

**Comment by tmontgomery** [comment]
We don't have any Subscription or Publication URI checks. We need those going forward, I think.

**Comment by mjpt777** [comment]
We have some basic checks like for the triplet when setting a starting position. More makes sense.
