### ISSUE TITLE
Unexpected behavior on a dying leader

### ISSUE THREAD

**Issue by ratcashdev** [real-logic/aeron#590]
Related to the cluster-module. 
If a dying leader results in the majority of the nodes being down, the offer by the client results in Publication.NOT_CONNECTED (after some time). This seem to be irreversible, even after some nodes come up again so that a new leader can be elected.
Not sure if this a consequence of the design (or raft), a bug, or a not properly followed protocol of the test code?
The test scenario is here: https://gist.github.com/ratcashdev/bd03856cfab77da206d5bf83f4f40211

**Comment by JPWatson** [comment]
Try running `pollEgress` on the client after the election so that it picks up the new leader event and switches the publication to the new leader.

**Comment by mjpt777** [comment]
Yes, as @JPWatson has pointed out you need to poll egress to get the new leadership event.

**Comment by ratcashdev** [comment]
All right. Thanks for the heads-up. So the egress channel is used to carry also technical messages (new leader) in addition to the user's messages? I have modified the test by having a thread that does not anything else just `client.pollEgress()`;
I have also realized that using `ClusterTool.removeMember` actually reconfigures the cluster so that consensus is possible to reach even if there's only a single node running out of the 3. Thus i got rid of this code (and the corresponding waits, since the `terminationHook` is not fired if I only call close() on the clusteredServices and mediaDrivers).

So now it behaves as I would expect: after shutting down the leader, it stops receiving messages. Catch-up kicks in after re-starting a previously shut-down static node. But the expected number of messages is not reached. Some seem to be lost.

**Comment by mjpt777** [comment]
Offer of a message does not guarantee reception within the cluster. You need to have an application protocol level acknowledgement to ensure reception and processing. The cluster does not loose messages that it has reached consensus on, until then messages are considered in-flight.

**Comment by tmontgomery** [comment]
There is an additional point here, which is why I suggested @ratcashdev file the issue. If an election takes a significant amount of time that a client session timeout causes it to close, should the new leader try to inform the client or not? i.e. if quorum is lost for longer than the timeout, then what is the result of the sessions all timing out?

**Comment by mjpt777** [comment]
Client session timeouts are reset to allow for a full timeout duration after a leader change regardless of the time it takes for the election. If the new leader cannot connect to the client within this timeout and the client does not then send a heartbeat if will timeout. Regardless the client should have some concept of timeout itself and if it cannot connect to the cluster within this time it should retry or give up.

**Comment by tmontgomery** [comment]
Another requirement that the test app needs. Needs to send a heartbeat. As well as retry/timeout logic on the leader.

**Comment by ratcashdev** [comment]
I have updated the gist (https://gist.github.com/ratcashdev/bd03856cfab77da206d5bf83f4f40211) to include the periodic egressPoll and heartbeat. 

I understand the important of the ACK, for a guaranteed processing, I think.
However, strictly from a delivery perspective, I thought that:
1. if the client loses connection to the leader, it will eventually miss a StatusMessage and thus will realize, that the messages since the last SM MAY have been lost. Obviously no leader, no NAK. However, it still has them in its send-buffer. I presume it will try re-sending them (or re-connecting to the new leader and re-sending). So if the (same) leader becomes reachable again, those messages will be delivered. Correct?
2. the new leader is the one with the highest offset (of the commited log), obviously
3. the new leader will let the client know, so that the client now knows where to re-send the messages since the last SM.
4. The new leader will distribute the commited log offset and start replicating his own uncommited log (if any) and that new messages are appended at the end of the uncommited log 

Slight improvement idea:  if a Follower realizes quorum is lost, it becomes a candidate and it could append to their own uncommited log any message they receive (e.g. in a multicast situation) and after becoming the leader they will first replicate the messages received during its candidate status. Messages after reaching LEADER status would be appended at the end of the uncommited log.

So combining the above (and assuming my presumptions are correct) it would mean no messages would get lost as long as there is at least a single node running. Either because the client keeps resending the messages since the last SM, or because the client will(?) try-to resend the very same (assumingly undelivered messages) to the newly elected leader.
