### ISSUE TITLE
CMake find_packages support

### ISSUE THREAD

**Issue by jmazar** [real-logic/aeron#617]
Hi all,

I was thinking it might be nice in the c++ build of aeron when you package using cmake package it also put a FindAeron.cmake file in the output that could be used with cmake's find_package functionality. I've written a small one myself I wouldn't mind passing along. It finds and sets AERON_INCLUDE_DIR and AERON_LIBRARIES. Let me know if I can help out in any way.

**Comment by mjpt777** [comment]
Submit a PR and we can review it.

**Comment by mjpt777** [comment]
Closing due to no followup.
