### ISSUE TITLE
Handle failed log buffer delete in C Media Driver

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#620]
The Java Media Driver attempts the delete the log buffer during the slow tick of the conductor duty cycle and if it fails it increments the FREE_FAILS counter and tries again in the next cycle. The C Media Driver should do similar to support Windows.

**Comment by mjpt777** [comment]
This will not be picked up until the C Media Driver officially supports Windows.

**Comment by farnyser** [comment]
Hi @mjpt777 
How is that different on Windows compared to the Linux version ?
Do you have some pointers on how to start looking at this ? 
Thanks

**Comment by mjpt777** [comment]
You can see the Java driver conductor attempting to free resources [here](https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/DriverConductor.java#L1600). If the client still has a file open it needs to be retried later. The resources such as publications an images need to support separate free and close operations.

https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java#L236-L263
https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/IpcPublication.java#L167-L191
https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/PublicationImage.java#L229-L257
