### ISSUE TITLE
Support session assigned publications in the C Media Driver

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#623]
Allow an original Publication to provide a session-id to be assigned when it is added to the C Media Driver to work like the Java Media Driver.

**Comment by mikeb01** [comment]
As part of this, should the C media driver support a reserved range?

**Comment by mikeb01** [comment]
This would also require checking that the session ids match when using concurrent publications.  In the Java driver, this section of the code also does verification of mtu and term length, should those bits of validation be added too?

**Comment by tmontgomery** [comment]
Yes, I think so, validation and reserved ranges should be done with this as well. The use of session-specific publications is used a lot with the archive for replay and normally sets MTU and term length when used.

**Comment by mjpt777** [comment]
The reserved ranges are required for those who reserve a range when using session assigned publications and dynamic MDC to traverse firewalls using NAT.
