### ISSUE TITLE
Java module support

### ISSUE THREAD

**Issue by cowwoc** [real-logic/aeron#627]
Are there any plans to add Java module support?

I am expecting `module-info.java` files or (at the very least) `Automatic-Module-Name` entries in `MANIFEST.MF` to help my own modular code depend on your library.

**Comment by mjpt777** [comment]
We currently have no plans for adding module support. If your company was willing to sponsor the work or purchase support then we could look into it.

**Comment by cowwoc** [comment]
@mjpt777 What about just adding an `Automatic-Module-Name` to `MANIFEST.MF`? Surely that is easy/quick to do?

**Comment by mjpt777** [comment]
Please send a PR for that then.

**Comment by cowwoc** [comment]
@mjpt777 Sure. What module names would you like?

**Comment by mjpt777** [comment]
What do you see as the modules and then we can suggest suitable names?

**Comment by cowwoc** [comment]
@mjpt777 I'd break it down the same lines as https://search.maven.org/search?q=g:io.aeron

So your module names would probably be `io.aeron.driver`, `io.aeron.cluster` and so on.

**Comment by cowwoc** [comment]
Very cool. Thanks Martin.
