### ISSUE TITLE
Add C++ LossStat tool

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#637]
Produce a C++ client for LossStat that is similar to the Java LossStat.

**Comment by mattgodbolt** [comment]
+1 to this. I started a quick spike but got distracted by my day job. Doesn't look like it's too much work though.

**Comment by mjpt777** [comment]
Added with this commit. https://github.com/real-logic/aeron/commit/2b331d2a354df99c61c7e8525ad82e3a34fc3ad0

**Comment by mattgodbolt** [comment]
Fantastic: thanks!
