### ISSUE TITLE
Unable to open markfile with version 0

### ISSUE THREAD

**Issue by pgrange** [real-logic/aeron#638]
After upgrading aeron, I suddenly can't open mark-files generated by the cluster.

aeron-cluster-mark-codecs version has been _downgraded_ from 1 to 0 in this commit: https://github.com/real-logic/aeron/commit/3cdafbdfb57c86b0146ef8b7021bdaa9a80a7f1d

We can see this version 0 here: https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/resources/aeron-cluster-mark-codecs.xml#L5

Now, when I try to open a mark-file generated by aeron using ClusterMarkFile I get this exception:

```
java.lang.IllegalStateException: Mark file is created but not initialised
	at org.agrona.MarkFile.mapExistingMarkFile(MarkFile.java:420)
	at org.agrona.MarkFile.<init>(MarkFile.java:180)
	at io.aeron.cluster.service.ClusterMarkFile.<init>(ClusterMarkFile.java:142)
	at Status.openMarkFile(Status.java:224)
	at Status.healthyness(Status.java:158)
	at Status.isHealthy(Status.java:131)
	at Status.main(Status.java:117)
```
This seems to be directly related to agrona considering that 0, as a version, is its _null_ value and considers it an error:
https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/MarkFile.java#L533

**Comment by BodySplash** [comment]
That means also, that most commands in `io.aeron.cluster.ClusterTool` are not working.

**Comment by ZachBray** [comment]
FYI this seems to surface when using the `ClusterTool` but not when running a cluster node. Whilst they both construct `ClusterMarkFile`s they do so using different constructors. Only the `ClusterTool` ends up executing `MarkFile.mapExistingMarkFile(...)` which contains this check.

**Comment by mjpt777** [comment]
The use of SBE schema version and mark file version have been conflated by mistake. We'll look at how to address this and give priority in the solution to those with a support contract.

**Comment by mjpt777** [comment]
Fixed with this commit. https://github.com/real-logic/aeron/commit/d3fc6b7d8e26108dcc05afc08e81cb8efab44584
