### ISSUE TITLE
Label inconsistency in AeronStats with single publisher and multiple subscribers on the same machine

### ISSUE THREAD

**Issue by johnpr01** [real-logic/Aeron#64]
Test setup:
Start AeronDriver (from driver jar)
Start AeronStat (from samples jar)
Start BasicSubscriber
Start BasicPublisher

You will see something similar to this in the output of AeronStat (I have removed the 20 base stats for simplicity):
12:03:47 - Aeron Stat
=========================
 20:               28,880 - sender pos: udp://localhost:40123 ec38cf33 a
 21:            8,417,488 - publisher limit: udp://localhost:40123 ec38cf33 a
 22:               28,880 - subscriber pos: udp://localhost:40123 ec38cf33 a
 23:               28,880 - receiver pos: udp://localhost:40123 ec38cf33 a
 24:               28,880 - receiver hwm: udp://localhost:40123 ec38cf33 a

Then start up a second BasicSubscriber on the same machine and you will get the following from AeronStat:
12:03:55 - Aeron Stat
=========================
 20:              354,640 - sender pos: udp://localhost:40123 ec38cf33 a
 21:            8,743,248 - publisher limit: udp://localhost:40123 ec38cf33 a
 22:              354,640 - subscriber pos: udp://localhost:40123 ec38cf33 a
 23:              354,640 - receiver pos: udp://localhost:40123 ec38cf33 a
 24:              354,640 - receiver hwm: udp://localhost:40123 ec38cf33 a
 25:              354,640 - subscriber: udp://localhost:40123 ec38cf33 a

Notice that on entry 25, the subscriber does not show "pos" in the label.

If you then kill the first subscriber (entry 22) you will get the following:
12:03:58 - Aeron Stat
=========================
 20:              479,728 - sender pos: udp://localhost:40123 ec38cf33 a
 21:            8,868,336 - publisher limit: udp://localhost:40123 ec38cf33 a
 23:              479,728 - receiver pos: udp://localhost:40123 ec38cf33 a
 24:              479,728 - receiver hwm: udp://localhost:40123 ec38cf33 a
 25:              479,728 - subscriber: udp://localhost:40123 ec38cf33 a

Notice that entry 22 has been removed

If you then restart that subscriber:
12:04:10 - Aeron Stat
=========================
 20:              983,056 - sender pos: udp://localhost:40123 ec38cf33 a
 21:            9,371,664 - publisher limit: udp://localhost:40123 ec38cf33 a
 22:              983,056 - subscriber: udp://localhost:40123 ec38cf33 a
 23:              983,104 - receiver pos: udp://localhost:40123 ec38cf33 a
 24:              983,104 - receiver hwm: udp://localhost:40123 ec38cf33 a
 25:              983,056 - subscriber: udp://localhost:40123 ec38cf33 a

Entry 22 shows back up but this time the "pos" label is no longer there.

**Comment by mjpt777** [comment]
Nice spot on detail. Thanks!
