### ISSUE TITLE
C media driver: ability to configure context programmatically

### ISSUE THREAD

**Issue by mattgodbolt** [real-logic/aeron#640]
It would be fantastic to be able to programmatically configure the context. Right now the environment-variable based approach is very clunky, potentially race-conditiony, and very undiscoverable from an IDE.

Having access to the context to mutate it in some way would be great, or having functions to set the options too. Anything instead of looking through a load of `SHOUTY_CASE_ENV_VAR` settings in a header file manually :grinning:

**Comment by tmontgomery** [comment]
I've added a few option set/get functions in this commit 83b7a666e . Let me know what you think.

**Comment by mattgodbolt** [comment]
Thanks Todd!

**Comment by tmontgomery** [comment]
I've added a ton of functions for this as of 91e53ff17
