### ISSUE TITLE
Massive network traffic noticed from Market Data Publisher causing system outage

### ISSUE THREAD

**Issue by harnitbakshi** [real-logic/aeron#654]
Hello, we have been running Aeron quite successfully in production so far but there was an instance recently where there was a surge in market data causing outage in network on one of our servers

**Our setup is as follows:**
- We have 4 market data publishers on one machine
- We have 3 market data subscribers on 4 different servers
- We are running this on EC2 instances on AWS

**scenario is as follows:**
- Around 4:40 pm we have more than normal traffic coming in
- I can explain this as our subscribers cannot keep up at this stage (I see a lot of back pressure logs in our producers during this time), hence we back pressure our market data stream. Currently our producers just drop the message and do no retries when they see back pressure
- Our monitoring shows the network traffic produced by our market data feed to be > 8gbps from less than ~ 0.3 gbps before the surge
- Could I ask if this is because of Aeron Media Driver retrying to send the market data to other subscribers? For market data feed we can accept loss of messages and afford unreliability
- Could you please tell me are the config setting below not ideal? Or could we set reliable=false on the market data stream? Essentially we are looking to handle this scenario gracefully without maxing out the network

**Here are the settings we have for our aeron-media-driver currently:**

- aeron.mtu.length=8000
- aeron.rcv.initial.window.length=25m 
- aeron.term.buffer.sparse.file=false 
- aeron.socket.so_rcvbuf=30m
- aeron.socket.so_sndbuf=30m

**Aeron stat:**
`17:47:13 - Aeron Stat (CnC v15), pid 5304
======================================================================
  0:    4,132,931,131,776 - Bytes sent
  1:    5,282,552,048,064 - Bytes received
  2:                    0 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:                    0 - Failed offers to DriverConductorProxy
  5:                5,655 - NAKs sent
  6:            6,722,793 - NAKs received
  7:           16,427,572 - Status Messages sent
  8:          356,101,365 - Status Messages received
  9:            3,781,466 - Heartbeats sent
 10:            3,762,948 - Heartbeats received
 11:            3,110,657 - Retransmits sent
 12:          167,609,171 - Flow control under runs
 13:              413,714 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:              150,183 - Short sends
 17:                    0 - Failed attempts to free log buffers
 18:                  112 - Sender flow control limits applied
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    0 - ControllableIdleStrategy status
 23:                    0 - Loss gap fills
 24:                  986 - Client liveness timeouts
 25:                    0 - sub-pos: 18004 -1425330367 104 aeron:ipc @0
 26:    1,554,803,233,221 - client-heartbeat: 17808
 27:           16,777,216 - pub-lmt: 17766 -1425330407 36 aeron:ipc
 28:        6,610,320,000 - pub-pos (sample): 17690 -1425330420 97 aeron:ipc
 29:               49,344 - sub-pos: 17676 -1425330399 70 aeron:ipc @0
 30:                3,520 - sub-pos: 17962 -1425330410 109 aeron:ipc @0
 31:                    0 - sub-pos: 17958 -1425330407 36 aeron:ipc @0
 32:       54,513,152,512 - snd-pos: 17812 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
 33:                    0 - sub-pos: 18015 -1425330405 95 aeron:ipc @0
 34:                6,336 - sub-pos: 17739 -1425330389 108 aeron:ipc @0
 35:                    0 - pub-pos (sample): 17845 -1425330385 25 aeron:ipc
 36:                3,520 - pub-pos (sample): 17741 -1425330410 109 aeron:ipc
 37:                6,336 - pub-pos (sample): 17833 -1425330389 108 aeron:ipc
 38:    1,554,803,233,285 - client-heartbeat: 17790
 39:                    0 - sub-pos: 17973 -1425330366 39 aeron:ipc @0
 40:           16,777,216 - pub-lmt: 17819 -1425330396 15 aeron:ipc
 41:                    0 - sub-pos: 17965 -1425330409 38 aeron:ipc @0
 42:        5,556,882,848 - sub-pos: 18079 -1425330419 98 aeron:ipc @0
 43:           16,777,216 - pub-lmt: 18093 -1425330362 64 aeron:ipc
 44:                    0 - sub-pos: 18025 -1425330366 39 aeron:ipc @0
 45:                    0 - pub-lmt: 17683 -1425330424 56 aeron:ipc
 46:                    0 - sub-pos: 18051 -1425330408 106 aeron:ipc @0
 47:                4,032 - sub-pos: 17943 -1425330411 33 aeron:ipc @0
 48:                4,032 - pub-pos (sample): 17738 -1425330411 33 aeron:ipc
 49:                4,608 - pub-pos (sample): 17822 -1425330395 16 aeron:ipc
 50:                    0 - sub-pos: 18009 -1425330406 81 aeron:ipc @0
 51:                    0 - sub-pos: 18008 -1425330405 95 aeron:ipc @0
 52:           16,777,216 - pub-lmt: 17716 -1425330414 32 aeron:ipc
 53:           16,777,216 - pub-lmt: 17778 -1425330406 81 aeron:ipc
 54:                    0 - sub-pos: 17674 -1425330363 74 aeron:ipc @0
 55:           16,777,216 - pub-lmt: 17781 -1425330405 95 aeron:ipc
 56:                2,400 - sub-pos: 17996 -1425330412 45 aeron:ipc @0
 57:                    0 - pub-pos (sample): 17842 -1425330386 24 aeron:ipc
 58:                    0 - pub-lmt: 17682 -1425330425 90 aeron:ipc
 59:                    0 - pub-lmt: 17913 -1425330372 112 aeron:ipc
 60:                1,248 - pub-pos (sample): 17851 -1425330384 26 aeron:ipc
 61:              309,472 - pub-pos (sample): 17865 -1425330381 29 aeron:ipc
 62:    1,554,803,233,020 - client-heartbeat: 18085
 63:    1,554,803,232,979 - client-heartbeat: 18066
 64:                    0 - pub-lmt: 17832 -1425330390 21 aeron:ipc
 65:           16,777,216 - pub-lmt: 18090 -1425330364 73 aeron:ipc
 66:                    0 - sub-pos: 17987 -1425330416 31 aeron:ipc @0
 67:       54,513,152,512 - sub-pos: 18087 -1425330401 53 aeron:udp?control-mode=manual @50634144
 68:           16,777,216 - pub-lmt: 17881 -1425330378 94 aeron:ipc
 69:                    0 - pub-pos (sample): 17907 -1425330373 110 aeron:ipc
 70:                1,248 - sub-pos: 17787 -1425330384 26 aeron:ipc @0
 71:        6,801,324,832 - pub-pos (sample): 17688 -1425330421 96 aeron:ipc
 72:                    0 - sub-pos: 17999 -1425330406 81 aeron:ipc @0
 73:                  320 - sub-pos: 17985 -1425330402 44 aeron:ipc @0
 74:                    0 - sub-pos: 17971 -1425330403 40 aeron:ipc @0
 75:            1,024,000 - pub-pos (sample): 17854 -1425330383 27 aeron:ipc
 76:           16,777,216 - pub-lmt: 17789 -1425330404 42 aeron:ipc
 77:                2,400 - pub-pos (sample): 17725 -1425330412 45 aeron:ipc
 78:                2,400 - sub-pos: 18043 -1425330412 45 aeron:ipc @0
 79:                    0 - pub-pos (sample): 17717 -1425330413 34 aeron:ipc
 80:                    0 - sub-pos: 18003 -1425330406 81 aeron:ipc @0
 81:           16,777,216 - pub-lmt: 17836 -1425330388 22 aeron:ipc
 82:    1,554,803,233,280 - client-heartbeat: 17806
 83:            1,024,000 - pub-pos (sample): 17824 -1425330393 18 aeron:ipc
 84:           16,777,216 - pub-lmt: 17706 -1425330415 43 aeron:ipc
 85:                  320 - sub-pos: 17992 -1425330402 44 aeron:ipc @0
 86:           16,777,216 - pub-lmt: 17865 -1425330381 29 aeron:ipc
 87:            1,024,000 - pub-pos (sample): 17836 -1425330388 22 aeron:ipc
 88:                    0 - pub-pos (sample): 17683 -1425330424 56 aeron:ipc
 89:                    0 - sub-pos: 17978 -1425330403 40 aeron:ipc @0
 90:                    0 - pub-lmt: 17890 -1425330376 101 aeron:ipc
 91:                    0 - sub-pos: 17977 -1425330403 40 aeron:ipc @0
 92:           16,777,216 - pub-lmt: 17842 -1425330386 24 aeron:ipc
 93:                1,152 - sub-pos: 17986 -1425330404 42 aeron:ipc @0
 94:                    0 - pub-pos (sample): 17816 -1425330397 14 aeron:ipc
 95:                4,608 - sub-pos: 17712 -1425330395 16 aeron:ipc @0
 96:                    0 - pub-pos (sample): 17874 -1425330379 80 aeron:ipc
 97:                    0 - sub-pos: 17980 -1425330415 43 aeron:ipc @0
 98:                    0 - sub-pos: 18012 -1425330367 104 aeron:ipc @0
 99:                  320 - pub-pos (sample): 17805 -1425330402 44 aeron:ipc
100:                    0 - sub-pos: 17779 -1425330378 94 aeron:ipc @0
101:                2,560 - pub-pos (sample): 17716 -1425330414 32 aeron:ipc
102:              590,080 - sub-pos: 17678 -1425330398 60 aeron:ipc @0
103:    1,554,803,233,275 - client-heartbeat: 17782
104:    1,554,803,233,107 - client-heartbeat: 17679
105:                    0 - sub-pos: 17951 -1425330413 34 aeron:ipc @0
106:                    0 - pub-pos (sample): 17755 -1425330409 38 aeron:ipc
107:           16,777,216 - pub-lmt: 17874 -1425330379 80 aeron:ipc
108:           16,777,216 - pub-lmt: 17704 -1425330416 31 aeron:ipc
109:                2,560 - sub-pos: 17990 -1425330414 32 aeron:ipc @0
110:           16,777,216 - pub-lmt: 17823 -1425330394 17 aeron:ipc
111:        6,021,819,744 - sub-pos: 18077 -1425330418 99 aeron:ipc @0
112:                    0 - sub-pos: 17972 -1425330409 38 aeron:ipc @0
113:        5,556,879,392 - pub-pos (sample): 17692 -1425330419 98 aeron:ipc
114:                    0 - sub-pos: 18011 -1425330408 106 aeron:ipc @0
115:           16,777,216 - pub-lmt: 17815 -1425330398 60 aeron:ipc
116:        6,610,325,440 - sub-pos: 18081 -1425330420 97 aeron:ipc @0
117:        6,801,342,400 - sub-pos: 18083 -1425330421 96 aeron:ipc @0
118:                    0 - sub-pos: 18002 -1425330405 95 aeron:ipc @0
119:           16,777,216 - pub-lmt: 17859 -1425330382 28 aeron:ipc
120:                    0 - sub-pos: 17757 -1425330375 102 aeron:ipc @0
121:                    0 - rcv-channel: aeron:udp?control-mode=manual
122:                    0 - sub-pos: 17938 -1425330416 31 aeron:ipc @0
123:    1,554,803,233,427 - client-heartbeat: 17765
124:                    0 - pub-pos (sample): 17684 -1425330423 52 aeron:ipc
125:           16,777,216 - pub-lmt: 18065 -1425330367 104 aeron:ipc
126:                   64 - pub-pos (sample): 18089 -1425330365 61 aeron:ipc
127:                    0 - sub-pos: 18049 -1425330367 104 aeron:ipc @0
128:                  320 - sub-pos: 17993 -1425330402 44 aeron:ipc @0
129:                    0 - pub-pos (sample): 17813 -1425330400 58 aeron:ipc
130:                1,152 - sub-pos: 18034 -1425330404 42 aeron:ipc @0
131:       54,513,035,616 - pub-pos (sample): 17812 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
132:               49,344 - pub-pos (sample): 17814 -1425330399 70 aeron:ipc
133:           10,417,984 - sub-pos: 17675 -1425330417 72 aeron:ipc @0
134:                    0 - pub-lmt: 17685 -1425330422 89 aeron:ipc
135:    1,554,803,233,171 - client-heartbeat: 17669
136:                4,032 - sub-pos: 17946 -1425330411 33 aeron:ipc @0
137:           16,777,216 - pub-lmt: 17824 -1425330393 18 aeron:ipc
138:                   64 - sub-pos: 18080 -1425330365 61 aeron:ipc @0
139:                    0 - sub-pos: 18026 -1425330408 106 aeron:ipc @0
140:    1,554,803,233,314 - client-heartbeat: 17731
141:                    0 - pub-pos (sample): 17870 -1425330380 62 aeron:ipc
142:                    0 - sub-pos: 18027 -1425330403 40 aeron:ipc @0
143:            1,024,000 - sub-pos: 17698 -1425330396 15 aeron:ipc @0
144:            1,024,000 - pub-pos (sample): 17839 -1425330387 23 aeron:ipc
145:                    0 - pub-lmt: 17902 -1425330374 103 aeron:ipc
146:              118,016 - pub-pos (sample): 18093 -1425330362 64 aeron:ipc
147:                    0 - sub-pos: 18047 -1425330406 81 aeron:ipc @0
148:            1,024,000 - sub-pos: 17714 -1425330393 18 aeron:ipc @0
149:           16,777,216 - pub-lmt: 17805 -1425330402 44 aeron:ipc
150:       54,513,152,512 - rcv-hwm: 18091 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
151:                2,560 - sub-pos: 17941 -1425330414 32 aeron:ipc @0
153:                    0 - pub-lmt: 17816 -1425330397 14 aeron:ipc
154:                4,032 - sub-pos: 17994 -1425330411 33 aeron:ipc @0
155:                    0 - sub-pos: 18017 -1425330408 106 aeron:ipc @0
156:                    0 - pub-pos (sample): 17832 -1425330390 21 aeron:ipc
157:                    0 - pub-pos (sample): 17797 -1425330403 40 aeron:ipc
158:                2,560 - sub-pos: 17939 -1425330414 32 aeron:ipc @0
159:            1,024,288 - sub-pos: 17803 -1425330382 28 aeron:ipc @0
160:                3,520 - sub-pos: 17967 -1425330410 109 aeron:ipc @0
161:                    0 - pub-pos (sample): 18092 -1425330363 74 aeron:ipc
162:                    0 - sub-pos: 18018 -1425330367 104 aeron:ipc @0
163:               36,352 - sub-pos: 18076 -1425330370 2 aeron:ipc @0
164:           16,777,216 - pub-lmt: 17755 -1425330409 38 aeron:ipc
165:        5,572,355,712 - pub-lmt: 17692 -1425330419 98 aeron:ipc
166:           16,777,216 - pub-lmt: 17921 -1425330370 2 aeron:ipc
167:            1,024,000 - sub-pos: 17753 -1425330388 22 aeron:ipc @0
168:              590,080 - sub-pos: 18086 -1425330398 60 aeron:ipc @0
169:                    0 - sub-pos: 18001 -1425330413 34 aeron:ipc @0
170:            1,024,000 - sub-pos: 18071 -1425330387 23 aeron:ipc @0
171:                1,152 - sub-pos: 17984 -1425330404 42 aeron:ipc @0
172:                    0 - pub-pos (sample): 17890 -1425330376 101 aeron:ipc
173:        6,626,465,248 - pub-lmt: 17690 -1425330420 97 aeron:ipc
174:                1,152 - pub-pos (sample): 17789 -1425330404 42 aeron:ipc
175:                    0 - pub-pos (sample): 17706 -1425330415 43 aeron:ipc
176:                    0 - sub-pos: 17670 -1425330364 73 aeron:ipc @0
177:                    0 - pub-pos (sample): 17778 -1425330406 81 aeron:ipc
178:                    0 - sub-pos: 17969 -1425330366 39 aeron:ipc @0
179:           16,777,216 - pub-lmt: 17839 -1425330387 23 aeron:ipc
180:                    0 - pub-pos (sample): 17917 -1425330371 114 aeron:ipc
181:            1,026,880 - pub-pos (sample): 17823 -1425330394 17 aeron:ipc
182:                    0 - pub-pos (sample): 17826 -1425330392 19 aeron:ipc
183:               36,352 - sub-pos: 17671 -1425330368 68 aeron:ipc @0
184:                    0 - pub-pos (sample): 18065 -1425330367 104 aeron:ipc
185:                    0 - pub-pos (sample): 17762 -1425330408 106 aeron:ipc
186:        6,816,358,944 - pub-lmt: 17688 -1425330421 96 aeron:ipc
187:                3,520 - sub-pos: 17963 -1425330410 109 aeron:ipc @0
188:                   64 - sub-pos: 18084 -1425330365 61 aeron:ipc @0
189:                    0 - sub-pos: 17795 -1425330386 24 aeron:ipc @0
190:               36,352 - pub-pos (sample): 17921 -1425330370 2 aeron:ipc
191:                    0 - pub-lmt: 17845 -1425330385 25 aeron:ipc
192:    1,554,803,233,129 - client-heartbeat: 17817
193:    1,554,803,233,023 - client-heartbeat: 17686
194:            1,024,288 - pub-pos (sample): 17859 -1425330382 28 aeron:ipc
195:                    0 - pub-pos (sample): 17913 -1425330372 112 aeron:ipc
196:                    0 - pub-pos (sample): 18090 -1425330364 73 aeron:ipc
197:           16,777,216 - pub-lmt: 17741 -1425330410 109 aeron:ipc
198:              118,016 - sub-pos: 17811 -1425330362 64 aeron:ipc @0
199:           16,777,216 - pub-lmt: 17886 -1425330377 100 aeron:ipc
200:                    0 - sub-pos: 17776 -1425330379 80 aeron:ipc @0
201:                    0 - pub-lmt: 17826 -1425330392 19 aeron:ipc
202:    1,554,803,233,182 - client-heartbeat: 17707
203:                    0 - pub-pos (sample): 17895 -1425330375 102 aeron:ipc
204:                    0 - sub-pos: 17989 -1425330415 43 aeron:ipc @0
205:       54,521,541,120 - pub-lmt: 17812 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
206:    1,554,803,233,132 - client-heartbeat: 18058
207:    1,554,803,233,364 - client-heartbeat: 17726
208:                    0 - sub-pos: 18037 -1425330415 43 aeron:ipc @0
209:    1,554,803,233,318 - client-heartbeat: 17810
210:                    0 - pub-pos (sample): 17704 -1425330416 31 aeron:ipc
211:           16,777,216 - pub-lmt: 17822 -1425330395 16 aeron:ipc
212:                    0 - sub-pos: 17953 -1425330407 36 aeron:ipc @0
213:                    1 - snd-channel: aeron:udp?control=raichu-4.sg.m-daq.net:40123
214:    1,554,803,233,205 - client-heartbeat: 18074
215:                    0 - sub-pos: 17964 -1425330409 38 aeron:ipc @0
216:                    0 - sub-pos: 17945 -1425330413 34 aeron:ipc @0
217:              118,016 - sub-pos: 17818 -1425330362 64 aeron:ipc @0
218:                    0 - pub-pos (sample): 17881 -1425330378 94 aeron:ipc
219:                    0 - sub-pos: 18063 -1425330377 100 aeron:ipc @0
220:           16,777,216 - pub-lmt: 17725 -1425330412 45 aeron:ipc
221:       54,521,541,120 - snd-lmt: 17812 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
222:    1,554,803,233,014 - client-heartbeat: 17752
223:            1,024,000 - pub-pos (sample): 17819 -1425330396 15 aeron:ipc
224:                    0 - sub-pos: 17933 -1425330416 31 aeron:ipc @0
225:                    0 - pub-lmt: 17917 -1425330371 114 aeron:ipc
226:           16,777,216 - pub-lmt: 18032 -1425330369 67 aeron:ipc
227:           16,777,216 - pub-lmt: 17717 -1425330413 34 aeron:ipc
228:                    0 - sub-pos: 17955 -1425330407 36 aeron:ipc @0
229:           16,777,216 - pub-lmt: 18089 -1425330365 61 aeron:ipc
230:                    0 - pub-lmt: 17870 -1425330380 62 aeron:ipc
231:                    0 - pub-pos (sample): 17682 -1425330425 90 aeron:ipc
232:                1,152 - sub-pos: 17975 -1425330404 42 aeron:ipc @0
233:                    0 - sub-pos: 18007 -1425330407 36 aeron:ipc @0
234:    1,554,803,233,427 - client-heartbeat: 17798
235:           16,777,216 - pub-lmt: 17854 -1425330383 27 aeron:ipc
236:           16,777,216 - pub-lmt: 18039 -1425330368 68 aeron:ipc
237:           16,777,216 - pub-lmt: 18092 -1425330363 74 aeron:ipc
238:            1,024,000 - pub-pos (sample): 17828 -1425330391 20 aeron:ipc
239:                    0 - pub-pos (sample): 17902 -1425330374 103 aeron:ipc
240:    1,554,803,233,138 - client-heartbeat: 17742
241:                    0 - sub-pos: 17929 -1425330416 31 aeron:ipc @0
242:            1,024,000 - sub-pos: 17763 -1425330391 20 aeron:ipc @0
243:            1,024,000 - sub-pos: 17699 -1425330383 27 aeron:ipc @0
244:                3,520 - sub-pos: 18014 -1425330410 109 aeron:ipc @0
245:                    0 - sub-pos: 18048 -1425330405 95 aeron:ipc @0
246:           16,777,216 - pub-lmt: 17797 -1425330403 40 aeron:ipc
247:                   64 - sub-pos: 18082 -1425330365 61 aeron:ipc @0
248:              118,016 - sub-pos: 17809 -1425330362 64 aeron:ipc @0
249:                    0 - pub-pos (sample): 17766 -1425330407 36 aeron:ipc
250:    1,554,803,233,303 - client-heartbeat: 17718
251:        6,021,814,976 - pub-pos (sample): 17694 -1425330418 99 aeron:ipc
252:    1,554,803,232,975 - client-heartbeat: 17745
253:                2,400 - sub-pos: 17995 -1425330412 45 aeron:ipc @0
254:       54,513,152,512 - rcv-pos: 18091 -1425330401 53 aeron:udp?control=raichu-4.sg.m-daq.net:40123
255:              590,080 - pub-pos (sample): 17815 -1425330398 60 aeron:ipc
256:           16,777,216 - pub-lmt: 17738 -1425330411 33 aeron:ipc
257:                    0 - pub-pos (sample): 17781 -1425330405 95 aeron:ipc
258:                    0 - pub-pos (sample): 18032 -1425330369 67 aeron:ipc
259:                    0 - pub-pos (sample): 17685 -1425330422 89 aeron:ipc
260:           16,777,216 - pub-lmt: 17895 -1425330375 102 aeron:ipc
261:        6,037,155,744 - pub-lmt: 17694 -1425330418 99 aeron:ipc
262:           10,417,984 - pub-pos (sample): 17700 -1425330417 72 aeron:ipc
263:              118,016 - sub-pos: 17677 -1425330362 64 aeron:ipc @0
264:                    0 - sub-pos: 17988 -1425330415 43 aeron:ipc @0
265:                    0 - sub-pos: 18021 -1425330409 38 aeron:ipc @0
266:                    0 - pub-pos (sample): 18073 -1425330366 39 aeron:ipc
267:                2,560 - sub-pos: 17934 -1425330414 32 aeron:ipc @0
268:           16,777,216 - pub-lmt: 17828 -1425330391 20 aeron:ipc
269:              309,472 - sub-pos: 17723 -1425330381 29 aeron:ipc @0
270:    1,554,803,233,097 - client-heartbeat: 17696
271:            1,026,880 - sub-pos: 17734 -1425330394 17 aeron:ipc @0
272:                  320 - sub-pos: 18042 -1425330402 44 aeron:ipc @0
273:                   64 - sub-pos: 18078 -1425330365 61 aeron:ipc @0
274:           25,203,520 - pub-lmt: 17700 -1425330417 72 aeron:ipc
275:                4,032 - sub-pos: 17942 -1425330411 33 aeron:ipc @0
276:           16,777,216 - pub-lmt: 17762 -1425330408 106 aeron:ipc
277:                    0 - sub-pos: 17968 -1425330366 39 aeron:ipc @0
278:               36,352 - pub-pos (sample): 18039 -1425330368 68 aeron:ipc
279:                    0 - sub-pos: 17948 -1425330413 34 aeron:ipc @0
280:           16,777,216 - pub-lmt: 18073 -1425330366 39 aeron:ipc
281:                2,400 - sub-pos: 17991 -1425330412 45 aeron:ipc @0
282:           16,777,216 - pub-lmt: 17814 -1425330399 70 aeron:ipc
283:    1,554,803,232,975 - client-heartbeat: 17687
284:           16,777,216 - pub-lmt: 17851 -1425330384 26 aeron:ipc
285:                    0 - sub-pos: 17672 -1425330369 67 aeron:ipc @0
286:                    0 - pub-lmt: 17813 -1425330400 58 aeron:ipc
287:              118,016 - sub-pos: 17807 -1425330362 64 aeron:ipc @0
288:                    0 - pub-pos (sample): 17886 -1425330377 100 aeron:ipc
289:                    0 - pub-lmt: 17907 -1425330373 110 aeron:ipc
290:                    0 - pub-lmt: 17684 -1425330423 52 aeron:ipc
291:           16,777,216 - pub-lmt: 17833 -1425330389 108 aeron:ipc
292:    1,554,803,232,975 - client-heartbeat: 17768
`

**Comment by harnitbakshi** [comment]
Hi Martin from our stats we have no packet loss at all. Anything else you can point out thanks !

**Comment by mjpt777** [comment]
As @tmontgomery has pointed out your config setting are not appropriate for a market data usecase.
