### ISSUE TITLE
Provide indication of retransmission due to NAK

### ISSUE THREAD

**Issue by dameiss** [real-logic/Aeron#66]
For analysis (e.g. the Wireshark dissector I'm working on), it would be helpful to be able to distinguish between data frames which are repeated because the publisher is idle, and data frames which are retransmitted in response to a NAK. An additional bit in the data frame flags would be sufficient.

**Comment by tmontgomery** [comment]
This should be possible to add. Not really needed for operation due to how the `LogRebuilder` works, but definitely nice for dissection.

**Comment by mjpt777** [comment]
We could create a scanner for retransmission that sets the bit in the header before sending.
