### ISSUE TITLE
how to best design with channel/stream?

### ISSUE THREAD

**Issue by andmer** [real-logic/aeron#661]
2 different feeds, "feed_a" and "feed_b"

should they go to a different port? and streamid is some default on every port
feed_a = aeron:udp?endpoint=224.0.1.1:9000, streamid 10
feed_b = aeron:udp?endpoint=224.0.1.1:9001, streamid 10
continuing along this for subsequent separate feeds etc...

or a different streamid on the same port?
feed_a = aeron:udp?endpoint=224.0.1.1:9000, streamid 10
feed_b = aeron:udp?endpoint=224.0.1.1:9000, streamid 11
continuing along this for subsequent separate feeds etc...

Essentially port/streamid giving me "topic" semantics, or am I thinking about this wrong?

when do i use a different port and when do i use a different stream?

**Comment by andmer** [comment]
when do i use a different port and when do i use a different stream?

**Comment by tmontgomery** [comment]
Depends on what you need and your application demands. Lots of variables to consider. So, not a straight forward question.

**Comment by andmer** [comment]
Hey Todd,


Lets say some simple case like:
10 broadcast nodes, each node pubs to multiple subscribers (1 way)

10 request/response node, each node receives requests from and pubs responses to multiple subscribers (2 way)


Any insight is appreciated.

**Comment by tmontgomery** [comment]
Still, I number of options and variables to consider. Do you want to use Multi-Destination Cast or Multicast, etc. How latency sensitive? Kernel bypass? What else is on the network? Expected throughput? How should flow control back pressure? How much space in /dev/shm? How big are the messages? etc.

Sorry, there just is no hard and fast rule to follow. It's more of a system design exercise. For that, Martin and I offer consulting services.

**Comment by andmer** [comment]
thank you. understood. I guess I was looking for a general rule of thumb to start my evaluation, before diving deep.
