### ISSUE TITLE
Directory mismatch between media driver and examples under Linux

### ISSUE THREAD

**Issue by dameiss** [real-logic/Aeron#67]
On Linux, the media driver uses `/tmp/aeron/conductor`, `/tmp/aeron/data`, and so forth for communication between the media driver and clients. However the example programs default to using `/dev/shm/aeron/conductor`, `/dev/shm/aeron/data` etc.

As a workaround, I added `-Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.dir.data=/tmp/aeron/data` and so forth on the example command lines. This allows the examples to work. But this is not immediately obvious. If the clients can use shared memory to communicate with the media driver, the media driver should probably also use shared memory.

**Comment by tmontgomery** [comment]
I'll move the shared memory for linux check into common from samples. Then hook it into the media driver config.

**Comment by tmontgomery** [comment]
Plan is to do this and to make it so that if `/dev/shm` is not available to default back to `/tmp` or more precisely `java.io.tmpdir`.
