### ISSUE TITLE
cpp compile  as shared object

### ISSUE THREAD

**Issue by ilia987** [real-logic/aeron#673]
Currently libaeron_client.a is static, shared library option would be great

**Comment by sshanks-kx** [comment]
This looks like it may have been done as part of 
https://github.com/real-logic/aeron/commit/0e716c5cdee513e2f051606b7ee4ce73e89608fe#diff-751998d20f15036aea603a63c5dae00781bdc2258315bc2269a1698dd6fff51d
i.e.
aeron-client/src/main/cpp/CMakeLists.txt
`add_library(aeron_client_shared SHARED ${SOURCE} ${HEADERS})`

after build, aeron/cppbuild/Release/lib/ has libaeron_client_shared.so

**Comment by vyazelenko** [comment]
Implemented.
