### ISSUE TITLE
Linux and IPv4/IPv6 sockets

### ISSUE THREAD

**Issue by dameiss** [real-logic/Aeron#68]
On Linux, subscribers appear to create UDP6 sockets.

Using the command line

`java -cp aeron-samples/build/libs/samples.jar -Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.dir.data=/tmp/aeron/data -Daeron.sample.channel=udp://172.16.179.139:50000 uk.co.real_logic.aeron.samples.BasicSubscriber`

on a Linux VM, a listening socket was created, but reported by netstat as

`udp6 0 0 172.16.179.139:50000 [::]:*`

One (rather unsatisfactory) workaround is to disable IPv6 on Linux.

Doing some code sleuthing, the call to `DatagramChannel.open()` doesn’t specify a protocol family, and according to [this link](http://docs.oracle.com/javase/8/docs/api/java/nio/channels/DatagramChannel.html#open--):

> The ProtocolFamily of the channel's socket is platform (and possibly configuration) dependent and therefore unspecified.

An overloaded call, `DatagramChannel.open(ProtocolFamily family)`, allows the protocol family (e.g., IPv4 or IPv6) to be specified. If an IPv4 address is specified in the URI, then an IPv4 socket should be opened, and similarly for an IPv6 address.

I was able to work around this by adding

`-Djava.net.preferIPv4Stack=true`

to each Java command line (media driver, publisher, and subscriber)

**Comment by rlankenau** [comment]
Is this related to #33?

**Comment by rlankenau** [comment]
Or rather, exactly the same thing?

**Comment by dameiss** [comment]
Looks like it. I think requiring `-Djava.net.preferIPv4Stack=true` is... ah... less than optimal.

**Comment by mikeb01** [comment]
I'll have a look at this.  There is an alternate URL format that supports IPv4 and IPv6.  I'll make sure that it sets the family correctly.

**Comment by mikeb01** [comment]
@dameiss Can you try the pull request linked above (#75)?  I don't get the same behaviour on my Linux box, so I can be sure that change fixes the problem.
