### ISSUE TITLE
Non delivered messages in multicast pub/sub

### ISSUE THREAD

**Issue by puiuvlad** [real-logic/aeron#682]
Hi,

This question is related to https://github.com/real-logic/aeron/issues/670. I finally was able to figure out what is happening but I need a little help with how to fix it.

I have three processes that each contain a publication and a subscription on the same multicast channel and same stream. The media driver is in a separate process, and all processes run on the same machine. Processes A and B send infrequent messages to each other while process C just listens on the conversation. Processes also log each message they publish and receive. I can therefore see in the log that when A sends a message to B. A receives the message as well (as expected).

After a while process C is killed deliberately and soon after the log shows that A no longer receives the messages it publishes. B does not receive these messages either. The Aeron logs show no errors and no data loss. Clearly, the non delivery of messages is related to C being killed and maybe not having the subscription properly closed. I assume I would need to somehow close the subscription in a shutdown hook but if the hook is not invoked in case of a crash communication between A and B would come to a halt, wouldn't it?

Any suggestions?

Thanks,
Vladimir

**Comment by tmontgomery** [comment]
Have not seen anything like this. But should be straight forward to reproduce in a system test. So, feel free to reproduce it that way.

**Comment by puiuvlad** [comment]
Thanks Todd,

While trying to reproduce the issue with a simpler setup I think I figured out what was going on. 

I was using SIGTERM and thought that process C was killed but in fact it was not. The thread that does the polling was shut down but the process itself lingered around. When I brought down the media driver (a separate process)  I got this stack trace in my log:
```
20:57:38,190 INFO [AeronClient] inactive image on aeron:udp?endpoint=224.0.1.1:40123 streamId 10 sessionId 1660701017
io.aeron.exceptions.DriverTimeoutException: MediaDriver keepalive older than (ms): 10000
	at io.aeron.ClientConductor.checkLiveness(ClientConductor.java:868)
	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:841)
	at io.aeron.ClientConductor.service(ClientConductor.java:758)
	at io.aeron.ClientConductor.doWork(ClientConductor.java:161)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:286)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.lang.Thread.run(Thread.java:748)
```
So, I assume on the shutdown hook I need to do something which I am not. What would that be?

If I kill process C with SIGKILL then processes A and B continue about their business undisturbed. So the issue is on my side :-).

Vladimir

**Comment by puiuvlad** [comment]
What am I missing in my code?

**Comment by tmontgomery** [comment]
Looks like you killed the media driver by mistake.

**Comment by puiuvlad** [comment]
Process C was in a weird state with the polling thread stopped. Processes A and B were not receiving each other messages because I suppose media driver was trying to deliver them to process C that was not listening. I killed media driver when I noticed that A and B were not receiving messages, not by mistake.

The question is, is there an Aeron thread in process C that needs to be marked as daemon thread when the media driver is in external process?

**Comment by tmontgomery** [comment]
Does a thread need to be marked a daemon thread? Not really. The client conductor is for the app and lives with the app lifetime typically. That thread monitors the liveliness of the media driver as you see from the fact that it reports the driver is inactive after you shut it down.

If you stop the polling thread, polling stops, data will eventually stop due to backpressure from flow control.

**Comment by puiuvlad** [comment]
Thanks Todd,

Process C receives a SIGTERM and is supposed to gracefully exit. My polling thread terminates. There must be another non daemon thread that keeps the process from exiting and could be one of my other threads.

I’ll keep digging.

Vladimir

**Comment by puiuvlad** [comment]
In the shutdown hook I needed to close the Aeron object. Now SIGTERM gracefully shuts down process C.
