### ISSUE TITLE
Question: is it possible to turn on SO_REUSEADDR for sender?

### ISSUE THREAD

**Issue by ZachBray** [real-logic/aeron#683]
Hello chaps,

I see this error when a publication is created after a couple of subscriptions have been created (using multiple drivers - see context section for more info):

```
Address already in use (at sun.nio.ch.Net.bind0(Native Method)): aeron:udp?control=239.9.9.1:10000
```

I think Aeron only uses the `SO_REUSEADDR` socket option when setting up the receive channel and not the send channel.

Is it OK to make this symmetric and turn it on for the send channel too?

This is somewhat outside of my expertise so apologies if I'm barking up the wrong tree or if I don't understand the ramifications of making such a change.

Thanks,
Zach

---

### Relevant file

https://github.com/real-logic/aeron/blob/eb9e7ec58772e40cd9c07ac9f53990be842c68bd/aeron-driver/src/main/java/io/aeron/driver/media/UdpChannelTransport.java#L104

---

### Context

I was recently putting together a couple of examples of how to use the channel URIs for some colleagues.

I wanted to cover: unicast, MDC and multicast.

I did this by running your `BasicPublisher` and `BasicSubscriber` inside some docker containers with different network configurations and channel URIs.

The repo is here: https://github.com/ZachBray/basic-aeron-example/

Unfortunately, I had some problems with the multicast example here:

https://github.com/ZachBray/basic-aeron-example/blob/master/multicast/docker-compose.yml#L3

Multiple subscribers can bind OK but publishers are not willing to share the address/port.

Docker doesn't support multicast out of the box so all containers have to use host networking. Hence why they are all competing to bind.

**Comment by tmontgomery** [comment]
The URI you are using is not supported and that is why it is getting confused. Control should only be a unicast address as MDC is only supported with unicast.

The receiveDatagramChannel is not simply for Receivers. It is also used for senders (for the receiving side of the control channel).

**Comment by ZachBray** [comment]
Doh! A copy paste error. Meant to change it to endpoint.

That explains why the publisher is trying to bind then.

Thanks Todd and sorry for wasting your time!

**Comment by tmontgomery** [comment]
No worries.
