### ISSUE TITLE
ExpandableRingBuffer append - toEndRemaining calculation issue

### ISSUE THREAD

**Issue by agritsiuk** [real-logic/aeron#689]
ExpandableRingBuffer.append()
an issue with a corner case 

1. Maximum buffer capacity is set to 16 bytes.
2. We're adding a message of size 4 which is aligned to 16, that succeeds
3. We're adding one more message which is not supposed to happen as there's no more room in the buffer and its maximum capacity is reached.
But what happens - the first message gets overwritten.

A chain of logic leading to the issue:
tailOffset => headOffset gives true
toEndRemaining = capacity - tailOffset gives 16,
because of that alignedLength > toEndRemaining gives false.
So we get to writing of the message and overwrite the first one.

The proposed fix is:
tailOffset => headOffset && tail < capacity

We're customizing our local version with:
1. void append changed to boolean append (to have backpressure semantics)
2. max capacity to be set in constructur
3. adding a method to check ahead whether it will be possible to add a new message with a given length
4. adding gc-free reusable iterator with reset method to reuse it which is also triggered in main reset method,  next() method returns null of no more messages. It skips padding messages adjusting its own pointer.

It would be great to have 1, 2, 3 in open source version. 4 - if possible.

**Comment by mjpt777** [comment]
Are you saying there is an issue with your modified buffer or the one in Aeron?

**Comment by agritsiuk** [comment]
I have also checked with original one setting its MAXIMUM_CAPACITY to 16

Kind regards,
Andrei Gritsiuk

вт, 23 Июл 2019, 18:43 Martin Thompson <notifications@github.com>:

**Comment by mjpt777** [comment]
I've added the `maxCapacity` and append with back pressure features. The `forEach` method with `headOffset` can be used instead of an iterator.

**Comment by agritsiuk** [comment]
Hi Martin, thanks a lot, test is now green. Could you please remove debug with System.out in resize
