### ISSUE TITLE
Eliminating Aeron MDC as a possible issue for increased network traffic.

### ISSUE THREAD

**Issue by kpdsquare** [real-logic/aeron#691]
Hi,

I'm investigating increased network traffic, and wanted to eliminate that it's not related to Aeron MDC. I have a server side application sending data to multiple applications. Data is published over a few different streams on the same port. Lets just say there are two streams in this scenario, stream ID 1 and stream ID 2. Lets also say client application 1, on host 1, is only subscribing to stream ID 1 and client application 2, on host 2, is only subscribing to stream ID 2. 

Is it at all possible the data for stream ID 1 is also being sent to host 2 and data for stream ID 2 is being sent to host 1, even though they are not subscribing to these streams? I'm using version 1.15.2, if that makes any difference.

**Comment by mjpt777** [comment]
Can you give more detail on the IP address and ports you are sending to? Addresses and ports are used to separate data at the network layer. Aeron stream ids support multiplexing within a channel over IP addresses and ports. Understanding your network data flows is something you should map out regardless of using Aeron or not.

**Comment by kpdsquare** [comment]
The publication channel on the server application is aeron:udp?control=10.60.10.10:40060.
The subscription channel on the client hosts are 
aeron:udp?endpoint=10.10.57.31:40062|control=10.60.10.10:40060|control-mode=dynamic
and
aeron:udp?endpoint=10.60.10.14:40062|control=10.60.10.10:40060|control-mode=dynamic

I've come to a better understanding of MDC now, and I'm guessing I should really be sending data on stream 1 and stream 2 over different ports, given this is mimicking multicast behaviour. I've done a few tests now and stopping the second client application (10.60.10.14) reduces the network traffic seen on the receiving switch for first client application (10.10.57.31). Is this what you would expect?

**Comment by tmontgomery** [comment]
You will want to use different control ports on 10.60.10.10. Everything coming back to the same control port will cause things to be less than optimal from flow control and NAKing perspectives.

**Comment by kpdsquare** [comment]
That makes sense now. Thanks.
