### ISSUE TITLE
Multicast between virtual machine and host - subscriber not receiving messages

### ISSUE THREAD

**Issue by TejDNagaraja** [real-logic/aeron#692]
I have the sample C++ BasicPublisher running on a CentOS virtual machine and the Java BasicSubscriber on the host Windows 10 machine. Each environment also has media drivers running, the host machine specifically using the logging media driver. When using Unicast UDP, the publisher is able to communicate successfully with the subscriber. However, when supplying a multicast address to both the publisher and subscriber, the BasicPublisher reports the following:
"offering x/N- Offer failed because publisher is not connected to subscriber No active subscribers detected"
The BasicSubscriber and logging media driver continually wait for a message from a publisher but never receive one. Neither logs anything to reveal that a publisher is attempting to connect. One fact to note is that I am able to communicate via multicast between the sample C++ BasicPublisher running on one CentOS virtual machine and the sample C++ BasicSubscriber running on a different CentOS virtual machine on the same host.
The firewalls on both the virtual machine and the host have been fully disabled and I have enabled Microsoft Message Queue Server core (including Multicasting Support) on the host machine.
Any direction here would be very helpful. Thanks.

**Comment by tmontgomery** [comment]
Depending on the VM and the mode of the network, multicast may or may not be possible. Best to look at the details of the VM and network mode in use.

**Comment by TejDNagaraja** [comment]
It appears that I'm also unable to have the Java Basic Publisher messages reach the Java Basic Subscriber via multicast when each is hosted on its own Windows 10 machine (no virtual machines). Each machine has its firewall disabled and MSMQ Multicasting enabled.

**Comment by mjpt777** [comment]
Sorry but we cannot comment of your platform setup as this is not an Aeron issue. Start with basic network tooling and confirm connectivity.

**Comment by TejDNagaraja** [comment]
Seems like my Windows machine requires explicitly setting an IP interface when using multicast for the connection to work. Adding that to the Aeron channel solved my issues.

**Comment by tmontgomery** [comment]
Some OSs set the default multicast interface to be first (in the list) that supports multicast and is not loopback. Others do not. It is not possible to easily tell. So, it is suggested to always set the interface when dealing with multicast. Even outside of Aeron, this is a good idea. Just FYI.
