### ISSUE TITLE
Support channel and entity tags in C Media Driver

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#694]
Parse channel URIs for tags and allow them to identity and reference channels and entities such as publications and subscriptions in the C Media Driver as the Java driver does.

**Comment by tmontgomery** [comment]
This is already done and in. Has been for a while. The part that is not in is subscriptions without distinguishing characteristics as that is not possible until subscription destinations are supported.

Tests can be found in 
https://github.com/real-logic/aeron/blob/master/aeron-driver/src/test/c/aeron_driver_conductor_network_test.cpp#L1022
