### ISSUE TITLE
C Media Driver thread enhancements

### ISSUE THREAD

**Issue by j-joshua** [real-logic/aeron#696]
1. Ability to set C media driver's threads' cpu affinity through pthread_setaffinity_np.  This is necessary where a process is running on a linux box with isolcpus using taskset.

2. Ability to name C media driver threads on linux using pthread_setname_np.  This is useful to identify individual threads through htop, etc.

**Comment by tmontgomery** [comment]
This is already supported. There is an on_start function called when each agent is started.

https://github.com/real-logic/aeron/blob/master/aeron-driver/src/main/c/aeronmd.h#L440

**Comment by j-joshua** [comment]
Thanks.  Works perfectly.
