### ISSUE TITLE
C Media：A question about aeron_driver_receiver_do_work？

### ISSUE THREAD

**Issue by tedqian** [real-logic/aeron#698]
In function aeron_driver_receiver_do_work ：
  
```c
   struct mmsghdr mmsghdr[AERON_DRIVER_RECEIVER_NUM_RECV_BUFFERS];
    .......
    int poll_result = aeron_udp_transport_poller_poll(
        &receiver->poller,
        mmsghdr,
        AERON_DRIVER_RECEIVER_NUM_RECV_BUFFERS,
        aeron_receive_channel_endpoint_dispatch,
        receiver);

    if (poll_result < 0)
    {
        AERON_DRIVER_RECEIVER_ERROR(receiver, "receiver poller_poll: %s", aeron_errmsg());
    }

    for (int i = 0; i < poll_result; i++)
    {
        bytes_received += mmsghdr[i].msg_len;
        work_count++;
    }
```

`//AERON_DRIVER_RECEIVER_NUM_RECV_BUFFERS = 2 `
Is there a possibility that poll_result  is greater than 2? Maybe something is wrong？

**Comment by tmontgomery** [comment]
It shouldn't. Can you provide an example where it is?

**Comment by tmontgomery** [comment]
I see what you mean. Yes, it might be possible if there is more than 1 transport and there is more than 1 packet waiting. Is that what you are seeing? Or was this just from inspection?

**Comment by tmontgomery** [comment]
Went ahead and rewrote this in eca92b1b46b9863b5d16d6304b5df35bc881d022

**Comment by tedqian** [comment]
> I see what you mean. Yes, it might be possible if there is more than 1 transport and there is more than 1 packet waiting. Is that what you are seeing? Or was this just from inspection?

I added a line of logs and printed them out： aeron_driver_receiver_do_work poll_result=3, bytes_received=32. It shows that the array mmsghdr  is out of bounds.
