### ISSUE TITLE
Observed "MALFORMED_FRAME_LENGTH [0/0]: COMMAND_UNKNOWN" error at MediaDriver

### ISSUE THREAD

**Issue by vksingh70** [real-logic/Aeron#70]
I was testing Aeron with different TERM lengths and observed "MALFORMED_FRAME_LENGTH [0/0]: COMMAND_UNKNOWN" error at subscriber side media driver.
1> Started  media driver at producer machine
    java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true -Daeron.term.buffer.length=65536  uk.co.real_logic.aeron.driver.MediaDriver

2> Started Media Driver at different machine
java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true  uk.co.real_logic.aeron.driver.MediaDriver
WARNING: conductor directory already exists: /tmp/aeron/conductor
WARNING: data directory already exists: /tmp/aeron/data
( Error is printed after step 3)
[1241.685856] MALFORMED_FRAME_LENGTH [0/0]: COMMAND_UNKNOWN
[1241.688031] MALFORMED_FRAME_LENGTH [0/0]: COMMAND_UNKNOWN
)

3> Started a producer app (https://github.com/strangelydim/Aeron.git
     java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.BasicPublisherWithFragmentation

ava -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.BasicPublisherWithFragmentation
Publishing to udp://224.168.33.11:5000 on stream Id 10
Exception in thread "main" java.lang.IllegalArgumentException: encoded message exceeds maxMessageLength of 8192, length=8204
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.checkMessageLength(LogAppender.java:310)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:133)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:146)
	at uk.co.real_logic.aeron.samples.BasicPublisherWithFragmentation.main(BasicPublisherWithFragmentation.java:73)

4> Repeated the same test with TERM Buffer length set to 131072 at a machine where producer is
 java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true -Daeron.term.buffer.length=131072  uk.co.real_logic.aeron.driver.MediaDriver

No error were seen and messages were exchanged between Producer and Consumer.

**Comment by MichaelDrogalis** [comment]
I've been able to reproduce this, and can confirm it's a problem.

**Comment by tmontgomery** [comment]
The exception is due to sending a message larger than the max message length. Which is expected. I'll add a method to grab the max message length from the Publication for ease of use.

However, why that is causing a frame to be sent that is malformed is undesirable. I'll take a deeper look.

**Comment by strangelydim** [comment]
I get a stream of these:
```
[1426808727.658380] MALFORMED_FRAME_LENGTH [0/0]: COMMAND_UNKNOWN
```
just running this incredibly simple test app:
```
package uk.co.real_logic.aeron.tools;

import uk.co.real_logic.aeron.Aeron;
import uk.co.real_logic.aeron.Publication;
import uk.co.real_logic.aeron.Subscription;
import uk.co.real_logic.aeron.common.concurrent.logbuffer.Header;
import uk.co.real_logic.aeron.driver.MediaDriver;
import uk.co.real_logic.agrona.DirectBuffer;

public class MalformedTest
{

	public static void onMessage(DirectBuffer buffer, int offset, int length, Header header)
	{

	}

	public static void main(String[] args)
	{
		final MediaDriver driver = MediaDriver.launch();

		final Aeron.Context ctx = new Aeron.Context();

		final Aeron aeron = Aeron.connect(ctx);

		final Publication pub = aeron.addPublication("udp://localhost:40001", 10000, 12345);
		final Subscription sub = aeron.addSubscription("udp://localhost:40001", 10000, MalformedTest::onMessage);

		while (true)
		{
			try
			{
				Thread.sleep(1000);
			}
			catch (final InterruptedException e)
			{
				e.printStackTrace();
			}
		}

	}

}
```
No actual sending or receiving of messages required - just a publication and a subscription on the same channel in the same app.
However, for some reason, the EmbeddedPingPong sample app works fine for me without the MALFORMED errors.
If I don't create either the Subscription or the Publication in the app, no errors.  They both have to be created.

**Comment by tmontgomery** [comment]
Looks like this is isolated to publishers that are created and then never send anything. The heartbeat can't send any data since no data has been sent. So, it sends a 0 length UDP datagram. Which is dropped as malformed. This is benign. But noisy.

This behavior is different than it was in the past. So, some of the refactoring of the DriverPublication probably got rid of some checks.

Will be looking at this logic a little closer.

**Comment by tmontgomery** [comment]
Note that the change committed means that your app will see inactive connections since on data has been sent. This will be a new connection immediately as the SETUP frame will come in again.

I think this is the right semantics. Until data is sent, it's really not a true stream.

Thoughts?

**Comment by strangelydim** [comment]
How about if no data has been sent on a connection, you don't get a newConnection notification for the connection at all?  So no newConnection/inactiveConnection notification flapping, just no notifications at all unless the publication actually sends something.

**Comment by tmontgomery** [comment]
Downside to that might be more branching in the client subscription.

**Comment by strangelydim** [comment]
Is it possible to send a non-0-byte message, then, as the heartbeat even when no data has yet been sent?  Just a dummy message with a few bytes of padding that the client knows to ignore?

**Comment by tmontgomery** [comment]
Not without changing the LogRebuilder, no. We decided at one point to remove 0 length data frames so that we can simplify the processing on the receiver.

**Comment by tmontgomery** [comment]
It's not that bad to keep the receiver active with the SETUP frame. I'm just not convinced it is the right semantic...

**Comment by mjpt777** [comment]
We probably could change the rebuilder to handle 0 length messages and make the hearbeat work correctly now that we are position based. I could have a look at doing this if it would be useful?

**Comment by tmontgomery** [comment]
Here is a couple questions I am interested in hearing opinions on.

* Is the liveness of a stream only indicated by the publisher being alive?
* Does the liveness of a stream depend on there being data?

What it comes down to: "is a stream with no data considered alive"?

Maybe this is too metaphysical...

**Comment by mjpt777** [comment]
@tmontgomery I like to think that everything has a life cycle, or a state machine if you want to think of it another way. There needs to be an event that takes something into the alive state. In this case it springs into life when the connection is made, not on first data packet.

Another way to think of this is if I send one message and then not send another for a long time but the publisher is still active would you kill the stream? We currently do not. I think as long as the publisher is alive then the connection is alive.

Stream with no data is the same as a stream with no data in a long while to me. It is an attentive stream waiting to receive data along as the source is alive.

**Comment by mjpt777** [comment]
Also if we send a heartbeat data frame with a frame length of 0 it should be processed on the receiver side correctly. A position of 0 plus a length of 0 takes the position to 0 which will imply a heartbeat at start of stream. Any data packet that if it was applied takes the stream to the current position is considered a heartbeat without actually processing it. Having moved to position based makes this quite easy.

**Comment by tmontgomery** [comment]
The issue here was that it wasn't actually 0 length Aeron Data Frame. It was a 0 length UDP datagram. No UDP payload to hold an Aeron header. The receiver got the message, logged it got it and dropped it. It couldn't even know what the session Id or anything else was since it had no Aeron header. Clearly shouldn't be sent since it has no value Aeron can assume from it.

A 0 length Aeron Data frame is valid. And should be fine.

This was simply noise. And it wasn't operating correctly.

I've been warming to the idea of keeping the stream alive while the sender is alive as I thought about it over the weekend.

**Comment by mjpt777** [comment]
@tmontgomery do you know how we ended up sending a zero length datagram?

**Comment by tmontgomery** [comment]
Yes. Length of last send in the `DriverPublication` is 0. We sent 0 UDP length datagram when we tried to send a heartbeat.

**Comment by tmontgomery** [comment]
I'll be looking at the cleanest way to use a `SETUP` frame to keep a connection active. I've been looking at it more from the usability angle and it only makes sense. The metaphysical angle brings up other "uncomfortable truths" that should be left out anyway.

**Comment by tmontgomery** [comment]
Just an update. We intend to change the heartbeat to be a 0 frame length data frame. I.e. all heartbeats will be a single data frame with a frame length of 0. This should elegantly solve the keepalive issue as well as provide a cleaner heartbeat all around. Timeframe is "soon".
