### ISSUE TITLE
Driver assigned port for channel in ephemeral range 

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#705]
I wonder in many cases(most of them are test cases) it would be very useful to be able to open a channel with some random port. 
Something like we set up a channel "aeron:udp?endpoint=192.168.0.1:0" or "aeron:udp?endpoint=192.168.0.1:\*"  and the media driver looks up a free port and replace '0' or '*' with the found value. 
What do you think? I can contribute this feature, but i need your blessing  =) 

Thank you!

**Comment by tmontgomery** [comment]
You can specify a 0 for port and one will be chosen by the OS from the ephemeral range. This can be used with dynamic MDC for endpoints just fine.

However, communicating an assigned port back to the API is needed for most other uses. So, this requires a change to a number of pieces. Specifically, it either needs to be part of the send/receive channel status indicator or a change to the CnC protocol. And appropriate means for the client to be informed. Getting that to play well with backward compatibility will be necessary.

**Comment by mjpt777** [comment]
It would be possible to do this and add the assigned port to the metadata of the channel status indicator counter before it is marked as `ACTIVE`. This would give a synchronization edge for reading it from subscriptions. We need to protect use so it is not applied to publications for the endpoint.

**Comment by tmontgomery** [comment]
That is one of the issues that can be addressed. The status indicator metadata needs to be set after the counter creation. And can be invalid on an error. But using `ACTIVE` should be enough, I think.

**Comment by mikeb01** [comment]
Java client & driver support was added in PR #906.  C driver and C++ client support coming.

**Comment by mikeb01** [comment]
C driver supported added with #910
