### ISSUE TITLE
Possible regression or behavior change

### ISSUE THREAD

**Issue by denizevrenci** [real-logic/aeron#713]
The following code which sets up an IPC publication at a non-zero position returns in v1.21.0. While the publication cannot connect in v1.22.0 and the program never terminates. Has there been a change in channel configuration?

```cpp
#include <Aeron.h>

int main()
{
  aeron::Context ctx;
  aeron::Aeron proxy{ctx};

  const auto pub_reg_id = proxy.addExclusivePublication(
    "aeron:ipc?init-term-id=0|term-length=67108864|term-offset=67098624|term-id=2147483647", 0);
  const auto sub_reg_id = proxy.addSubscription("aeron:ipc", 0);

  auto pub = proxy.findExclusivePublication(pub_reg_id);
  while (!pub)
    pub = proxy.findExclusivePublication(pub_reg_id);

  auto sub = proxy.findSubscription(sub_reg_id);
  while (!sub)
    sub = proxy.findSubscription(sub_reg_id);

  while (!pub->isConnected())
    continue;

  std::cerr << "Reached here\n";
  return EXIT_FAILURE;
}
```

Update: Changed to `ExclusivePublication` to actually observe the position after offer.

In both v1.21.0 and v1.22.0, non-exclusive publication's initial offer position does not get modified with the channel configuration. If possible, I want to confirm if that is expected behaviour as well.

**Comment by mjpt777** [comment]
C or Java Media Driver?

**Comment by denizevrenci** [comment]
Sorry, forgot to add that. I am using the Java driver.

**Comment by mjpt777** [comment]
The position is only modified with exclusive publications.

**Comment by mjpt777** [comment]
I've confirmed it works fine to connect with Java client to Java Media Driver. Now need to check C++ client to Java Media Driver.

**Comment by mjpt777** [comment]
I wrote a test and this works. What I think you've done wrong is not connecting the Aeron client. Try replacing your first two lines with the following:

```cpp
    aeron::Context context;
    std::shared_ptr<Aeron> aeron = Aeron::connect(context);
```

**Comment by denizevrenci** [comment]
I tried the above and I do not get a different result.

Some additional observations:
1. Actually, with both the constructor and the factory function methods, the loop that fails is not the `isConnected` loop but the `findSubscription()` loop even though the subscription has the normal channel value. That means the client is able to connect to the driver.
2. When I replace, the channel string for the publication to `"aeron:ipc"`, both the constructor and the factory function methods reach the end of the function. Which again means that the client is able to connect to the driver.

**Comment by denizevrenci** [comment]
Further observations:
1. If I wait up to timeout period, `findSubscription` throws `DriverTimeoutException`.
2. When I flip the order of `addExclusivePublication` with `addSubscription`, the code correctly progresses to the end of the function.

**Comment by mjpt777** [comment]
This commit addresses and introduced issue. https://github.com/real-logic/aeron/commit/5d40ac70fab90ff756fcafb881df93e153d1f893

**Comment by denizevrenci** [comment]
I can confirm that the bug has been fixed on my side as well. Thank you for the quick resolution.
