### ISSUE TITLE
Image's position moves back

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#728]
hi! I made a very simple test method in `io.aeron.ExclusivePublicationTest` for better understanding subscription's images work: 

```java 
    @Theory
    @Test(timeout = 100_000)
    public void mytest(final String channel)
    {
        ExclusivePublication publication = aeron.addExclusivePublication(channel, STREAM_ID);
        try (Subscription subscriptionOne = aeron.addSubscription(channel, STREAM_ID);
            Subscription subscriptionTwo = aeron.addSubscription(channel, STREAM_ID))
        {
            while (subscriptionOne.imageCount() < 1)
            {
                SystemTest.checkInterruptedStatus();
                Thread.yield();
            }
            while (subscriptionTwo.imageCount() < 1)
            {
                SystemTest.checkInterruptedStatus();
                Thread.yield();
            }

            while (publication.offer(srcBuffer, 0, MESSAGE_LENGTH) < 0L)
            {
                SystemTest.checkInterruptedStatus();
                Thread.yield();
            }

            do
            {
                subscriptionOne.poll((buffer, offset, length, header) ->{}, 100);
                try
                {
                    Thread.sleep(1000);
                } catch (InterruptedException e)
                {
                    e.printStackTrace();
                }
            }
            while (subscriptionOne.imageBySessionId(publication.sessionId()).position() < publication.position());

            publication.close();

            do
            {
                System.out.println("sub1: " +  subscriptionOne.imageBySessionId(publication.sessionId()));
                System.out.println("sub2: " +  subscriptionTwo.imageBySessionId(publication.sessionId()));
                try
                {
                    Thread.sleep(1000);
                } catch (InterruptedException e)
                {
                    e.printStackTrace();
                }
                subscriptionTwo.poll((buffer, offset, length, header) ->{}, 1000);
            }
            while (subscriptionOne.imageCount() != 0 && subscriptionTwo.imageCount() != 0);
        }
```

and i've got a strange (at least for me) results: 
```
sub1: Image{correlationId=1, sessionId=540644486, isClosed=false, isEos=false, initialTermId=-2002686078, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub2: Image{correlationId=1, sessionId=540644486, isClosed=false, isEos=false, initialTermId=-2002686078, termLength=67108864, joinPosition=0, position=0, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub1: Image{correlationId=1, sessionId=540644486, isClosed=false, isEos=false, initialTermId=-2002686078, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub2: Image{correlationId=1, sessionId=540644486, isClosed=false, isEos=false, initialTermId=-2002686078, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}

// see position of sub2 
sub1: Image{correlationId=4, sessionId=-285653962, isClosed=false, isEos=false, initialTermId=1412185246, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59739', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}
sub2: Image{correlationId=4, sessionId=-285653962, isClosed=false, isEos=false, initialTermId=1412185246, termLength=16777216, joinPosition=0, position=0, sourceIdentity='127.0.0.1:59739', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}


sub1: Image{correlationId=4, sessionId=-285653962, isClosed=false, isEos=false, initialTermId=1412185246, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59739', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}
sub2: Image{correlationId=4, sessionId=-285653962, isClosed=false, isEos=false, initialTermId=1412185246, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59739', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}

// see position of sub2 
sub1: Image{correlationId=3, sessionId=-799012415, isClosed=false, isEos=false, initialTermId=492480662, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59740', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
sub2: Image{correlationId=3, sessionId=-799012415, isClosed=false, isEos=false, initialTermId=492480662, termLength=16777216, joinPosition=0, position=0, sourceIdentity='127.0.0.1:59740', subscription=Subscription{registrationId=4, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}



sub1: Image{correlationId=3, sessionId=-799012415, isClosed=false, isEos=false, initialTermId=492480662, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59740', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
sub2: Image{correlationId=3, sessionId=-799012415, isClosed=false, isEos=false, initialTermId=492480662, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:59740', subscription=Subscription{registrationId=4, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
```

you may see that the position of subscriptionTwo (in logs sub2) is jumping from 256 to zero and back.... Is that expected? I thought the main idea of position values is to be monotonic increasing function.

Thank you.

**Comment by QIvan** [comment]
and another question for this code, if you please: 
if i remove the latest 
```java
subscriptionTwo.poll((buffer, offset, length, header) ->{}, 1000);
```
from the last while loop, the test will stuck forever. 

My understanding it happens because the publication waits for when subscriptionTwo reads up all messages from the stream, but that means that one application may affect another one.... Is that ok? 
I met it in my test, but I a little bit worried about who it may affect real applications.

**Comment by QIvan** [comment]
all that tests are against Aeron master on Windows 10 (unfortunately i have only this OS on my dev machine =( )

**Comment by tmontgomery** [comment]
Your test doesn't read from Sub2 until it prints and thus the first time it is printed, it is 0 position. The Theory in the test means it runs the test multiple times per channel. I added a print so you can see the separation of each invocation. Each time sub2 is printed, it has had no poll and thus position is 0.

Theory aeron:ipc
sub1: Image{correlationId=1, sessionId=-1631943004, isClosed=false, isEos=false, initialTermId=1549718400, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub2: Image{correlationId=1, sessionId=-1631943004, isClosed=false, isEos=false, initialTermId=1549718400, termLength=67108864, joinPosition=0, position=0, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub1: Image{correlationId=1, sessionId=-1631943004, isClosed=false, isEos=false, initialTermId=1549718400, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}
sub2: Image{correlationId=1, sessionId=-1631943004, isClosed=false, isEos=false, initialTermId=1549718400, termLength=67108864, joinPosition=0, position=256, sourceIdentity='aeron:ipc', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:ipc', imageCount=1}}

Theory aeron:udp?endpoint=224.20.30.39:54326|interface=localhost
sub1: Image{correlationId=4, sessionId=1331163220, isClosed=false, isEos=false, initialTermId=1836689592, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:62716', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}
sub2: Image{correlationId=4, sessionId=1331163220, isClosed=false, isEos=false, initialTermId=1836689592, termLength=16777216, joinPosition=0, position=0, sourceIdentity='127.0.0.1:62716', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}
sub1: Image{correlationId=4, sessionId=1331163220, isClosed=false, isEos=false, initialTermId=1836689592, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:62716', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}
sub2: Image{correlationId=4, sessionId=1331163220, isClosed=false, isEos=false, initialTermId=1836689592, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:62716', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=224.20.30.39:54326|interface=localhost', imageCount=1}}

Theory aeron:udp?endpoint=localhost:54325
sub1: Image{correlationId=4, sessionId=1318473483, isClosed=false, isEos=false, initialTermId=344733923, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:53125', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
sub2: Image{correlationId=4, sessionId=1318473483, isClosed=false, isEos=false, initialTermId=344733923, termLength=16777216, joinPosition=0, position=0, sourceIdentity='127.0.0.1:53125', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
sub1: Image{correlationId=4, sessionId=1318473483, isClosed=false, isEos=false, initialTermId=344733923, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:53125', subscription=Subscription{registrationId=2, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}
sub2: Image{correlationId=4, sessionId=1318473483, isClosed=false, isEos=false, initialTermId=344733923, termLength=16777216, joinPosition=0, position=256, sourceIdentity='127.0.0.1:53125', subscription=Subscription{registrationId=3, isClosed=false, streamId=7, channel='aeron:udp?endpoint=localhost:54325', imageCount=1}}

**Comment by QIvan** [comment]
ahhhh.... crap!
I'm awfully sorry, I didn't mentioned that there are several Datapoints in the test. It's my fault, thank you.

**Comment by QIvan** [comment]
but originaly I made the test because of my second question. Any comments?

I mean, I can understand a linger timeout or something like that, but the sub1 will have an image forever even when the publisher was closed. Is that expected? Is that because I use the same md?

Thank you.

**Comment by mjpt777** [comment]
An image captured by a subscription will stay around after the publication is gone until the image is drained by the consumer, or the subscription is closed. This allows for a consumer that is running a little slow to have time to consume the data.

**Comment by mjpt777** [comment]
Note that the publication does not wait. It is the subscription keeping the un-drained image around. Other subscriptions would be impacted. However a slow subscriber on another box can be address with flow control strategies, and a slow consumer on the same box can be addressed with the `tether` semantics.

https://github.com/real-logic/aeron/wiki/Flow-And-Congestion-Control

**Comment by QIvan** [comment]
ok, that makes sence, but if a subscription reached "the end" of the image why does the subscription keep it?

**Comment by mjpt777** [comment]
If the image is consumed, i.e. drained, by all subscribers then it goes unavailable. Draining is not tracked on an individual subscription basis.

**Comment by QIvan** [comment]
shouldn't `isEos` be `true` for sub1 then? 
I remember you told about an app should have it's own protocol for "good bye", but for me it sounds logical if a sub reached the position, where a publisher was up to before it closed, we are able to determine this case somehow (it either EOS or closed or just gone)

**Comment by mjpt777** [comment]
Your code had a race between the image getting EOS and you losing it in the Subscription. Try the below.

```java
    @Theory
    @Test(timeout = 100_000)
    public void mytest(final String channel) throws InterruptedException
    {
        System.out.println("\nchannel = " + channel);

        ExclusivePublication publication = aeron.addExclusivePublication(channel, STREAM_ID);
        try (Subscription subscriptionOne = aeron.addSubscription(channel, STREAM_ID);
            Subscription subscriptionTwo = aeron.addSubscription(channel, STREAM_ID))
        {
            while (subscriptionOne.imageCount() < 1)
            {
                Thread.yield();
                SystemTest.checkInterruptedStatus();
            }
            while (subscriptionTwo.imageCount() < 1)
            {
                Thread.yield();
                SystemTest.checkInterruptedStatus();
            }

            final Image imageOne = subscriptionOne.imageBySessionId(publication.sessionId());
            final Image imageTwo = subscriptionTwo.imageBySessionId(publication.sessionId());

            while (publication.offer(srcBuffer, 0, MESSAGE_LENGTH) < 0L)
            {
                SystemTest.checkInterruptedStatus();
                Thread.yield();
            }

            do
            {
                subscriptionOne.poll((buffer, offset, length, header) -> {}, 100);
                Thread.sleep(1000);
            }
            while (imageOne.position() < publication.position());

            publication.close();

            do
            {
                System.out.println("sub1: " + subscriptionOne.imageBySessionId(publication.sessionId()));
                System.out.println("sub2: " + subscriptionTwo.imageBySessionId(publication.sessionId()));

                Thread.sleep(1000);
                subscriptionTwo.poll((buffer, offset, length, header) -> {}, 1000);
            }
            while (subscriptionOne.imageCount() != 0 && subscriptionTwo.imageCount() != 0);

            System.out.println("imageOne = " + imageOne);
            System.out.println("imageTwo = " + imageTwo);
        }
    }
```

**Comment by QIvan** [comment]
thank you for the snipped. 

sorry i had to share whole code. I meant if we don't drain subscriptionTwo at all (let's imagine that it's a separate application which is in a deadlock), but subscriptionOne is polled: 
```java 
    @Theory
    @Test(timeout = 100_000)
    public void mytest(final String channel) throws InterruptedException
    {
        System.out.println("\nchannel = " + channel);

        ExclusivePublication publication = aeron.addExclusivePublication(channel, STREAM_ID);
        try (Subscription subscriptionOne = aeron.addSubscription(channel, STREAM_ID);
            Subscription subscriptionTwo = aeron.addSubscription(channel, STREAM_ID))
        {
            while (subscriptionOne.imageCount() < 1)
            {
                Thread.yield();
                SystemTest.checkInterruptedStatus();
            }
            while (subscriptionTwo.imageCount() < 1)
            {
                Thread.yield();
                SystemTest.checkInterruptedStatus();
            }

            final Image imageOne = subscriptionOne.imageBySessionId(publication.sessionId());
            final Image imageTwo = subscriptionTwo.imageBySessionId(publication.sessionId());

            while (publication.offer(srcBuffer, 0, MESSAGE_LENGTH) < 0L)
            {
                SystemTest.checkInterruptedStatus();
                Thread.yield();
            }

            do
            {
                subscriptionOne.poll((buffer, offset, length, header) -> {}, 100);
                Thread.sleep(1000);
            }
            while (imageOne.position() < publication.position());

            publication.close();

            do
            {
                System.out.println("sub1: " + subscriptionOne.imageBySessionId(publication.sessionId()));
                System.out.println("sub2: " + subscriptionTwo.imageBySessionId(publication.sessionId()));

                Thread.sleep(1000);
                subscriptionOne.poll((buffer, offset, length, header) -> {}, 1000);
            }
            while (subscriptionOne.imageCount() != 0 && subscriptionTwo.imageCount() != 0);

            System.out.println("imageOne = " + imageOne);
            System.out.println("imageTwo = " + imageTwo);
        }
    }

```

**Comment by QIvan** [comment]
should I open another issue for future discussion or this one is fine? 
I can create a test for this and pull-request if it's useful for you.

**Comment by mjpt777** [comment]
This is the why we have subscription tethering. https://github.com/real-logic/aeron/wiki/Flow-and-Congestion-Control#subscription-tethering

**Comment by QIvan** [comment]
fair enough... 
Don't you think that it'd be suitable for every subscription?

**Comment by mjpt777** [comment]
No ;-) It needs to be a conscious decision who you leave behind.
