### ISSUE TITLE
Performance on Windows

### ISSUE THREAD

**Issue by buybackoff** [real-logic/aeron#734]
As promised in [Twitted thread](https://twitter.com/buybackoff/status/1194707976315133955), here are some benchmarks. The setup is 10G network, 20 (Win) / 24 (Lin) cores doing almost nothing else than the benchmark. Running on the first 10 cores.

Transport codes mean, e.g. **wajds** **W**indows **A**eron **J**ava driver with **d**edicated threading and **s**pinning idle strategy.  Or **lacny** means **L**inux **A**eron **C** driver with shared **n**etwork and **y**ielding idle strategy.

The twitter discussion started after we were testing Aeron C media driver and results for certain test combinations were very suspicious (512 size with bursts 2-4). Other configs were faster than ZMQ and therefore looked less suspicios. The Windows servers are production-like and were supposed to have the right settings for minimal latency. But it turned out that _Interrupt Moderation_ was enabled and set to adaptive rate. When we fixed the config the results completely changed.

In the table codes ending with underscore are before the config change.

![image](https://user-images.githubusercontent.com/489852/68884960-8debc280-0714-11ea-91dd-ed40b8102076.png)

The improvement is massive and affects all tests configs and ZMQ as well. Interestingly, the C media driver performance is almost the same as Java one. We are running the C driver embedded into .NET application, we configure and start is with P/Invoke calls. Native bindings are generated using SharpGenTools from aeronmd.h.

On average, C media driver on Windows has 6-7% higher latency, or 1-3 microseconds more.

Below is comparison with Linux, where the networks cards are ~~special~~ normal.

![image](https://user-images.githubusercontent.com/489852/68885402-66e1c080-0715-11ea-81bd-66203d91c32c.png)

* Message size - payload without Aeron header.
* Delay - number of microseconds before sending bursts of messages.
* Burst - number of messages sent without delay.

-----------------------------

What else could affect latency on Windows in terms of network driver config? We are seeing latency explodes when we reach 1.5-2 Gbps, on Linux that starts only after 3 Gbps.

**Comment by mikeb01** [comment]
It is interesting that the max values under Linux are significantly higher than windows.  Is there any chance that latency numbers for the Java driver on Linux could be included?

**Comment by buybackoff** [comment]
@mikeb01 Using openjdk 8 and very quick test (not the full test suite) I see the similar max latencies, still higher than on Windows. But Linux servers are doing some small work other than the benchmark, while Windows servers are doing nothing else. Maybe this is the reason.

**Comment by buybackoff** [comment]
Did a 5 hours (1 minutes per test config) test on Linux with Java (openjdk 8), typical results are: up to P99 latencies are almost the same. Starting from P99.9 Java starts to show higher latencies. Then from P99.99 and to Max Java shows much higher latencies. This pattern shows up on multuple test configs.

![image](https://user-images.githubusercontent.com/489852/69052604-bec74280-0a07-11ea-8bb8-a36136882107.png)

**Comment by buybackoff** [comment]
Closing since this is not actually an issue, but FYI
