### ISSUE TITLE
C++ client leaks file descriptors on Windows

### ISSUE THREAD

**Issue by lukeocamden** [real-logic/aeron#737]
Hello, it looks like the non-Windows implementations of MemoryMappedFile::createNew and MemoryMappedFile::mapExisting close file decsriptors by creating OnScopeExit objects immediately after a successful open.

However these OnScopeExit objects are missing from the Windows implementations of MemoryMappedFile::createNew and MemoryMappedFile::mapExisting so the file descriptors are leaked. This means that a client will hold the files open throughout its lifetime, preventing them from being cleaned up.

If you agree, do you think it makes sense to add them?

Thanks!

**Comment by mjpt777** [comment]
I've pushed a fix. Can you test if it works as expected for you now?

**Comment by lukeocamden** [comment]
Works perfectly - thank you!
