### ISSUE TITLE
1.24 breaks Windows build - field renaming

### ISSUE THREAD

**Issue by bspeice** [real-logic/aeron#758]
Wanted to first say that I'm not sure what the intended support level for Windows is, but I've been running into issues trying to get the 1.24 release to build. It seems that definition of `interface` expands to the keyword `struct`, and so [this commit](https://github.com/real-logic/aeron/commit/8708c2d0f51b5d3d0d8cfcf5f8afc02a234eba12#diff-254e051bdd6ce0d121749b9f59b82e56) leads to all sorts of errors because the syntax gets thrown off. I'm not yet able to tell if this is the only issue.

Example failure [here](https://travis-ci.org/bspeice/aeron-rs/jobs/617026061#L286).

I'm happy to dig into this further if it would be helpful (Visual Studio leads me to believe the definition comes from `combaseapi.h`, not sure if it's actually needed).

**Comment by tmontgomery** [comment]
To answer the support level for Windows.... the Windows version of the C native driver is experimental.

I do believe, though, that the main cause may be the removal of "key" from the names. You are absolutely correct that `interface` is usually a macro and possibly colliding.

**Comment by tmontgomery** [comment]
I've pushed 4e6d5bb071f1403cf879b1aa52d5a55d4d2ae43b that should avoid the name conflict. It builds, but uri_test fails.
