### ISSUE TITLE
There is a bug on line 65 in aeron_driver_context.h (since release 1.22.0 version)

### ISSUE THREAD

**Issue by linux-hl** [real-logic/aeron#765]
This bug leads to free memory errorly. The correct code is as follows: 
#define AERON_THREADING_MODE_IS_SHARED_OR_INVOKER(m) (AERON_THREADING_MODE_SHARED == m || AERON_THREADING_MODE_INVOKER == m)

**Comment by mjpt777** [comment]
Thanks
