### ISSUE TITLE
Large packages cause subscriptions to always report that the image is unavailable.

### ISSUE THREAD

**Issue by linux-hl** [real-logic/aeron#772]
How to resolve the problem of always reporting that the image is unavailable——for example, publish 1000K bytes?

**Comment by mjpt777** [comment]
I don't understand the question. Can you provide more details?

**Comment by linux-hl** [comment]
A publication and subscription are created using same multicast address and stream id. 
Run as follows: using C media driver——aeronmd,  the publication——./StreamingPublisher -s 10 -c "aeron:udp?endpoint=225.10.0.5:55013|interface=10.206.0.120" -L 1000000 -m 1000000, the subscription——./BasicSubscriber -s 10 -c "aeron:udp?endpoint=225.10.0.5:55013|interface=10.206.0.121". 
The availableImageHandler and unavailableImageHandler for the BasicSubscriber are called multiple times. Shouldn't it be just once. 
Why?
