### ISSUE TITLE
C Media driver will not work if missing both POLL and EPOLL

### ISSUE THREAD

**Issue by farnyser** [real-logic/aeron#779]
Hi,

`aeron_udp_transport_poller_poll` will always return 0 (work count) when there is more than 5 (`AERON_UDP_TRANSPORT_POLLER_ITERATION_THRESHOLD`) file descriptors if both poll & epoll are not available. 

This happen (at least) on windows. 

I think it could be good to add a check that at least one of poll or epoll is available

**Comment by tmontgomery** [comment]
This is a good idea. Will add it to the TODO list. Or feel free to send a PR.
