### ISSUE TITLE
Got access violation running BasicPublisher application

### ISSUE THREAD

**Issue by poulls** [real-logic/Aeron#78]
Hi,

I built latest c++ code on Windows via VS 2013 successfully. While running BasicPublisher use default args, I got access violation. The call stack is belowed:

 	BasicPublisher.exe!aeron::common::concurrent::AtomicBuffer::~AtomicBuffer() Line 49	C++
 	[External Code]	
>	BasicPublisher.exe!aeron::Aeron::createDriverReceiver(aeron::Context & context) Line 78	C++
 	BasicPublisher.exe!aeron::Aeron::Aeron(aeron::Context & context) Line 30	C++
 	BasicPublisher.exe!main(int argc, char * * argv) Line 104	C++
 	[External Code]	

Did I miss any steps before?

**Comment by tmontgomery** [comment]
The C++ port is incomplete yet. And the Java version has been ongoing with some changes that could effect the C++ API.

Thanks for pointing out the fault. Once we stabilize the changes for Java, I'll be jumping back onto C++. Until then, it may be good to wait on using C++.

**Comment by mjpt777** [comment]
Closing for now as C++ is not yet complete.
