### ISSUE TITLE
Repeated failures of tryClaim

### ISSUE THREAD

**Issue by johnpr01** [real-logic/Aeron#82]
I have had a number of occurrences where the call to tryClaim fails repeatedly. When I say repeatedly I'm not talking about 5 or 6 times, but 100s of thousands of times in a row.

int iterations = 0;
while (!pub.tryClaim(buffer.capacity(), bufferClaim))
{
   iterations++;
}
if (iterations > 10)
{
  System.out.println("Took too many tries: " + iterations);
}

From one run I got this:
Took too many tries: 44140
Took too many tries: 11291
Took too many tries: 5092
Took too many tries: 155517
Took too many tries: 24986
Took too many tries: 27407
Took too many tries: 956905
Took too many tries: 577498

I have also found that when I do have a large number of failures my latency values are quite bad as well.

This is on linux with default configuration.

**Comment by johnpr01** [comment]
I can attach the test code I used if needed (or I can point you to it).

**Comment by mjpt777** [comment]
Obvious question is are you calling `commit()`?

It is possible the try is failing due to backpressure. If the network cannot keep up then it will return false to indicate back pressure.

**Comment by mjpt777** [comment]
It is also worth running `AeronStat` to see if the Sender is being back pressured by the Receiver.

**Comment by johnpr01** [comment]
I will check the stats tomorrow. Yes I am calling commit. Also, publisher and subscriber are on the same box, and I'm using upd://localhost:[portNum] for the channel.

**Comment by mjpt777** [comment]
Even on the same box with well sized buffers I see back pressure. This can be in the region of 50% of total offers. This is not bad. All it is saying is that the publication is not the bottleneck when going flat out. The publication path is faster than the subscription path.

**Comment by tmontgomery** [comment]
Back pressure is expected. As what you are doing is spinning on tryClaim, it should be normal to see quite a few fail. You might also try doing a `yield` between claim attempts as well.

**Comment by mjpt777** [comment]
Closing this because no more data has been provided and we cannot recreate and issue that is behaviour other than back pressure.
