### ISSUE TITLE
C++ version is difficult to build offline

### ISSUE THREAD

**Issue by thmzlt** [real-logic/aeron#827]
I use [Nix](https://nixos.org/nix/) to manage dependencies and build a C++ project that uses Aeron. Nix packages are reproducible (builds can't use the network), and I can't use  the script that downloads Gradle to build the SBE/Aeron jars. Nix works on any Linux and on macOS.

Gradle isn't a problem when running the default C++ build, but it crashes when building the archive API because it downloads/builds the SBE tool to generate the archive codecs.

I managed to put together a Nix package spec (they are called derivations) to build the C++ version with the archive API by patching the CMake files to use pre-downloaded jars. If you have Nix installed and want to give it a try, put the following `default.nix` file on the root of the repo checked out to the _1.25.0_ tag, and run **`nix-build`**.

This issue isn't currently blocking me, but I'm adding it here for future reference, or in case the maintainers are interested in making the build process "offline-friendly". Happy to help.

`default.nix`:
```nix
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs-channels/archive/37df59d1c36a5d1283f79a0cde668de9ca74fb9a.tar.gz) {} }:

let
  aeron-all-jar = pkgs.fetchurl {
    url = "https://repo1.maven.org/fromsearch?filepath=io/aeron/aeron-all/1.25.0/aeron-all-1.25.0.jar";
    sha256 = "110dd4z4bf6qphkgl57pdgbbldpzvzvdagrxg5i6d0sh8rkkm90y";
  };

  sbe-all-jar = pkgs.fetchurl {
    url = "https://search.maven.org/remotecontent?filepath=uk/co/real-logic/sbe-all/1.16.0/sbe-all-1.16.0.jar";
    sha256 = "1kp971nbflw48wfysl5cpk08zq6c415frz1wk13d0l47v3y8xnby";
  };
in

pkgs.stdenv.mkDerivation {
  name = "aeron";
  src = ./.;

  nativeBuildInputs = with pkgs; [ cmake jdk8 libbsd libuuid zlib ];

  cmakeFlags = "-DBUILD_AERON_DRIVER=ON -DBUILD_AERON_ARCHIVE_API=ON";

  patchPhase = ''
    substituteInPlace CMakeLists.txt \
      --replace 'set(AERON_ALL_JAR "''${CMAKE_CURRENT_SOURCE_DIR}/aeron-all/build/libs/aeron-all-''${AERON_VERSION_TXT}.jar")' \
                'set(AERON_ALL_JAR "${aeron-all-jar}")'
    substituteInPlace aeron-archive/src/main/cpp/CMakeLists.txt \
      --replace './gradlew -Dcodec.target.dir=''${ARCHIVE_CODEC_TARGET_DIR} :aeron-archive:generateCppCodecs' \
                'java -Dsbe.output.dir=''${ARCHIVE_CODEC_TARGET_DIR} -Dsbe.target.language=Cpp  -Dsbe.target.namespace=aeron.archive.client -Dsbe.validation.xsd=''${ARCHIVE_CODEC_SCHEMA_DIR}/fpl/sbe.xsd -Dsbe.validation.stop.on.error=true -jar ${sbe-all-jar} ''${CODEC_SCHEMA}'
  '';
}
```

**Comment by mjpt777** [comment]
Gradle will cache the JARs used in dependencies. You could prime the local cache with your build. Look under ``~/.gradle/caches/modules-2/files-2.1.

**Comment by thmzlt** [comment]
I'm not sure that would work because the build inputs have to be explicitly passed in order to make the build fully reproducible. I think a pair of new CMake flags with the location of the two jars would be good enough for this specific case.

If you are interest, I can help coming up with a proper solution for a reproducible build.

**Comment by tmontgomery** [comment]
If you want to take a shot, we can look at it. However, if the jars are downloaded, Gradle does use them, so not sure why what @mjpt777 mentions would not work.

**Comment by thmzlt** [comment]
Thanks for waiting for my response.

> However, if the jars are downloaded

That is the issue: either the build isn't reproducible (because it is affected by the machine state) or it needs to fetch from the network. If I can explicitly pass the location of the jars to CMake, the build can be reproducible offline.

**Comment by mjpt777** [comment]
Closing due to no further progress.
