### ISSUE TITLE
sample.jar no longer being built

### ISSUE THREAD

**Issue by phaynes** [real-logic/Aeron#83]
Hi,

Sample.jar is no longer being built (nor deleted when cleaning).
Either this should be re-created or the Wiki documentation updated.

Kind Regards,

**Comment by mjpt777** [comment]
I'm seeing this after building in `aeron-samples/build/libs/samples.jar`

If I run `gradlew clean` it is cleaned.

Can you provide more details? A clone of the latest repo is working fine for me.

**Comment by phaynes** [comment]
Martin, thanks for the rapid response.

Got to the bottom of the issue.

We have been running  gradlew install to ensure artefacts are published into maven repos.
This fails to produce the sample.jar. 

gradlew by itself works.

**Comment by tmontgomery** [comment]
I will sort this out.

**Comment by mjpt777** [comment]
Is built now as part of standard build.
