### ISSUE TITLE
ReplayMerge and IPC

### ISSUE THREAD

**Issue by nathaniel-cross** [real-logic/aeron#839]
​I've got ReplayMerge to work catching up an IPC stream but had to comment the following condition which prevents attemptLiveJoin() from succeeding:

```
    inline bool shouldStopAndRemoveReplay(std::int64_t position)
    {
        return m_isLiveAdded &&
            (m_nextTargetPosition - position) <= REPLAY_MERGE_REPLAY_REMOVE_THRESHOLD /*(&&
            m_image->activeTransportCount() >= 2*/;
    }
```

According to the code activeTransportCount() only ever returns 0 for IPC, which means the live join cannot happen. It's not clear if this is a bug or if only UDP streams are intended to be supported by ReplayMerge?

Also, having two simultaneous instances of ReplayMerge catching up different streams did not work, calling poll() causes data to be read from either of the streams. We fixed a similar issue in our own code by adding session-id to the channel URI, but ReplayMerge does not appear to do something similar, unless I misunderstand the source?​

**Comment by tmontgomery** [comment]
ReplayMerge is only for UDP streams at the moment.

To use multiple ReplayMerge instances, you will need to consider using multiple tags and ports, etc. so that nothing collides.

**Comment by tmontgomery** [comment]
I've added some checks and Javadoc in c709994c0

**Comment by mjpt777** [comment]
@tmontgomery We'll need to do similar for C++.

**Comment by tmontgomery** [comment]
@mjpt777 already done in b13a00c29
