### ISSUE TITLE
Deadlock if aeron::Aeron object destroyed too quickly

### ISSUE THREAD

**Issue by lukeocamden** [real-logic/aeron#844]
I managed to get a deadlock by destroying an aeron::Aeron object too quickly after its construction. It happens if `m_isRunning = false` in `AgentRunner::close` executes before `atomic_compare_exchange_strong` in `AgentRunner::run` (which sets `AgentRunner::m_isRunning` back to `true` thus the spawned thread never exits).

Should it be that `AgentRunner::run` checks `while (!m_isClosed)` instead of `while (m_isRunning)`? I think that would fix it so that a close-request can't be "missed". Or can you see a better way to fix this? Thanks!

**Comment by mjpt777** [comment]
Can you check if this works for you now?

**Comment by lukeocamden** [comment]
Thanks for the quick patch. I think this may now crash if `if (m_isRunning)` in `close` runs before `m_isRunning = true;` in `run` (because `m_thread` never gets joined so calls `std::terminate` in its destructor).

**Comment by lukeocamden** [comment]
Just tested this and no more deadlock - thanks again.
