### ISSUE TITLE
BusySpinIdleStrategy.pause static method for Java

### ISSUE THREAD

**Issue by agritsiuk** [real-logic/aeron#845]
Hello,

it would be great to have a static method in Java BusySpinIdleStrategy.pause()
like in CPP version.

Thank you in advance!

**Comment by tmontgomery** [comment]
This is Agrona. So, better to file the issue there.

**Comment by agritsiuk** [comment]
Moved to https://github.com/real-logic/agrona/issues/204

**Comment by agritsiuk** [comment]
Moved to https://github.com/real-logic/agrona/issues/204

**Comment by agritsiuk** [comment]
Moved to https://github.com/real-logic/agrona/issues/204

**Comment by agritsiuk** [comment]
Moved to https://github.com/real-logic/agrona/issues/204
