### ISSUE TITLE
Using the C driver version of RTT performance testing, warm and non warm, there is an order of magnitude difference?

### ISSUE THREAD

**Issue by szqm123** [real-logic/aeron#884]
Hello：
Testing environment：
dell R740, Intel(R) Xeon(R) Gold 6137 CPU @ 3.90GHz；
Red Hat Enterprise Linux Server release 7.5；
10G NIC and switch.

Thread：DEDICATED，
Idle strategy：spinning

2 dell server, 2 App , with libaeron_driver.so and libaeron_client.a.

 RTT test：every test, restart  client app
One thread publication, one thread subscription.
 send：500byte
 recv：500byte

speed: 10000/s:
order number                 consume time
1-236:                           113us-24ms
237-10000:                    20-26us，very stable

speed: 20000/s:
1-234:                           1ms-22ms
235-438:                       130us-970us
439-20000                    20-26us，very stable

speed: 100000/s：
1-552:                             25ms-20ms
553-1702:                       10ms-20ms
1703-2734:                     1ms-10ms
2735-2839:                     89us-1ms
2839-100000:                 22-27us, very stable 

using aeron Ping and Pong  is same thing.
warming:  max 263us
not warming:  max 2224us

The greater the pressure, the longer the time.
why? cpu cache or other reason.

Thanks!

**Comment by szqm123** [comment]
already binding CPU and using numa

**Comment by mjpt777** [comment]
Are you pre-touching memory and not using sparse files?

**Comment by szqm123** [comment]
hello，
After repeated tests, turning off the pre touch in the driver has a better effect. The performance can reach the optimal value at the beginning, which is very confusing?

in aeron_fileutil.c,
int aeron_map_raw_log(...) 

use_sparse_files=true
test data:
****************** sum:9.999(s)  tps:10001.000  mean:31(us) min:28(us) max:123(us) **
1:67us
2:34us
32
32
32
30
39
36
30
31
31
30
30
37
30
33
30
32
29
32
36
31

not use sparse:

****************** sum:9.999(s)  tps:10001.000  mean:39(us)  min:26(us)  max:3607(us) ****************** 
1:3585us
2:3584us
3:3584us
3584
3583
3583
3580
3607
3607
3606
3606
3606
3605
3603
3602
3602
3601
3601
3601
3600
3601
3600
3600
3599
3599
3598
3597
3597
3596
3595
3595
3594
3593
3592
.........
297: 65us
298: 31us
......

**Comment by mjpt777** [comment]
I don't think you understand how memory pages get allocated and faulted in. You should set sparse files to false on the driver and pre-touch on the client to true.

**Comment by szqm123** [comment]
hello：
Warming up memory reduces latency, as I have done before, but after several days of comparative testing, in our scenario, the driver and client do not warm up under the average delay and minimum hour delay and TPS is better.

To find out why， I'll do it as you say and then test it.
Thank you very much.
