### ISSUE TITLE
Counter values buffer too big in Cnc file?

### ISSUE THREAD

**Issue by smandy** [real-logic/Aeron#89]
Hi ,

Is the counter values buffer the correct length in the cnc file? I've just cracked open the metadata section of a command control file when running the defaults. The labels and values buffers are both equal length (67108864). But label length is 1024 and value length is one cache line (64). Shouldn't the values buffer be .. erm.. 16 times smaller than the labels buffer?

( In MediaDriver.java  the two buffers are being created with the same value...)

```
                CncFileDescriptor.fillMetaData(
                    cncMetaDataBuffer,
                    CONDUCTOR_BUFFER_LENGTH,
                    TO_CLIENTS_BUFFER_LENGTH,
                    COUNTER_BUFFERS_LENGTH,
                    COUNTER_BUFFERS_LENGTH);
```

**Comment by mjpt777** [comment]
I think you are right. The labels file should be significantly larger than the counters file by about 16X. 

@tmontgomery can you have a look?

**Comment by tmontgomery** [comment]
I'll look at this soon. When I moved everything to the cnc file, I used the then current sizes as specified. Which didn't seem right, but I wanted to not change them at that time. But, yes, they do need to be modified.

**Comment by tmontgomery** [comment]
Reopening to set different sizes for buffers.

1MB values
1MB labels
256 bytes label size

**Comment by tmontgomery** [comment]
From @mjpt777 : Label size of 124 bytes + 4 bytes for length so each is 2 cache lines. This will be the same as the counters.
