### ISSUE TITLE
cannot work on Red Hat

### ISSUE THREAD

**Issue by dzy19832006** [real-logic/aeron#891]
I have encountered a problem
aeron can doing work on windows7 and ubuntu(Ubuntu 18.04.4 LTS),but it cannot work on Red Hat (Enterprise Linux Server release 7.5).I tested aeron can doing work with MulticastSocket on red hat.
thanks!

**Comment by mikeb01** [comment]
Please could you provide some more details about what is not working.  What is the error that your are seeing?  Which API are you using (C++ or Java)?  If Java which version of the JDK?  When you say it doesn't work, what test are you running?  Could you supply the example?  Are you seeing any specific errors?

**Comment by dzy19832006** [comment]
aeron just cannot accpet any message.
I deploy the sub and pub on the same redhat,the sub can received message from the pub.but deploy pub on the other redhat,the sub cannot accepted any message.
I use jdk8(1.8.0_161-b14).
`
public static MediaDriver driver;
    static long startTime;

    public static void main(String[] args) {
        driver = MediaDriver.launchEmbedded();
        subscribing(1);
    }

    public static void subscribing(int i) {
        final int fragmentLimitCount = 1;
        final String channel = "aeron:udp?endpoint=224.10.9.7:4050|ttl=10";

        final int streamId = 10;

        System.out.println("Subscribing to " + channel + " on stream id " + streamId);

        final AtomicBoolean running = new AtomicBoolean(true);
        SigInt.register(() -> running.set(false));

        final FragmentHandler fragmentHandler =
                (buffer, offset, length, header) ->
                {
                    final byte[] data = new byte[length];
                    buffer.getBytes(offset, data);
                    Message message = null;
                    try {
                        message = new Message(data);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    System.out.println(i + "_" + message + "_" + System.nanoTime());
                    System.out.println(startTime);
                };

        final Aeron.Context ctx = new Aeron.Context().aeronDirectoryName(driver.aeronDirectoryName());

        try (Aeron aeron = Aeron.connect(ctx);
             Subscription subscription = aeron.addSubscription(channel, streamId)) {
            final IdleStrategy idleStrategy = new BackoffIdleStrategy(
                    100, 10, TimeUnit.MICROSECONDS.toNanos(10), TimeUnit.MICROSECONDS.toNanos(100));

            while (running.get()) {
                final int fragmentsRead = subscription.poll(fragmentHandler, fragmentLimitCount);
                idleStrategy.idle(fragmentsRead);
            }
        }
    }`

**Comment by mjpt777** [comment]
The channel URI does not have the interface specified which you should do for multicast. You have set `ttl=10` do you have good reason for that? Given that you have not provided the publisher then no way to know if the connections match up or if you are publishing correctly. 

It could also be something like having a firewall enabled.

**Comment by dzy19832006** [comment]
added the interface on the URI. it can work.thanks!
