### ISSUE TITLE
HasContext<C> interface ?

### ISSUE THREAD

**Issue by hrstoyanov** [real-logic/aeron#899]
Consider adding a **HasContext<C>** interface in Aeron to capture commonality among classes that have context:

```
@FunctionalInterface
public interface HasContext<C>{
 C context();
}
```

I can easily see: **Aeron**, **MediaDriver**, **Archive**, **ClusteredServiceContainer** and many others implementing this interface, similar to how they implement java.lang. **AutoCloseable**, for example:

```
public class Aeron implements AutoCloseable, HasContext<Context>{
  Context context(){ return ctx;}
}
```

If you want to add javadocs to HasContext:
- https://accu.org/index.php/journals/246
- https://www.dre.vanderbilt.edu/~schmidt/PDF/Context-Object-Pattern.pdf

**Comment by mjpt777** [comment]
What is the value to doing this? The contexts are not polymorphic and thus do not benefit from a common interface, the concrete type is required to use it. Extra semantic burden has a cost. What is the payback?
