### ISSUE TITLE
Embedded media driver needs usability improvements

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Aeron#90]
After doing some work with the "embedded media driver feature", I believe the usability of the APIs needs to be improved, specifically around deleteDirsOnExit and dirName when attempting to embed the media driver or else using an embedded media driver in general should not be recommended or demonstrated in the samples.  

For example, the simplest possible case of trying out the embedded media driver (running a BasicPublisher and BasicSubscriber and setting both to use an embedded media driver) doesn't work and throws an exception.  In a way, it feels like embedded media drivers are something that happens to work as a result of the design rather than is an intended/recommended way to run.  Several improvements need to be made in my opinion to make embedded media drivers easier to use/configure.

The basic deployment patterns that I would like to address (on a single machine) are:
1) 3 Aeron client processes and 1 media driver process
2) 3 Aeron client processes (each using its own embedded media driver to avoid any additional media driver process)
3) everything from item 1 as well as 1 gateway-like process that runs its own media driver as well as 3 Aeron clients all in process sharing the media driver
4) everything from item 2 as well as 1 gateway-like process that runs its own media driver as well as 3 Aeron clients all in process sharing the media driver

Improvement #1 - deleteDirsOnExit seems like it should be moved out of CommonContext and into MediaDriver.Context

In each of the cases above, it seems like enabling deleteDirsOnExit on anything other than the media driver context would be a bad idea and it should be the media driver's responsibility to do the cleanup as I wouldn't want to set this at a single Aeron client and have it incorrectly try to clean up data that was still in use by the running media driver.

Looking further at the delete dirs code, the deleteDirsOnExit boolean exists in CommonContext, which is then inherited by MediaDriver.Context and Aeron.Context making it appear to the user of the API that either an Aeron client application via its Aeron Context or a Media Driver application via its MediaDriver Context could both set deleteDirsOnExit to true to control when the dirs are cleaned up (or I could globally configure it for the JVM via the system property "aeron.dir.delete.on.exit").  In reality, the MediaDriver Context is the only one that accesses this boolean and does any deleting of the files (the Aeron Context does not currently do any deleting or look at this boolean from its base class).  This seems appropriate to protect against a single Aeron client wiping out any directories or files needed by the MediaDriver and other Aeron running clients.  

Based on the current implementation then, the deleteDirsOnExit boolean seems as though it should move up from the base class into MediaDriver.Context which would simplify how it can be used and remove any confusion around whether Aeron clients can trigger directory delete on exit.

Improvement #2 - isolating an embedded media driver should be the default behavior

While attempting to setup deployment pattern 1 above, with a BasicSubscriber and BasicPublisher both configured to use an embedded media driver, I immediately get the exception:
Exception in thread "main" java.nio.file.FileSystemException: C:\Users\Jesse\AppData\Local\Temp\aeron\conductor\cnc: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at uk.co.real_logic.agrona.IoUtil.delete(IoUtil.java:106)
	at uk.co.real_logic.agrona.IoUtil.delete(IoUtil.java:97)
	at uk.co.real_logic.agrona.IoUtil.ensureDirectoryIsRecreated(IoUtil.java:146)
	at uk.co.real_logic.aeron.driver.MediaDriver.ensureDirectoriesAreRecreated(MediaDriver.java:223)
	at uk.co.real_logic.aeron.driver.MediaDriver.<init>(MediaDriver.java:103)
	at uk.co.real_logic.aeron.driver.MediaDriver.launch(MediaDriver.java:170)
	at uk.co.real_logic.aeron.driver.MediaDriver.launch(MediaDriver.java:159)
	at uk.co.real_logic.aeron.samples.BasicPublisher.main(BasicPublisher.java:44)

This of course happened because both embedded media drivers are sharing the same default dirName ("Temp\aeron") and they collide but this was unexpected to me because the reason for using an embedded media driver seemed to be so that it was isolated and not shared with other processes.  

This line of code in BasicPublisher/BasicSubscriber:

final MediaDriver driver = EMBEDDED_MEDIA_DRIVER ? MediaDriver.launch() : null;

is actually launching a super-collision-prone media driver rather than an embedded media driver.

To get an embedded media driver to work, in each process next I configured the dirName of the both the MediaDriver Context and the Aeron Context to a unique path by using a random uuid:
String uniqueAeronDir = IoUtil.tmpDirName() + "aeron" + File.separator + UUID.randomUUID().toString();

This isolated the two processes as expected and I was able to deploy the different patterns described above but it felt as though this should have been the default behavior for an "embedded media driver".  Something like MediaDriver.launchIsolated() or launchEmbedded seems appropriate so that the user doesn't have to worry about correctly isolating the media driver.

Improvement #3 - setting a unique dirName and also setting deleteDirsOnExit results in the top level unique dirName being left on the file system

After working through the steps above on setting a unique dirName, I noticed that a number of folders were being created and not deleted under "Temp\aeron" on my system.  It turns out that the deleteDirsOnExit boolean in MediaDriver really just delete the adminDir and dataDir but then leak the top level parent directory that it also created.  If the Media Driver is creating the top level directory, it seems as though it should also be responsible for deleting the directory.  On the other hand, if we didn't want to always delete the configured dirName ("parent" directory) for whatever reason, doing it only for the embedded case described above might also be ok.

I will be doing a pull request with a proposed set of changes but I'm open to ideas on how to improve the usability of the embedded media driver.

**Comment by tmontgomery** [comment]
These look to be great changes. If the PR can be updated, I will merge it in.

**Comment by jessefugitt** [comment]
Pulled the latest, fixed the conflict, built and tested the samples and then updated the PR.

**Comment by tmontgomery** [comment]
merged.
