### ISSUE TITLE
Question on Gap Detection/NACK

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#903]
Hi, I would like to understand why a PublicationImage only scans for Gaps from the rebuildPosition up to the first gap detected. For instance, it could report all the gaps from the rebuildPosition up to the high water mark position.

By stopping the gap scan to the first gap, it does prevent multiple NACK to be sent which in increases the recovery time.

**Comment by tmontgomery** [comment]
Few inter-related reasons.

1) It optimizes the common case of a single loss or a burst loss that is multiple datagrams in a row.
2) that gap must be recovered before data reception on that stream can resume, and
3) loss for multicast endpoints must also add delay to avoid self-similar behavior and eventual storms.

Doing more than a single gap at a time optimizes the wrong things for a low latency system. In most cases, if you have more than a single loss event in an RTT in such systems, you have other problems than recovery time to deal with.

**Comment by goglusid** [comment]
I understand your design decision. Thank you very much for the detailed explanations.
