### ISSUE TITLE
CubicCongestionControl 

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#915]
Hi,

It should be **max** between 1 and 80% of current window.

https://github.com/real-logic/aeron/blob/3448ff15b4f0b570883bde8a83660d70d0f5778e/aeron-driver/src/main/java/io/aeron/driver/ext/CubicCongestionControl.java#L177

**Comment by tmontgomery** [comment]
Will look into it later. Thanks!

**Comment by goglusid** [comment]
Also, according to:

                // W_tcp(t) = w_max * (1 - B) + 3 * B / (2 - B) * t / RTT

The following should be (2.0 - B).

https://github.com/real-logic/aeron/blob/3448ff15b4f0b570883bde8a83660d70d0f5778e/aeron-driver/src/main/java/io/aeron/driver/ext/CubicCongestionControl.java#L197

**Comment by tmontgomery** [comment]
I've checked the ID as well as the papers and such. You are correct in both accounts. I've also updated the java doc to point to better sources. Thanks!
