### ISSUE TITLE
Seeing "IndexOutOfBoundsException" at media driver

### ISSUE THREAD

**Issue by vksingh70** [real-logic/Aeron#93]
Occasionally, I see "java.lang.IndexOutOfBoundsException" error at media driver
[[347215.675806] EXCEPTION [605/605]: java.lang.IndexOutOfBoundsException(index=-1786265548, length=4, capacity=16777216)
uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck UnsafeBuffer.java:795
uk.co.real_logic.agrona.concurrent.UnsafeBuffer.getIntVolatile UnsafeBuffer.java:423
uk.co.real_logic.aeron.common.concurrent.logbuffer.FrameDescriptor.frameLengthVolatile FrameDescriptor.java:262
uk.co.real_logic.aeron.common.concurrent.logbuffer.TermScanner.scanForAvailability TermScanner.java:62
uk.co.real_logic.aeron.driver.DriverPublication.onRetransmit DriverPublication.java:214
]
Steps to reproduce on a machine 
1> Start a media driver on machine1
    java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.driver.MediaDriver

2> Start a Stat sample app on  machine1 
    java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.AeronStat

3>  Start media driver on a different machine2
     java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.driver.MediaDriver

4> Start a samle stat app on machine2
    java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.AeronStat

5> Start a subscriber app on machine2
     java -cp aeron-samples/build/libs/samples.jar -Daeron.dir.data=/tmp/aeron/data -Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.MultipleSubscriberWithFrag

6> Start a publisher on machine1
    java -cp aeron-samples/build/libs/samples.jar -Daeron.dir.data=/tmp/aeron/data -Daeron.dir.conductor=/tmp/aeron/conductor -Daeron.sample.channel=udp://224.168.33.11:5000 -Djava.net.preferIPv4Stack=true uk.co.real_logic.aeron.samples.MultiplePublisherWithFrag

Once in a while, I see the error on media driver at machine1.

**Comment by vksingh70** [comment]
Sample apps referred in the above bug can be found at 
https://github.com/strangelydim/Aeron

**Comment by mjpt777** [comment]
This looks like an invalid range has been requested for retransmission on a NAK. It is likely to be related to whatever has gone wrong when the completion code got migrated and raised issue #87.

**Comment by tmontgomery** [comment]
Are these errors still seen with the latest set of changes?
