### ISSUE TITLE
ERROR_DELETING_FILE

### ISSUE THREAD

**Issue by rmizuta** [real-logic/Aeron#94]
Hi,

I have updated to the most recent version and after a while I started receiving the following error again:

[1716166.111576] ERROR_DELETING_FILE [130/130]: C:\driver\data\publications\UDP-00000000-0-7f000001-1001\2AEAE803\2\2\stream.log

Once this error occurs, the error pops-up over and over again.

What causes this error and how can I avoid this? 

Thank you.

RM

**Comment by tmontgomery** [comment]
Are you running two media drivers?

**Comment by rmizuta** [comment]
Yes. I am running 2 media drivers but using different directories for each media drivers.

Thank you.

RM

**Comment by rmizuta** [comment]
I recently updated the code and received a similar error. I only have a single instance of media driver running on the computer.

[2418469.062105] ERROR_DELETING_FILE [124/124]: C:\driver\publications\UDP-00000000-0-7f000001-1001-75862CDF-2-2.logbuffer

Once I see the error, it keeps repeating every time I close and restart the application and stops receiving messages from the publisher.  Is there a way to handle the above error so that the driver will keep receiving data after the error? or Is there a way to restart the application without seeing the error repeatedly?

I have tried restarting it after deleting the whole directory but I would still see the error. What doesn't make sense to me is that it eventually starts working again without showing errors. Could there be some kind of memory leak or is it holding some state outside of the directory?

Thank you.

RM

**Comment by tmontgomery** [comment]
For Windows, the Publication logbuffer is held until the Publication is explicitly closed by the application. Then the driver will timeout it's state and delete the file. What might be happening is that the application is not calling Publication.close when it is done with the Publication.

**Comment by tmontgomery** [comment]
There have been some cleanup changes on the client that might address this. Would be great if you could retest.

**Comment by mjpt777** [comment]
I cannot recreate in recent versions. Closing due to no further feedback that it is still occurring.
