### ISSUE TITLE
The result of sendmsg_func are sent_bytes and not returned 

### ISSUE THREAD

**Issue by lygstate** [real-logic/aeron#945]
https://github.com/real-logic/aeron/blob/dbf92ebcf51361b66b1edc386b22ca056266619d/aeron-driver/src/main/c/media/aeron_receive_channel_endpoint.c#L189-L202

The result sent_bytes of 

destination->data_paths->sendmsg_func(destination->data_paths, &destination->transport, msghdr) 

are not returned.

**Comment by tmontgomery** [comment]
That is correct. The send bytes do not increment on the Receiver. Thus we only need to catch errors. We do it this way so that if we decide to change later, we won't need to change the transport bindings.

**Comment by lygstate** [comment]
gocha

**Comment by lygstate** [comment]
For porting to new system, I have to moving os related things down into C file but not in header files.
There is too much confliction when include OS header in C header files. That's why I refactoring struct mmsghdr down into aeron_udp_channel_transport.c, and do not expose everywhere. I've already did the same thing for fileutil and atomic.
