### ISSUE TITLE
Support for GCC variants on Windows

### ISSUE THREAD

**Issue by Boereck** [real-logic/Aeron#95]
Hi,
When I run cmake with -G "MSYS Makefiles" .. the compiler flags get mixed up.
I am new to CMake, but it seems that the check in CMakeLists.txt is simply checking for the operating system and not for the compiler being used. I had a quick search and found that there are CMake variables to check for the compiler rather than the OS. E.g. see CMAKE_CXX_COMPILER_ID or (see http://www.cmake.org/Wiki/CMake_Useful_Variables). I was able to start compilation when having a check if(${CMAKE_CXX_COMPILER_ID} STREQUAL "GNU") and set the GCC related commands in the branch. But then I ran into compilation errors. It seems that in "aeron-common/src/main/cpp/util/MemoryMappedFile.cpp" _WIN32 is used to distinguish between MSVC and other compilers. Unfortunately MinGW also defines _WIN32. I replaced the define in the _WIN32 branch with the following:
```
	#ifndef __GNUC__
		#define AERON_NOEXCEPT
	#else
		#define AERON_NOEXCEPT noexcept
	#endif
```
Maybe this should better check for _MSC_VER instead. In aeron-samples/src/main/cpp/BasicPublisher.cpp:123 the WIN32 can be replaced with _WIN32, then the build completes without a problem. Unfortunately a couple of tests fail (broadcastReceiverTest, broadcastTransmitterTest, logAppenderTest, logReaderTest), so I am not sure if the compiling and linking completely works as expected.

**Comment by tmontgomery** [comment]
Will clean this up when getting back to the C++ driver.
