### ISSUE TITLE
Subscription's Timeout

### ISSUE THREAD

**Issue by goglusid** [real-logic/aeron#952]
Hi, 
I would like your opinion on the following (names are taken from the Java driver but I guess the C Driver follows the same design):

First I have to mention that it might very well be a covered case but I can't find the code dealing with what would happen.

Suppose you have a NetworkPublication using the MinMulticastFlowControl to drive the senderLimit based on 2 tethered Subscriptions.

Suppose that one Subscription timeouts in the MinMulticastFlowControl BUT in fact is still running.
I know loosing 2 seconds (the default timeout period) of SubscriptionStatus messages would easily lead you to conclude that we have an the equivalent of an unplugged cable but nevertheless please keep reading my argumentation. 

My understanding is the current code would lead to the following (Unless I missed something which is obviously possible):

- The NetworkPublication would continue sending.

- The timedout subscription would still send NACK but the NetworkPosition would not answer because the dataframe would be too far in the past. This code: 

https://github.com/real-logic/aeron/blob/58495564e5a87be82ee69677920c5f55d04beb60/aeron-driver/src/main/java/io/aeron/driver/NetworkPublication.java#L361

- The timedout subscription would wait "forever" for a missing Gap. 

How about adding code to do the following?

If the distance between your lowest gap position and the highest NetworkPubication's position received is > termlength the Subscription should become inactive and then "rejoin" the NetworkPublication.

**Comment by tmontgomery** [comment]
This is not needed. The subscription has timed out with respect to flow control. The moment that has happened, the subscription is in danger of falling outside the NAK window and outside the flow control window. The subscription will not wait forever as it will timeout the image as it falls further and further behind and will eventually stop seeing any messages within its known window.

If you have a reproducible test case that doesn't do this, let us know.

**Comment by goglusid** [comment]
I knew I was mssing a part!

Indeed PublicationImage's insertPacket() has protection to avoid dealing with too old/recent dataframes.
       ...
        if (!isFlowControlOverRun(proposedPosition))
        {
            if (!isFlowControlUnderRun(packetPosition))

And indeed, by rejecting all packets it will timeout...and stop waiting for a missing Gap.

Thank you so much for always taking the time to respond rapidly to my questions. Regards

**Comment by tmontgomery** [comment]
No worries! :)

**Comment by goglusid** [comment]
AbstractMinMulticastFlowControl's processStatusMessage ensures that senderLimit only move forward.

However, AbstractMinMulticastFlowControl's onIdle allows senderLimit to move backward. Is it a bug?

It seems the fix would be the following:

return receivers.length < groupMinSize || receivers.length == 0 ? senderLimit : **Math.max(senderLimit,** minLimitPosition**)**;

**Comment by tmontgomery** [comment]
This is by design.
