### ISSUE TITLE
Aeron Stat analyze

### ISSUE THREAD

**Issue by dzy19832006** [real-logic/aeron#954]
0:           84,477,632 - Bytes sent
  1:           84,468,320 - Bytes received
  2:                    0 - Failed offers to ReceiverProxy
  3:                    0 - Failed offers to SenderProxy
  4:                    0 - Failed offers to DriverConductorProxy
  5:                    0 - NAKs sent
  6:                    0 - NAKs received
  7:                2,854 - Status Messages sent
  8:                  602 - Status Messages received
  9:                  861 - Heartbeats sent
 10:                  571 - Heartbeats received
 11:                    0 - Retransmits sent
 12:                    0 - Flow control under runs
 13:                    0 - Flow control over runs
 14:                    0 - Invalid packets
 15:                    0 - Errors
 16:                    0 - Short sends
 17:                    0 - Failed attempts to free log buffers
 18:                    0 - Sender flow control limits, i.e. back-pressure events
 19:                    0 - Unblocked Publications
 20:                    0 - Unblocked Control Commands
 21:                    0 - Possible TTL Asymmetry
 22:                    0 - ControllableIdleStrategy status
 23:                    0 - Loss gap fills
 24:                    0 - Client liveness timeouts
 26:                    0 - client-heartbeat: 0
 27:                    1 - snd-channel: aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119 0.0.0.0:4051
 28:           84,451,200 - pub-pos (sampled): 2 1632211722 1003 aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119
 29:           84,451,200 - pub-lmt: 2 1632211722 1003 aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119
 30:           84,451,200 - snd-pos: 2 1632211722 1003 aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119
 31:           86,548,352 - snd-lmt: 2 1632211722 1003 aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119
 32:                    0 - snd-bpe: 2 1632211722 1003 aeron:udp?endpoint=224.2.2.1:4051|interface=192.168.4.119
 33:           70,401,024 - rcv-pos: 4 664135644 1002 aeron:udp?endpoint=224.2.2.1:4050|interface=192.168.4.119
 35:           70,401,024 - rcv-hwm: 4 664135644 1002 aeron:udp?endpoint=224.2.2.1:4050|interface=192.168.4.119

the report show that some fileds value is too large.
for example:snd-lmt, pub-lmt ...

i want known,why these values so large?
thanks！

**Comment by mjpt777** [comment]
How the the fields "too large"? The larger values are positions a stream has reached or has been limited to.
