### ISSUE TITLE
[QUESTION] Distinguishing different clients

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [real-logic/aeron#966]
I am developing a client-server architecture using aeron in `C`. Multiple publishers connect to a single subscriber.  When subscriber receives a message, it has to identified from which client the message is receiving and send a message back to the client.

1.  How the identification should be done?
2.  How to get the channel from which the message is receiving?

**Comment by tmontgomery** [comment]
You might check into how the Java client handles this for the Archive and Cluster.

**Comment by PrabhakarTayenjam** [comment]
I have tried the following:

When the subscriber received a message, I get the session id using

`sess_id = aeron_header_session_id(header);`

But message from different clients are having same session ID. Why is it having same session ID. Isn't session ID suppose to be different for different clients?

**Comment by tmontgomery** [comment]
First make sure that the value returned, if -1, doesn't indicate an error.

Also, Session ID is only guaranteed to be different for the same media driver. Between media drivers, they may not be unique. Using Session ID is not enough to be unique.

If you look at the Archive and Cluster clients, the server side assigns an ID to the client and sends it back. The request has a respond-to type field (stream ID and channel) to send responses to. The response acts as both an ACK of the request and can hold whatever information (client ID, for example, is only part of it) is required to continued operation.

**Comment by PrabhakarTayenjam** [comment]
I am using a single external media driver and exclusive publication. So client identification problem is solve using the session ID of the received message as session id is guaranteed to be different in same media driver. 

I have multiple clients running its own subscriber. The subscriber stream ID and port is different for each client. Whenever a client connects to the server for the first time, it sends its subscriber info (stream ID and port) to the server. Then the server creates a publisher to connect to the subscriber of the client.

In short, the server creates a publisher for each client. All the publishers have different stream ID and port.

The problem is, when I run with 6-7 clients, two publishers (created on server side) are having same publication session ID. Below is the log:

```Setup new aeron publisher done. channel: [aeron:udp?endpoint=127.0.0.1:7000], stream_id: [7000], pub_sess_id: [2041103187], msg_hdr_session_id: [2041103194]

Setup new aeron publisher done. channel: [aeron:udp?endpoint=127.0.0.1:2000], stream_id: [2000], pub_sess_id: [2041103187], msg_hdr_session_id: [2041103186]```

Here the stream ID and port are different but they are having the same publication session ID. As a result when I respond to the clients, one client is getting the messages for both the clients.

NOTE:
`pub_sess_id` in the log is the publication session ID. I get the session ID using `aeron_publication_session_id`
I am running the server and clients on same machine.
I tried with the exclusive publications also. Same result.

My question is: Why the publishers are having same session id even if they have different port and stream ID?

**Comment by tmontgomery** [comment]
If you can replicate it in a test, let us know.

**Comment by tmontgomery** [comment]
Actually, what version are you using? If using the C API, you should really be using the head of the repo.

**Comment by PrabhakarTayenjam** [comment]
After using the head of the repo, the issue is gone.
