### ISSUE TITLE
Problems when setting sessionId as part of addPublication

### ISSUE THREAD

**Issue by jessefugitt** [real-logic/Aeron#98]
Should sessionId ever be allowed to be set via the public addPublication API?

Many components appear to rely on the fact that sessionId is a random value that uniquely identifies a specific instance of a publication (along with its channel and streamId pair).  It seems dangerous to allow setting this to a non-unique value and causes various problems (deafness, errrors) when I try to set it to any value and then do anything non-trivial with an app that has it set.  If the goal was to provide a way to "logically" identify the same publication, it seems like a user settable publication id or some other metadata could be used and let sessionId stay as a non-settable, required unique value.

A few of the bugs I noticed when setting sessionId to a specific value were:
1) deafness at subscribers
2) errors at the subscribers' media driver that looked like:
[440758.300720] FLOW_CONTROL_OVERRUN [38/38]: 58000 > 0 + 131072
[440758.301708] FLOW_CONTROL_OVERRUN [38/38]: 63000 > 0 + 131072
[440758.302711] FLOW_CONTROL_OVERRUN [38/38]: 6f000 > 0 + 131072
[440758.303749] FLOW_CONTROL_OVERRUN [38/38]: 7c000 > 0 + 131072
[440758.304704] FLOW_CONTROL_OVERRUN [38/38]: 8a000 > 0 + 131072
[440758.305702] FLOW_CONTROL_OVERRUN [38/38]: 99000 > 0 + 131072
3) some fragmentation problems

The trivial case where you start a publisher one time and set its sessionId and send some messages seems to work fine.  However, if that publisher ever stops and starts again and sets the sessionId to the same value, there is the potential for problems at the subscribers.  Even worse, if the publisher app is configured to use a specific sessionId and its media driver is ever stopped and started, a number of deafness, potential naking, and other errors can occur at subscribers.  The reason for this is that the media driver creates a random initialTermId inside DriverConductor.java upon creation of a publication that it doesn't previously know about and if it is ever stopped and started, it will blow away all of the old data on disk including the previous record of the sessionId and termId.  When the publisher app that is configured to use that same specific sessionId joins to its media driver again, it will trigger a new random initialTermId for that sessionId that is either way ahead or way behind from where it was previously at in the stream.  The end result is that all subscribers that had previously received data on that sessionId experience a variety of problems.  I don't know the use case where you would want to set sessionId but it seems like even that case may be very susceptible to the problems I was seeing.

I suppose you could document that you can never stop a media driver if you are using addPublication and specifying your own sessionId but it seems easier to just take out the ability in the API to set sessionId at all because it gives the impression that this is an easy to use way to uniquely identify a publication to its subscribers but in reality it causes a lot of problems at subscribers.

**Comment by tmontgomery** [comment]
There are a number of things to tease out here.

The intention is to have multiple processes that can send to the same streamId and sessionId on the same channel as long as they are using the _same media driver_. The data structures and Publication, etc. are all designed with this in mind. If that is not working, we should look and understand why and plan to address them. The plans we have for IPC revolve around this, so any issues need to be ironed out. Are these effects happening with the _same_ media driver with 2 Publication apps?

The suggestion of using a publication ID might work. Will have to think about that. But it does change the API a bit and will change the underlying protocol between the client and driver. Not necessarily bad, though.

I'll mark as enhancement for now.

The restarted driver with a set sessionId is potentially a more difficult problem. The initialTermId picked would have to fit into the receiver window, which is small. So, right termId and offsets. This is unlikely. Combined with liveness, this is well within most usage. Or should be.

However, an unsettable invocation Id that can is unique might be a possibility. Or wrapping that into a sessionId.

Setting sessionId for Publications is advanced usage and takes with it more responsibility. But, it would be good to know the boundaries and maybe soften them a bot.

**Comment by jessefugitt** [comment]
Agreed that this can probably be a lower priority since the workaround is to avoid setting sessionId.  We removed the code that sets sessionId from our test tools and the problems we were seeing went away so if others using Aeron see similar problems, this issue may help provide some background.

Also, to confirm, I was using a single media driver with 1 or two publications and I was running some tests that involved stopping the media driver and starting it again (which really cannot be known to a publisher app whether a media driver has been stopped or the machine has been rebooted, etc).  

Steps to reproduce in the most basic case are:
1) Start a media driver and a subscriber on a separate machine
2) Start a media driver on the local machine
3) Start a publisher app on the local machine that sets sessionId to some number (ex: 57)
4) Send 1 message and let the publisher app exit
5) Stop the local media driver (or reboot the machine, etc)
6) Start the local media driver again
7) Start the publisher app on the local machine again that sets sessionId to the same number, 57 (or actually start any publisher app on any machine in the system and set sessionId to 57)
8) Send any number of messages

Expected result:
Subscribers will received those messages sent in step 8 without errors

Actual result:
Subscribers will not receive any messages in step 8 or they will cause errors and problems (depending on the random value given to initialTermId in step 7)

Workaround:
Don't set sessionId via the API (more specifically, it isn't safe to reuse a sessionId in two publications if there is a chance the media driver will ever stop, the machine will ever be rebooted, etc)

**Comment by tmontgomery** [comment]
Thanks, @jessefugitt !

Will start looking at this and #96 soon. Multiple apps using the same Publication is a use case we want and will require sessionId to be set (or something else).

**Comment by tmontgomery** [comment]
We do not intend to allow a restarted Media Driver pick up any existing publications. In addition, any usage of session Id generation by the application comes with it a number of responsibilities and coordination. So, at this time, we don't intend to add any additional limitations.
